### ISSUE TITLE
mexopencv cv.VideoCapture not working with rtsp streaming in matlab

### ISSUE THREAD

**Issue by nitin-v** [kyamagu/mexopencv#106]
Hello 
my problem is with the streaming of an ip cam using rtsp. In opencv it is working fine with cv::VideoCapture but in matlab am getting an empty array with the mexopencv function cv.VideoCapture .
please give a suggestion to overcome this and access video frames from matlab

**Comment by sbowman487** [comment]
I'm having a similar problem.  I can open my rtsp feed in VLC and view it that way but when I try to access it via MATLAB i keep getting an empty array.  I've tried adding a pause and still nothing.  I have managed to get other rtsp feeds to work via MATLAB but only pre recorded files, nothing live is coming through.  Any help?
