### ISSUE TITLE
issue with using moments after findcontours

### ISSUE THREAD

**Issue by MichaelShenouda** [kyamagu/mexopencv#109]
hi
i want to find the centroid of shapes in my image
i used cv.canny to find edges then cv.findcontours to get all contours and i want to pass all the contours to cv.moments to calculate all the moments and thus i can get the centroids.
but unfortunately, cv.moments give a lot of errors due the structure of the contours as it is produced as cells of cell array of double cell, i tried passing other arrays to cv.moments and the function itself works just fine
kindly help how to change the output of findcontours, or the input of cv.moments
thanks

**Comment by amroamroamro** [comment]
`cv.findContours` returns an array of contours as a `vector<vector<Point>>` (i.e cell array of cell array of 2d points).

`cv.moments` expects one contour as input `vector<Point>` (i.e a cell array of 2d points).

So you should loop over the contours returns by `findContours` passing one each time to `moments`.

There's a sample included in mexopencv that shows something very similar to what you're doing:

> https://github.com/kyamagu/mexopencv/blob/master/samples/moments_demo_gui.m#L42-L55
