### ISSUE TITLE
undefined symbol: _ZTIN2cv16ParallelLoopBodyE

### ISSUE THREAD

**Issue by Jadecity** [kyamagu/mexopencv#123]
Nothing wrong when make, but when I run make test, the following error occurred:

```
FAIL
== TestAdaptiveThreshold ======
-- test_1 ------
Error using cv.adaptiveThreshold
Invalid MEX-file '/nfs/hlv/workspace/data-driven-hall/mexopencv/+cv/adaptiveThreshold.mexa64': /nfs/hlv/localsys/lib/libopencv_superres.so.2.4: undefined symbol: _ZTIN2cv16ParallelLoopBodyE
```

My environment is as below:
Centos 6.5 64bit
Opencv 2.4.9.1
GCC    4.4.7

I will appreciate it a lot if any one can help me

**Comment by ErCmos** [comment]
Hi all,

I Preload all the libs (manually or with the .bash_profile is the same) and obtein the same ldd results from shell and from MatLab. I'm running opencv-2.4.10 under Linux with MatLab R2013a. I checked that all path in the make file are the ones where the soft is installed, but allways appears the same error:
"Invalid MEX-file '/home/ercmos/Soft/mexopencv/+cv/private/CascadeClassifier_.mexa64':
/usr/local/MATLAB/MATLAB_Production_Server/R2013a/bin/glnxa64/libopencv_ocl.so.2.4: undefined
symbol: _ZTIN2cv16ParallelLoopBodyE"
Any idea?

Thanks in advance

**Comment by kyamagu** [comment]
/usr/local/MATLAB/MATLAB_Production_Server/R2013a/bin/glnxa64/libopencv_ocl.so.2.4: undefined symbol: _ZTIN2cv16ParallelLoopBodyE"

This clearly indicate you're loading Matlab's own OpenCV binary. Where do you install OpenCV and how do you preload?

**Comment by ErCmos** [comment]
Hi kyamagu,

First at all thanks for your quick answer.
 I notice that and make a soft link to the opencv libs as you can see below, but is still the same.
The preload is made inside MatLab like this:

LD_PRELOAD='/usr/lib/x86_64-linux-gnu/libstdc++.so.6:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_imgproc.solibopencv_calib3d.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_imgproc.solibopencv_contrib.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_imgproc.solibopencv_core.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_imgproc.solibopencv_features2d.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_imgproc.solibopencv_flann.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_imgproc.solibopencv_gpu.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_imgproc.solibopencv_highgui.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_imgproc.solibopencv_imgproc.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_imgproc.solibopencv_legacy.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_imgproc.solibopencv_ml.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_imgproc.solibopencv_nonfree.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_imgproc.solibopencv_objdetect.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_imgproc.solibopencv_ocl.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_imgproc.solibopencv_photo.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_imgproc.solibopencv_stitching.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_imgproc.solibopencv_superres.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_imgproc.solibopencv_video.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_imgproc.solibopencv_videostab.so.2.4 matlab'

Invalid MEX-file
'/home/ercmos/Soft/mexopencv-master/+cv/private/CascadeClassifier_.mexa64':
/usr/local/lib/libopencv_ocl.so.2.4: undefined symbol: _ZTIN2cv16ParallelLoopBodyE

>> !ldd /home/ercmos/Soft/mexopencv-master/+cv/private/CascadeClassifier_.mexa64 | grep libopencv_ocl.so.2.4
	libopencv_ocl.so.2.4 => /usr/local/lib/libopencv_ocl.so.2.4 (0x00007ff4b74e8000)
>> !ls -aslh /usr/local/lib/libopencv_ocl.so.2.4
4.0K lrwxrwxrwx 1 root root 64 Feb 18 17:55 /usr/local/lib/libopencv_ocl.so.2.4 -> /home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_ocl.so.2.4
>> !ls -aslh /home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_ocl.so.2.4
0 lrwxrwxrwx 1 ercmos ercmos 23 Feb 18 11:05 /home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_ocl.so.2.4 -> libopencv_ocl.so.2.4.10
>> !strings /usr/local/lib/libopencv_ocl.so.2.4 | grep  _ZTIN2cv16ParallelLoopBodyE
_ZTIN2cv16ParallelLoopBodyE
_ZTIN2cv16ParallelLoopBodyE
>> 

Thanks in advance for all your help

**Comment by kyamagu** [comment]
@ErCmos Your preload path contains incorrect file name: `libopencv_imgproc.solibopencv_calib3d.so`.

You might find the following command handy to generate file paths:

    pkg-config --libs opencv | grep -E -o "/.*\.(so|dylib)" | sed "s/ /:/g"

**Comment by ErCmos** [comment]
Thanks kyamagu,

I Preload just this lib and is still the same:

>> LD_PRELOAD='/usr/local/lib/libopencv_ocl.so matlab'

LD_PRELOAD =

/usr/local/lib/libopencv_ocl.so matlab

>> TestFacedetect
Invalid MEX-file
'/home/ercmos/Soft/mexopencv-master/+cv/private/CascadeClassifier_.mexa64':
/usr/local/lib/libopencv_ocl.so.2.4: undefined symbol: _ZTIN2cv16ParallelLoopBodyE

Error in cv.CascadeClassifier (line 33)
            this.id = CascadeClassifier_(filename);

Error in TestFacedetect (line 2)
detector = cv.CascadeClassifier('haarcascade_frontalface_alt.xml');

**Comment by amroamroamro** [comment]
@ErCmos:
In addition to the incorrect filenames that @kyamagu pointed out, can you also double-check your script that launches MATLAB, I don't think you need the quotations.

Here is what it should look like:
``` sh
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_calib3d.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_contrib.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_core.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_features2d.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_flann.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_gpu.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_highgui.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_imgproc.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_legacy.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_ml.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_nonfree.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_objdetect.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_ocl.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_photo.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_stitching.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_superres.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_video.so.2.4:/home/ercmos/Soft/opencv-2.4.10/release/lib/libopencv_videostab.so.2.4 matlab
```

When you fix that, you don't really need all the soft links either.

**Comment by ErCmos** [comment]
Thanks for your answer and help @amroamroamro.

The problem with the libs is fixed now, sorry for the inconveniences.
