### ISSUE TITLE
Installing on OSX 10.9 with R2014a

### ISSUE THREAD

**Issue by dpfau** [kyamagu/mexopencv#126]
I'm running into two issues when trying to install mexopencv.

First, in R2014a MATLAB does away with `mexopts.sh`, instead using two XML files, `mex_C_maci64.xml` and `mex_C++_maci64.xml`. I changed the `CXXFLAGS` line to `CXXFLAGS="-fno-common -no-cpp-precomp -arch x86_64 -mmacosx-version-min=$SDKVER -fexceptions -isysroot $ISYSROOT -fobjc-arc -std=c++11 -stdlib=libc++ -DCHAR16_T"` but left the rest of the MEX settings the same. Install instructions should probably be updated with instructions for changing these XML files.

Second, my OpenCV header files are in `/opt/local/include`, so I changed `INCLUDEDIR` in `Makefile`, but when I try to compile I get the following output:

```
make MATLABDIR="/Applications/MATLAB_R2014a.app" MEXEXT=mexmaci64  
make: pkg-config: Command not found
make: pkg-config: Command not found
make: *** No rule to make target `+cv/CamShift.mexmaci64', needed by `all'.  Stop.
```

I'm at a loss for what to do.

**Comment by RachelZheng** [comment]
I have had the same issue.

You should change the pkg-config path in the makefile to be absolute path.
