### ISSUE TITLE
Need help in writing my mexFunction

### ISSUE THREAD

**Issue by khurram-amin** [kyamagu/mexopencv#131]
I have written a cpp code and trying to write a mexFunction to bind it with matlab. 
I am trying to use MxArray to convert data between mxArray and Mat. 
But it is not compiling i.e. mex file is not generating. It is giving an Unresolved External symbol errors.
I have correctly provided the opencv lib files what I am using in this function
I have tried with both (1- my own built opencv 2- pre-built binaries) I am using Matlab R2012b, Windows 7, 64-bit, VS 2010
I have pasted the error below.

Creating library C:\Users\Khurram\AppData\Local\Temp\mex_Om0nW2\templib.x and object C:\Users\Khurram\AppData\Local\Temp\mex_Om0nW2\templib.exp 
MxArray.obj : error LNK2019: unresolved external symbol "public: __cdecl cv::Moments::Moments(double,double,double,double,double,double,double,double,double,double)" (??0Moments@cv@@QEAA@NNNNNNNNNN@Z) referenced in function "public: class cv::Moments __cdecl MxArray::toMoments(int)const " (?toMoments@MxArray@@QEBA?AVMoments@cv@@H@Z) 
stitching.mexw64 : fatal error LNK1120: 1 unresolved externals 
 
  C:\PROGRA~1\MATLAB\MATLAB~1\R2012B\BIN\MEX.PL: Error: Link of 'stitching.mexw64' failed. 
 
Error using mex (line 206)
Unable to complete successfully.

**Comment by khurram-amin** [comment]
command executed to generate mexw64:
mex -largeArrayDims -I'D:\OPENCV\MexOpenCV\mexopencv-master\include' -I'C:\opencv\build\x64\vc10\include' -L'C:\opencv\build\x64\vc10\lib' -lopencv_core245 -lopencv_highgui245 'D:\OPENCV\MexOpenCV\mexopencv-master\lib\MxArray.obj' 'D:\OPENCV\MexOpenCV\mexopencv-master\+cv\stitching.cpp' -output 'D:\OPENCV\MexOpenCV\mexopencv-master\+cv\stitching'


Output:
 Creating library C:\Users\Khurram\AppData\Local\Temp\mex_RFKX7r\templib.x and object C:\Users\Khurram\AppData\Local\Temp\mex_RFKX7r\templib.exp 
MxArray.obj : error LNK2019: unresolved external symbol "public: __cdecl cv::Moments::Moments(double,double,double,double,double,double,double,double,double,double)" (??0Moments@cv@@QEAA@NNNNNNNNNN@Z) referenced in function "public: class cv::Moments __cdecl MxArray::toMoments(unsigned __int64)const " (?toMoments@MxArray@@QEBA?AVMoments@cv@@_K@Z) 
D:\OPENCV\MexOpenCV\mexopencv-master\+cv\stitching.mexw64 : fatal error LNK1120: 1 unresolved externals 
 
  C:\PROGRA~1\MATLAB\MATLAB~1\R2012B\BIN\MEX.PL: Error: Link of 'D:\OPENCV\MexOpenCV\mexopencv-master\+cv\stitching.mexw64' failed. 
 
Error using mex (line 206)
Unable to complete successfully.

**Comment by amroamroamro** [comment]
It looks like you need to link against `-lopencv_imgproc245` as well, that's where the class `cv::Moments` is [defined](http://docs.opencv.org/modules/imgproc/doc/structural_analysis_and_shape_descriptors.html).

You might get other linking errors about unresolved external symbols. You should be able to solve them in the same manner by specifying the required missing libraries.

**Comment by khurram-amin** [comment]
Thank you so much amroamroamro. It is compiled.
