### ISSUE TITLE
Unknown file extension '.10'. (Ubuntu 14.04 x64, opencv 2.4.10, R2014a)

### ISSUE THREAD

**Issue by Tschurtsch** [kyamagu/mexopencv#132]
Hello,

first of all thanks for your efforts Kyamagu!

I have been using mexopencv on a Win64 machine and want to run it on a linux cluster now. On Windows everything worked out well. On Unix (Ubuntu 14.04 64bit) I run into problems using opencv 2.4.10.

Compiling with the libs-only flags yields the same error (undefined reference) as in other threads, so I changed 

LD_FLAGS    := -L$(LIBDIR) $(shell pkg-config --libs-only-L --libs-only-l opencv)

to

LD_FLAGS    := -L$(LIBDIR) $(shell pkg-config --libs opencv)

However now I get a strange error:

Unknown file extension '.10'.
make: *** [+cv/adaptiveThreshold.mexa64] Error 255

The command "pkg-config opencv --cflags --libs" results in:

-I/usr/local/include/opencv -I/usr/local/include  /usr/local/lib/libopencv_calib3d.so /usr/local/lib/libopencv_contrib.so /usr/local/lib/libopencv_core.so /usr/local/lib/libopencv_features2d.so /usr/local/lib/libopencv_flann.so /usr/local/lib/libopencv_gpu.so /usr/local/lib/libopencv_highgui.so /usr/local/lib/libopencv_imgproc.so /usr/local/lib/libopencv_legacy.so /usr/local/lib/libopencv_ml.so /usr/local/lib/libopencv_nonfree.so /usr/local/lib/libopencv_objdetect.so /usr/local/lib/libopencv_ocl.so /usr/local/lib/libopencv_photo.so /usr/local/lib/libopencv_stitching.so /usr/local/lib/libopencv_superres.so /usr/local/lib/libopencv_ts.a /usr/local/lib/libopencv_video.so /usr/local/lib/libopencv_videostab.so -lrt -lpthread -lm -ldl  

Any simple opencv example compiled outside matlab works. So I guess the problem is not the opencv installation. Any help would be appreciated!

Best,
Georg.

**Comment by kyamagu** [comment]
The `.10` error is due to `pkg-config` when used with `--libs` flag. Please use the `--libs-only-L --libs-only-l` flag to fix this. Also please post what exactly is the `undefined reference` error.

**Comment by Tschurtsch** [comment]
Thanks for the answer. The result when running "mexopencv.make" with "--libs-only-L" in the Makefile is (shortened):

/usr/local/MATLAB/R2014a/bin/mex -cxx -largeArrayDims -Iinclude -I/usr/local/include/opencv -I/usr/local/include   src/+cv/adaptiveThreshold.cpp -lMxArray -Llib -lrt -lpthread -lm -ldl   -output +cv/adaptiveThreshold.mexa64
Building with 'g++'.
/tmp/mex_9854277061539194_15678/adaptiveThreshold.o: In function `mexFunction':
adaptiveThreshold.cpp:(.text+0x502): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
adaptiveThreshold.cpp:(.text+0x515): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
adaptiveThreshold.cpp:(.text+0x54c): undefined reference to `cv::adaptiveThreshold(cv::_InputArray const&, cv::_OutputArray const&, double, int, int, int, double)'
adaptiveThreshold.cpp:(.text+0x59d): undefined reference to `cv::Mat::deallocate()'
adaptiveThreshold.cpp:(.text+0x5fe): undefined reference to `cv::fastFree(void*)'
adaptiveThreshold.cpp:(.text+0x624): undefined reference to `cv::Mat::deallocate()'
adaptiveThreshold.cpp:(.text+0x69d): undefined reference to `cv::fastFree(void*)'
/tmp/mex_9854277061539194_15678/adaptiveThreshold.o: In function `cv::Mat::~Mat()':
adaptiveThreshold.cpp:(.text._ZN2cv3MatD2Ev[_ZN2cv3MatD5Ev]+0x24): undefined reference to `cv::Mat::deallocate()'
adaptiveThreshold.cpp:(.text._ZN2cv3MatD2Ev[_ZN2cv3MatD5Ev]+0x7f): undefined reference to `cv::fastFree(void*)'
...

**Comment by kyamagu** [comment]
Seems like your `PKG_CONFIG_PATH` is incorrect. I assume you're using a custom-built OpenCV. In the opencv package, you should be able to locate a file `opencv.pc`. Set `PKG_CONFIG_PATH` to point to that file, and perhaps use the `--libs` flag with `pkg-config`.

**Comment by Tschurtsch** [comment]
Thanks for the quick reply!

I set the path using:

export PKG_CONFIG_PATH=/home/username/opencv-2.4.10/build/unix-install/opencv.pc 

The errors still remain the same...
...with "--libs-only-L" I get the "undefined reference to cv::..." errors.
...with "--libs" I get (again)

/usr/local/MATLAB/R2014a/bin/mex -cxx -largeArrayDims -Iinclude -I/usr/local/include/opencv -I/usr/local/include   src/+cv/adaptiveThreshold.cpp -lMxArray -Llib /usr/local/lib/libopencv_calib3d.so /usr/local/lib/libopencv_contrib.so /usr/local/lib/libopencv_core.so /usr/local/lib/libopencv_features2d.so /usr/local/lib/libopencv_flann.so /usr/local/lib/libopencv_gpu.so /usr/local/lib/libopencv_highgui.so /usr/local/lib/libopencv_imgproc.so /usr/local/lib/libopencv_legacy.so /usr/local/lib/libopencv_ml.so /usr/local/lib/libopencv_nonfree.so /usr/local/lib/libopencv_objdetect.so /usr/local/lib/libopencv_ocl.so /usr/local/lib/libopencv_photo.so /usr/local/lib/libopencv_stitching.so /usr/local/lib/libopencv_superres.so /usr/local/lib/libopencv_ts.a /usr/local/lib/libopencv_video.so /usr/local/lib/libopencv_videostab.so -lrt -lpthread -lm -ldl   -output +cv/adaptiveThreshold.mexa64
Unknown file extension '.10'.
make: *** [+cv/adaptiveThreshold.mexa64] Error 255

**Comment by kyamagu** [comment]
The `--libs-only-L` must be specified together with `--libs-only-l` flag.

The strange thing is that your `mex` command does not include any `libopencv_*.so.2.4.10` file, which is usually the reason why you get `Unknown file extension` error. Can you edit `Makefile` and append `-v` flag in the mex flags? That will give you the verbose output of the internal build command.

**Comment by Tschurtsch** [comment]
Sorry for being not detailed enough, I switched between

LD_FLAGS    := -L$(LIBDIR) $(shell pkg-config --libs opencv)

and 

LD_FLAGS    := -L$(LIBDIR) $(shell pkg-config --libs-only-L --libs-only-l opencv)

in the Makefile.

~~~

Verbose mode:
make MATLABDIR="/usr/local/MATLAB/R2014a" MEXEXT=mexa64  

/usr/local/MATLAB/R2014a/bin/mex -v -cxx -largeArrayDims -Iinclude -I/usr/local/include/opencv -I/usr/local/include   src/+cv/adaptiveThreshold.cpp -lMxArray -Llib -lrt -lpthread -lm -ldl   -output +cv/adaptiveThreshold.mexa64
Verbose mode is on.
... Looking for compiler 'g++' ...
... Executing command 'which g++' ...Yes ('/usr/bin/g++').
... Executing command 'g++ -print-file-name=libstdc++.so' ...Yes ('/usr/lib/gcc/x86_64-linux-gnu/4.7/libstdc++.so').
Found installed compiler 'g++'.
Options file details
-------------------------------------------------------------------
	Compiler location: $GCC_DIR
	Options file: /home/test/.matlab/R2014a/mex_C++_glnxa64.xml
	CMDLINE1 : /usr/bin/g++ -c -D_GNU_SOURCE -DMATLAB_MEX_FILE  -Iinclude -I/usr/local/include/opencv -I/usr/local/include  -I"/usr/local/MATLAB/R2014a/extern/include" -I"/usr/local/MATLAB/R2014a/simulink/include" -ansi -fexceptions -fPIC -fno-omit-frame-pointer -pthread -O -DNDEBUG /media/europahome/03_Projekte/01_extern_Code/01_Util/mexopencv-master_unix/mexopencv/src/+cv/adaptiveThreshold.cpp -o /tmp/mex_9868296671049428_19668/adaptiveThreshold.o
	CMDLINE2 : /usr/bin/g++ -pthread -Wl,--no-undefined  -shared -O -Wl,--version-script,"/usr/local/MATLAB/R2014a/extern/lib/glnxa64/mexFunction.map" /tmp/mex_9868296671049428_19668/adaptiveThreshold.o   -lMxArray  -lrt  -lpthread  -lm  -ldl   -Llib   -Wl,-rpath-link,/usr/local/MATLAB/R2014a/bin/glnxa64 -L"/usr/local/MATLAB/R2014a/bin/glnxa64" -lmx -lmex -lmat -lm -lstdc++ -o /media/europahome/03_Projekte/01_extern_Code/01_Util/mexopencv-master_unix/mexopencv/+cv/adaptiveThreshold.mexa64
	CMDLINE3 : rm -f /tmp/mex_9868296671049428_19668/adaptiveThreshold.o
	CXX : /usr/bin/g++
	DEFINES : -D_GNU_SOURCE -DMATLAB_MEX_FILE 
	MATLABMEX : -DMATLAB_MEX_FILE 
	CXXFLAGS : -ansi -fexceptions -fPIC -fno-omit-frame-pointer -pthread
	INCLUDE : -Iinclude -I/usr/local/include/opencv -I/usr/local/include  -I"/usr/local/MATLAB/R2014a/extern/include" -I"/usr/local/MATLAB/R2014a/simulink/include"
	CXXOPTIMFLAGS : -O -DNDEBUG
	CXXDEBUGFLAGS : -g
	LDXX : /usr/bin/g++
	LDFLAGS : -pthread -Wl,--no-undefined 
	LDTYPE : -shared
	LINKEXPORT : -Wl,--version-script,"/usr/local/MATLAB/R2014a/extern/lib/glnxa64/mexFunction.map"
	LINKLIBS : -lMxArray  -lrt  -lpthread  -lm  -ldl   -Llib   -Wl,-rpath-link,/usr/local/MATLAB/R2014a/bin/glnxa64 -L"/usr/local/MATLAB/R2014a/bin/glnxa64" -lmx -lmex -lmat -lm -lstdc++
	LDOPTIMFLAGS : -O
	LDDEBUGFLAGS : -g
	OBJEXT : .o
	LDEXT : .mexa64
	GCC : /usr/bin/g++
	CPPLIB_DIR : /usr/lib/gcc/x86_64-linux-gnu/4.7/libstdc++.so
	MATLABROOT : /usr/local/MATLAB/R2014a
	ARCH : glnxa64
	SRC : /media/europahome/03_Projekte/01_extern_Code/01_Util/mexopencv-master_unix/mexopencv/src/+cv/adaptiveThreshold.cpp
	OBJ : /tmp/mex_9868296671049428_19668/adaptiveThreshold.o
	OBJS : /tmp/mex_9868296671049428_19668/adaptiveThreshold.o 
	SRCROOT : /media/europahome/03_Projekte/01_extern_Code/01_Util/mexopencv-master_unix/mexopencv/src/+cv/adaptiveThreshold
	DEF : /tmp/mex_9868296671049428_19668/adaptiveThreshold.def
	EXP : /media/europahome/03_Projekte/01_extern_Code/01_Util/mexopencv-master_unix/mexopencv/+cv/adaptiveThreshold.exp
	LIB : /media/europahome/03_Projekte/01_extern_Code/01_Util/mexopencv-master_unix/mexopencv/+cv/adaptiveThreshold.lib
	EXE : /media/europahome/03_Projekte/01_extern_Code/01_Util/mexopencv-master_unix/mexopencv/+cv/adaptiveThreshold.mexa64
	ILK : /media/europahome/03_Projekte/01_extern_Code/01_Util/mexopencv-master_unix/mexopencv/+cv/adaptiveThreshold.ilk
	MANIFEST : /media/europahome/03_Projekte/01_extern_Code/01_Util/mexopencv-master_unix/mexopencv/+cv/adaptiveThreshold.mexa64.manifest
	TEMPNAME : /media/europahome/03_Projekte/01_extern_Code/01_Util/mexopencv-master_unix/mexopencv/+cv/adaptiveThreshold
	EXEDIR : /media/europahome/03_Projekte/01_extern_Code/01_Util/mexopencv-master_unix/mexopencv/+cv/
	EXENAME : adaptiveThreshold
	OPTIM : -O -DNDEBUG
	LINKOPTIM : -O
-------------------------------------------------------------------
Building with 'g++'.
/usr/bin/g++ -c -D_GNU_SOURCE -DMATLAB_MEX_FILE  -Iinclude -I/usr/local/include/opencv -I/usr/local/include  -I"/usr/local/MATLAB/R2014a/extern/include" -I"/usr/local/MATLAB/R2014a/simulink/include" -ansi -fexceptions -fPIC -fno-omit-frame-pointer -pthread -O -DNDEBUG /media/europahome/03_Projekte/01_extern_Code/01_Util/mexopencv-master_unix/mexopencv/src/+cv/adaptiveThreshold.cpp -o /tmp/mex_9868296671049428_19668/adaptiveThreshold.o
/usr/bin/g++ -pthread -Wl,--no-undefined  -shared -O -Wl,--version-script,"/usr/local/MATLAB/R2014a/extern/lib/glnxa64/mexFunction.map" /tmp/mex_9868296671049428_19668/adaptiveThreshold.o   -lMxArray  -lrt  -lpthread  -lm  -ldl   -Llib   -Wl,-rpath-link,/usr/local/MATLAB/R2014a/bin/glnxa64 -L"/usr/local/MATLAB/R2014a/bin/glnxa64" -lmx -lmex -lmat -lm -lstdc++ -o /media/europahome/03_Projekte/01_extern_Code/01_Util/mexopencv-master_unix/mexopencv/+cv/adaptiveThreshold.mexa64
/tmp/mex_9868296671049428_19668/adaptiveThreshold.o: In function `mexFunction':
adaptiveThreshold.cpp:(.text+0x502): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
adaptiveThreshold.cpp:(.text+0x515): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
adaptiveThreshold.cpp:(.text+0x54c): undefined reference to `cv::adaptiveThreshold(cv::_InputArray const&, cv::_OutputArray const&, double, int, int, int, double)'
adaptiveThreshold.cpp:(.text+0x59d): undefined reference to `cv::Mat::deallocate()'
adaptiveThreshold.cpp:(.text+0x5fe): undefined reference to `cv::fastFree(void*)'
adaptiveThreshold.cpp:(.text+0x624): undefined reference to `cv::Mat::deallocate()'
adaptiveThreshold.cpp:(.text+0x69d): undefined reference to `cv::fastFree(void*)'
/tmp/mex_9868296671049428_19668/adaptiveThreshold.o: In function `cv::Mat::~Mat()':
adaptiveThreshold.cpp:(.text._ZN2cv3MatD2Ev[_ZN2cv3MatD5Ev]+0x24): undefined reference to `cv::Mat::deallocate()'
adaptiveThreshold.cpp:(.text._ZN2cv3MatD2Ev[_ZN2cv3MatD5Ev]+0x7f): undefined reference to `cv::fastFree(void*)'
...
make: *** [+cv/adaptiveThreshold.mexa64] Error 255

**Comment by kyamagu** [comment]
Ok, use `--libs` flag for your custom-built OpenCV. What is the output of verbose build?

**Comment by Tschurtsch** [comment]
Again the problem with the '.10' files. :(

>> mexopencv.make
make MATLABDIR="/usr/local/MATLAB/R2014a" MEXEXT=mexa64  
/usr/local/MATLAB/R2014a/bin/mex -v -cxx -largeArrayDims -Iinclude -I/usr/local/include/opencv -I/usr/local/include   src/+cv/adaptiveThreshold.cpp -lMxArray -Llib /usr/local/lib/libopencv_calib3d.so /usr/local/lib/libopencv_contrib.so /usr/local/lib/libopencv_core.so /usr/local/lib/libopencv_features2d.so /usr/local/lib/libopencv_flann.so /usr/local/lib/libopencv_gpu.so /usr/local/lib/libopencv_highgui.so /usr/local/lib/libopencv_imgproc.so /usr/local/lib/libopencv_legacy.so /usr/local/lib/libopencv_ml.so /usr/local/lib/libopencv_nonfree.so /usr/local/lib/libopencv_objdetect.so /usr/local/lib/libopencv_ocl.so /usr/local/lib/libopencv_photo.so /usr/local/lib/libopencv_stitching.so /usr/local/lib/libopencv_superres.so /usr/local/lib/libopencv_ts.a /usr/local/lib/libopencv_video.so /usr/local/lib/libopencv_videostab.so -lrt -lpthread -lm -ldl   -output +cv/adaptiveThreshold.mexa64
Verbose mode is on.
Unknown file extension '.10'.
make: *** [+cv/adaptiveThreshold.mexa64] Error 255

**Comment by kyamagu** [comment]
No, what is the verbose output with `--libs` flag?

**Comment by Tschurtsch** [comment]
This _is_ the verbose output with <code>--libs</code> flags, assuming this is correct in the Makefile?:

<code>LD_FLAGS    := -L$(LIBDIR) $(shell pkg-config --libs opencv)</code>

**Comment by kyamagu** [comment]
No, you should see the detailed compiler configuration with `-v` flag in `mex`. What is the verbose output of the build command?

**Comment by kyamagu** [comment]
Or, what happens if you launch `make` in UNIX console? You can do something like:

    make MATLABDIR=/usr/local/MATLAB/R2014a

**Comment by kyamagu** [comment]
In the worst case that `pkg-config` doesn't work, you can manually modify build flags like the following

For each of `libopencv_*.so`, change from:

    /usr/local/lib/libopencv_core.so 

to

    -lopencv_core 

And manually list all of the opencv objects.

I am suspecting symlink of your `*.so` files are doing something wrong for your Matlab version, but not 100% sure.

**Comment by Tschurtsch** [comment]
Thanks again for your help.

The output from before was the result of calling <code>make</code> from the command line. Here is the full output:

<code>
some_path/mexopencv$ make
</code>
<code>
/usr/local/MATLAB/R2014a/bin/mex -v -cxx -largeArrayDims -Iinclude -I/usr/local/include/opencv -I/usr/local/include   src/+cv/adaptiveThreshold.cpp -lMxArray -Llib /usr/local/lib/libopencv_calib3d.so /usr/local/lib/libopencv_contrib.so /usr/local/lib/libopencv_core.so /usr/local/lib/libopencv_features2d.so /usr/local/lib/libopencv_flann.so /usr/local/lib/libopencv_gpu.so /usr/local/lib/libopencv_highgui.so /usr/local/lib/libopencv_imgproc.so /usr/local/lib/libopencv_legacy.so /usr/local/lib/libopencv_ml.so /usr/local/lib/libopencv_nonfree.so /usr/local/lib/libopencv_objdetect.so /usr/local/lib/libopencv_ocl.so /usr/local/lib/libopencv_photo.so /usr/local/lib/libopencv_stitching.so /usr/local/lib/libopencv_superres.so /usr/local/lib/libopencv_ts.a /usr/local/lib/libopencv_video.so /usr/local/lib/libopencv_videostab.so -lrt -lpthread -lm -ldl   -output +cv/adaptiveThreshold.mexa64
</code>
<code>
Verbose mode is on.
</code>
<code>
Unknown file extension '.10'.
</code>
<code>
make: *** [+cv/adaptiveThreshold.mexa64] Error 255
</code>
<code>
some_path/mexopencv$ make
</code>

I'm not quote sure that <code>pk-config</code> is the problem, as the output seems correct:
<code>
some_path/mexopencv$ pkg-config opencv --libs
</code>
<code>
/usr/local/lib/libopencv_calib3d.so /usr/local/lib/libopencv_contrib.so /usr/local/lib/libopencv_core.so /usr/local/lib/libopencv_features2d.so /usr/local/lib/libopencv_flann.so /usr/local/lib/libopencv_gpu.so /usr/local/lib/libopencv_highgui.so /usr/local/lib/libopencv_imgproc.so /usr/local/lib/libopencv_legacy.so /usr/local/lib/libopencv_ml.so /usr/local/lib/libopencv_nonfree.so /usr/local/lib/libopencv_objdetect.so /usr/local/lib/libopencv_ocl.so /usr/local/lib/libopencv_photo.so /usr/local/lib/libopencv_stitching.so /usr/local/lib/libopencv_superres.so /usr/local/lib/libopencv_ts.a /usr/local/lib/libopencv_video.so /usr/local/lib/libopencv_videostab.so -lrt -lpthread -lm -ldl 
</code>

I will try with the <code>-lopencv_...</code> options.

**Comment by amroamroamro** [comment]
@Tschurtsch : can you post the contents of your `opencv.pc` file?

Usually the linking flags should be specified as `-lopencv_xx` instead of directly listing the file name of the shared library with .so extension `opencv_xx.so`...

If that's the case, just manually edit it as explained above.

**Comment by amroamroamro** [comment]
btw, how did you [build OpenCV from sources](http://docs.opencv.org/doc/tutorials/introduction/linux_install/linux_install.html#building-opencv-from-source-using-cmake-using-the-command-line)? I see above that you listed that `opencv.pc` is located in `/home/username/opencv-2.4.10/build/unix-install/opencv.pc`, and the libs and headers are installed in `/usr/local`.

Shouldn't the PC file be also installed in `/usr/local/lib/pkgconfig/opencv.pc`. I think the one you're currently using is a template from the build process...

**Comment by Tschurtsch** [comment]
Just a short notice: Thanks for the comments, I had to switch to Win to complete some work and will post updates later.

**Comment by Tschurtsch** [comment]
@amroamroamro 
1) Both opencv.pc files (user directory, /usr/local/...) are the same and as follows:
<code>
# Package Information for pkg-config

prefix=/usr/local
exec_prefix=${prefix}
libdir=
includedir_old=${prefix}/include/opencv
includedir_new=${prefix}/include

Name: OpenCV
Description: Open Source Computer Vision Library
Version: 2.4.10
Libs:  ${exec_prefix}/lib/libopencv_calib3d.so ${exec_prefix}/lib/libopencv_contrib.so ${exec_prefix}/lib/libopencv_core.so ${exec_prefix}/lib/libopencv_features2d.so ${exec_prefix}/lib/libopencv_flann.so ${exec_prefix}/lib/libopencv_gpu.so ${exec_prefix}/lib/libopencv_highgui.so ${exec_prefix}/lib/libopencv_imgproc.so ${exec_prefix}/lib/libopencv_legacy.so ${exec_prefix}/lib/libopencv_ml.so ${exec_prefix}/lib/libopencv_nonfree.so ${exec_prefix}/lib/libopencv_objdetect.so ${exec_prefix}/lib/libopencv_ocl.so ${exec_prefix}/lib/libopencv_photo.so ${exec_prefix}/lib/libopencv_stitching.so ${exec_prefix}/lib/libopencv_superres.so ${exec_prefix}/lib/libopencv_ts.a ${exec_prefix}/lib/libopencv_video.so ${exec_prefix}/lib/libopencv_videostab.so -lrt -lpthread -lm -ldl
Cflags: -I${includedir_old} -I${includedir_new}
</code>

2) If I remember correctly, I followed the link you provided and chose "build" as the <cmake_binary_dir>.

BTW: I have no problems compiling OpenCV code in the terminal, nor using OpenCV in mex files.

**Comment by amroamroamro** [comment]
@Tschurtsch:
like said before, edit the `opencv.pc` file and replace the line containing listed libraries with:

```
Libs: -L${exec_prefix}/lib -lopencv_calib3d -lopencv_contrib -lopencv_core -lopencv_features2d -lopencv_flann -lopencv_gpu -lopencv_highgui -lopencv_imgproc -lopencv_legacy -lopencv_ml -lopencv_nonfree -lopencv_objdetect -lopencv_ocl -lopencv_photo -lopencv_stitching -lopencv_superres -lopencv_ts -lopencv_video -lopencv_videostab -lrt -lpthread -lm -ldl
```

**Comment by Tschurtsch** [comment]
@amroamroamro 
# Thank you so much!
That worked. (I now also changed back the <code>LD_FLAGS</code> to <code>--libs-only-L --libs-only-l </code>)
