### ISSUE TITLE
Issue with compiling with MATLAB R2014b and Windows SDK 7.1

### ISSUE THREAD

**Issue by jstolle13** [kyamagu/mexopencv#134]
My name is Jacob Stolle, I am a student at the University of Ottawa. I have recently been trying to work with your mexopencv MATLAB program and have had difficulties with getting MATLAB to compile the OpenCV software. I am using MATLAB R2014b and using the Windows SDK 7.1. When I use the mexopencv.make function it gives me the following error:
>
> >> mexopencv.make('opencv_path','C:\opencv')
> Error using mexopencv.make>compiler_str (line 233)
> Unsupported compiler: Microsoft Windows SDK 7.1 (C++)
> Error in mexopencv.make>pkg_config (line 186)
>     L_path = fullfile(opts.opencv_path,arch_str(),compiler_str(),'lib');
> Error in mexopencv.make (line 95)
>     [cv_cflags,cv_libs] = pkg_config(opts);
>
> Any help you could give with this would be appreciated.

**Comment by kyamagu** [comment]
Can you try opening `+mexopencv\make.m` and edit line 228 to the following?

    elseif ~isempty(strfind(c.Name, 'Microsoft Windows SDK')) % win64

**Comment by amroamroamro** [comment]
@kyamagu:
I went through the page containing all versions of [Windows SDK][1]. Here is the summary:

Windows SDK | for Windows | Visual Studio | .NET Framework
----------- | ----------- | ------------- | --------------
[v8.1][2] | Windows 8.1 | VS2013 | .NET 4.5.1
[v8.0][3] | Windows 8 | VS2012 | .NET 4.5
[v7.1][4] | Windows 7 | VS2010 | .NET 4.0
[v7.0][5] | Windows 7 | VS2008 SP1 | .NET 3.5 SP1
[v6.1][6] | Windows Server 2008 | VS2008 | .NET 3.5
[v6.0 (update)][7] | Windows Vista | VS2005 SP1 | .NET 3.0

Based on that, we should maybe update the detection code in `+mexopencv\make.m` with something like:

``` matlab
% ...
elseif ~isempty(strfind(c.Name, 'Windows SDK'))
	if ~isempty(strfind(c.Version, '8.1'))
		s = 'vc12';    % VS2013
	elseif ~isempty(strfind(c.Version, '8.0'))
		s = 'vc11';    % VS2012
	elseif ~isempty(strfind(c.Version, '7.1'))
		s = 'vc10';    % VS2010
	elseif ~isempty(strfind(c.Version, '7.0')) || ~isempty(strfind(c.Version, '6.1'))
		s = 'vc9';    % VS2008
	elseif ~isempty(strfind(c.Version, '6.0'))
		s = 'vc8';    % VS2005
	else
		error('mexopencv:make', 'Unsupported compiler: %s', c.Name);
	end
% ...
```

---

@jstolle13:
Just to confirm, can you please run the following line in MATLAB, and post the exact output here?
``` matlab
>> cc = mex.getCompilerConfigurations('C++','Selected')
```

[1]: http://msdn.microsoft.com/en-US/windows/desktop/ff851942.aspx
[2]: http://msdn.microsoft.com/en-US/windows/desktop/bg162891.aspx
[3]: http://msdn.microsoft.com/en-US/windows/desktop/hh852363.aspx
[4]: http://www.microsoft.com/en-us/download/details.aspx?id=8279
[5]: http://www.microsoft.com/en-us/download/details.aspx?id=3138
[6]: http://www.microsoft.com/en-us/download/details.aspx?id=24826
[7]: http://www.microsoft.com/en-us/download/details.aspx?id=23719

**Comment by kyamagu** [comment]
@amroamroamro agreed.

We perhaps need to double-check if the compiler string always contains `Windows SDK`, since some old versions might be `Microsoft SDK`. Maybe using only `SDK` works.

**Comment by kyamagu** [comment]
@amroamroamro Thanks!

@jstolle13 You can now pull the latest `mexopencv` commit. Please post a comment if that fixes your problem.

**Comment by amroamroamro** [comment]
I thought I should mention this here: Microsoft has recently added [Visual Studio 2013 Community](http://www.visualstudio.com/en-us/products/visual-studio-community-vs) **for free**. This is equivalent in functionality to the full VS2013 Professional edition, without the limitations of the Express editions.

So if you are running Win7/Win8 (Vista and XP not supported), I suggest you get [VS2013 Community](http://www.visualstudio.com/) instead of working with *Windows SDK 7.1* (which includes an older C++ compiler).

**Comment by jstolle13** [comment]
Problem is fixed.

Thank you.
