### ISSUE TITLE
Unexpected Standard exception from MEX file.

### ISSUE THREAD

**Issue by SanchitAggarwal** [kyamagu/mexopencv#138]
I am using Matlab R2013a on mac. I have successfully compiled the mex file. But when I using Grabcut, I am getting the following error.

```
Error using cv.grabCut
Unexpected Standard exception from MEX file.
What() is:/Applications/opencv-2.4.9/modules/imgproc/src/grabcut.cpp:327: error: (-5) mask must have CV_8UC1 type in function
checkMask
```

I am new to mex and not able to figure out what might be the problem.
Kindly suggest something.

**Comment by amroamroamro** [comment]
You're probably calling the function with the wrong input...

Try calling: `[trimap, bgdmodel, fgdmodel] = cv.grabCut(img, mask, 'Init','Mask')` where:

- `img` is a `uint8` image of size NxMx3
- `mask` is a `uint8` matrix of size NxM (its values are one of: 0, 1, 2, or 3)

**Comment by SanchitAggarwal** [comment]
No, I am not calling with wrong inputs, I have used similar code in Linux machine and it was running fine. I guess I have messed up with mex setup on mac.

**Comment by ricardojdferreira** [comment]
It's happening the samething to me with findCirclesGrid.
Check out my open issue https://github.com/kyamagu/mexopencv/issues/179
