### ISSUE TITLE
matchFeatures(descriptors1,descriptors2) in Tutorial does not work

### ISSUE THREAD

**Issue by Mo-randn** [kyamagu/mexopencv#139]
Hi, 

I am just checking out the example. Unfortunately, the feature matching does not work, since Matlab can't find matchFeatures:

```
??? Undefined function or method 'matchFeatures' for input arguments of type 'single'.

Error in ==> feature_extraction at 17
index_pairs = matchFeatures(descriptors1,descriptors2);
```

The face detection example works fine for me.
I am using Matlab R2010b and OpenCV 2.4.1 on a 64 bit machine.

**Comment by kyamagu** [comment]
`matchFeatures` is [a function from Matlab's CV toolbox](http://www.mathworks.com/help/vision/ref/matchfeatures.html). Please contact Mathworks support.
