### ISSUE TITLE
problem with Makefile on Arch Linux

### ISSUE THREAD

**Issue by mljli** [kyamagu/mexopencv#144]
`pkg-config --libs opencv` gives the following output on my fresh-installed Arch Linux:

```
-lopencv_calib3d -lopencv_contrib -lopencv_core -lopencv_features2d -lopencv_flann -lopencv_gpu -lopencv_highgui -lopencv_imgproc -lopencv_legacy -lopencv_ml -lopencv_nonfree -lopencv_objdetect -lopencv_ocl -lopencv_photo -lopencv_stitching -lopencv_superres -lopencv_ts -lopencv_video -lopencv_videostab -ltbb /lib64/libXext.so /lib64/libX11.so /lib64/libICE.so /lib64/libSM.so /lib64/libGL.so /lib64/libGLU.so -lrt -lpthread -lm -ldl
```

Those '/lib64/*' items are processed incorrectly. I though the `CV_LDFLAGS` should be
```
CV_LDFLAGS  := $(filter-out $(LIB_SUFFIX),$(CV_LDFLAGS)) \
               $(addprefix -L, $(sort $(dir $(filter $(LIB_SUFFIX),$(CV_LDFLAGS))))) \
               $(patsubst lib%, -l%, \
               $(basename $(notdir $(filter $(LIB_SUFFIX),$(CV_LDFLAGS))))) 
```

But I'm not sure if this is correct for all the distros.

**Comment by amroamroamro** [comment]
That seems to work with all the patterns we've seen so far (#110, #137, #143, #132, and probably others)...

I say commit this change :)

**Comment by amroamroamro** [comment]
That seems to work with all the patterns we've seen so far (#110, #137, #143, #132, and probably others)...

I say commit this change :)

**Comment by kyamagu** [comment]
@mljli Thanks for your report and solution! [Could you make a pull-request?](https://help.github.com/articles/creating-a-pull-request/)

@amroamroamro Yes, this seems correct. Thanks for checking the past reports:)
