### ISSUE TITLE
How can I set mexopenCV to run 32 bits, although I have 64 bits machine?

### ISSUE THREAD

**Issue by meirela** [kyamagu/mexopencv#150]
How can I set mexopenCV to run 32 bits, although I have 64 bits machine?

It's just that I've done some work on a 32 bits machine, then moved to a 64 bits one and there are some problems such as:

    Error using cv.matchTemplate
    Attempt to execute SCRIPT matchTemplate as a function:

when calling `cv.matchTemplate`
(It is a function, after all...)

**Comment by kyamagu** [comment]
Compile the code before you run on a new platform.

**Comment by amroamroamro** [comment]
You cannot call 32-bit MEX-files `*.mexw32` from a 64-bit MATLAB, you'll have to recompile mexopencv from scratch to produce 64-bit MEX-files `*.mexw64`.

In fact this a general rule in that a 64-bit process cannot load a 32-bit module into its process space, and a 32-bit processes cannot load a 64-bit module into its process space.

**Comment by meirela** [comment]
thanks kyamagu for your quick response

but I did compile the code, with no errors

as for your reply, amroamroamro, I think that you may be wrong, as far as I know and experienced, MATLAB, as well as other platforms, is fully capable of running 32-bit process on a 64-bit machine...

![bits](https://cloud.githubusercontent.com/assets/12196398/7428268/489dbe98-eff6-11e4-901a-d72c3bf248ed.JPG)
http://www.mathworks.com/matlabcentral/answers/143754-64-bit-32-bit-compatible-standalone-app

**Comment by amroamroamro** [comment]
Yes I know, Windows has an interop layer called [WOW64](https://en.wikipedia.org/wiki/WoW64) that allows it to run 32-bit **processes** even on a 64-bit system.

What I said earlier is that a 64-bit **process** cannot load a 32-bit **modules** (as in a DLL or MEX-file) in its process space...

Meaning that 32-bit and 64-bit processes can co-exit and be running at the same time, but they cannot load modules/DLLs with a different bit-ness...

**Comment by meirela** [comment]
ohhhhh, I think I got it now...

so, if I would install a 32-bit MATLAB on my 64-bit machine, there should be no problem compiling it as a 32-bit process.
right?

**Comment by amroamroamro** [comment]
Like I said, you can install a 32-bit version of MATLAB on a 64-bit Windows, and run your existing 32-bit MEX-files...

But an easier option is to just recompile mexopencv to match your 64-bit version :)
