### ISSUE TITLE
Is cv.matchTemplate uses the CV::GPU implementation or the sequential one?

### ISSUE THREAD

**Issue by meirela** [kyamagu/mexopencv#151]
Is `cv.matchTemplate` uses the CV::GPU implementation or the sequential one?

I am willing to test it's performances against matlab's gpuArray of normxcorr2.

**Comment by amroamroamro** [comment]
No. mexopencv does not use the `gpu` module nor `ocl`.

You could check the source code yourself:
https://github.com/kyamagu/mexopencv/blob/master/src/%2Bcv/matchTemplate.cpp

**Comment by meirela** [comment]
Thanks

Would it be possible to "simply change" it, so it'd use the GPU library?
Or is it a whole compiling challenge with the MATLAB-mex-C-CUDA bundle?

**Comment by amroamroamro** [comment]
You can certainly try it. The code would be something like:

```cpp
#include <opencv2/gpu/gpu.hpp>        // GPU/CUDA stuff

{
    // matrix in main memory
    Mat mat = ...;

    // copy matrix from system memory to GPU memory
    gpu::GpuMat gpu_mat;
    gpu_mat.upload(mat);

    // call some GPU function
    gpu::matchTemplate(gpu_mat, ...);

    // transfer result back to host
    Mat result = gpu_mat;
    ...
}
```

Obviously you'll have to change the build scripts to link against the required gpu libs.

**Comment by meirela** [comment]
Thanks again!
Be sure I'll give it a try and update.

**Comment by codestamp** [comment]
What is the equivalent match template function for cv::cuda?

**Comment by amroamroamro** [comment]
@codestamp 
Looking at the [docs][4]:
- for opencv 2.x, that would be [`gpu::matchTemplate`][1].
- for opencv 3.x, you would first instantiate [`cv::cuda::TemplateMatching`][3] (using [`createTemplateMatching`][2]), then call its `match` method.

Note: as mentioned before, mexopencv does not use the gpu/cuda modules.

[1]: http://docs.opencv.org/2.4/modules/gpu/doc/image_processing.html#gpu-matchtemplate
[2]: http://docs.opencv.org/3.2.0/d0/d05/group__cudaimgproc.html#gad23350ed16d9b010d96c5ef76ccc29d0
[3]: http://docs.opencv.org/3.2.0/d2/d58/classcv_1_1cuda_1_1TemplateMatching.html
[4]: http://docs.opencv.org/

**Comment by codestamp** [comment]
Thanks @amroamroamro 

The code works like a charm. :-)

**Comment by codestamp** [comment]
Just in case someone like me need to have a peek at the code. It is here.

`void process() {
	cv::cuda::setDevice(0);	//initialize CUDA

	cv::Mat image_h =
			cv::imread(
					"/home/buddy/Documents/workspace/OpenCVTemplateMatch1/src/input_image.jpg");
	cv::Mat templ_h =
			cv::imread(
					"/home/buddy/Documents/workspace/OpenCVTemplateMatch1/src/template_image.jpg");

	cv::cuda::GpuMat templ_d(templ_h); //upload image on gpu
	cv::cuda::GpuMat image_d, result;

	if (image_h.empty())
		exit(1);

	image_d.upload(image_h);
	cv::Ptr<cv::cuda::TemplateMatching> alg = cv::cuda::createTemplateMatching(
			templ_h.type(), CV_TM_CCOEFF_NORMED);

	cv::cuda::GpuMat dst;
	alg->match(image_d, templ_d, result);

	cv::cuda::normalize(result, result, 0, 1, cv::NORM_MINMAX, -1);
	double max_value;

	cv::Point location;

	cv::cuda::minMaxLoc(result, 0, &max_value, 0, &location);


	//copying back to host memory for display
	cv::Mat result_h;
	result.download(result_h);

	//show now the two rectangles, one with the image and the other with matched template

	cv::rectangle(image_h, location,
			cv::Point(location.x + templ_h.cols, location.y + templ_h.rows),
			cv::Scalar::all(0), 2, 8, 0);
	cv::rectangle(result_h, location,
				cv::Point(location.x + templ_h.cols, location.y + templ_h.rows),
				cv::Scalar::all(0), 2, 8, 0);
	cv::imshow("Frame", result_h);
	cv::imshow("Image", image_h);

	cv::waitKey(0);

}`

**Comment by amroamroamro** [comment]
@codestamp Yep, that looks right.

If you want do it from MATLAB, write a MEX function similar to `matchTemplate.cpp` included with mexopencv, but modified to transfer data between host and device memory to call the GPU version.
Something like this:

### matchTemplateGPU.cpp

```cpp
#include "mexopencv.hpp"
#include "opencv2/cudaimgproc.hpp"
using namespace std;
using namespace cv;

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    nargchk(nrhs>=2 && (nrhs%2)==0 && nlhs<=1);
    vector<MxArray> rhs(prhs, prhs+nrhs);

    int method = cv::TM_SQDIFF;
    for (int i=2; i<nrhs; i+=2) {
        // [..option parsing..]
    }

    Mat image(rhs[0].toMat(rhs[0].isUint8() ? CV_8U : CV_32F)),
        templ(rhs[1].toMat(rhs[1].isUint8() ? CV_8U : CV_32F)),
        result;
    cuda::GpuMat image_d(image), templ_d(templ), result_d;
    Ptr<cuda::TemplateMatching> alg = cuda::createTemplateMatching(templ_d.type(), method);
    alg->match(image_d, templ_d, result_d);
    result_d.download(result);
    plhs[0] = MxArray(result);
}
```

Keep in mind the overhead involved in moving data around, which could negate the performance advantage of using the GPU.

**Comment by codestamp** [comment]
Hi @amroamroamro , great to see the code in Matlab. I agree that the memory overhead bet CPU <-> GPU transfer need to be avoided as much as possible. One of the popular method in CUDA is to collect all compute intensive tasks (even that are simple) and run them on the GPUs in a single kernel.
