### ISSUE TITLE
In matchTemplate, what is methodValue?

### ISSUE THREAD

**Issue by charismaticchiu** [kyamagu/mexopencv#152]
In the function cv.matchTemplate, what is methodValue?
I do not see any hint about the input parameter.
Can someone tell me? Thanks!

**Comment by kyamagu** [comment]
help cv.matchTemplate

  * __Method__ Parameter specifying the comparison method. One of the following:
          'SqDiff'        Squared difference
          'SqDiffNormed'  Normalized squared difference
          'CCorr'         Cross correlation
          'CCorrNormed'   Normalized cross correlation
          'CCoeff'        Cosine efficient
          'CCoeffNormed'  Normalized cosine efficient

**Comment by amroamroamro** [comment]
@charismaticchiu: In addition to the included [help in mexopencv][1], it's also a good idea to check the [OpenCV docs][2] of the function in question, which in this case gives you the equations of the available comparison methods.

[1]: http://kyamagu.github.io/mexopencv/matlab/matchTemplate.html
[2]: http://docs.opencv.org/modules/imgproc/doc/object_detection.html#matchtemplate

**Comment by charismaticchiu** [comment]
Thanks, it seems that I misunderstood the usage.
I thought it was like cv.template(image, tmpl,  'CCorr', methodValue) or so.
Thanks for enlighten me.
