### ISSUE TITLE
Error in mexopencv.make (line 149)

### ISSUE THREAD

**Issue by sbowman487** [kyamagu/mexopencv#153]
I get this error after running mexopencv.make('opencv_path','C:\Program Files\opencv\build').  I've tried using multiple versions of MATLAB, Visual Studio, and OpenCV.  I get the same error every time and have no idea what's going on.  I've even tried on multiple machines, one PC running Windows 7 the other a Mac running Windows 7 through Parallels 10.  The full error is listed below, any help is greatly appreciated.

mex -largeArrayDims   -I'\\psf\Home\Downloads\kyamagu-mexopencv-24b0b0c\include' -I'c:\opencv\build\include' -L'c:\opencv\build\x64\vc12\lib'  -lopencv_calib3d2410 -lopencv_contrib2410 -lopencv_core2410 -lopencv_features2d2410 -lopencv_flann2410 -lopencv_gpu2410 -lopencv_highgui2410 -lopencv_imgproc2410 -lopencv_legacy2410 -lopencv_ml2410 -lopencv_nonfree2410 -lopencv_objdetect2410 -lopencv_ocl2410 -lopencv_photo2410 -lopencv_stitching2410 -lopencv_superres2410 -lopencv_ts2410 -lopencv_video2410 -lopencv_videostab2410 '\\psf\Home\Downloads\kyamagu-mexopencv-24b0b0c\src\+cv\drawMatches.cpp' '\\psf\Home\Downloads\kyamagu-mexopencv-24b0b0c\lib\MxArray.obj' -output '\\psf\Home\Downloads\kyamagu-mexopencv-24b0b0c\+cv\drawMatches'
Building with 'Microsoft Visual C++ 2013 Professional'.
Error using mex
   Creating library \\psf\Home\Downloads\kyamagu-mexopencv-24b0b0c\+cv\drawMatches.lib and object
   \\psf\Home\Downloads\kyamagu-mexopencv-24b0b0c\+cv\drawMatches.exp
drawMatches.obj : error LNK2019: unresolved external symbol "public: class std::vector<struct
cv::DMatch,class std::allocator<struct cv::DMatch> > __cdecl MxArray::toVector<struct cv::DMatch>(void)const
" (??$toVector@UDMatch@cv@@@MxArray@@QEBA?AV?$vector@UDMatch@cv@@V?$allocator@UDMatch@cv@@@std@@@std@@XZ)
referenced in function mexFunction
\\psf\Home\Downloads\kyamagu-mexopencv-24b0b0c\+cv\drawMatches.mexw64 : fatal error LNK1120: 1 unresolved
externals

Error in mexopencv.make (line 149)
            if ~opts.dryrun, eval(cmd); end

**Comment by amroamroamro** [comment]
You say you're running `mexopencv.make('opencv_path','C:\Program Files\opencv\build')` but the output shown does not reflect that as it's using a different path for OpenCV: `c:\opencv\build`.

Can you double check that? Also might wanna run `mexopencv.make('clean',true)` first...

**Comment by sbowman487** [comment]
^^^  This guy.  Correct on both counts.  Thanks for the speedy help Amro!

**Comment by hgras** [comment]
I have the same problem. My opencv is at c and I have same issue
compiler is visual studio 11 x86
Error:

  C:\PROGRA~1\MATLAB\R2013A\BIN\MEX.PL: Error: Compile of 'C:\Users\Hgras\Desktop\mexopencv-master\mexopencv-master\src\mexopencv_features2d.cpp' failed. 
 
Error using mex (line 206)
Unable to complete successfully.

Error in mexopencv.make (line 153)
            if ~opts.dryrun, eval(cmd); end

**Comment by sbowman487** [comment]
Try mexopencv.make('clean',true)

**Comment by hgras** [comment]
It was not the problem, it tried it. The problem was using 2.4.9 opencv. I fixed it using opencv3

**Comment by hgras** [comment]
Thanks for you interest
