### ISSUE TITLE
Compatibility with OpenCV 3: namespace changes (list of .cpp that fail to build)

### ISSUE THREAD

**Issue by Dev-iL** [kyamagu/mexopencv#154]
Hello Everybody,

I recently wanted to use new functions added in OpenCV 3 (hereinafter "v3") and figured I might as well just replace v2 with v3 altogether and see if it works. Then, I tried building the `mex` files (using `mexopencv.make`) as per [the tutorial](https://www.youtube.com/watch?v=RQHQQWTqT8g&feature=youtu.be&list=PLmcMMZCV897pofUfG1yH-8fcjpUTFUSaJ&t=121). While many files compiled correctly, some (which compile just fine with v2) failed with various errors (as is also mentioned in other issues in this repository). From my limited understanding of C++ it seems that v3 introduced changes to namespaces which cause most of the compilation errors. While I have no idea how to fix such errors, I would gladly do it if anybody would kindly explain to me how.

I thought it might be useful to mention which of mexopencv's `.cpp` files currently fail to build. It is my sincere hope that this list will help get mexopencv ready for the release of v3.

For convenience, here's a reference to the [docs about the namespace structure in OpenCV 3.0rc1](http://docs.opencv.org/3.0-rc1/namespaces.html).

#### List of files with mex errors + error snippets (as of 13-May-15):
- [x] __MSER.cpp(67)__ : `error C2259: 'cv::MSER' : cannot instantiate abstract class due to following members: ...`
- [x] __ORB.cpp(30)__ : `error C2259: 'cv::ORB' : cannot instantiate abstract class due to following members: ...`
- [x] ~~__SIFT.cpp(8)__ : `fatal error C1083: Cannot open include file: 'opencv2/nonfree/nonfree.hpp': No such file or directory`~~ became optional with `opencv_contrib`
- [x] ~~__SURF.cpp(8)__ : `fatal error C1083: Cannot open include file: 'opencv2/nonfree/nonfree.hpp': No such file or directory`~~ became optional with `opencv_contrib`
- [x] ~~__StarDetector.cpp(51)__ : `error C2065: 'StarDetector' : undeclared identifier`~~
- [x] ~~__calcGlobalOrientation.cpp(34)__ : `error C3861: 'calcGlobalOrientation': identifier not found`~~ became optional with `opencv_contrib`
- [x] ~~__calcMotionGradient.cpp(41)__ : `error C3861: 'calcMotionGradient': identifier not found`~~ became optional with `opencv_contrib`
- [x] ~~__segmentMotion.cpp(33)__ : `error C3861: 'segmentMotion': identifier not found`~~ became optional with `opencv_contrib`
- [x] __solvePnP.cpp(15)__ : `error C2039: 'ITERATIVE' : is not a member of 'cv'`
- [x] __solvePnPRansac.cpp(15)__ : `error C2039: 'ITERATIVE' : is not a member of 'cv'`
- [x] __stereoCalibrate.cpp(174)__ : `error C2664: cannot convert argument 13 from 'cv::TermCriteria' to 'int'`
- [x] ~~__updateMotionHistory.cpp(31)__ : `error C3861: 'updateMotionHistory': identifier not found`~~ became optional with `opencv_contrib`
- [x] __ANN_MLP_.cpp(16)__ : `error C2065: 'CvANN_MLP' : undeclared identifier`
- [x] __BOWImgDescriptorExtractor_.cpp(8)__ : `fatal error C1083: Cannot open include file: 'opencv2/nonfree/nonfree.hpp': No such file or directory`
- [x] __BOWKMeansTrainer_.cpp(89)__ : `error C2039: 'descripotorsCount' : is not a member of 'cv::BOWKMeansTrainer'`
- [x] __BackgroundSubtractorMOG2_.cpp(57)__ : `error C2259: 'cv::BackgroundSubtractorMOG2' : cannot instantiate abstract class due to following members: ...`
- [x] __BackgroundSubtractorMOG_.cpp(57)__ : `error C2259: 'cv::BackgroundSubtractorMOG2' : cannot instantiate abstract class due to following members: ...`
- [x] __Boost_.cpp(16)__ : `error C2065: 'CvBoost' : undeclared identifier`
- [x] __DTree_.cpp(16)__ : `error C2065: 'CvDTree' : undeclared identifier`
- [x] __DescriptorExtractor_.cpp(8)__ : `fatal error C1083: Cannot open include file: 'opencv2/nonfree/nonfree.hpp': No such file or directory`
- [x] __DescriptorMatcher_.cpp(9)__ : `fatal error C1083: Cannot open include file: 'opencv2/nonfree/nonfree.hpp': No such file or directory`
- [x] __EM_.cpp(17)__ : `error C2065: 'EM' : undeclared identifier`
- [x] ~~__ERTrees_.cpp(16)__ : `error C2065: 'CvERTrees' : undeclared identifier`~~ temporarily disabled
- [x] __FeatureDetector_.cpp(9)__ : `fatal error C1083: Cannot open include file: 'opencv2/nonfree/nonfree.hpp': No such file or directory`
- [x] ~~__GBTrees_.cpp(16)__ : `error C2065: 'CvGBTrees' : undeclared identifier`~~ temporarily disabled
- [x] __KNearest_.cpp(16)__ : `error C2065: 'KNearest' : undeclared identifier`
- [x] __LatentSvmDetector_.cpp(16)__ : `error C2065: 'LatentSvmDetector' : undeclared identifier`
- [x] __NormalBayesClassifier_.cpp(16)__ : `error C2065: 'NormalBayesClassifier' : undeclared identifier`
- [x] __RTrees_.cpp(16)__ : `error C2065: 'CvRTrees' : undeclared identifier`
- [x] __SVM_.cpp(16)__ : `error C2065: 'SVM' : undeclared identifier`
- [x] __StereoBM_.cpp(14)__ : `error C2039: 'BASIC_PRESET' : is not a member of 'cv::StereoBM'`
- [x] __StereoSGBM_.cpp(37)__ : `error C2259: 'cv::StereoSGBM' : cannot instantiate abstract class
        due to following members: ...`

* Edit1: Forgot to include `MSER.cpp`
* Edit2: (13-May-15): Crossed off many errors from the list based on the modifications in #157 
* Edit3: (15-May-15): Crossed off the rest of the errors. There now seems to be a problem with the `opencv_contrib` modules where the `#include "opencv2/***.hpp"` is not resolved properly, due to possible missing `-I` flag for `OPENCV_ROOT\opencv_contrib\modules\***\include` (where the correct `opencv2` is located).

**Comment by amroamroamro** [comment]
As it so happens, I've recently started looking into this on my end :)
I downloaded 3.0.0-rc1 and starting working against it.

I've managed to fix most of the points you listed, I still have a couple of things to go through (mainly functions from the `ml` module which was greatly rewritten).
I will push a branch soon, let me just clean it up a bit...

Most of the modifications consists of:
- fix inclusion of modules headers from `#include "opencv2/<module>/<module>.hpp"` to `#include "opencv2/<module>.hpp"`
- some enums/constants changed names
- instantiating most of the classes now happens on the heap instead of stack using static factory methods: `Ptr<SomeClass> obj = SomeClass::create()`
- class properties are now accessed using strongly-typed getters/setters: `obj.getXX()` and `obj.setXXX(..)` rather than the generic get/set `obj.get<T>('XXX')`
- a couple of functions were either moved to `opencv_contrib` or removed completely.

This is explained in more details in this [transition guide](http://docs.opencv.org/3.0-rc1/db/dfa/tutorial_transition_guide.html).

**Comment by Dev-iL** [comment]
@amroamroamro Splendid! Is there any way I could buy you a beer? :)

@kyamagu - Back to matter at hand - may I suggest that opencv2 and opencv3 be split into two distinct branches? I could then fork and upload my custom `.cpp` to the appropriate branch.

**Comment by kyamagu** [comment]
@amroamroamro Big thanks to you!

@Dev-iL Sure, I will prepare a new branch for OpenCV 2.x and 3.x. My expectation is that the master branch should be there for 3.x in the future.

My initial thought on 3.x was that the official OpenCV started to include the matlab module and maybe mexopencv would soon receive the end of life. The official matlab module has an advantage of automatically generating the wrappers and up-to-date help documents. But now that the official module is in the contrib repo and seems difficult to use for beginners. Perhaps it is better to continue maintaining mexopencv for some more extended period of time. I will try to keep accepting community contributions.

**Comment by kyamagu** [comment]
v3.0 branch is the playground for OpenCV 3.x.

**Comment by amroamroamro** [comment]
@kyamagu, @Dev-iL: checkout #157

**Comment by Dev-iL** [comment]
@amroamroamro - Very impressive! I've updated the error list.

**Comment by amroamroamro** [comment]
@Dev-iL: here's the new PR #158 to cross the rest of the list.

**NOTE:** `ERTrees` and `GBTrees` are actually missing from OpenCV itself, so there is no way to fix those for the time being (I've kept them in mexopencv for now, waiting to see if they will be added back in OpenCV by the time 3.0 final is released...)
