### ISSUE TITLE
Cannot open include file opencv2/core.hpp

### ISSUE THREAD

**Issue by SailingDreams** [kyamagu/mexopencv#171]
I'm using msvc 2013 on Windows 7. 
I downloaded windows opencv http://opencv.org/
Openvc 3.0.0 is installed in e:\opencv\opencv
mexopencv is installed in e:\opencv\mexopencv
My PATH has E:\opencv\opencv\build\x64\vc12\bin

I've edited the make.m path
```
opts.opencv_path = 'e:\opencv\opencv';  % OpenCV location
```
The first error I got said 
```
Error using mexopencv.make>pkg_config (line 197)
OpenCV include path not found: e:\opencv\opencv\include
```
Since include has the path "E:\opencv\opencv\sources\include", I added "sources" to the make.m code
```
I_path = fullfile(opts.opencv_path,'sources\include');
```

Then I got an error on finding the lib directory
```
Error using mexopencv.make>pkg_config (line 202)
OpenCV library path not found: e:\opencv\opencv\x64\vc12\lib
```

Since the lib is in "e:\opencv\opencv\x64\vc12\lib", I added "build" to the following code
```
L_path = fullfile(opts.opencv_path,'build',arch_str(),compiler_str(),'lib');
```

Now when I run mexopencv.make, I get the error below
```
Error using mex MxArray.cpp
E:\opencv\opencv\sources\include\opencv2\opencv.hpp(46) 
: fatal error C1083: Cannot open include file: 'opencv2/core.hpp': 
No such file or directory
```

Matlab errors at the code 
```
if ~opts.dryrun, eval(cmd); end
```
where cmd = 
```
mex -largeArrayDims   -I'e:\opencv\mexopencv\include' -I'e:\opencv\opencv\sources\include' 
-L'e:\opencv\opencv\build\x64\vc12\lib'  -lopencv_ts300 -lopencv_world300 
-c 'e:\opencv\mexopencv\src\MxArray.cpp' -outdir 'e:\opencv\mexopencv\lib'
```

It seems that either the opencv 3.0.0 version I have (verified by checking version.hpp) has a different directory structure, or more likely, I've incorrectly installed something. At this point I've changed enough to dig myself into a deeper hole, so I hope someone can tell me the minor setup step that I missed. 

Thanks for your help.

**Comment by SailingDreams** [comment]
Update:
I added -I'e:\opencv\opencv\build\include" to the build string and now I get pass the include errors. 

However, I now get the error below. Hopefully this issue has already been posted.

```
e:\opencv\opencv\build\include\opencv2/hal/defs.h(278) : error C2144: syntax
error : 'unsigned int' should be preceded by ';'
e:\opencv\opencv\build\include\opencv2/hal/defs.h(278) : error C4430: missing
type specifier - int assumed. Note: C++ does not support default-int
e:\opencv\mexopencv\src\MxArray.cpp(377) : warning C4267: 'argument' :
conversion from 'size_t' to 'int', possible loss of data
e:\opencv\mexopencv\src\MxArray.cpp(388) : warning C4267: 'argument' :
conversion from 'size_t' to 'int', possible loss of data
e:\opencv\mexopencv\src\MxArray.cpp(406) : warning C4267: 'argument' :
conversion from 'size_t' to 'int', possible loss of data
```

**Comment by amroamroamro** [comment]
@SailingDreams 
The correct way is to invoke the `make.m` script directly passing the path, without having to edit anything:

```matlab
>> cd('e:\opencv\mexopencv')
>> addpath('e:\opencv\mexopencv')
>> mexopencv.make('opencv_path','e:\opencv\opencv\build')
```

You don't need to edit any file, and you can keep the original directory structure created by the official OpenCV installer/unpacker.

mexopencv doesn't use the OpenCV sources directly, it only requires the pre-built binaries and headers in the "build" directory.

**Comment by SailingDreams** [comment]
That's a good point. I thought I had to build it but I guess I don't. 

I tried your steps below but get the same error. I think I'll quit trying to build it and just get on with using the built dlls. Thanks for your help.

```
K>> cd('e:\opencv\mexopencv')
K>> addpath('e:\opencv\mexopencv')
K>> mexopencv.make('opencv_path','e:\opencv\opencv\build')
Error using mexopencv.make>pkg_config (line 197)
OpenCV include path not found: e:\opencv\opencv\build\sources\include

Error in mexopencv.make (line 107)
    [cv_cflags,cv_libs] = pkg_config(opts);
 
197         error('mexopencv:make', 'OpenCV include path not found: %s', I_path);
```

Here's what I get if I remove the "build" from the string. I brings me to the build error I got to on the previous post (but without the make.m edits), but like you said, I can use the binaries as is.
```
K>> mexopencv.make('opencv_path','e:\opencv\opencv\')
mex -largeArrayDims   -I'e:\opencv\mexopencv\include' -I'e:\opencv\opencv\sources\include' -I'e:\opencv\opencv\build\include' -L'e:\opencv\opencv\build\x64\vc12\lib'  -lopencv_ts300 -lopencv_world300 -c 'e:\opencv\mexopencv\src\MxArray.cpp' -outdir 'e:\opencv\mexopencv\lib'
Building with 'Microsoft Visual C++ 2013 Professional'.
Error using mex
MxArray.cpp
e:\opencv\opencv\build\include\opencv2/hal/defs.h(278) : error C2144: syntax
error : 'unsigned int' should be preceded by ';'
e:\opencv\opencv\build\include\opencv2/hal/defs.h(278) : error C4430: missing
type specifier - int assumed. Note: C++ does not support default-int
e:\opencv\mexopencv\src\MxArray.cpp(377) : warning C4267: 'argument' :
conversion from 'size_t' to 'int', possible loss of data
e:\opencv\mexopencv\src\MxArray.cpp(388) : warning C4267: 'argument' :
conversion from 'size_t' to 'int', possible loss of data
e:\opencv\mexopencv\src\MxArray.cpp(406) : warning C4267: 'argument' :
conversion from 'size_t' to 'int', possible loss of data
e:\opencv\mexopencv\src\MxArray.cpp(409) : warning C4267: 'argument' :
```

**Comment by amroamroamro** [comment]
Please revert all changes you've made, restore OpenCV folders to their original location, and try my instructions again... If you think you missed up something, just start over with a pristine copy :)

**Comment by SailingDreams** [comment]
Success! Thanks a bunch amroamroamro

I restored the mexopencv, then re-installed Opencv and the compile worked using 
```
mexopencv.make('opencv_path','e:\opencv\opencv\build')
```
For anyone else having this issue, my folder structure is below
```
e:\opencv
    - \mexopencv
        -\+cv
        -\+mexopencv
        -\doc
        etc
    - \opencv
        -\build
        -\sources
```
