### ISSUE TITLE
Complie Error In matlab

### ISSUE THREAD

**Issue by morepoch** [kyamagu/mexopencv#172]
I'm using Win8.1 64bit, VS 2013, opencv 3.0, when I try to build in matlab, I come with the following error:

>>mexopencv.make
Skipped "F:\Download\mexopencv-master\mexopencv-master\src\MxArray.cpp"
mex -largeArrayDims   -I'F:\Download\mexopencv-master\mexopencv-master\include' -I'D:\research\library\opencv\build\include' -L'D:\research\library\opencv\build\x64\vc12\lib'  -lopencv_ts300 -lopencv_world300 -c 'F:\Download\mexopencv-master\mexopencv-master\src\mexopencv_features2d.cpp' -outdir 'F:\Download\mexopencv-master\mexopencv-master\lib'
Building with 'Microsoft Visual C++ 2013 Professional'.
Error using mex
mexopencv_features2d.cpp
F:\Download\mexopencv-master\mexopencv-master\include\mexopencv_features2d.hpp(15)
: error C4430: missing type specifier - int assumed. Note: C++ does not support
default-int
F:\Download\mexopencv-master\mexopencv-master\include\mexopencv_features2d.hpp(15)
: error C2143: syntax error : missing ';' before ':'
F:\Download\mexopencv-master\mexopencv-master\include\mexopencv_features2d.hpp(15)
: error C2017: illegal escape sequence
F:\Download\mexopencv-master\mexopencv-master\include\mexopencv_features2d.hpp(15)
: error C2146: syntax error : missing ';' before identifier 'mexopencv'
F:\Download\mexopencv-master\mexopencv-master\include\mexopencv_features2d.hpp(15)
: error C2143: syntax error : missing ';' before '-'
F:\Program Files\VS2013\VC\INCLUDE\xfunctional(21) : error C2143: syntax error :
missing ';' before '{'
F:\Program Files\VS2013\VC\INCLUDE\xfunctional(21) : error C2447: '{' : missing
function header (old-style formal list?)
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(490) : error
C2039: 'const_mem_fun_ref_t' : is not a member of 'std'
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(490) : error
C2365: 'MxArray::toVector' : redefinition; previous definition was 'member
function'
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(490) : error
C2988: unrecognizable template declaration/definition
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(490) : error
C2059: syntax error : 'const'
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(494) : error
C2334: unexpected token(s) preceding '{'; skipping apparent function body
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(498) : error
C2988: unrecognizable template declaration/definition
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(498) : error
C2059: syntax error : 'return'
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(498) : error
C2238: unexpected token(s) preceding ';'
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(502) : error
C2146: syntax error : missing ';' before identifier 'toPoint3f'
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(116) : error
C2614: 'MxArray' : illegal member initialization: 'p_' is not a base or member
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(120) : error
C2039: 'p_' : is not a member of 'MxArray'
        f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(111) :
        see declaration of 'MxArray'
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(120) : error
C2614: 'MxArray' : illegal member initialization: 'p_' is not a base or member
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(316) : error
C2065: 'p_' : undeclared identifier
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(320) : error
C2065: 'p_' : undeclared identifier
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(326) : error
C2065: 'p_' : undeclared identifier
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(502) : error
C2270: 'toPoint3f' : modifiers not allowed on nonmember functions
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(502) : error
C4430: missing type specifier - int assumed. Note: C++ does not support
default-int
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(502) : error
C2065: 'toPoint3_' : undeclared identifier
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(502) : error
C2062: type 'float' unexpected
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(502) : warning
C4508: 'toPoint3f' : function should return a value; 'void' return type assumed
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(506) : error
C2270: 'toSize' : modifiers not allowed on nonmember functions
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(506) : error
C2065: 'toSize_' : undeclared identifier
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(506) : error
C2062: type 'int' unexpected
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(510) : error
C2270: 'toRect' : modifiers not allowed on nonmember functions
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(510) : error
C2065: 'toRect_' : undeclared identifier
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(510) : error
C2062: type 'int' unexpected
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(514) : error
C2270: 'toScalar' : modifiers not allowed on nonmember functions
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(514) : error
C2065: 'toScalar_' : undeclared identifier
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(514) : error
C2062: type 'double' unexpected
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(518) : error
C2270: 'classID' : modifiers not allowed on nonmember functions
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(518) : error
C2065: 'p_' : undeclared identifier
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(523) : error
C2270: 'className' : modifiers not allowed on nonmember functions
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(524) : error
C2065: 'p_' : undeclared identifier
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(529) : error
C2270: 'numel' : modifiers not allowed on nonmember functions
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(529) : error
C2065: 'p_' : undeclared identifier
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(533) : error
C2270: 'ndims' : modifiers not allowed on nonmember functions
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(533) : error
C2065: 'p_' : undeclared identifier
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(537) : error
C2270: 'dims' : modifiers not allowed on nonmember functions
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(537) : error
C2065: 'p_' : undeclared identifier
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(541) : error
C2270: 'rows' : modifiers not allowed on nonmember functions
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(541) : error
C2065: 'p_' : undeclared identifier
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(548) : error
C2270: 'cols' : modifiers not allowed on nonmember functions
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(548) : error
C2065: 'p_' : undeclared identifier
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(552) : error
C2270: 'nfields' : modifiers not allowed on nonmember functions
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(552) : error
C2065: 'p_' : undeclared identifier
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(557) : error
C2270: 'fieldname' : modifiers not allowed on nonmember functions
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(561) : error
C2270: 'fieldnames' : modifiers not allowed on nonmember functions
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(566) : error
C2270: 'nzmax' : modifiers not allowed on nonmember functions
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(566) : error
C2065: 'p_' : undeclared identifier
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(575) : error
C2270: 'subs' : modifiers not allowed on nonmember functions
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(584) : error
C2270: 'subs' : modifiers not allowed on nonmember functions
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(589) : error
C2270: 'isNull' : modifiers not allowed on nonmember functions
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(589) : error
C2065: 'p_' : undeclared identifier
f:\download\mexopencv-master\mexopencv-master\include\MxArray.hpp(593) : error
C2270: 'isCell' : modifiers not allowed on nonmember functions
f:\download\mexopencv-maste
Error in mexopencv.make (line 130)
            if ~opts.dryrun, eval(cmd); end

**Comment by amroamroamro** [comment]
huh... It sounds like there's a syntax error!

Assuming there are no local changes on your side, what revision are you on?

```
git rev-parse HEAD
```

**Comment by morepoch** [comment]
I didn't change any of the src code, simply download the file and try to compile it with mexopencv.make('opencv_path','my_path').
I'm pretty sure the opencv path is added in environmental variables.

**Comment by amroamroamro** [comment]
May I ask which OpenCV you're using? Is it the official installer (downloaded from [here](http://sourceforge.net/projects/opencvlibrary/files/opencv-win/3.0.0/)), or is it custom built from source?

fwiw I have the same configuration as you (Win8.1 + VS2013 + OpenCV 3.0.0) with the latest MATLAB R2015a...

**Comment by morepoch** [comment]
I'm also using opencv 3.0.0, I forget how to build it. So I re install the opencv3.0.0 from the offical installer. Then I try to build the mexopencv again, this time there's no previous errors, and it successfully generate several mexw64, but I come to the following errors:

..........
Building with 'Microsoft Visual C++ 2013 Professional'.
MEX completed successfully.
mex -largeArrayDims   -I'D:\research\library\mexopencv-master\include' -I'D:\research\library\opencv\build\include' -L'D:\research\library\opencv\build\x64\vc12\lib'  -lopencv_ts300 -lopencv_world300 'D:\research\library\mexopencv-master\src\+cv\HuMoments.cpp' 'D:\research\library\mexopencv-master\lib\MxArray.obj' 'D:\research\library\mexopencv-master\lib\mexopencv_features2d.obj' -output 'D:\research\library\mexopencv-master\+cv\HuMoments'
Building with 'Microsoft Visual C++ 2013 Professional'.
Error using mex
Microsoft (R) Manifest Tool version 6.3.9600.17298

Copyright (c) Microsoft Corporation 2012.

All rights reserved.

mt : general error c101008d: Failed to write the updated manifest to the resource
of file "D:\research\library\mexopencv-master\+cv\HuMoments.mexw64". Access is
denied.

**Comment by amroamroamro** [comment]
@morepoch:
That might happen if you already ran that MEX-function in the same session, and tried to recompile it while the file is still locked and in use...

I suggest you restart MATLAB, and build mexopencv again (it will continue where it left off).

**Comment by morepoch** [comment]
Thanks a lot, that works.
