### ISSUE TITLE
BackgroundSubtractorMOG not available

### ISSUE THREAD

**Issue by ShakedDovrat** [kyamagu/mexopencv#173]
Unable to use BackgroundSubtractorMOG (only BackgroundSubtractorMOG2). I used BackgroundSubtractorMOG in previous versions and now it's gone.
I've tried to import it from my older version but the compilation failed.

Can anyone please explain/help me?

**Comment by amroamroamro** [comment]
@ShakedDovrat 
In OpenCV 3.0, some functions and classes (including `BackgroundSubtractorMOG`, `SIFT`, `SURF`, ...) were moved out of the [main](https://github.com/Itseez/opencv) distribution into a separate repository of extra modules [`opencv_contrib`](https://github.com/Itseez/opencv_contrib).

So if you want to use those, you have to compile OpenCV from source yourself (by default they are not released as part of the official OpenCV distribution). You enable these optional modules at compile time, by telling CMake to build them in addition to the base ones...

I previously explained the steps to build it on Windows, see [here](https://github.com/kyamagu/mexopencv/issues/162#issuecomment-107305516). Note that I was using the RC version at the time, but the instructions still apply by simply using the final 3.0.0 version instead (so ignore the download links in that post).

@kyamagu 
Perhaps we should create a Wiki page explaining how to get opencv + opencv_contrib to compile on Windows, Linux, and Mac.

**Comment by kyamagu** [comment]
@amroamroamro Sure about [the Wiki page](https://github.com/kyamagu/mexopencv/wiki).

**Comment by amroamroamro** [comment]
@kyamagu
Great, I see you already started it :)
I'll see if I can add some screenshots to make it beginner-friendly.

**Comment by amroamroamro** [comment]
@ShakedDovrat 
Done, please try the instructions in Wiki page: https://github.com/kyamagu/mexopencv/wiki

**Comment by ShakedDovrat** [comment]
@kyamagu @amroamroamro Thanks a lot guys! I'll try this soon.
