### ISSUE TITLE
Ubuntu 14.04 Build errors

### ISSUE THREAD

**Issue by petteriTeikari** [kyamagu/mexopencv#175]
I got errors with the following files when running make Ubuntu 14.04 64-bit, Matlab 2015a and openCV 3.0.0

AgastFeatureDetector_
AKAZE_
BOWImgDescriptorExtractor_
BRISK_
DescriptorExtractor_.
etc. 

e.g. 

<code>/tmp/mex_46242412008003_9130/AgastFeatureDetector_.o: In function `mexFunction':
AgastFeatureDetector_.cpp:(.text+0x31cb): undefined reference to `createAgastFeatureDetector(__gnu_cxx::__normal_iterator<MxArray const*, std::vector<MxArray, std::allocator<MxArray> > >, __gnu_cxx::__normal_iterator<MxArray const*, std::vector<MxArray, std::allocator<MxArray> > >)'
collect2: error: ld returned 1 exit status
make: *** [+cv/private/AgastFeatureDetector_.mexa64] Error 255</code>

And then stopped cut+pasting them away from /mexopencv/src/+cv/private. Any idea what is going on there? For example "ANN_MLP_.cpp" compiled okay?

**Comment by amroamroamro** [comment]
Since we moved to OpenCV 3.0, the `Makefile` has not yet been updated to compile the new `mexopencv_features2d.cpp` file (which defines shared functionality used by classes and functions from the `features2d` module). Same for files in the `opencv_contrib` sub-directory which are not yet handled by the makefile.

So far I've been testing on Windows (where we use the MATLAB script `make.m` rather than the Makefile to build everything). I'll see if I can fix it...

**Comment by petteriTeikari** [comment]
Okay, thanks for the clarification. The build was successful when removing those problematic files and I can wait for the fix then :)

**Comment by amroamroamro** [comment]
@petteriTeikari 
Could you try the following pull request #176 on your platform, and see if I missed anything?

**Comment by petteriTeikari** [comment]
Thanks for the update @amroamroamro , but the make failed at the same file:

<code>
/tmp/mex_6939390917396_28878/AgastFeatureDetector_.o: In function `mexFunction':
AgastFeatureDetector_.cpp:(.text+0x31cb): undefined reference to `createAgastFeatureDetector(__gnu_cxx::__normal_iterator<MxArray const*, std::vector<MxArray, std::allocator<MxArray> > >, __gnu_cxx::__normal_iterator<MxArray const*, std::vector<MxArray, std::allocator<MxArray> > >)'
collect2: error: ld returned 1 exit status
make: *** [+cv/private/AgastFeatureDetector_.mexa64] Error 255
</code>

**Comment by amroamroamro** [comment]
@petteriTeikari: Did you make sure to run `make clean` first? Since `libMxArray.a` already exists, it might not have detected the change in dependencies...

**Comment by petteriTeikari** [comment]
Thanks for the update @amroamroamro , now the build went through as I thought that the source had been updated but it had not, but now it works :)

**Comment by amroamroamro** [comment]
Good to hear, thanks for testing it.
