### ISSUE TITLE
compile issue: undefined reference to createAgastFeatureDetector

### ISSUE THREAD

**Issue by jeremy-rutman** [kyamagu/mexopencv#177]
Hi 
I am running openCV3.0 on ubuntu14.04 . I downloaded the master branch of mexopencv, edited Makefile to point to my matlab install dir ('MATLABDIR   := /usr/local/MATLAB/R2015a'  - I took out the question mark) and now when I run 'make' , I go thru a long series of succesful compiles then hit 

```
Building with 'g++'.
MEX completed successfully.
/usr/local/MATLAB/R2015a/bin/mex -cxx -largeArrayDims -Iinclude -I/usr/local/include/opencv -I/usr/local/include   src/+cv/private/AgastFeatureDetector_.cpp -lMxArray -Llib -L/usr/local/lib -lopencv_shape -lopencv_stitching -lopencv_objdetect -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_core -lopencv_hal   -output +cv/private/AgastFeatureDetector_
Building with 'g++'.
/tmp/mex_52071645600973_25550/AgastFeatureDetector_.o: In function `mexFunction':
AgastFeatureDetector_.cpp:(.text+0x2890): undefined reference to `createAgastFeatureDetector(__gnu_cxx::__normal_iterator<MxArray const*, std::vector<MxArray, std::allocator<MxArray> > >, __gnu_cxx::__normal_iterator<MxArray const*, std::vector<MxArray, std::allocator<MxArray> > >)'
collect2: error: ld returned 1 exit status

make: *** [+cv/private/AgastFeatureDetector_.mexa64] Error 255
```

Any help appreciated, once again....output of pkg-config is:

```
$ pkg-config --cflags --libs opencv
-I/usr/local/include/opencv -I/usr/local/include  -L/usr/local/lib -lopencv_shape -lopencv_stitching -lopencv_objdetect -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_core -lopencv_hal  
```

**Comment by amroamroamro** [comment]
@jeremy-rutman 
Can you check that you have the final version of OpenCV 3.0.0 (not some beta or release-candidate)?

The reason I ask is because `AgastFeatureDetector` was added to `opencv` just before the final version was released (prior to that it was in `opencv_contrib`).

BTW, you don't need to edit the makefile, you can simply pass arguments to it on the command line to override any default values:

``` sh
$ make MATLABDIR=/usr/local/MATLAB/R2015a
```

**Comment by amroamroamro** [comment]
@jeremy-rutman 
What's the output of `pkg-config --modversion opencv`?

**Comment by jeremy-rutman** [comment]
I used wget to get the file here: https://github.com/Itseez/opencv/archive/3.0.0.zip
```
pkg-config --modversion opencv
3.0.0
```
I unzipped the latest from opencv.org/downloads and ran instructions here http://docs.opencv.org/doc/tutorials/introduction/linux_install/linux_install.html#linux-installation (but with extra cmake arguments - 
```
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON -D BUILD_PYTHON_SUPPORT=ON -D WITH_V4L=ON -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=ON -D BUILD_EXAMPLES=ON -D WITH_QT=ON -D WITH_OPENGL=ON ..
```
so I blv my version must be 3.0.0 (wierdly, python is not able to import cv2 but I don't think its related) .
I will try removing the Agast files since I don't need it

**Comment by amroamroamro** [comment]
Can you first try `make clean` and then `make` again? I wanna make sure you don't have stale compiled objects from previous runs...

**Comment by jeremy-rutman** [comment]
I did make clean and still ran into similar errors, so I pulled out the trouble files 
(AgastFeatureDetector_.cpp       BRISK_.cpp                FastFeatureDetector_.cpp  KAZE_.cpp  SimpleBlobDetector_.cpp
AKAZE_.cpp                      DescriptorExtractor_.cpp  FeatureDetector_.cpp      MSER_.cpp
BOWImgDescriptorExtractor_.cpp  DescriptorMatcher_.cpp    GFTTDetector_.cpp         ORB_.cpp)
and then the compile was ok.  The errors were always of the same form  - "undefined reference to `create'[Cfilename]

**Comment by amroamroamro** [comment]
@jeremy-rutman 
ah silly me, I forget to tell you to checkout the `v3.0` branch in mexopencv instead of `master`!

The fixes for the Makefile are there, they haven't yet yet merged into master..

**Comment by amroamroamro** [comment]
@kyamagu:
Would you consider merging the `v3.0` into master, it should be fine since we're still targeting the final OpenCV 3.0.0 version. Thanks

**Comment by jeremy-rutman** [comment]
that took care of it, thanks!

**Comment by amroamroamro** [comment]
yay :+1:

**Comment by kyamagu** [comment]
@amroamroamro Done

**Comment by amroamroamro** [comment]
Thanks
