### ISSUE TITLE
facedetect sample not showing any detection.

### ISSUE THREAD

**Issue by sumeetssaurav** [kyamagu/mexopencv#182]
Hello Kyamagu,
I have interfaced mexopencv with Matlab 2015a and opencv243 on windows8 64-bit OS. It got interfaced properly, but when i tried to run the facedetect sample code, i am not getting any detection on the Live Camera stream. I can see only the camera stream without any detection. Please help me to solve the issue. Other samples are working properly. And the same sample code is also working properly with Matlab 2013a (32-bit) and opencv243 on windows7 OS. 

Thanking You,
Sumeet Saurav

**Comment by amroamroamro** [comment]
Hard to say, perhaps the default detection parameters are not adequate for your case, try tuning them: http://kyamagu.github.io/mexopencv/matlab/CascadeClassifier.detect.html

Also you wanna make sure the room you're in is well lit, your face is facing the webcam in frontal position, and that there isn't too much noise in the background behind you.

If all that fails, you could train your own cascade classifier to detect faces (i.e build your own XML file), but its a bit advanced and not for the faint of heart :)
