### ISSUE TITLE
Feature Descriptors

### ISSUE THREAD

**Issue by mehmet25** [kyamagu/mexopencv#183]
Hello,

 When I have tried to use BRIEF extractor, it requires "xfeatures2d" module.in matlab by mexopencv

I wanted to ask you how to install/add that module? 

Thank you very much, 

my sincerely

**Comment by amroamroamro** [comment]
You have to compile `opencv` + `opencv_contrib` from source.

See this Wiki page for instructions: https://github.com/kyamagu/mexopencv/wiki.

**Comment by mehmet25** [comment]
ıt worked well,
thank for your reply   :)
