### ISSUE TITLE
About use of Brief Extractor

### ISSUE THREAD

**Issue by alisher1722** [kyamagu/mexopencv#185]
Hi, I wanted to ask if we can change the path size and/or kernel size  of BriefDescriptorExtractor manually?

Default parameter was: patch_size=48; kernel_size=9x9

I want to these parameters as: patch_size=16; kernel_size=3x3 for example, etc..

Thank you for your reply,
My sincerely

**Comment by amroamroamro** [comment]
I'm afraid not, these values are [not exposed by the class](http://docs.opencv.org/3.0.0/d1/d93/classcv_1_1xfeatures2d_1_1BriefDescriptorExtractor.html), and appear to be [hardcoded](https://github.com/Itseez/opencv_contrib/blob/3.0.0/modules/xfeatures2d/src/brief.cpp#L61) in the source... The only way would be to modify the source code yourself, and recompile the OpenCV module in question.

Perhaps you can file a feature request with OpenCV to expose these parameters in the class API, or make the improvement yourself and submit a pull request to OpenCV directly. Only then can we expose these paramteres in mexopencv.

**Comment by alisher1722** [comment]
Okay, thank you very much amroamroamro!
I wanted to use Brief Extractor with generic parameters. I needed it; now I will try to write Brief Extractor function by myself. :-)
Do you have m file of brief extractor? Can you share with me

thank you, sincerely

**Comment by amroamroamro** [comment]
I don't have such code, mexopencv only acts as a wrapper for OpenCV functions (which are implemented in C++), we don't write our own implementations...

**Comment by alisher1722** [comment]
Sir, can you create a mex file, if I send you my own c++ function?
Secondly, I wanted to know If I can change the original opencv    " *.cpp" as I want and mex it?
