### ISSUE TITLE
Error ussing mexopencv on matlab R2015a

### ISSUE THREAD

**Issue by SuyiHu** [kyamagu/mexopencv#186]
Hi,

I want to use mexopencv on my Matlab R2015a (32 bit). I followed in the introduction. I download opencv 3.0.0 and extracted to `C:\opencv` then I extracted mexopencv-master also to `C:\`. After that, I add mexopencv-master to MATLAB by right click the folder. Then, I used `mex -setup` and selected Microsoft Visual C++ 2012 (C).  After I have put opencv into system variable path, I run `mexopencv.make('opencv_path', 'C:\opencv\build')` and it worked.

But if I want to run a text files, like "face_detect.m", it shows me this error:

```
Invalid MEX-file
'C:mexopencv-master\+cv\private\CascadeClassifier_.mexw32':
Das angegebene Modul wurde nicht gefunden.

Error in
C:mexopencv-master\+cv\CascadeClassifier.m


Error in facedetect (line 8)
classifier = cv.CascadeClassifier(xml_file);
```

Can someone help me.

Best

Suyi

**Comment by SuyiHu** [comment]
If I run getenv('PATH'), it shows me:C:\opencv\build\x86\vc11\bin;

And I have a 64bit Windows and 32bit Matlab R2015a

**Comment by amroamroamro** [comment]
According to Google, the error message translates to:

> The specified module could not be found.

So use [Dependency Walker](http://www.dependencywalker.com/) on the MEX-file to figure out which DLLs MATLAB failed to locate:

http://www.mathworks.com/matlabcentral/answers/92362-how-do-i-determine-which-libraries-my-mex-file-or-stand-alone-application-requires

Just call the tool directly from inside MATLAB, that way it inherits the same PATH environment variable:

    >> !"C:\path\to\x86\depends.exe" C:\mexopencv\+cv\private\CascadeClassifier_.mexw32
