### ISSUE TITLE
Compiling with Visual Studio 12 outside matlab

### ISSUE THREAD

**Issue by Ivesirc** [kyamagu/mexopencv#188]
Hi, 
I was trying to use your excelent work (MxArray) outside of matlab in combination with OpenCv and Matlabs C++ Interface via mat.h.

Unfortunately I'm facing one compiling error I have no idea how to handle it.

```
Error   10  error C4996: 'std::_Copy_impl': Function call with parameters that may be unsafe 
- this call relies on the caller to check that the passed values are correct.
To disable this warning, use -D_SCL_SECURE_NO_WARNINGS.
See documentation on how to use Visual C++ 'Checked Iterators'
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xutility 2132    1   OPENCV_TEST
```

It points to xutility in VC include.
The marked section contains this piece of code:

```
template<class _InIt,
class _OutIt> inline
_OutIt copy(_InIt _First, _InIt _Last,
    _OutIt _Dest)
{   // copy [_First, _Last) to [_Dest, ...)
if (_First == _Last)
    return (_Dest);
else
    {   // worth copying, check then copy
    _DEBUG_RANGE(_First, _Last);
    _DEBUG_POINTER(_Dest);
    return (_Copy_impl(_Unchecked(_First), _Unchecked(_Last),
        _Dest, _Is_checked(_Dest)));
    }
}
```

Any Ideas on what I could be doing wrong.

Thanks and Regards,
Ralph

**Comment by amroamroamro** [comment]
Your report is not enough to pinpoint the problem..
We need to know what line in your code (or in mexopencv) triggers that [error](https://msdn.microsoft.com/en-us/library/ttcz0bys.aspx) by calling `std::copy` (directly or indirectly)?
