### ISSUE TITLE
MATLAB stops working

### ISSUE THREAD

**Issue by sezan92** [kyamagu/mexopencv#189]
I wanted to use MATLAB with opencv 3.0 and opencv contrib..followed all the procedures.But it always crashes when i start using opencv functions. MATLAB version is R2013a , windows 64 bit.

**Comment by amroamroamro** [comment]
We added a detailed step-by-step guide on how to compile mexopencv against OpenCV 3.0 + opencv_contrib:
https://github.com/kyamagu/mexopencv/wiki

If you are still getting crashes, please post more info so we can troubleshoot..
