### ISSUE TITLE
cv.calibrateCamera

### ISSUE THREAD

**Issue by Gappa88** [kyamagu/mexopencv#19]
Hello,

I'm trying to use `cv.calibrateCamera` but I didn't make it. Matlab is crashing and it doesn't highlight any errors in the formula of `cv.calibrateCamera`.

I built `objectPoints` cell array like this:

``` matlab
object_points = cell(1, BOARD_W*BOARD_H, successful_boards);
```

where `BOARD_W` and `BOARD_H` are width and height of the chessboard; `successful_boards` represents the number of good boards in which i want to store `objectpoints` and corners.

I built image points cell array like this:

``` matlab
img_points_L = cell(1, BOARD_W*BOARD_H, successful_boards);
img_points_R = cell(1, BOARD_W*BOARD_H, successful_boards);
```

when I run `calibrateCamera` matlab crashes.

Any idea?

thanks

**Comment by amroamroamro** [comment]
If anyone is wondering, there's a full demo on camera calibration:
https://github.com/kyamagu/mexopencv/blob/master/samples/calibration_demo.m
