### ISSUE TITLE
Always getting error in make.m 

### ISSUE THREAD

**Issue by FionaHH** [kyamagu/mexopencv#194]
When I run make.m, there's an error as following:

```
Error in mexopencv.make (line 144)
 if ~opts.dryrun, eval(cmd); end

And when I do mexOpenCv to one of cpp file in each folder such as \opencv_contrib\src\+cv\private\DAISY.cpp, there's an error like this:

k:\feature matching codes\mexopencv-master\include\mexopencv.hpp(84) : error C2039: 'DIST_USER': Ist kein Element von 'cv'
k:\feature matching codes\mexopencv-master\include\mexopencv.hpp(84) : error C2065: 'DIST_USER': nichtdeklarierter Bezeichner
k:\feature matching codes\mexopencv-master\include\mexopencv.hpp(85) : error C2039: 'DIST_L1': Ist kein Element von 'cv'
k:\feature matching codes\mexopencv-master\include\mexopencv.hpp(85) : error C2065: 'DIST_L1': nichtdeklarierter Bezeichner
k:\feature matching codes\mexopencv-master\include\mexopencv.hpp(85) : fatal error C1903: Weiterverarbeitung nach vorherigem Fehler nicht m”glich; Kompilierung wird abgebrochen.
```

Could you please tell me the reason? Thank you very much!

**Comment by amroamroamro** [comment]
As stated in the readme file:

> The current version of mexopencv is compatible with OpenCV 3.x.
> [Please check the v2.4 branch for OpenCV 2.4.x](https://github.com/kyamagu/mexopencv/tree/v2.4).

To be exact, use the stable release of OpenCV 3.0.0, or checkout the previous branches for older 2.4 version.

Also you might wanna read [this guide](https://github.com/kyamagu/mexopencv/wiki) if you want to compile both opencv and opencv_contrib (again 3.0.0).

**Comment by FionaHH** [comment]
I just use OpenCV 2.4.9 which was downloded from Computer Vision System Toolbox Support Packages in matlab, and I also use matlab2015b and Visual Studio 2013.
Thank you so much!

**Comment by amroamroamro** [comment]
1) Regardless of version, I'm not sure you can use MathWorks' version of OpenCV with mexopencv... It is probably customized for their own use in the CVST toolbox. Instead I suggest you use the official package from http://opencv.org/, that's the one we support and test against.

2) Like I said, for OpenCV version 2.4.x, grab the [`v2.4`](https://github.com/kyamagu/mexopencv/tree/v2.4) branch of mexopencv, and follow the instructions to build it.

**Comment by FionaHH** [comment]
Now I changed the version of opencv just as the guide. 
However, when I use cmake, 
set the source folder as C:/OpenCV300/opencv
set the destination folder as: C:/OpenCV300/build
press Configure, and choose Visual Studio 12 2013 Win64 as compiler
there's an error: CMake Error: The source directory "C:/OpenCV300/opencv" does not appear to contain CMakeLists.txt.
Do you know why?
