### ISSUE TITLE
Conflict using opencv 3.0 and matlab's own opencv 2.4 libs

### ISSUE THREAD

**Issue by chenfisher** [kyamagu/mexopencv#195]
I've successfully compiled opencv 3.0 + mexopencv.

I'm running matlab with LD_PRELOAD=/usr/local/lib/libopencv_core.so (which points to 3.0)
When not using the LD_PRELOAD I'm getting seg fault; so running with preload helps.

The problem is when matlab is trying to use it's own opencv 2.4 libs. it seems that the preload conflicts with what matlab needs.

**Without prelloading**
I get segmentation fault with following stack trace:
```
Stack Trace (from fault):
[  0] 0x00007f2b69ddbea2          /matlab/bin/glnxa64/libopencv_core.so.2.4+01621666 _ZNK2cv3Mat6copyToERKNS_12_OutputArrayE+00000034
[  1] 0x00007f2b69dfeb44          /matlab/bin/glnxa64/libopencv_core.so.2.4+01764164 _ZNK2cv3Mat9convertToERKNS_12_OutputArrayEidd+00000964
[  2] 0x00007f2b55495f4b  /matlab.install/mexopencv/+cv/equalizeHist.mexa64+00048971
[  3] 0x00007f2b5548c8e7  /matlab.install/mexopencv/+cv/equalizeHist.mexa64+00010471 mexFunction+00000215
...
...

This error was detected while a MEX-file was running...
```

It seems the mex file is using the 2.4 lib instead of 3.0; so preloading should help:

**With preloading**

```
>> vision.CascadeObjectDetector('xml.xml')
OpenCV Error: Bad argument (Invalid pointer to file storage) in cvGetRootFileNode, file /matlab.install/opencv/modules/core/src/persistence.cpp, line 772
Error using vision.internal.CascadeClassifier/load
Invalid OpenCV XML file.  An error occurred while reading xml.xml.
...
```

Now it seems matlab is using 3.0 libs instead of 2.4 and that messes things up.

**Is it possible to simultaneously use both opencv 3.0 with mexopencv and opencv 2.4 (the one that comes with matlab R2015b)  with matlab's vision toolbox?**

One solution I thought of was to statically link mexopencv and opencv 3.0 so I wouldn't need to preload shared opencv libs. I've successfully compiled opencv statically but failed to link mexopencv to it.

Is it possible to statically link mexopencv to opencv?

**Comment by amroamroamro** [comment]
I run mexopencv on Windows, and the solution seems simple. The shared libraries have different names between OpenCV 2.4 and 3.0:

    # 2.4
    opencv_core2411.dll
    ...
    # 3.0
    opencv_core300.dll
    ...

That way there is no ambiguity which version the MEX-function links to, and the system will always load the correct version. Note I didn't have to do anything special in CMake to get the version number in the file names. Isn't it the same for Linux?

[If I remember correctly][1], the convention on Linux is to create the shared library with explicit version in the name, and to also create a version-less symbolic link that points to the fully-qualified name, something like:

    libopencv_core.so.2.4   # fully qualified name
    linopencv_core.so       # symlink to the above

So perhaps you can change the build scripts to explicitly link against the libraries with the fully-qualified name, and avoid the confusion all together. Refer to gcc and ld manpages to see how to do that...

---

Another thing you could look into is using the `rpath` option of gcc and ld. [If I'm not mistaken][2], this is supposed to hard-code the path inside the executable which explicitly tells the loader where to look for shared libraries **at runtime**...

[1]: http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html
[2]: http://stackoverflow.com/a/8482308/97160

**Comment by kyamagu** [comment]
@chenfisher I think the best solution in this scenario is to use the v2.4 branch of mexopencv and link against Matlab's own shared object in the build script. I have never tried that, but probably you cannot load two versions at the same time. Static linking could remedy some issue, but that will require huge amount of dependent libs linked to OpenCV.

**Comment by amroamroamro** [comment]
@chenfisher 
It just occurred to me that you have another option here; There is a special module in OpenCV called [`opencv_world`](http://answers.opencv.org/question/3614/what-is-opencv_world-package-in-opencv-243-rc/). It is basically a super-module that combines all other modules into one, which is supposed to be easier for distribution (you only have one shared library to deploy as opposed to dozens of DLL/SO).

In fact starting with OpenCV 3.0.0, the precompiled binaries for Windows now ship this module by default, so when you download and extract the package you only find one DLL file `opencv_world300.dll` of slightly bigger size 30MB (and another for the debug version).

Since the CSVT toolbox comes with separate files for each module (last I checked it still uses OpenCV 2.4.9) , you can build mexopencv against OpenCV 3.0.0 linking it against this world module. That way you won't have any library names conflict, and you can run both mexopencv and CVST in the same session.

**Comment by chenfisher** [comment]
Thanks, guys. I thought this would be a problem.
I'll stick to opencv 2.4 for now.
