### ISSUE TITLE
Contrib module in Ubuntu 14.04

### ISSUE THREAD

**Issue by noagd** [kyamagu/mexopencv#204]
Hi, I am trying to use feature detector/extractos and I realised I need to compile contrib module. 

I download opencv_contrib from github, re-build and re-install OpenCV. Then, when I try to compile mexopencv by:

    make MATLABDIR=/usr/local/MATLAB/R2015b contrib

I get the following error:

> /tmp/mex_619067277620954_21116/BriefDescriptorExtractor_.o: In function ``mexFunction': BriefDescriptorExtractor_.cpp:(.text+0x31d8): undefined reference to `createBriefDescriptorExtractor(__gnu_cxx::__normal_iterator > >, __gnu_cxx::__normal_iterator > >)' collect2: error: ld returned 1 exit status

Do know what is going on?

I am using OpenCV 3.0, Matlab R2015b and Ubuntu 14.04.

**Comment by kyamagu** [comment]
@noagd Seems you miss a linker flag to the necessary library. Does your `pkg-config` return the linker flags to the installed OpenCV 3.0 correctly?

    pkg-config --cflags --libs opencv

**Comment by noagd** [comment]
Thanks for your response. If I run:

    pkg-config --cflags --libs opencv

I get:
```
-I/usr/local/include/opencv -I/usr/local/include  -L/usr/local/lib -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_viz -lopencv_adas -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_datasets -lopencv_face -lopencv_latentsvm -lopencv_objdetect -lopencv_line_descriptor -lopencv_optflow -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_surface_matching -lopencv_text -lopencv_tracking -lopencv_xfeatures2d -lopencv_calib3d -lopencv_features2d -lopencv_shape -lopencv_video -lopencv_ml -lopencv_flann -lopencv_ximgproc -lopencv_xobjdetect -lopencv_xphoto -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_photo -lopencv_imgproc -lopencv_core -lopencv_hal
```

**Comment by kyamagu** [comment]
@noagd hmm, could be simply a matter of `make clean` and `make` again. The error indicates xfeatures2d helpers are not linked correctly.

**Comment by noagd** [comment]
Wow!! That's magic!! `make clean` and `make` solve the issue. Thanks a lot :-)
