### ISSUE TITLE
Can't link testMXArray1_.mex64

### ISSUE THREAD

**Issue by andradx** [kyamagu/mexopencv#207]
On version bd6f96f the final compilation stage yields:

 >   /usr/bin/ld: cannot open output file +cv/+test/private/testMxArray1_.mexa64: No such file or directory
collect2: ld returned 1 exit status
 >   mex: link of ' "+cv/+test/private/testMxArray1_.mexa64"' failed.

The +cv/+test/private directory does not exist, so a mkdir -o +cv/+test/private is due.

**Comment by kyamagu** [comment]
@andradx Should be fixed now, thanks!
