### ISSUE TITLE
Start mexopencv in Ubuntu

### ISSUE THREAD

**Issue by sillyWiki** [kyamagu/mexopencv#212]
Hi kyamagu, I am a new user of Linux, I have adopted opencv methods in Matlab code using your mexopencv under win OS, but encountered in some problems using Linux, I wonder if you can give me some tips?  Maybe my problems are really naive, because I am totally a greenhand.

The environment is Ubuntu 14.04, opencv2.4.10(), pkg-config 0.28, matlab2013a. First, I was confused by the offered README. I had no idea which step should I followed, the UNIX one or the Ubuntu one? I firstly launched the terminal and entered the mexopencv-2.4 folder. My path of matlab is `/usr/local/MATLAB/R2013a`, so I entered like this: `make MATLABDIR=/usr/local/MATLAB/R2013a`. At the first time, it ran for a while and stopped with no error, but I entered `make MATLABDIR=/usr/local/MATLAB/R2013a test`, there were endless errors, for example: 

```
== TestComputeCorrespondEpilines ======
-- test_error_1 ------
Error using TestComputeCorrespondEpilines.test_error_1 (line 12)
Assertion failed.

Error in UnitTest.all (line 44)
                    feval([class_name,'.',m{:}]);

Error in UnitTest (line 18)
                UnitTest.all(class_name);

FAIL
== TestContourArea ======
-- test_1 ------
Error using cv.contourArea
Invalid MEX-file '/home/vilab/.local/share/Trash/files/mexopencv-2.4/+cv/contourArea.mexa64': /usr/local/lib/libopencv_ocl.so.2.4: undefined symbol: _ZTIN2cv16ParallelLoopBodyE

Error in TestContourArea.test_1 (line 9)
            a = cv.contourArea(TestContourArea.curve);

Error in UnitTest.all (line 44)
                    feval([class_name,'.',m{:}]);

Error in UnitTest (line 18)
                UnitTest.all(class_name);

FAIL
-- test_error_1 ------
Error using TestContourArea.test_error_1 (line 17)
Assertion failed.

Error in UnitTest.all (line 44)
                    feval([class_name,'.',m{:}]);

Error in UnitTest (line 18)
                UnitTest.all(class_name);

FAIL
```

....At the second time, I did not remember what changes I have made to the terminal, maybe after my entering  `$ sh utils/remove_nonfree.sh` , the terminal returned: `make: Nothing to be done for 'all'`. if I entered `make MATLABDIR=/usr/local/MATLAB/R2013a` again. 

I don't know how it happened.  Then I launched the matlab, adding the mexopencv-2.4 folder in the path .  when I entered 'make' or 'makefile', it returned `Undefined function or variable 'make'`. 
if I entered `make MATLABDIR=/usr/local/MATLAB/R2013a`, Matlab also gave `make: Nothing to be done for 'all'`

Can you tell me how to build and use mexopencv under Ubuntu step by step, I am really a greenhand and almost be driven to mad by this T.T

**Comment by kyamagu** [comment]
@sillyWiki It looks like you have a version mismatch somewhere. Probably you need to debug where the error is coming from using `ldd` tools.

**Comment by sillyWiki** [comment]
@kyamagu ok, then how about the method I used to build mexopencv in Ubuntu? Should I always build it using a terminal and the script 'make MATLABDIR=/usr/local/MATLAB/R2013a'? 

I remember that when I build it in Windows, I make it in Matlab, and the output mex functions were stored in the folder of mexopencv. The script used in Win is "cv.make('opencv_path','D:\develop\opencv244\opencv')", which is concerned about  opencv. Then why is that we use 'make MATLABDIR=/usr/local/MATLAB/R2013a' in Ubuntu?

**Comment by kyamagu** [comment]
@sillyWiki According to the following:

    /usr/local/lib/libopencv_ocl.so.2.4

You probably installed OpenCV 2.4 from source but that is not on `pkg-config` path. That is causing the problem. Try to uninstall OpenCV 2.4 installed at `/usr/local` unless you have a specific reason to keep it, and make sure `pkg-config --cflags --libs opencv` correctly returns the path to the system library (which probably you already installed by `apt-get install libopencv-dev`. After removing the `/usr/local` installation, `make clean` and `make` again. You need to call `sh utils/remove_nonfree.sh` only once.

The reason we use `Makefile` in Linux is because it's more functional and standard in Unix platforms.
