### ISSUE TITLE
Problems encountered when compiling mexopencv

### ISSUE THREAD

**Issue by Starethics** [kyamagu/mexopencv#213]
Hi kyamagu,
Ko ni ji wa :)
I'm currently trying to implementing your amazing paper doll parsing. 
When I was running the make.m script, a bug occurs at cv.make();
Here is the error information:
----------------------------------------------------------------------------------------------------------------
>> make
/usr/local/MATLAB/R2014b/bin/mex -cxx -largeArrayDims -Iinclude -I/usr/local/include/opencv -I/usr/local/include   src/+cv/calcGlobalOrientation.cpp -lMxArray -Llib /usr/local/lib/libopencv_calib3d.so /usr/local/lib/libopencv_contrib.so /usr/local/lib/libopencv_core.so /usr/local/lib/libopencv_features2d.so /usr/local/lib/libopencv_flann.so /usr/local/lib/libopencv_gpu.so /usr/local/lib/libopencv_highgui.so /usr/local/lib/libopencv_imgproc.so /usr/local/lib/libopencv_legacy.so /usr/local/lib/libopencv_ml.so /usr/local/lib/libopencv_nonfree.so /usr/local/lib/libopencv_objdetect.so /usr/local/lib/libopencv_ocl.so /usr/local/lib/libopencv_photo.so /usr/local/lib/libopencv_stitching.so /usr/local/lib/libopencv_superres.so /usr/local/lib/libopencv_ts.a /usr/local/lib/libopencv_video.so /usr/local/lib/libopencv_videostab.so -lrt -lpthread -lm -ldl   -output +cv/calcGlobalOrientation.mexa64
Building with 'g++'.
Warning: You are using gcc version '4.8.4'. The version of gcc is not supported. The version currently supported with MEX is '4.7.x'. For a list of currently supported compilers see: http://www.mathworks.com/support/compilers/current_release.
Warning: You are using gcc version '4.8.4-2ubuntu1~14.04)'. The version of gcc is not supported. The version currently supported with MEX is '4.7.x'. For a list of currently supported compilers see: http://www.mathworks.com/support/compilers/current_release.
lib/libMxArray.a(MxArray.o): In function `MxArray::toMoments(unsigned long) const':
MxArray.cpp:(.text+0x22da): undefined reference to `cv::Moments::Moments(double, double, double, double, double, double, double, double, double, double)'
collect2: error: ld returned 1 exit status

make: *** [+cv/calcGlobalOrientation.mexa64] Error 255
--------------------------------------------------------------------------------------------------------------------
Could you help me with this bug?
a ri ka do go za yi ma si!

My system is Ubuntu14.04 with matlabR2014b and opencv-2.4.9

**Comment by kyamagu** [comment]
@Starethics Very likely you're building against wrong version of OpenCV. Either get a fresh `mexopencv` v2.4 or find the correct OpenCV version to link to.

**Comment by Starethics** [comment]
@kyamagu  The opencv 2.4.9 I used was downloaded from the offcial opencv.org. And I reinstalled it but it doesn't work. Or I tried other version of 2.4.x? such as 2.4.10...

**Comment by Starethics** [comment]
@kyamagu 2.4.11 seems works well... Thanks for the help!

**Comment by Starethics** [comment]
@kyamagu Sorry to trouble you again.
another bug with the vl_make() in the make.m script;
The error is:
make: Nothing to be done for `all'.

And when I ignored this error and tried the command "result = feature_calculator.apply(config, input_sample)"
an error shows:
[12-Nov-2015 22:31:28] Error:feature_calculator: 1 / 1
Attempt to execute SCRIPT vl_imsmooth as a function:
/media/starethics/Entertainment/models/paperdoll-v1.0/lib/vlfeat-0.9.16/toolbox/imop/vl_imsmooth.m

**Comment by kyamagu** [comment]
@Starethics This is off-topic here. But error is apparently due to `vl_make` not compiling.

**Comment by kyamagu** [comment]
@Starethics [The working version of paper doll is on github now](https://github.com/kyamagu/paperdoll).
