### ISSUE TITLE
Error building mexopencv

### ISSUE THREAD

**Issue by hgras** [kyamagu/mexopencv#217]
My opencv is at c and I have same issue
compiler is visual studio 11 x86
Error:

C:\PROGRA~1\MATLAB\R2013A\BIN\MEX.PL: Error: Compile of 'C:\Users\Hgras\Desktop\mexopencv-master\mexopencv-master\src\mexopencv_features2d.cpp' failed.

Error using mex (line 206)
Unable to complete successfully.

Error in mexopencv.make (line 153)
if ~opts.dryrun, eval(cmd); end

**Comment by amroamroamro** [comment]
It seems you already [figured out](https://github.com/kyamagu/mexopencv/issues/153#issuecomment-161044810) that you were using the wrong OpenCV version, please close the issue as resolved.
