### ISSUE TITLE
MATLAB 2015a with OpenCV 2.4.9 crashed in "MxArray(m)" when I converted cv::Mat back to mxArray

### ISSUE THREAD

**Issue by jacky8230** [kyamagu/mexopencv#218]
OS: Windows7 64bits
MATLAB version : MATLAB 2015a
OpenCV version : 2.4.9
C/C++ Compiler : Microsoft Visual Studio 2010

Here is an example copied from "https://github.com/kyamagu/mexopencv/tree/v2.4"

``` cpp
#include "mexopencv.hpp"
void mexFunction(int nlhs, mxArray *plhs[],
                 int nrhs, const mxArray *prhs[])
{

    // Check arguments
    if (nlhs!=1 || nrhs!=1)
        mexErrMsgIdAndTxt("myfunc:invalidArgs", "Wrong number of arguments");

    // Convert MxArray to cv::Mat
    cv::Mat mat = MxArray(prhs[0]).toMat();

    // Do whatever you want

    // Convert cv::Mat back to mxArray*
    plhs[0] = MxArray(mat);
}
```
---

(1)
It doesn't show any error message when I use `mexopencv.make('opencv_path', 'D:\OpenCV2.4.9\build')` to compile each file. But in runtimes, MATLAB always crashed at the line `plhs[0] = MxArray(mat)`. I'm pretty sure that the error caused by `MxArray(mat)` function. Due to this reason, I can't use any cv.xxx function which has been compiled.

```
plhs[0] = MxArray(mat); % => MATLAB crashed
plhs[0] = MxArray(prhs[0]); % => OK
```

I run same compiled mex files at MATLAB 2013b, and everything is going well. How can I fix this problem in MATLAB 2015a?

---

(2)
By the way, I try to use `cv.imread('peppers.png')` in MATLAB 2015a, but it shows the strange error message as follows:
```
Error using imread
imread failed
```

It seems that this command just call MATLAB's `imread` function instead of `cv.imread`. But in 2013b version, it calls `cv.imread` correctly.

---

(3)
This simple code below also crashed because of the same problem mentioned at (1).

    img = cv.blur(rand(100)); % => crashed in 2015a, but work well in 2013b.

Thank you

Jacky

**Comment by amroamroamro** [comment]
let me get this clear, are you compiling MEX-files in R2013 and using those binaries in R2015a?

If I recall, there was a breaking change at the ABI level in some recent version, which meant we had to recompile MEX-files using the new MATLAB version..

**Comment by jacky8230** [comment]
@amroamroamro I am pretty sure that I had cleaned all compiled MEX-files before I recompiled them in R2015a. When I finish compiling all MEX-files in R2015a, I still can't call use any cv function. Strangely, I can use those binaries in R2013b with MEX files compiled by R2015a.

I didn't execute R2013b and R2015a at the same time and I only have VS2010 and OpenCV 2.4.9 in my system. 

When I used mex -setup in R2015a, it automatically configured to use VS2010 without change any settings by user.
>> mex -setup
MEX configured to use 'Microsoft Visual C++ 2010 (C)' for C language compilation.

Here are some information showed by cv.getBuildInformation( I show several strange parts)：

______________________________R2013b_________________________________
General configuration for OpenCV 2.4.9 =====================================
  Version control:               2.4.9

  Platform:
    Host:                        Windows 6.1 AMD64
    CMake:                       2.8.11.2
    CMake generator:             Visual Studio 10 Win64
    CMake build tool:            C:/Windows/Microsoft.NET/Framework/v4.0.30319/MSBuild.exe
    MSVC:                        1600

 C/C++:
    Built as dynamic libs?:      YES
    C++ Compiler:                C:/Program Files (x86)/Microsoft Visual Studio 10.0/VC/bin/x86_amd64/cl.exe  (ver 16.0.40219.1)
    C++ flags (Release):         /DWIN32 /D_WINDOWS /W4 /GR /EHa  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /wd4251 /MD /O2 /Ob2 /D NDEBUG  /Zi
    C++ flags (Debug):           /DWIN32 /D_WINDOWS /W4 /GR /EHa  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /wd4251 /D_DEBUG /MDd /Zi /Ob0 /Od /RTC1 
    C Compiler:                  C:/Program Files (x86)/Microsoft Visual Studio 10.0/VC/bin/x86_amd64/cl.exe

  Install path:                  C:/builds/2_4_PackSlave-win64-vc10-shared/build/install

  cvconfig.h is in:              C:/builds/2_4_PackSlave-win64-vc10-shared/build/opencv_build

______________________________R2015a_________________________________
General configuration for OpenCV 2.4.9 =====================================
  Version control:               unknown

  Platform:
    Host:                        Windows 6.1 AMD64
    CMake:                       2.8.12.2
    CMake generator:             Visual Studio 11 Win64
    CMake build tool:            C:/PROGRA~2/MICROS~3.0/Common7/IDE/devenv.com
    MSVC:                        1700

C/C++:
    Built as dynamic libs?:      YES
    C++ Compiler:                cl  (ver 17.0.61030.0)
    C++ flags (Release):         -DWIN32 -D_WIN32_WINNT=0x0503 -DWINVER=0x0503 -D_WIN32_IE=0x0600 -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE -D_SECURE_SCL=0 /D_MBCS /D_WINDOWS -FC -MD -nologo -Z7     -GR -EHs -O2 -GS-  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /wd4251  -DWIN32 -D_WIN32_WINNT=0x0503 -DWINVER=0x0503 -D_WIN32_IE=0x0600 -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE -D_SECURE_SCL=0 /D_MBCS /D_WINDOWS -FC -MD -nologo -Z7     -GR -EHs -O2 -GS-  /Zi
    C++ flags (Debug):           -DWIN32 -D_WIN32_WINNT=0x0503 -DWINVER=0x0503 -D_WIN32_IE=0x0600 -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE -D_SECURE_SCL=0 /D_MBCS /D_WINDOWS -FC -MD -nologo -Z7     -GR -EHs -O2 -GS-  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /wd4251  -DWIN32 -D_WIN32_WINNT=0x0503 -DWINVER=0x0503 -D_WIN32_IE=0x0600 -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE -D_SECURE_SCL=0 /D_MBCS /D_WINDOWS -FC -MD -nologo -Z7     -GR -EHs -O2 -GS- 
    C Compiler:                  cl

  Install path:                  B:/3p/install/1021490/win64/OpenCV

  cvconfig.h is in:              C:/TEMP/A3p0_5828a_1708/win64/OpenCV

**Comment by kyamagu** [comment]
Do you have Mathworks Computer Vision System Toolbox? Did you try DependencyWalker?

**Comment by jacky8230** [comment]
1.Yes
Computer Vision System Toolbox                        Version 5.3        (R2013b)
Computer Vision System Toolbox                        Version 6.2        (R2015a)

2.
Yes
I check cv.blur(crashed condition) and the cv.imread(missed match condition) in DependencyWalker.
(1) cv.blur
LIBMX.DLL
LIBMEX.DLL.

(2) cv.imread
LIBMEX.DLL
LIBMX.DLL
API-MS-WIN-APPMODEL-RUNTIME-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-ERROR-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-ROBUFFER-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-STRING-L1-1-0.DLL
API-MS-WIN-SHCORE-SCALING-L1-1-1.DLL
DCOMP.DLL
IESHIMS.DLL

**Comment by amroamroamro** [comment]
@jacky8230: Are you using two different OpenCV binaries? 

According to the second `getBuildInformation` output (the one in R2015a), you're building against the wrong OpenCV, it's a custom built version compiled using VS2012, which doesn't match the VS2010 compiler you're using to compile the MEX-files...

Instead you should use the same OpenCV binaries you used in the first `getBuildInformation`, if I'm not mistaken these are the official ones downloaded from opencv.org, right?

### 1

```
CMake: 2.8.11.2
CMake generator: Visual Studio 10 Win64
MSVC: 1600
Install path: C:/builds/2_4_PackSlave-win64-vc10-shared/build/install
cvconfig.h is in: C:/builds/2_4_PackSlave-win64-vc10-shared/build/opencv_build
```

### 2

```
CMake: 2.8.12.2
CMake generator: Visual Studio 11 Win64
MSVC: 1700
Install path: B:/3p/install/1021490/win64/OpenCV
cvconfig.h is in: C:/TEMP/A3p0_5828a_1708/win64/OpenCV
```

**Comment by amroamroamro** [comment]
.. and @kyamagu is right, the CVST toolbox in MATLAB 2015 ships with OpenCV 2.4.9 (if you check `$matlabroot\bin\win64` folder you'll see the `opencv_*249.dll` files), so their DLLs are loaded instead of the one you compiled against when you run the MEX-functions (the two versions are incompatible).

You can debug this by calling dependency walker **from inside** MATLAB and seeing exactly which version is being loaded and from what location. See this previous comment: https://github.com/kyamagu/mexopencv/issues/192#issuecomment-140804062

**Comment by jacky8230** [comment]
Thank you.
@amroamroamro and @kyamagu 
You are right. I check the folder both D:\MATLAB\R2013b\bin\win64 and D:\MATLAB\R2015a\bin\win64.I find that there are ```opencv_*242.dll``` files in R2013b and ```opencv_*249.dll``` files in R2015a. 

I don't realize how can I compiled these MEX-files in R2015a. These binaries worked well in R2013b but not R2015a.

How can I solve this problem? Just delete all ```opencv_*242.dll``` files in R2013b and then rebuild mexOpenCV?

I use dependency walker to check where those .dlls loaded from.

**_________________________R2013b_________________________**
![2013b](https://cloud.githubusercontent.com/assets/16115923/11566831/187b49dc-9a1f-11e5-864e-7b984cca2d2b.PNG)

**_________________________R2015a_________________________**
![2015a](https://cloud.githubusercontent.com/assets/16115923/11566871/4e289c7e-9a1f-11e5-9f6c-d447d5a3bda3.PNG)

How can I let them both loaded from ```$opencvroot\build\x64\vc10``` instead of ```$matlabroot\bin\win64```?

**Comment by amroamroamro** [comment]
@jacky8230 like I explained above, put the folder `$opencvroot\build\x64\vc10` early in the PATH environment variable (before any MATLAB directories) and restart MATLAB.

On a side note, I like to use RapidEE to manage environment variables http://www.rapidee.com/

**Comment by jacky8230** [comment]
@amroamroamro
I followed your advice to put the  ```$opencvroot\build\x64\vc10``` early in the PATH environment variable before any MATLAB path. I also restart MATLAB and my computer.

Unfortunately, it didn't change the load path in R2015a.
![r2015a_2](https://cloud.githubusercontent.com/assets/16115923/11570650/4ea47204-9a33-11e5-9a7d-779879cf73c2.PNG)

Here is the message showed by ```getenv('PATH')```.
```C:\ProgramData\Oracle\Java\javapath;
C:\Program Files (x86)\Intel\iCLS Client\;
C:\Program Files\Intel\iCLS Client\;
C:\Windows\system32;
C:\Windows;
C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;
C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;
C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;
C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;
C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;
C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;
C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;
D:\OpenCV2.4.9\build\x64\vc10\bin;
D:\MATLAB\R2015a\runtime\win64;
D:\MATLAB\R2015a\bin;
D:\MATLAB\R2013b\runtime\win64;
D:\MATLAB\R2013b\bin;
D:\MATLAB\R2013b\polyspace\bin;
C:\Program Files\Java\jdk1.8.0_25\bin;
D:\MATLAB\R2015a\polyspace\bin;```

**Comment by amroamroamro** [comment]
@jacky8230 
Oh I was wrong, the PATH is only considered last which is too late by then! I just checked MSDN, and according to [this](https://msdn.microsoft.com/en-us/library/7d83bc18.aspx), the search order for DLLs is the following:

1. The directory where the executable module for the current process is located. In this case this is `$matlabroot\bin\win64`.
2. The current directory. Basically `pwd`.
3. The Windows system directory. `C:\Windows\System32` and `C:\Windows\System`.
4. The Windows directory. `C:\Windows`.
5. The directories listed in the `PATH` environment variable.

In fact I just ran [`ProcMon`](https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx) (sorta like `strace` for Windows), and I can confirm that when first running a MEX-function like `cv.imread` the search starts with the MATLAB directory looking for dependency OpenCV DLLs by name `opencv_*249.dll`, and will stop there once a match is found...

So your only option here is to either uninstall the Computer Vision Toolbox or to temporarily delete/rename the `$matlabroot\bin\win64\opencv_*249.dll` files when you want to run mexopencv code. Again this mean that you cannot run CVST **and** mexopencv functions at the same time in the same MATLAB session.

*(Actually there are other solutions to try like [DLL redirection](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682600.aspx) or using [Win32 API calls](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586.aspx#standard_search_order_for_desktop_applications) to change the search order, but these are too advanced/complicated to my liking).*

If you want my advice, a cleaner solution would be to avoid using the same OpenCV version that MATLAB is currently using (2.4.9), thus avoiding any conflicts. For OpenCV 2.x, you can [download](http://opencv.org/downloads.html) 2.4.10 or 2.4.11 and pick one of those versions instead when you compile mexopencv. You wont have to worry about name clashing because the files are named differently as `opencv_*2410.dll` and `opencv_*2411.dll`, and you could continue to use both CVST and mexopencv normally at the same time.

**Comment by jacky8230** [comment]
@amroamroamro
I install OpenCV2.4.11 and chage the PATH ```D:\OpenCV2.4.9\build\x64\vc10\bin;``` with ```D:\OpenCV2.4.11\build\x64\vc10\bin;```. It works well both in R2013b and R2015a now. 

Thanks a lot.
