### ISSUE TITLE
Mac os 10.11.1 matlab 2015b insert an explicit cast to silence this issue

### ISSUE THREAD

**Issue by aminshabani** [kyamagu/mexopencv#219]
Hi! I got a problem with compiling make file ...
I fix some errors but now when I use make I got this error :
type 'mwSize' (aka 'unsigned long') to 'int' in initializer list [-Wc++11-narrowing]
    const int dims[] = {m, n};
                           ^
/Caffe/mexopencv-master/src/MxArray.cpp:621:28: note: insert an explicit cast to silence this issue
    const int dims[] = {m, n};
                           ^
                           static_cast<int>( )
2 errors generated.

make: *** [lib/MxArray.o] Error 255

the complete error link : http://paste.ubuntu.com/13801618/
Could anyone help me to fix it?

**Comment by kyamagu** [comment]
@aminshabani Can you fix by modifying the following? Make sure to `make clean` first.

    const int dims[] = {m, n};

to

    const int dims[] = {static_cast<int>(m), static_cast<int>(n)};

**Comment by aminshabani** [comment]
Yees it's work! Thanks a lot !
but now after a procedure I got a new error :
```
Building with 'Xcode Clang++'.
Undefined symbols for architecture x86_64:
  "cv::imdecode(cv::_InputArray const&, int)", referenced from:
      _mexFunction in imdecode.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

make: *** [+cv/imdecode.mexmaci64] Error 255
```

**Comment by kyamagu** [comment]
@aminshabani What is your OpenCV version? Can you post the output of

    pkg-config --cflags --libs opencv

or if you use Homebrew installation,

    pkg-config --cflags --libs opencv3

**Comment by aminshabani** [comment]
I changed pkg-config opencv.pc and set opencv3 directory to it. now when i run :
```
pkg-config --cflags --libs opencv
```
show :
```
-I/usr/local/Cellar/opencv3/3.0.0/include/opencv -I/usr/local/Cellar/opencv3/3.0.0/include -L/usr/local/Cellar/opencv3/3.0.0/lib -lopencv_calib3d -lopencv_contrib -lopencv_core -lopencv_features2d -lopencv_flann -lopencv_gpu -lopencv_highgui -lopencv_imgproc -lopencv_legacy -lopencv_ml -lopencv_nonfree -lopencv_objdetect -lopencv_ocl -lopencv_photo -lopencv_stitching -lopencv_superres -lopencv_ts -lopencv_video -lopencv_videostab
```

**Comment by kyamagu** [comment]
@aminshabani The output looks correct. Just double-check that you run `make clean` before recompiling anything. If that doesn't help, you might need to add `-v` flag to debug; i.e.

    CFLAGS=-v make

**Comment by aminshabani** [comment]
@kyamagu sorry maybe it's a weak question but when i run ```make clean``` I get this :
```
rm -f -r \
        *.o \
        lib/*.a lib/*.o \
        +cv/*.mexmaci64 \
        +cv/private/*.mexmaci64 \
        +cv/+test/private/*.mexmaci64 \
        opencv_contrib/+cv/*.mexmaci64 \
        opencv_contrib/+cv/private/*.mexmaci64
```
is it correct ?!
Also in debug mode I copy the last outputs in this link :
http://paste.ubuntu.com/13803251/

**Comment by kyamagu** [comment]
@aminshabani Yes, the `make clean` output looks correct. [You might have a `libc++` issue in OpenCV installation](https://github.com/BVLC/caffe/issues/2286). I'm not completely sure of the cause. Do you see `libstdc++` dependency (which shouldn't appear) in the output of the following?

    otool -L /usr/local/Cellar/opencv3/3.0.0/lib/libopencv_highgui.dylib

**Comment by amroamroamro** [comment]
@aminshabani that's weird, the output of `pkg-config`you've shown indicates OpenCV 3.0.0 headers, but the libraries listed are from OpenCV 2.x !
(e.g `opencv_nonfree` was removed in 3.x, and you're missing new libs like `opencv_hal`, `opencv_imgcodecs`, `opencv_videoio`, etc..)

So the question is how did you install OpenCV 3.0.0?
Is that really 3.x or just 2.x but you've manually edited the `opencv.pc` file?

**Comment by aminshabani** [comment]
@kyamagu  Thanks. There is no libstdc++ in output. I try some solutions of that link but unfortunately it doesn't work yet. maybe i must try these in Linux not OSX.

@amroamroamro yes i install both OpenCV 2.4.12 and OpenCV 3.0.0 with brew but i manually edit ```opencv.pc``` for OpenCV3 path and version.

**Comment by kyamagu** [comment]
@aminshabani Installing both OpenCV 2.4 and 3.0 can mess up library path. Unless there is a good reason, you should remove either of them.

**Comment by aminshabani** [comment]
@kyamagu I uninstall ```opencv``` and now I only have a ```opencv3``` that it's install with brew but pkg-config doesn't have any ```opencv.pc```.

**Comment by kyamagu** [comment]
@aminshabani Try using `opencv3` instead of `opencv` in `pkg-config`; That is,

    PKG_CONFIG_OPENCV=opencv3 make

**Comment by aminshabani** [comment]
@kyamagu There is now ```opencv.pc``` or ```opencv3.pc``` in pkg-config path in library so ```opencv3```   can not find in the pkg-config path.

**Comment by kyamagu** [comment]
@aminshabani It depends on how you installed OpenCV. Are you using a package manager or building from the source? Generally it is not recommended to manually edit `opencv.pc` file.

**Comment by aminshabani** [comment]
@kyamagu  I use this code for installation:
```
brew install --build-from-source -vd homebrew/science/opencv3
```

**Comment by kyamagu** [comment]
@aminshabani Did you remove the `opencv3.pc`? I believe Homebrew installs the file at `/usr/local/lib/pkgconfig/opencv3.pc`.

**Comment by aminshabani** [comment]
@kyamagu No there is no ```opencv3.pc``` for me.

**Comment by kyamagu** [comment]
@aminshabani Ok, then do you have the file at `/usr/local/Cellar/opencv3/3.0.0/lib/pkgconfig/opencv.pc`? The path might be different if you build from source. Copy that to `/usr/local/lib/pkgconfig/`.

**Comment by aminshabani** [comment]
@kyamagu Yes thanks a lot, it's worked and installed finally after 3 days!

**Comment by amroamroamro** [comment]
Looking at the [opencv3 formula](https://github.com/Homebrew/homebrew-science/blob/master/opencv3.rb) in homebrew, it specifies the [`keg_only`](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/FAQ.md#what-does-keg-only-mean) option (as the comment says, the reason is opencv and opencv3 share many of the same files and shouldnt be both installed at the same time).

If I understand correctly, `keg_only` keeps stuff installed in `/usr/local/Cellar` without symlink-ing them under `/usr/local`. So you might wanna run `brew link opencv3` to get the files in the expected locations.

(PS: this is only based on reading the docs online, I don't have a mac to test it)

**Comment by kyamagu** [comment]
@amroamroamro Thanks for the follow-up. Yes, that sounds like the necessary step to correctly set up `pkg-config`.
