### ISSUE TITLE
Camera Control

### ISSUE THREAD

**Issue by SailingDreams** [kyamagu/mexopencv#221]
Hi
I'd like to control the brightness of a Logitech C920 webcam. How do I use the set command?

    cap = cv.VideoCapture(0);        % open the default camera
    pause(3);
    cap.set('Brightness',1);

and tried

    cap.set.Brightness(1);

and tried

    set(cap, 'Brightness', 1);

The top 2 return the error
"No appropriate method, property, or field set for class cv.VideoCapture."

The last one returns
"Cannot find 'set' method for cv.VideoCapture class."

Cheers2u
Eddie

**Comment by kyamagu** [comment]
@SailingDreams The syntax is

    cap.Brightness = 1

**Comment by SailingDreams** [comment]
Doh! I didn't try that one. Thanks a bunch!
