### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by rikenmehta03** [kyamagu/mexopencv#224]
Hi, I am using MATLAB R2014a with Ubuntu 14.04 and opencv 2.4 
I am getting this error when I try to compile mexopencv in paperdoll parsing package. 

/usr/local/MATLAB/R2014a/bin/mex -cxx -largeArrayDims -Iinclude -I/usr/local/include/opencv -I/usr/local/include   src/+cv/adaptiveThreshold.cpp -lMxArray -Llib /usr/local/lib/libopencv_calib3d.so /usr/local/lib/libopencv_contrib.so /usr/local/lib/libopencv_core.so /usr/local/lib/libopencv_features2d.so /usr/local/lib/libopencv_flann.so /usr/local/lib/libopencv_gpu.so /usr/local/lib/libopencv_highgui.so /usr/local/lib/libopencv_imgproc.so /usr/local/lib/libopencv_legacy.so /usr/local/lib/libopencv_ml.so /usr/local/lib/libopencv_nonfree.so /usr/local/lib/libopencv_objdetect.so /usr/local/lib/libopencv_photo.so /usr/local/lib/libopencv_stitching.so /usr/local/lib/libopencv_superres.so /usr/local/lib/libopencv_ts.so /usr/local/lib/libopencv_video.so /usr/local/lib/libopencv_videostab.so   -o +cv/adaptiveThreshold.mexa64
Unknown file extension '.5'.
make: *** [+cv/adaptiveThreshold.mexa64] Error 255

**Comment by kyamagu** [comment]
@rikenmehta03 Not sure about the error, but you can replace the `mexopencv` package to [the up-to-date version for v2.4](https://github.com/kyamagu/mexopencv/releases/tag/v2.4.11).

**Comment by rikenmehta03** [comment]
Thanks.. 
I have solved the problem by separately building the mexopencv package. I was already using the up-to-date version of mexopencv.
