### ISSUE TITLE
gh-pages branch: Doxygen and Jekyll

### ISSUE THREAD

**Issue by amroamroamro** [kyamagu/mexopencv#228]
Doxygen generates filenames beginning with an underscore `_`, and Jekyll treats these as special pages (Jekyll is the static site generator behind GitHub Pages).

So if you try to access [this page](http://kyamagu.github.io/mexopencv/html/_o_r_b___8cpp.html) for example, you get a 404 error even though the HTML file exists.

According [to this](https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/), one solution is to create an empty file `.nojekyll` at the root directory of the `gh-pages` branch. This is acceptable in this case because the whole branch only contains regular HTML files to be served as is, nothing to be processed by Jekyll

**Comment by kyamagu** [comment]
@amroamroamro Thanks, just added `.nojekyll` to the root.
