### ISSUE TITLE
fatal error C1083: Cannot open include file: 'opencv2/optflow.hpp': No such file or directory

### ISSUE THREAD

**Issue by sezan92** [kyamagu/mexopencv#230]
> fatal error C1083: Cannot open include file: 'opencv2/optflow.hpp': No such file or directory

I dont know why , this error always comes! Although `optflow.hpp` is present there!

**Comment by kyamagu** [comment]
@sezan92 Please describe your environment (OS, compiler, Matlab version, OpenCV version) as well as how you compile the code.

**Comment by sezan92** [comment]
Windows 10, Matlab R2015a. Compiled Code how you said in the wiki ..

**Comment by amroamroamro** [comment]
@sezan92 optflow is part of opencv_contrib. Are you sure you've enabled it correctly?

We do need more info from you to help...

**Comment by sezan92** [comment]
What Kind of infos should i give to you ? Like Visual Studio Version ? its Visual Studio 12 2013 win64. or anything else? in mex-setup , i used SDK 7.1

**Comment by sezan92** [comment]
just noticed CMAKE results .. it says 
"Matlab:
    mex:                         C:/Program Files/MATLAB/R2015a/bin/mex.bat
    Compiler/generator:          Not working (bindings will not be generated)"
is it the problem?

**Comment by amroamroamro** [comment]
@sezan92 
no, that warning in CMake is unrelated to mexopencv.

We need you to describe in details the steps you took to compile opencv (with opencv_contrib?) as well as mexopencv. The wiki page guides you step by step, but chances are you missed something...

**Comment by sezan92** [comment]
i changed some settings.. In CMAKe it showed, MATLAB working. But new problem arised! 

"F:\Opencv310\mexopencv\opencv_contrib\+cv\calcGlobalOrientation.exp
calcGlobalOrientation.obj : error LNK2019: unresolved external symbol "double __cdecl cv::motempl::calcGlobalOrientation(class
cv::_InputArray const &,class cv::_InputArray const &,class cv::_InputArray const &,double,double)"
(?calcGlobalOrientation@motempl@cv@@YANAEBV_InputArray@2@00NN@Z) referenced in function mexFunction
F:\Opencv310\mexopencv\opencv_contrib\+cv\calcGlobalOrientation.mexw64 : fatal error LNK1120: 1 unresolved externals
"

**Comment by amroamroamro** [comment]
@sezan92 As I mentioned before, the message you see in CMake about MATLAB bindings working or not have nothing to do with mexopencv.

In fact if you follow the guide in the [wiki](https://github.com/kyamagu/mexopencv/wiki), it intentionally mentions disabling all contrib modules (including the so called "matlab" module) except for the listed ones in that page. So it is expected you see a message like `Matlab not found or implicitly disabled`.

Now this last problem you encountered is a linking issue. Without knowing what steps you took to compile opencv+opencv_contrib, it is difficult for us to troubleshoot... Assuming you are using the `master` branch of mexopencv, are you sure you've compiled against **v3.1.0**? It needs to be this exact version in both opencv and opencv_contrib.

**Comment by adityaksai** [comment]
Hello  I have installed opencv3.1 with matlab and works fine. but I want to use saliency API for that i have  installed Opencv_contrib and changed the path variable from build/include/x64/lib to build/install/x64/lib which has more files and saliency API. but now I am getting this error
mexOpenCV objectDetection.cpp
Warning: The OpenCV libraries were built using 'Microsoft Visual C++ 2012'.
 Your compiler is 'Microsoft Visual C++ 2015 Professional'.
 These compilers may not be compatible.
 Note that you can select a compiler using 'mex -setup' command. 
> In mexOpenCV>checkCompilerCompatibility (line 155)
  In mexOpenCV (line 49) 
Building with 'Microsoft Visual C++ 2015 Professional'.
Error using mexOpenCV (line 122)
objectDetection.cpp
C:\CPP code\objectDetection.cpp(1): fatal error C1083: Cannot open include file: 'opencv2/objdetect.hpp': No such file or
directory

**Comment by amroamroamro** [comment]
@adityaksai please don't post to old/unrelated issues, [create a new one](https://github.com/kyamagu/mexopencv/issues/new).

From what I can tell, your problem is NOT about mexopencv, you seem to be confusing it with the CVST opencv interface provided by MathWorks: https://www.mathworks.com/help/vision/ug/opencv-interface.html
This project is not related to that...
