### ISSUE TITLE
Error using cv.resize

### ISSUE THREAD

**Issue by hjasonmurphy** [kyamagu/mexopencv#235]
I am using Win7 x64, Matlab R2015b x64, OpenCV 3.1.0 and VS2013.  Everything builds ok with the mexopencv.make command and all of the sample files work except facedetect.  The error I am receiving is:

Error using cv.resize
Unexpected Standard exception from MEX file.
What() is:C:\builds\master_PackSlave-win64-vc12-shared\opencv\modules\imgproc\src\imgwarp.cpp:3229: error: (-215) ssize.area() > 0 in function
cv::resize

..

Error in facedetect (line 27)
    im = cv.resize(im,0.5,0.5);

Any help is very much appreciated.
Jason

**Comment by kyamagu** [comment]
Just to make sure, can you read and display the image without face detection?

**Comment by hjasonmurphy** [comment]
I can read in and display the image.

**Comment by amroamroamro** [comment]
@hjasonmurphy 
Try adding the following lines to the `facedetect.m` sample:

``` matlab
% Set up camera
camera = cv.VideoCapture;
pause(3); % Necessary in some environment. See help cv.VideoCapture
assert(camera.isOpened(), 'camera failed to initialized');    % <-- add this line
...
```

and

``` matlab
% Start main loop
while true
    % Grab and preprocess an image
    im = camera.read;
    if isempty(im), break; end    % <-- add this line
    im = cv.resize(im,0.5,0.5);
    ...

end
```

**Comment by hjasonmurphy** [comment]
Thanks very much. There was an issue with the camera.  Not sure why it was locked up but I removed it and plugged it back into USB and it then worked.  Sorry to bother you.  I should have thought of the hardware being an issue.  I apologize for misunderstanding the earlier question... imread() and imshow ()were working for images which I tested first.  I hope I didn't waste too much time.
