### ISSUE TITLE
Octave no lib found when using mex

### ISSUE THREAD

**Issue by matbee** [kyamagu/mexopencv#236]
Hey,
I succesfully build the mex files for Octave.
When loading a mex, for example: cv.watershed(A,B). I get following error:
`/mexopencv-master/+cv/watershed.mex: failed to load: libopencv_imgproc.so.3.1: cannot open shared object file: No such file or directory`

I know libopencv_imgproc.so.3.1 is located at /usr/local/lib.

How do I need to point to the location?
using Octave 4.0.0 with opencv 3.1.0 on a Ubunte 14.0 system.

Thank you for all the effort.

**Comment by kyamagu** [comment]
@matbee Perhaps you will need to set `LD_LIBRARY_PATH` to `/usr/local/lib`; i.e.,

    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

**Comment by matbee** [comment]
In which environment do I need to apply this? In Octave environment variables or do I need to rebuild the mex files?

**Comment by kyamagu** [comment]
In UNIX shell where you launch Octave. Runtime env has nothing to do with compile options

**Comment by amroamroamro** [comment]
@matbee 
Usually after building and installing OpenCV, I would do this:

```sh
make
make install

sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'
sudo ldconfig
```

Both this and the `LD_LIBRARY_PATH` variable do the same thing of telling the system which directories to search for shared libraries.

**Comment by matbee** [comment]
Thank you guys! I tried both, but only amroamroamro solution did the trick.
