### ISSUE TITLE
MEX cannot find library 'opencv_stitching300' specified with the -l option.

### ISSUE THREAD

**Issue by sezan92** [kyamagu/mexopencv#237]
I dont know why Opencv 3.0 with matlab is so problematic!! Every time i solve an issue, another one arises!!! Now this one! It says openc_stitching300 couldnt be found! I went to the location where it should have been , i saw the lib file was there , but the name is "opencv_stitching300d.lib" instead of "opencv_stitching300.lib" !!! only a letter "d"!! now what should i do ? rename all of them ?!!!

**Comment by amroamroamro** [comment]
That is a lot of exclamation points!!!

But seriously, you're gonna have to be more specific and give more info if you want help.

Are you working with OpenCV 3.0.0 or 3.1.0? Did you checkout the correct branch of mexopencv? How did you compile/install opencv?  What are you invoking to compile mexopencv? and so on...

PS: the "d" stands for the debug version, the ones without "d' are the release version binaries and libs.

Also we have a wiki page with detailed instructions: https://github.com/kyamagu/mexopencv/wiki

**Comment by sezan92** [comment]
Opencv 3.0.0
Compiled using Cmake and Installed using Visual C++ 2010. 
Mexopencv is using SDK 7.1

**Comment by amroamroamro** [comment]
Still not enough, please provide full answers here...

What branch of mexopencv are you using? the `master` branch requires opencv 3.1.0. There's a corresponding [v3.0](https://github.com/kyamagu/mexopencv/tree/v3.0) branch for opencv 3.0.0 version.

How did you configure opencv in cmake? Did you select all modules? Did you customize any of the other cmake options? Are you also using opencv_contrib?

Where did you install opencv? What is the directory structure? Did you correctly set the PATH afterwards?

Which MATLAB version are you using? What did you call in MATLAB to compile mexopencv (the full call to `mexopencv.make`)?

Again we have thorough instructions in [the wiki](https://github.com/kyamagu/mexopencv/wiki), it is worth checking out.
