### ISSUE TITLE
cv function  giving errors

### ISSUE THREAD

**Issue by fjansari0201** [kyamagu/mexopencv#242]
```
Invalid MEX-file 'C:\mexopencv-3.0.0+cv\private\CascadeClassifier_.mexw64':
The specified module could not be found.

Error in cv.CascadeClassifier (line 113)
            this.id = CascadeClassifier_(0, 'new');
```

**Comment by kyamagu** [comment]
@fjansari0201 Make sure [you set up the correct PATH](https://github.com/kyamagu/mexopencv#2-install-opencv-library). You might need to sign-out or reboot after changing the variable.

![image](https://camo.githubusercontent.com/8664a790197d53e61d6777adf3e7437d48b892b2/687474703a2f2f692e696d6775722e636f6d2f474167744a41612e706e67)

**Comment by fjansari0201** [comment]
Thanks for the speedy reply but the problem is still there after setting the system variable and also after re starting the PCs

**Comment by AvinoamK** [comment]
There is a discussion on this in http://www.mathworks.com/matlabcentral/answers/92040-why-do-i-receive-a-specified-module-could-not-be-found-error-while-running-a-mex-file-created-from?requestedDomain=www.mathworks.com
and in
http://stackoverflow.com/questions/17023419/win-7-64-bit-dll-problems

To summarize: use Dependency Walker to find missing DLL's, ignore API-MS-WIN-... dlls.
There might be OpenCV dlls or Visual Studio dlls.

**Comment by amroamroamro** [comment]
@fjansari0201 refer to the wiki for complete instructions: https://github.com/kyamagu/mexopencv/wiki
