### ISSUE TITLE
Undefined variable "cv" or class "cv.CascadeClassifier"

### ISSUE THREAD

**Issue by hjasonmurphy** [kyamagu/mexopencv#244]
This is not an issue with your software (which is great... many thanks).  I have written some Matlab code (R2016A) on Ubuntu (14,04) using your matlab mex functions for opencv.  Everything works great  within Matlab.  I compiled the Matlab code so that it could be deployed onto a machine without Matlab.  The compiled Matlab code runs fine on the Ubuntu machine where Matlab and your mex files are installed.  When I move the application to an Ubuntu machine without Matlab or your functions I get the error in the subject line.

I have added /mexopencv-master/+cv/private/CascadeClassifier_.mexa64 as a "required file for the application to run" so it should be a part of the deployment package.  Is there any other files required for it to work?

Thanks in advance,
Jason

**Comment by amroamroamro** [comment]
I've never tried "deploying" projects using mexopencv, but you also need OpenCV libraries to be installed on the target machine. Obviously this is platform-dependent, and should be taken care of outside of MATLAB.

Ideally you would instruct users to install it as any dependency `apt-get install ...`, but the official OpenCV package is usually behind the latest version (I think Ubuntu Trusty is still on OpenCV 2.4). This leaves you with compiling it from source if you want to use the latest 3.1.0 version. You could then create your own [.deb package](https://wiki.debian.org/Packaging) that you distribute along with your deployed app...

**Comment by kyamagu** [comment]
@hjasonmurphy As long as you do not need OpenCV 3, use [the 2.4 release](https://github.com/kyamagu/mexopencv/releases/tag/v2.4.11) of mexopencv and also require OpenCV installation in the target host.

    sudo apt-get install libopencv-dev

If you need OpenCV 3.1, things are a bit complicated as @amroamroamro explains. There seems to be an attempt of [building a deb package for Ubuntu 14.04](https://launchpad.net/~amarburg/+archive/ubuntu/opencv3), but I have never checked if it works.

**Comment by hjasonmurphy** [comment]
Thanks... I am using 3.1.0 so I built opencv on the target machine and the matlab compiled code runs now with just the matlab runtime environment.
