### ISSUE TITLE
Could hep me on the mexopencv error

### ISSUE THREAD

**Issue by khawlah18** [kyamagu/mexopencv#245]
@amroamroamro 

cloud you please help me in this error
I have Matlan 2016 trial use, opencv2.11 and i extract it in D:\

```
Error using mexopencv.make>pkg_config (line 294)
OpenCV library path not found: D:\opencv\build\x64\mingw\lib

Error in mexopencv.make>mex_options (line 251)
[cv_cflags, cv_libs] = pkg_config(opts);

Error in mexopencv.make (line 75)
mex_flags = mex_options(opts);
```

**Comment by amroamroamro** [comment]
A few notes:

- If you're building against OpenCV 2.x, you must use the corresponding [2.4 branch](https://github.com/kyamagu/mexopencv/tree/v2.4) of mexopencv: https://github.com/kyamagu/mexopencv/releases/tag/v2.4.11

- if you're using MinGW/GCC, you must build both OpenCV and mexopencv with the same compiler version. This means that the prebuilt MinGW binaries downloaded are likely not useful, you must re-build it from source.

If you're still having trouble, please provide a more complete report of your environment and the steps you took to compile OpenCV and mexopencv...

Also we have a wiki page with detailed instructions (using Visual C++ as compiler): https://github.com/kyamagu/mexopencv/wiki
