### ISSUE TITLE
Invalid MEX-file - CascadeClassifier_

### ISSUE THREAD

**Issue by RustyProgrammer** [kyamagu/mexopencv#247]
Hello,
 when i try to  run facedetect script in matlab, i get this error : 

> Invalid MEX-file
> 'D:\matlab\bin\MEX\mexopencv-master+cv\private\CascadeClassifier_.mexw64': The
> specified module could not be found.
> 
> Error in cv.CascadeClassifier (line 113)
>            this.id = CascadeClassifier_(0, 'new');
> 
> Error in facedetect (line 8)
> classifier = cv.CascadeClassifier(xml_file);

I did the same steps as like this video said [mexopencv, Tutorial 1: Setup](https://www.youtube.com/watch?v=RQHQQWTqT8g&index=1&list=PLmcMMZCV897pofUfG1yH-8fcjpUTFUSaJ)  .

Can anyone help me with this error ,please?

Thank you !

**Comment by amroamroamro** [comment]
That usually means it couldn't load OpenCV DLLs. You must add the correct folder to the `PATH` environment variable.

You can find a detailed guide in the wiki: https://github.com/kyamagu/mexopencv/wiki
