### ISSUE TITLE
*.mexw64 is not a valid Win32 application

### ISSUE THREAD

**Issue by emro** [kyamagu/mexopencv#25]
Hi, I'm having some trouble with my compiled mex files in Matlab.  The compilation seems to work without any issues, but then when I try to call a function, I get the following error:

```
??? Error using ==> cv.resize
Invalid MEX-file '...\mexopencv-master\+cv\resize.mexw64':
...\mexopencv-master\+cv\resize.mexw64 is not a valid Win32 application.
```

The pathname is correct and the file is present and not empty.  I'm using Matlab R2011a, on Windows 7, both 64-bit.  When I do the compilation, the strings look like this:

```
mex -largeArrayDims -D_SECURE_SCL=1 -Iinclude -I"C:\opencv\build\include" -L"C:\opencv\build\x64\vc9\lib" -lopencv_calib3d243 -lopencv_contrib243 -lopencv_core243 -lopencv_features2d243 -lopencv_flann243 -lopencv_gpu243 -lopencv_haartraining_engine -lopencv_highgui243 -lopencv_imgproc243 -lopencv_legacy243 -lopencv_ml243 -lopencv_nonfree243 -lopencv_objdetect243 -lopencv_photo243 -lopencv_stitching243 -lopencv_ts243 -lopencv_video243 -lopencv_videostab243  src+cv\private\FeatureDetector_.cpp lib\MxArray.obj -output +cv\private\FeatureDetector_
```

When I type "help cv" I get a long list of functions and their usages, so that seems to be working well also.  The only thing that looks a little funny is that the included library are in "vc9" instead of "vc10" - is that problematic?

Any ideas about what could be going wrong and how to fix it would be great!  Thanks.

**Comment by ahmedcoo** [comment]
i got the same error can you help to solve it plz
.mexw64 is not a valid Win32 application
