### ISSUE TITLE
compiling my own created function in mexopencv gives error

### ISSUE THREAD

**Issue by fjansari0201** [kyamagu/mexopencv#252]
I have created my own function and places it in `c:\mexopencv-3.0.0\src\+cv\`. Now when I say `mex filename1` I get an error `unable to include mexopencv.hpp`

**Comment by amroamroamro** [comment]
This is not enough, you must specify the header files locations (of both opencv and mexopencv headers), and link against `MxArray.obj` class (and supporting `mexopencv_*.obj` if using any of these modules) as well as the OpenCV libs...

It would be just easier to use `mexopencv.make` which takes care of this stuff (or turn on verbose/dryrun modes and emulate the commands it emits).
