### ISSUE TITLE
Mex-Error: convert.cpp

### ISSUE THREAD

**Issue by RGring** [kyamagu/mexopencv#253]
Hello I use OpenCV 3.1; Matlab 2013b and Compiler Microsoft Software Development Kit (SDK) 7.1. I did excecute mexopencv.make without error. But when I tried the functions by starting "face_detection-m" from the first Tutorial I got the following error.

Error using cv.cvtColor
Unexpected Standard exception from MEX file.
What() is:..\..\..\sources\modules\core\src\convert.cpp:202: error: (-215) mv
&& n > 0 in function cv::merge

..
Error in face_detection (line 5)
gr = cv.cvtColor(im, 'RGB2GRAY');

Can anybody help? I would apreciate that.
Thanks!

**Comment by kyamagu** [comment]
@RGring I'm not sure what's happening, but can you check the `size` of the image given to `cv.cvtColor` in the `facedetect.m`? You can insert `disp(size(im))` in the demo script.

**Comment by amroamroamro** [comment]
@RGring  May I ask which demo you're running exactly? The one we have in `samples/` has a different name with a different content at line 5: https://github.com/kyamagu/mexopencv/blob/master/samples/facedetect.m

Anyway you should check the image coming from the webcam is not empty and is in fact a color image? Simply run the code line by line and inspect the image `im` just before the `cv.cvtColor` call...

**Comment by RGring** [comment]
I found the problem: I built the Libraries in "Debug"-Mode. After building in "Release"-Mode everything worked fine. Thanks a lot for replying!
