### ISSUE TITLE
help for compiling mexopencv

### ISSUE THREAD

**Issue by hosna** [kyamagu/mexopencv#255]
I am facing this error when I try to compile the mexopencv
cv.make();

/usr/lib/matlab-8.6/bin/mex -cxx -largeArrayDims -Iinclude -I/usr/include/opencv  src/+cv/threshold.cpp -lMxArray -Llib /usr/lib/x86_64-linux-gnu/libopencv_calib3d.so -lopencv_calib3d /usr/lib/x86_64-linux-gnu/libopencv_contrib.so -lopencv_contrib /usr/lib/x86_64-linux-gnu/libopencv_core.so -lopencv_core /usr/lib/x86_64-linux-gnu/libopencv_features2d.so -lopencv_features2d /usr/lib/x86_64-linux-gnu/libopencv_flann.so -lopencv_flann /usr/lib/x86_64-linux-gnu/libopencv_gpu.so -lopencv_gpu /usr/lib/x86_64-linux-gnu/libopencv_highgui.so -lopencv_highgui /usr/lib/x86_64-linux-gnu/libopencv_imgproc.so -lopencv_imgproc /usr/lib/x86_64-linux-gnu/libopencv_legacy.so -lopencv_legacy /usr/lib/x86_64-linux-gnu/libopencv_ml.so -lopencv_ml /usr/lib/x86_64-linux-gnu/libopencv_objdetect.so -lopencv_objdetect /usr/lib/x86_64-linux-gnu/libopencv_ocl.so -lopencv_ocl /usr/lib/x86_64-linux-gnu/libopencv_photo.so -lopencv_photo /usr/lib/x86_64-linux-gnu/libopencv_stitching.so -lopencv_stitching /usr/lib/x86_64-linux-gnu/libopencv_superres.so -lopencv_superres /usr/lib/x86_64-linux-gnu/libopencv_ts.so -lopencv_ts /usr/lib/x86_64-linux-gnu/libopencv_video.so -lopencv_video /usr/lib/x86_64-linux-gnu/libopencv_videostab.so -lopencv_videostab  -o +cv/threshold.mexa64
Unknown MEX argument '-o'.
Makefile:31: recipe for target '+cv/threshold.mexa64' failed
make: *** [+cv/threshold.mexa64] Error 255

**Comment by kyamagu** [comment]
@hosna Looks like `mexopencv` is out of date, check out the latest release for your OpenCV ([v2.4](https://github.com/kyamagu/mexopencv/releases/tag/v2.4.11) or [v3.1](https://github.com/kyamagu/mexopencv/releases/tag/v3.1.0))

**Comment by hosna** [comment]
for the new one I have this problem 
 mexopencv.make
make MATLABDIR="/usr/lib/matlab-8.6" MEXEXT=mexa64    all
Makefile:97: *** "OpenCV 3.x package was not found in the pkg-config search path".  Stop

**Comment by hosna** [comment]
I dont have root access for my pc then I have to install everything locally. is there a way to change the path to my installation of opnecv for mexopencv?

**Comment by amroamroamro** [comment]
@hosna First make sure you are using the correct mexopencv branch that matches your OpenCV version (the master branch expects the latest stable v3.1.0 version, use one of the branches/tags for older opencv versions).

And to answer your question, yes, you can have OpenCV installed anywhere as long as `pkg-config` can locate its corresponding `opencv.pc` file which tells it where to find the headers and libs (set `PKG_CONFIG_PATH` if necessary).

**Comment by hosna** [comment]
I change it to mexopencv2.4.0 and now I have 
In file included from /usr/include/opencv2/opencv.hpp:52:0,
                 from include/MxArray.hpp:14,
                 from include/mexopencv.hpp:14,
                 from /BS/wild-search-gaze/work/mexopencv-2.4 (2)/src/+cv/ORB.cpp:7:
/usr/include/opencv2/features2d/features2d.hpp:460:3: note: cv::ORB::ORB(size_t, const cv::ORB::CommonParams&)
/usr/include/opencv2/features2d/features2d.hpp:460:3: note:   candidate expects 2 arguments, 8 provided
/usr/include/opencv2/features2d/features2d.hpp:416:18: note: cv::ORB::ORB(const cv::ORB&)
/usr/include/opencv2/features2d/features2d.hpp:416:18: note:   candidate expects 1 argument, 8 provided

make: *** [+cv/ORB.mexa64] Error 255

**Comment by kyamagu** [comment]
@hosna Do you have any reason you choose mexopencv v2.4.0? For OpenCV 2.4.x, you should use [v2.4.11 release](https://github.com/kyamagu/mexopencv/releases/tag/v2.4.11).

**Comment by hosna** [comment]
for version 2.4.11 I get this error 
/BS/wild-search-gaze/work/mexopencv-2.4.11/src/+cv/SIFT.cpp:8:39: fatal error: opencv2/nonfree/nonfree.hpp: No such file or directory
 #include "opencv2/nonfree/nonfree.hpp"
                                       ^
compilation terminated.

Makefile:37: recipe for target '+cv/SIFT.mexa64' failed
make: *** [+cv/SIFT.mexa64] Error 255

 2.4.0 compiled but I cant run demos.

**Comment by amroamroamro** [comment]
@hosna see #115 about the 'nonfree' error

**Comment by hosna** [comment]
well, I remove the nonfree based on 115 , the code compiled but now when I am running the calibration_demo I get:
Error using cv.findChessboardCorners
Invalid MEX-file '/BS/wild-search-gaze/work/mexopencv-2.4.11/+cv/findChessboardCorners.mexa64':
/usr/lib/matlab-8.6/bin/glnxa64/../../sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by
/usr/lib/x86_64-linux-gnu/libopencv_ocl.so.2.4)

Error in calibration_demo (line 19)
    pts_l_ = cv.findChessboardCorners(im_l, mesh_size);

**Comment by amroamroamro** [comment]
@hosna 
This one is mentioned in the README file and how to solve it: https://github.com/kyamagu/mexopencv#troubleshooting-invalid-mex-file-or-segmentation-fault

There are also several issues explaining the same solution, see: #9, #45, #80

**Comment by hosna** [comment]
Thanks. its working now.
