### ISSUE TITLE
compiling for Octave in Windows

### ISSUE THREAD

**Issue by matbee** [kyamagu/mexopencv#256]
Hey,

I tried all the steps explained in https://github.com/kyamagu/mexopencv/wiki 
It looks like Octave has another approach, but can I use the Visual Studio approach in Octave?
Allthough make.m is searching for /x86/mingw/, I already tried compiling with mingw, but no succes.

So I'm wondering if I should try further with Visual Studio or MinGW.

Thank you.

**Comment by amroamroamro** [comment]
@matbee 

yes Octave is supported (we require a recent Octave version >= 4.0.0).
However for Octave on Windows, you must compile both OpenCV and mexopencv using the same MinGW GCC compiler included with the Octave distribution (which was used to compile Octave itself).
You can't use Visual Studio, the two don't mix too well.

In fact this is what we do for continuous integration testing on AppVeyor.
So if you want to compile it yourself, the file [`appveyor.yml`][5] contains all the necessary steps to build everything from scratch. See my previous comment here: https://github.com/kyamagu/mexopencv/issues/239#issuecomment-206463530

---

Or you could just download the binaries generated from the AppVeyor builds. Basically you'll need to:
- download binaries of Octave for Windows: `octave-4.0.0_0.zip` from [here][1]
- download binaries of OpenCV (+ opencv_contrib) compiled using Octave's MinGW: `build_mingw_x86.7z` from [here][2]
- extract these two and set the PATH environment variable appropriately:

        %OPENCV_DIR%\x86\mingw\bin
        %OCTAVE_HOME%\bin

- download the latest mexopencv sources: master branch from [here][4]
- download corresponding binaries of mexopencv compiled using same the same MinGW: `mexopencv.7z` from [here][3]
- extract the binaries on top of the sources
- start Octave, set `addpath` correctly, and call any mexopencv function:

        >> MCV_ROOT = 'C:\path\to\mexopencv';
        >> addpath(fullfile(MCV_ROOT,'+cv','private'))
        >> addpath(fullfile(MCV_ROOT,'opencv_contrib'))
        >> addpath(fullfile(MCV_ROOT,'opencv_contrib','+cv','private'))
        >> cv.getBuildInformation()

[1]: https://ftp.gnu.org/gnu/octave/windows/
[2]: https://github.com/amroamroamro/opencv/releases/tag/3.1.0
[3]: https://ci.appveyor.com/project/kyamagu/mexopencv/build/artifacts
[4]: https://github.com/kyamagu/mexopencv/archive/master.zip
[5]: https://github.com/kyamagu/mexopencv/blob/master/appveyor.yml

**Comment by matbee** [comment]
Thank you! Should I still install opencv-2.4.13.exe in your last method? Because I see %OPENCV_DIR% is used, or could I just paste build_mingw_x86.7z somewhere?

**Comment by amroamroamro** [comment]
@matbee 
No need, ` build_mingw_x86.7z ` is actually the compiled opencv + opencv_contrib v3.1.0. Just extract it somewhere, say `c:\dev\opencv`, and add the folder containing the DLLs `c:\dev\opencv\install\x86\mingw\bin` to the system PATH.

Similarly replace the `%OCTAVE_HOME%` part with the location where you have Octave extracted/installed.

**Comment by matbee** [comment]
Ok! Just out of interest, is the content in the directory install still used? Linked with the DLLs or  something?

**Comment by amroamroamro** [comment]
yes those *.dll files are dependencies (mexopencv is linked against OpenCV shared libraries). They are loaded at runtime when you run any of the mexoepncv mex-files in octave.

**Comment by Speederc** [comment]
@amroamroamro Thank you very much for your detailed tutorial, it works like a charm !
