### ISSUE TITLE
error when using mexopencv.make

### ISSUE THREAD

**Issue by KaiyangZhou** [kyamagu/mexopencv#257]
Hi, I have downloaded mexopencv and tried to use mexopencv.make, but these errors appeared on the command line in matlab. (my system: OS X Yosemite 10.10.5, matlab version: matlab2014b)

make MATLABDIR="/Applications/MATLAB_R2014b.app" MEXEXT=mexmaci64    all
/bin/sh: pkg-config: command not found
Makefile:97: *** "OpenCV 3.x package was not found in the pkg-config search path".  Stop.

I have changed the path location to: opts.opencv_path = '/usr/local/include/opencv';

I am very unfamiliar with linux system and command line operation... Could anyone help me with these errors?

**Comment by kyamagu** [comment]
@KaiyangZhou You have to install `pkg-config` tool in UNIX environment. On OS X, I recommend installing OpenCV via Homebrew and do not use a custom-built package unless there is a good reason. Check [this thread](https://github.com/kyamagu/mexopencv/issues/249).

**Comment by KaiyangZhou** [comment]
@kyamagu Thanks. I followed the procedure mentioned in the thread. I installed pkg-config and opencv3 from homebrew.

I typed 'LDFLAGS=-L/usr/local/Cellar/opencv3/3.1.0_3/share/OpenCV/3rdparty/lib/ MATLABDIR=/Applications/MATLAB_R2014b.app make -j4' and it showed

Makefile:97: *** "OpenCV 3.x package was not found in the pkg-config search path".  Stop.

I typed 'pkg-config --exists --atleast-version=3 opencv3
echo $?' and it returned 1. And I also typed 'pkg-config opencv
echo $?' but it also returned 1. I don't know what should I do to remove these errors

**Comment by amroamroamro** [comment]
@KaiyangZhou first make sure that `pkg-config` on its own is able to find your OpenCV installation. Depending on how you installed it, one of these two should work:

``` sh
$ pkg-config --cflags --libs opencv
```
``` sh
$ pkg-config --cflags --libs opencv3
```

If `opencv3` was the one that worked, then you need to invoke the makefile with the `PKG_CONFIG_OPENCV=opencv3` option (by default it looks using the name `opencv`).

If neither worked, then you must locate the file `opencv.pc` or `opencv3.pc` and add the directory containing it to the `PKG_CONFIG_PATH` environment variable, before using `pkg-config`.

**Comment by KaiyangZhou** [comment]
@amroamroamro I found the errors, which were related to wrong path information of opencv.pc. I corrected it and complied successfully with 'LDFLAGS=-L/usr/local/Cellar/opencv3/3.1.0_3/share/OpenCV/3rdparty/lib/ MATLABDIR=/Applications/MATLAB_R2014b.app make -j4'. Now everything is ok. Thanks for both of your comments @kyamagu @amroamroamro
