### ISSUE TITLE
OpenCV FindCirclesGrid doesnt work with 3x3 circles?

### ISSUE THREAD

**Issue by soulslicer** [kyamagu/mexopencv#259]
http://imgur.com/a/cufHy

http://imgur.com/a/kRCBx

`    [isFound, centers] = cv2.findCirclesGrid(gray, (3,3),cv2.CALIB_CB_SYMMETRIC_GRID + cv2.CALIB_CB_CLUSTERING)`

It works with a 4x4 grid, but is unable to detect with a 3x3 grid. Why is this the case? Unfortunately most of my experiment data has already been captured with a 3x3 grid and not a 4x4 one. The documentation seems very sparse, is there something in the code that has a hard limit on the number found?

**Comment by amroamroamro** [comment]
Isn't that the Python binding?
Anyway this is working fine for me, and the grid is detected in both 3x3 and 4x4 cases.

``` matlab
imgs = {
    'http://i.imgur.com/uGll1tQ.jpg'
    'http://i.imgur.com/lIPPtSD.jpg'
};
sizes = {[3 3], [4 4]};
for i=1:numel(imgs)
    img = imread(imgs{i});
    sz = sizes{i};
    [centers, found] = cv.findCirclesGrid(img, sz, ...
        'SymmetricGrid',true, 'Clustering',true);
    out = cv.drawChessboardCorners(img(:,:,[1 1 1]), sz, centers, ...
        'PatternWasFound',found);
    figure, imshow(out)
end
```

If you're not getting good detection, you might wanna play around with the blob detector used by the `findCirclesGrid` function and tweak its options. In mexopencv, you do this as:

``` matlab
cv.findCirclesGrid(img, sz, 'BlobDetector',{'SimpleBlobDetector', 'key',val, 'key',val})
```

where the pairs key/value specify the options of the `cv.SimpleBlobDetector` class, as listed here: https://kyamagu.github.io/mexopencv/matlab/SimpleBlobDetector.SimpleBlobDetector.html

Here is an example where I had to change the area threshold: https://github.com/kyamagu/mexopencv/issues/179#issuecomment-124821942

**Comment by soulslicer** [comment]
That is very surprising. Yes, I am using the Python bindings with the latest version of OpenCV. Are you able to test this out in the Python version? It most certainly is not working with the same settings set.

**Comment by amroamroamro** [comment]
@soulslicer 
This is not the right place to report issues with the Python bindings (head over to [opencv](https://github.com/Itseez/opencv/issues) instead), mexopencv is obviously concerned with MATLAB!

Anyway I think I know what is the problem here, you're calling the function with arguments in the wrong order:

``` python
>>> help(cv2.findCirclesGrid)
Help on built-in function findCirclesGrid:

findCirclesGrid(...)
    findCirclesGrid(image, patternSize[, centers[, flags[, blobDetector]]]) -> retval, centers
```

Flags is not the third argument, but the fourth, so you should use Python's named arguments instead as in: ` cv2.findCirclesGrid(img, sz, flags = cv2.CALIB_CB_CLUSTERING)`

Although wasn't necessary here, you can also pass a blob detector object, something like:

``` python
blobParams = cv2.SimpleBlobDetector_Params()
# .. set blobParams.xxx options ...
blob = cv2.SimpleBlobDetector_create(blobParams)
isfound, centers = cv2.findCirclesGrid(img, sz, blobDetector = blob)
```

---

For reference, here is the example I tested (using OpenCV 3.1.0):

``` python
import cv2

print "OpenCV", cv2.__version__
#print cv2.getBuildInformation()

sizes = [(3,3), (4,4)]
imgs = ["uGll1tQ.jpg", "lIPPtSD.jpg"]
for fname,sz in zip(imgs, sizes):
    img = cv2.imread(fname, cv2.IMREAD_GRAYSCALE)
    isfound, centers = cv2.findCirclesGrid(img, sz,
        flags = cv2.CALIB_CB_SYMMETRIC_GRID + cv2.CALIB_CB_CLUSTERING)
    out = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
    out = cv2.drawChessboardCorners(out, sz, centers, isfound)
    cv2.imshow(fname, out)
cv2.waitKey(0)
cv2.destroyAllWindows()
```
