### ISSUE TITLE
Master branch not compatible with 3.0.0

### ISSUE THREAD

**Issue by scortes48** [kyamagu/mexopencv#262]
This is a lie
"The latest version of mexopencv (master branch) is compatible with OpenCV 3.x. For older OpenCV versions, please checkout the corresponding 2.x branches in (v2.4, v2.3, and v2.1)."

**Comment by kyamagu** [comment]
@scortes48 That's right. OpenCV 3.0 users should use the [release 3.0](https://github.com/kyamagu/mexopencv/releases/tag/v3.0.0).

**Comment by amroamroamro** [comment]
@scortes48 you're right, master branch targets opencv 3.1.0. To be fair though, it does mention it further down in the ["build" section](https://github.com/kyamagu/mexopencv#build):

> Currently, mexopencv targets the final 3.1.0 stable version of OpenCV. You must build it against this exact version [...]

**Comment by amroamroamro** [comment]
Granted the readme file is a bit too long. Perhaps it would be better to move some of that stuff into the wiki instead and link to it. Also we should separate instructions that are meant for 2.x vs 3.x opencv versions..

**Comment by kyamagu** [comment]
@amroamroamro Agreed. The current README is a bit long. Perhaps we can move details like troubleshooting to a dedicated Wiki page. Maybe platform-specific pages there?

**Comment by kyamagu** [comment]
@scortes48 For now, [PR#263](https://github.com/kyamagu/mexopencv/pull/263) fixes the specific issue.
