### ISSUE TITLE
how to debug third-party software of mexopencv

### ISSUE THREAD

**Issue by wangli75850911** [kyamagu/mexopencv#264]
Hi, I am a new user of mexopencv and I am also a new user of matlab, I want to know that how can I debug third-party software of mexopencv. For example, I used a interface of opencv which is in provided by a .mexa64, but when I try to step into it, I fount it dose not  work. Is anyone can help me?

**Comment by kyamagu** [comment]
@wangli75850911 You will need to use an external debugger (gdb). See [this](http://www.mathworks.com/help/matlab/matlab_external/debugging-on-linux-platforms.html).

**Comment by wangli75850911** [comment]
First of all, thanks very much for your attention. But it seem at most can step into the C++ source of mexopencv-master, not opencv source code

**Comment by kyamagu** [comment]
@wangli75850911 It depends on how the linked binary is compiled. Probably you will need to link mexopencv against custom-built OpenCV with debugging symbols (typically, `-g` option in `g++` compiler), if you really need to debug OpenCV source code...

**Comment by wangli75850911** [comment]
You are right, my mexopencv and opencv are also compiled with -g. But I've find the reason is that the method I used gdb is wrong, and now I can debug with the method you provided. so, Thank you very much for help me.
