### ISSUE TITLE
problem compiling dataset

### ISSUE THREAD

**Issue by AvinoamK** [kyamagu/mexopencv#266]
Using the command
 mexopencv.make(..., 'opencv_contrib', true) 
to compile opencv_contrib, the compilation failed on Dataset_.cpp.

First, opencv2/datasets/dataset.hpp was not found. When I have copied it from opencv distribution,
the compilation failed on link errors.

I have used Octave ver 4.1.0+ (pre 4.2 dev branch) on Windows. using the instructions in
https://github.com/kyamagu/mexopencv/issues/256 and opencv from https://github.com/amroamroamro/opencv/releases/tag/3.1.0

Thanks,

Avinoam

**Comment by amroamroamro** [comment]
The precompiled binaries in `cv310_x86_gcc493.7z` have actually changed, even though the file name stayed the same. I had to add additional opencv modules that were previously disabled, including `datasets`. The new binaries are compiled with MinGW-GCC 4.9.3 that comes with the latest stable release of Octave 4.0.3.

So please redownload the file `cv310_x86_gcc493.7z` and try again.

I did also update the instructions in [the wiki](https://github.com/kyamagu/mexopencv/wiki) to reflect the new modules added.. So if you want you can always compile OpenCV yourself from scratch.

**Comment by AvinoamK** [comment]
Thanks, I will use the new file.

**Comment by AvinoamK** [comment]
Updating  cv310_x86_gcc493.7z   fixed the problem. Thanks,
