### ISSUE TITLE
Unable to use Aruco

### ISSUE THREAD

**Issue by Apicio** [kyamagu/mexopencv#270]
Hi there. Above all let me say that this is an awesome work. This is great.
I've a big trouble: I need to use Aruco with Matlab, but I am unable to use it trough mexopencv. In fact I can't find any mex file of Aruco library when compiling against OpenCV.

Matlab 2015a 64bit.
Compiler: MSVC14 (2015) x64
OpenCV version: latest from their git cde9d64
Contrib installed: yes
Contrib compiled: yes
OS: Windows 10 AnniversayUpdate x64

Please let me know if you need anything else, I really need to use Aruco with Matlab!

Thank you.

**Comment by amroamroamro** [comment]
Unfortunately aruco module is not yet covered in mexopencv.

Here is a list of [modules](http://docs.opencv.org/3.1.0/) that are currently missing in mexopencv:

### opencv
- `cuda*`
- `viz`

### opencv_contrib
- `aruco`
- `ccalib`
- `cvv`
- `dnn`
- `fuzzy`
- `hdf`
- `reg`
- `rgbd`
- `sfm`
- `stereo`
- `structured_light`
- `surface_matching`
- `text`
- `tracking`

---

We're slowly adding more, but some of these modules expose an API that is tricky to wrap for other languages in a clean way.
For instance, some functions in aruco module take and return arguments that are instances of complex classes (`CharucoBoard`, `Dictionary`, etc..), where these objects are meant to be passed between calls to different functions. So we have to either persist state between separate MEX-files or somehow serialize them when we cross between C++ and MATLAB and back.

**Comment by amroamroamro** [comment]
@Apicio we've added aruco module to mexopencv. Pull the latest changes and recompile (against opencv+opencv_contrib v3.1.0). Follow the instructions in the [wiki](https://github.com/kyamagu/mexopencv/wiki).

**Comment by Apicio** [comment]
Well this is simply great, I was really waiting for it. I've implemented my marker detector, but I'll test it for sure :) I'll close this asap.

**Comment by amroamroamro** [comment]
You can find a bunch of samples in `opencv_contrib/samples/aruco_*.m`, translated from the original [C++ samples](https://github.com/opencv/opencv_contrib/tree/3.1.0/modules/aruco/samples). Also consult the aruco tutorials in opencv docs: http://docs.opencv.org/3.1.0/d9/d6d/tutorial_table_of_content_aruco.html

**Comment by amroamroamro** [comment]
@Apicio I'm closing the issue as resolved.
If you find any issues with aruco in mexopencv, please file new bug reports.
