### ISSUE TITLE
BioInspired fails to compile, always.

### ISSUE THREAD

**Issue by Apicio** [kyamagu/mexopencv#271]
Hi there. Another issue. mexopencv is unable to compile latest bioninspired lib from Opencv_contrib.

Here's my specs:

Matlab 2015a 64bit.
Compiler: MSVC14 (2015) x64
OpenCV version: latest from their git cde9d64
Contrib installed: yes
Contrib compiled: yes
OS: Windows 10 AnniversayUpdate x64

EDIT: I found that this module fails to compile in Visual Studio stage, so I think this is not mexopencv fault.

![image_2016-09-21_19-05-05](https://cloud.githubusercontent.com/assets/3626130/18720954/6197854a-802e-11e6-8cdd-036eabc5f386.png)

**Comment by amroamroamro** [comment]
mexopencv targets the last stable release of opencv/opencv_contrib (which is v3.1.0 for the time being).
We don't keep up with the nightly 3.x from the master branch...

PS: you can find instructions in the wiki on how to compile mexopencv with opencv+opencv_contrib 3.1.0 for Windows/VisualStudio: https://github.com/kyamagu/mexopencv/wiki

**Comment by Apicio** [comment]
Thanks for answering. :)
