### ISSUE TITLE
BriefDescriptorExtractor_.cpp issue !!!!

### ISSUE THREAD

**Issue by MassifalE** [kyamagu/mexopencv#273]
hello
I'm new in OpenCV. I have an issue when i build the MexOpenCV in Matlab 2016a.
I use Microsoft Visual studio 2015 as compiler.
I use the official build provided From OpenCV3.1.0 in the official website. 
when I execute the command:

`mexopencv.make('opencv_path','C:\opencv\opencv\build', 'opencv_contrib',true)`

 The build begin and after a moment I have the following message:

mex -O -largeArrayDims   -I'C:\OpenCV300\mexopencv\include' -I'C:\opencv\opencv\build\include' -L'C:\opencv\opencv\build\x64\vc14\lib'  -lopencv_bgsegm310 -lopencv_calib3d310 -lopencv_core310 -lopencv_datasets310 -lopencv_dnn310 -lopencv_dpm310 -lopencv_face310 -lopencv_features2d310 -lopencv_flann310 -lopencv_fuzzy310 -lopencv_highgui310 -lopencv_imgcodecs310 -lopencv_imgproc310 -lopencv_line_descriptor310 -lopencv_ml310 -lopencv_objdetect310 -lopencv_optflow310 -lopencv_photo310 -lopencv_plot310 -lopencv_reg310 -lopencv_rgbd310 -lopencv_saliency310 -lopencv_shape310 -lopencv_stereo310 -lopencv_stitching310 -lopencv_superres310 -lopencv_text310 -lopencv_tracking310 -lopencv_video310 -lopencv_videoio310 -lopencv_videostab310 -lopencv_world310 -lopencv_xfeatures2d310 -lopencv_ximgproc310 -lopencv_xobjdetect310 -lopencv_xphoto310 'C:\OpenCV300\mexopencv\opencv_contrib\src\+cv\private\BriefDescriptorExtractor_.cpp' 'C:\OpenCV300\mexopencv\lib\MxArray.obj' 'C:\OpenCV300\mexopencv\lib\mexopencv_features2d.obj' 'C:\OpenCV300\mexopencv\lib\mexopencv_ml.obj' 'C:\OpenCV300\mexopencv\lib\mexopencv_shape.obj' 'C:\OpenCV300\mexopencv\lib\mexopencv_stitching.obj' 'C:\OpenCV300\mexopencv\lib\mexopencv_videostab.obj' -output 'C:\OpenCV300\mexopencv\opencv_contrib\+cv\private\BriefDescriptorExtractor_'

Building with 'Microsoft Visual C++ 2015 Professional'.
Error using mex
BriefDescriptorExtractor_.cpp
C:\OpenCV300\mexopencv\opencv_contrib\src\+cv\private\BriefDescriptorExtractor_.cpp(44): error C3861:
'createBriefDescriptorExtractor': identifier not found

Error in mexopencv.make (line 139)
            if ~opts.dryrun, eval(cmd); end
 `
OS: Windows 10
Version: OpenCV 3.1.0
Matlab R2016a
Compiler: Microsoft Visual C++ 2015 Professional

Where is the problem in your opinion? 
I hope someone help me :)
Thank you very much

**Comment by kyamagu** [comment]
@MassifalE The path `C:\OpenCV300\mexopencv\include` indicate you are using OpenCV 3.0, not OpenCV 3.1. Check if you are really using the right version of `mexopencv`.

**Comment by MassifalE** [comment]
it is a mistake when i create the folder in the first time. I use the OpenCV version 3.1.0

**Comment by amroamroamro** [comment]
@MassifalE  

>  I use the official build provided From OpenCV3.1.0 in the official website. 

Note that the official installer does not include the contrib modules, so you can't set `'opencv_contrib',true` in the make call.

Either set it to false, or compile both opencv and opencv_contrib yourself from source. You can find instructions [here](https://github.com/kyamagu/mexopencv/wiki).

**Comment by MassifalE** [comment]
@amroamroamro Thank you for your help. The problem is resolved by using 'opencv_contrib',false. Now I have another problem:
When I execute `cv.getBuildInformation()` to verify the installation, I have the following message:
Error using cv.getBuildInformation
Invalid MEX-file 'C:\OpenCV300\mexopencv\+cv\getBuildInformation.mexw64': The specified module could not be found.
I added the bin folder in the PATH system.
Thank you @kyamagu and @amroamroamro  :)

**Comment by amroamroamro** [comment]
@MassifalE 
Make sure you've added the correct `bin` folder to the PATH (the one containing the `opencv_*310.dll` files). In your case that would be: `C:\opencv\opencv\build\x64\vc14\bin`.

**Comment by MassifalE** [comment]
@amroamroamro MATLAB was proposed the wrong PATH. Now the problem is resolved thank you for you all 
have a good night
