### ISSUE TITLE
Issue compiling MATLAB 2016a with MinGW64 Compiler

### ISSUE THREAD

**Issue by DNLFe** [kyamagu/mexopencv#274]
Hi, I just start working with OpenCV and I am struggling to get Matlab to compile OpenCV. I am using a Matlab 2016a 64-bit and OpenCV 3.1. When I use mexopencv.make function I get the following error:

Error using mexopencv.make>pkg_config (line 300)
OpenCV library path not found: C:\opencv\build\x64\mingw\lib

Error in mexopencv.make>mex_options (line 257)
    [cv_cflags, cv_libs] = pkg_config(opts);

Error in mexopencv.make (line 81)
    mex_flags = mex_options(opts);

I would appreciate any help

**Comment by kyamagu** [comment]
@DNLFe Do you have VisualStudio? You have to install a working C++ compiler. Check [Mathworks support page](http://www.mathworks.com/support/compilers/R2016a/index.html).

**Comment by DNLFe** [comment]
Ah, ok. Because when I runned `mex -setup`, Matlab advised me to go with MinGW64 which is a free one. I don't have Visual Studio, I am trying to figure that out now. Thank you, @kyamagu.  Just one doubt, is mexopencv a alternative to the "CMake-phyton" process to run OpenCV code within Matlab?

**Comment by kyamagu** [comment]
@DNLFe mexopencv has nothing to do with python nor CMake. Of course, you can write a Python program to use OpenCV.

**Comment by DNLFe** [comment]
@kyamagu My big problem now is that I am not being able to run a Matlab code that has "cv." commands on it. So, the solution would follow the steps to use "mexopencv" (https://github.com/kyamagu/mexopencv)? I mentioned CMake because I saw a tutorial using it to, probably, solve my problem but I just saw mexopencv as well. I am sorry I just start working on it and also still getting familiar with the terms once I am not from a pure computational background.

**Comment by kyamagu** [comment]
@DNLFe Yes, follow the instruction in the [README](https://github.com/kyamagu/mexopencv). You have to first compile the code `mexopencv.make` to use cv functions.

**Comment by amroamroamro** [comment]
@DNLFe 
- CMake is a cross-platform build system, used to generate build files for a variety of systems (GNU Make, Visual Studio, XCode, etc..). It is used by OpenCV and many other projects, but we don't use it in mexopencv itself.

- You can use either MinGW or Visual Studio to compile mexopencv for MATLAB. However you must have OpenCV binaries compiled using the same compiler as well. The official `opencv-3.1.0.exe` installer does not include mingw binaries (only vc12 and vc14), that's why you get the error message about `C:\opencv\build\x64\mingw\lib` not found.. This means you must manually compile opencv from source if you want to use MinGW-w64 as compiler for mexopencv.

**Comment by amroamroamro** [comment]
@DNLFe 
For someone getting started, here is the easiest way to work with mexopencv on Windows:
- install MATLAB
- install Visual Studio (2013 or 2015)
- install OpenCV (the official 3.1.0 installer), and set `PATH` environment variable as explained
- download mexopencv
- in MATLAB, first call `addpath` as required, then run `mexopencv.make` with the appropriate options

**Comment by DNLFe** [comment]
Thank you, @kyamagu and @amroamroamro. I really appreciate your help!

**Comment by DNLFe** [comment]
The Visual Studio and the Matlab must be in the same architecture (32 or 64 bit), right? @amroamroamro

**Comment by amroamroamro** [comment]
Visual Studio includes compilers for both 32 and 64 bit, so you don't need to worry about that.

**Comment by DNLFe** [comment]
@amroamroamro in the steps you said a Visual Studio 2012 wouldn't work.. am I right?

**Comment by DNLFe** [comment]
Got it! It worked with Visual Studio 2015 community. Thank you so much, @amroamroamro and @kyamagu

**Comment by amroamroamro** [comment]
Glad you got it to work.
Just to be clear, it also works with VS2012 (or any version really), it's just that the official opencv-3.1.0 installer does not include the precompiled binaries for it, so you'll end up having to compile opencv yourself... It would be easier to use VS2013/2015 instead to get started quickly.
