### ISSUE TITLE
TestFiltLine failed with Octave

### ISSUE THREAD

**Issue by AvinoamK** [kyamagu/mexopencv#278]
I have check last version (after pull request #277) with Octave-4.2-rc2.
There was 1 failure, with TestFiltLine. The reason of this failure is that the lines
```
           if ~license('test', stat_lic) || isempty(ver(stat_pkg))
                disp('SKIP');
                return;
            end
```
check is the statistics package is installed. In my case it was installed, but the script failed on
`           points = mvnrnd([0 0 0], [7 5 5; 5 7 5; 5 5 7], 100);`
because the statistics package is not loaded. It can be solved simply by
```
           if mexopencv.isOctave()
              pkg load statistics
            end
```
Or maybe there is a better way to check if the package is loaded already, and load it if needed.

Thanks,

Avinoam

**Comment by amroamroamro** [comment]
Apparently `license test` in Octave will return true if a package is installed, regardless of whether or not it is loaded, weird..

As a solution, I think it would be easier to just load all required system packages before running the test suite. You really only need these two:

    pkg load statistics
    pkg load image

This is in fact what we do in CI tests (see the travis and appveyor scripts).

If you want packages to autoload when Octave starts, you can put those commands in your `.octaverc` config file, or run this once `pkg rebuild -auto statistics image`.

**Comment by amroamroamro** [comment]
Here is a snippet of code to see if a package is loaded in Octave:

```matlab
pkgname = 'statistics';
[~,list] = pkg('list');
list = list(cellfun(@(s) s.loaded, list));
list = cellfun(@(s) s.name, list, 'Uniform',false);
if ~ismember(pkgname, list)
    pkg('load', pkgname);
end
```

**Comment by AvinoamK** [comment]
Thanks,
BTW "`pkg rebuild -auto`" will not work in the next version of Octave. This option was removed,
but the option of using `.octaverc`  (or `octaverc` in Windows) still exists.

**Comment by amroamroamro** [comment]
@AvinoamK I added a new function `mexopencv.require` to better handle this. It should now check and load packages as required, without having to manually do it. See 20cdd220b291196fc30b207b992e67ac06a926e0 for details.

Could you test it in beta/RC version of Octave 4.2

**Comment by AvinoamK** [comment]
I check this version with octave 4.2-rc2 and it was OK:
Totals:
  934 Passed, 0 Failed
  Elapsed time is 294.163197 seconds.

I did not check the samples yet.

BTW: what about adding  a version number to mexopencv, instead of using commit number?
It could something like opencv_version.commit_running number, for example: 3.1.54.
Thanks,

**Comment by amroamroamro** [comment]
@AvinoamK 
Samples were not modified by this, they either work in Octave or don't..
Like I explained before, samples were developed with the latest MATLAB in mind, and would require a significant rewrite of some of these examples to fill the missing functionalities in Octave and get them to work.

---

What do you mean by the version number, where would this number be used?

**Comment by AvinoamK** [comment]
First of all: checking with Octave-4.2-rc2, now with opencv_contrib:
mexopencv.make('test',true, 'opencv_contrib', true) 
Totals:
  1094 Passed, 0 Failed

---

About the version number, it could be helpful to know what version do I have, and what is
the latest version in the repository. Moreover,  when people report a problem or a bug, they should report their mexopencv version.

**Comment by amroamroamro** [comment]
Ah. Well if you're working from a git repo (i.e you cloned mexopencv not just downloaded the zip file), you can always [ask `git`](http://stackoverflow.com/questions/949314/how-to-retrieve-the-hash-for-the-current-commit-in-git) to describe the current version. Personally I like this format:

``` sh
$ git describe --tags --always --long --dirty
v3.1.0-67-gf469436-dirty
```

Which [means](https://git-scm.com/docs/git-describe) HEAD is currently 67 commits on top of the last tag (v3.1.0) with commit hash f469436 and a dirty working tree (i.e uncommitted local changes).

Of course in git world the SHA-1 alone is a unique ID for any commit. Here is the full hash:

``` sh
$ git rev-parse HEAD
f469436775c49dce3e8f408484cfd4d77c854364
```
