### ISSUE TITLE
snapnow cause error in some sample programs when using Octave

### ISSUE THREAD

**Issue by AvinoamK** [kyamagu/mexopencv#279]
snapnow is not implemented in Octave, so some of the sample programs emit error in the end.
A simple solution:
```
           if ~mexopencv.isOctave()
              snapnow
            end
```
Thanks,
Avinoam

**Comment by amroamroamro** [comment]
I submitted a fix for this.

But as you'll find out, there are several samples that don't work in Octave, `snapnow` is just one of those things that fail...

Some samples use UI features not implemented in Octave (especially the GUI ones), like HG2 stuff that won't work on older MATLAB releases or Octave. We also use functions from Statistics, IPT, or CVST toolboxes without testing if they are available, or use new stuff only available in new versions (`tables`, `rng`, .. to name a few). Many of these don't yet have an Octave equivalent.
 
IMO the purpose of the examples is to illustrate how to use various opencv functions. Unlike the core of mexopencv implementation or unit tests, the focus here is on showing a demo and less so on maintaining octave-compatibility or even being backward-compatible with previous MATLAB releases. That would only clutter the code, losing on readability having to write alternate code paths for each difference (think: MATLAB vs Octave, HG1 vs HG2, etc...)

As a matter of fact, I was thinking or removing all those `mexopencv.isOctave` checks from samples!

Personally I think it's ok to be less strict in the samples and use any functions needed for convenience, even if they won't work on every version/installation. @kyamagu what do you think?

**Comment by amroamroamro** [comment]
@AvinoamK 
BTW many of the samples are meant to be run [section-by-section](https://www.mathworks.com/help/matlab/matlab_prog/run-sections-of-programs.html) (i.e cell-mode, like in the `showdemo` function).

You can also [`publish`](https://www.mathworks.com/help/matlab/matlab_prog/publishing-matlab-code.html) them in MATLAB to produce a nice HTML document, showing both code and output.
That was the reason for the `snapnow` calls there..

**Comment by kyamagu** [comment]
@amroamroamro I basically agree with your view. Code clarity and maintainability is more of the priority here. Indeed, some of the tests/samples do not work anymore on my old Matlab.

There is no one-fit-all solution to version/platform issues anyway. The fact Matlab requires a license makes it hard to prepare testing environment also. So, I would be just okay if the code is at least passing the test in the CI environment...

Btw, @amroamroamro, do you have an interest in owning the repository? I am a bit off the Github activity these days, and might not be able to respond to issues quickly in the future.

**Comment by amroamroamro** [comment]
@kyamagu Sure, I'm happy to maintain the project and keep it up-to-date.

**Comment by kyamagu** [comment]
@amroamroamro Thanks, then I will transfer the repository to you. Perhaps this involves a bit of URL rewrite if anything is hard-coded. I truly appreciate your continuous effort on development, maintenance, and user support ;)

**Comment by kyamagu** [comment]
@amroamroamro Actually, repository transfer doesn't work when a new user already has the repository fork or the repository with the same name.

https://help.github.com/articles/about-repository-transfers/

Let me know if you clean up your fork and wish to transfer. Meanwhile I sent you a collaborator request, which also allows you to administer without transfer. If you don't like the burden of URL-related rewrite, I can just keep this without repository transfer.

**Comment by amroamroamro** [comment]
@kyamagu 
I see, I'm actually fine with [collaborator access](https://help.github.com/articles/permission-levels-for-a-user-account-repository/), we get to keep all existing URLs this way..

I'll delete my fork next and continue working against this repo directly.

Thanks again for doing this :)

**Comment by kyamagu** [comment]
@amroamroamro Alright, if the collaborator access is just fine with you, you can keep your fork or delete whenever you want. I will of course try to help and keep up with the development ;)

**Comment by AvinoamK** [comment]
@amroamroamro: 
Thanks for the detailed answer.
However, I think that if a sample program needs a small change to work with Octave, this change
should be done. Also, all those` mexopencv.isOctave `checks from samples should not be remove.

**Comment by AvinoamK** [comment]
@amroamroamro: 
I understand your attitude regarding to samples, but still
I would like to report on another problem, you can fix it  or not..

connected_components_demo_gui fails in Octave because of the line
      ` dst = uint8(255 * ind2rgb(labels, clr));`
The problem is that labels is int32 and Octave's ind2rgb does not support int32.
The fix is simple: Change:
   `[labels, nLabels] = cv.connectedComponents(bw);`
to:
   `[labels, nLabels] = cv.connectedComponents(bw, 'LType', 'uint16');`

BTW,
I have checked last version (#295) with Octave-4.2-rc4 and I did not see any problem.

Thanks.

**Comment by amroamroamro** [comment]
@AvinoamK 
I'll include a fix for Octave, mine is a bit different using:

``` matlab
labels = double(labels) + 1;
```

This converts the 0-based *integer* indices to *double* type (1-based indices).
That works for `ind2rgb` in both [MATLAB](https://www.mathworks.com/help/matlab/ref/ind2rgb.html) and [Octave](https://www.gnu.org/software/octave/doc/v4.0.3/Representing-Images.html).
