### ISSUE TITLE
Error using cv.findTransformECC

### ISSUE THREAD

**Issue by dongx358** [kyamagu/mexopencv#291]
Hi,

I used Matlab R2015a, and compiled mexopencv successfully using vs2013. The functions for features tracking I used (e.g. `cv.calcOpticalFlowPyrLK`, `cv.goodFeaturesToTrack`, `cv.cornerSubPix`, ORB etc) work very well. But when I use `cv.findTransformECC` it doesn't work. I simply tried the basic one:

``` matlab
img1 = imread('1.jpg'); 
img2 = imread('2.jpg');
warpMatrix  = cv.findTransformECC(img2, img1);
```

Then it gave error like this below:

```
Error using cv.findTransformECC
Unexpected Standard exception from MEX file.
What() is:C:\builds\master_PackSlave-win64-vc12-shared\opencv\modules\video\src\ecc.cpp:337:
error: (-210) warpMatrix must be single-channel floating-point matrix in function
cv::findTransformECC
```

I tried to other usage shown in documentation, but it still doesn't work.
Could you help me with this? Is there any thing wrong with my compilation or my usage about this function? Thanks a lot.

**Comment by amroamroamro** [comment]
Check the class and size of input images, i.e `class(img)` and `size(img)`, and make sure they are grayscale (single-channel) not color images.

**Comment by amroamroamro** [comment]
Now that I read the docs a second time, it seems you must supply an initial transformation matrix (the 'InputWarpMatrix' option is not optional after all). Like the docs says, if you don't have that information, use an identity 2x3 or 3x3 matrix.

**Comment by dongx358** [comment]
@amroamroamro 
Thanks for you reply. My original jpg files are already grayscale. They are both single-channel. I think the problem is not this you first mentioned.

Besides, I also tried using the following command:

warpMatrix  = cv.findTransformECC(img2, img1, 'MotionType', 'Homography', 'InputWarpMatrix', single(eye(3)));

Then I got the error like this:

Error using findTransformECC
Unrecognized option InputWarpMatrix

Have you tried it successfully? So could you show me how to correct use this function just in this version? I just need to compute the homography using ECC algorithm. Thanks a lot.

**Comment by amroamroamro** [comment]
Sorry doc typo, the option is called `InputWarp` not `InputWarpMatrix`.

**Comment by dongx358** [comment]
@amroamroamro 
Yeah, this time it works. You are right that it is a typo. Hope you'll fix it in next update. Thanks a lot for your help.

**Comment by m7ammad7assan** [comment]
this problem still happens to me, i have used default wrap matrix with no avail ..

**Comment by amroamroamro** [comment]
@m7ammad7assan
Can you elaborate? A reproducible example would help.

As mentioned above, also check the [unit tests](https://github.com/kyamagu/mexopencv/blob/master/test/unit_tests/TestFindTransformECC.m) to understand the [cv.findTransformECC](http://amroamroamro.github.io/mexopencv/matlab/cv.findTransformECC.html) function usage.
