### ISSUE TITLE
No .mexmaci64 generated on El Capitan

### ISSUE THREAD

**Issue by chattob** [kyamagu/mexopencv#294]
Hi,

I have an issue building the package using Mac OS El Capitan and openCV 3.1.
I executed the command from the README.md : 

$ make MATLABDIR=/Applications/MATLAB_R2016a.app PKG_CONFIG_MATLAB=opencv3 LDFLAGS=-L/usr/local/share/OpenCV/3rdparty/lib -j2

This runs without error but no .mexmaci64 files are generated...
The console returns the following last message:

MEX completed successfully.
ar -crs lib/libMxArray.a lib/MxArray.o lib/mexopencv_features2d.o lib/mexopencv_ml.o lib/mexopencv_shape.o lib/mexopencv_stitching.o lib/mexopencv_videostab.o

Thanks a lot for your work and your support!

Bastien

**Comment by kyamagu** [comment]
@chattob Can you try `all` target?

    make MATLABDIR=/Applications/MATLAB_R2016a.app PKG_CONFIG_MATLAB=opencv3 LDFLAGS=-L/usr/local/share/OpenCV/3rdparty/lib -j2 all

**Comment by chattob** [comment]
It worked, thanks! 
I still have an issue. For instance running "img = cv.imread('picture.jpg')" in MATLAB, I get

Error using cv.imread
Attempt to execute SCRIPT imread as a function:
/Users/bchatton/Documents/MATLAB/mexopencv/+cv/imread.m

Do you know where it might come from?

**Comment by kyamagu** [comment]
@chattob Are you sure you successfully compiled `+cv/imread.mexmaci64`? This could be due to dependency issue. Check the following to see if there is any broken dependency.

    otool -L +cv/imread.mexmaci64  # On UNIX terminal

    !otool -L +cv/imread.mexmaci64  # Inside Matlab

**Comment by chattob** [comment]
I think so. I don't see any. 

[otool.txt](https://github.com/kyamagu/mexopencv/files/587819/otool.txt)

**Comment by kyamagu** [comment]
@chattob Seems right. Can you also check the following and see if there is any difference between inside/outside Matlab? I once experienced image codecs shipped with Matlab doing bad.

    otool -L /usr/local/opt/opencv3/lib/libopencv_imgcodecs.3.1.dylib

**Comment by chattob** [comment]
Indeed you were right!
The libtiff provided by MATLAB was causing the trouble. I fixed it following this issue: https://github.com/kyamagu/mexopencv/issues/250
Thanks a lot!

**Comment by amroamroamro** [comment]
@kyamagu 
Regarding `make` vs. `make all`, that's my fault, when I made [these](https://github.com/kyamagu/mexopencv/commit/c66cb37bbee7937049aea136af3eb6f2fa9f52ea#diff-b67911656ef5d18c4ae36cb6741b7965L134) changes.
The default target `all` should be listed first before any other target. I'll include a fix in my next PR.

**Comment by kyamagu** [comment]
@amroamroamro I see, thanks. `libtiff` seems to be a common case in mac.

**Comment by amroamroamro** [comment]
@kyamagu 
Perhaps we should elaborate on this entry in the wiki: https://github.com/kyamagu/mexopencv/wiki/Troubleshooting-%28UNIX%29#invalid-mex-file-or-segmentation-fault

**Comment by kyamagu** [comment]
@amroamroamro Sure, will edit.
