### ISSUE TITLE
Matlab2014 with vs2010 \opencv_contrib issues error LNK2019

### ISSUE THREAD

**Issue by nutsqiang** [kyamagu/mexopencv#297]
```
Error using mex
   正在创建库 （Creating library）D:\dev\mexopencv\opencv_contrib\+cv\private\Dataset_.lib 和对象（and class）
   D:\dev\mexopencv\opencv_contrib\+cv\private\Dataset_.exp
Dataset_.obj : error LNK2019: 无法解析的外部符号（unresolved external symbol）;
 "public: static struct cv::Ptr<class cv::datasets::TRACK_vot> __cdecl cv::datasets::TRACK_vot::create(void)"
(?create@TRACK_vot@datasets@cv@@SA?AU?$Ptr@VTRACK_vot@datasets@cv@@@3@XZ)，
该符号在函数(this symbol in function) 
"struct cv::Ptr<class cv::datasets::Dataset> __cdecl `anonymous namespace'::create_Dataset(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)"
(?create_Dataset@?A0x7ae8552b@@YA?AU?$Ptr@VDataset@datasets@cv@@@cv@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
中被引用(be cited)
```

the content in bracket is translated for Chinese,my english is very poor.
what can I do?

**Comment by amroamroamro** [comment]
Can you confirm that you are building against the 3.1.0 version of BOTH opencv and opencv_contrib?

If so, please turn on verbose output by adding:

``` matlab
>> mexopencv.make(..., 'Verbose',2)
```

and post the output here for the mex call that fails.

**Comment by amroamroamro** [comment]
And to address the error message you see, the function that the linker is complaining about in your case should not be an issue.. It is [declared here](https://github.com/opencv/opencv_contrib/blob/3.1.0/modules/datasets/include/opencv2/datasets/track_vot.hpp#L71) and [defined here](https://github.com/opencv/opencv_contrib/blob/3.1.0/modules/datasets/src/track_vot.cpp#L224).

**Comment by nutsqiang** [comment]
Thank you very mach! I try it using your comment,but it is still unsuccessful.When I build the lib and dll using vs 2010 and cmake(win7 32bit),some is failed.So I think maybe it is the problem.

**Comment by amroamroamro** [comment]
Ok, but can you show us the output from the verbose command?

More importantly, you still haven't confirmed that you are indeed using the **CORRECT VERSIONS** of `opencv`/`opencv_contrib`. Like I mentioned earlier, you *MUST* use v3.1.0, so please verify that first...

**Comment by nutsqiang** [comment]
When I input this “mexopencv.make('opencv_path','D:\dev\build\install', 'verbose',2)”,it can mex successful.However,it doesn’t include “opencv_contrib”.
When I run “mexopencv.make('opencv_path','D:\dev\buildnew\install', 'opencv_contrib',true)” ,it will show the massage
 “错误使用 mex
   正在创建库 D:\dev\mexopencv\opencv_contrib\+cv\private\Dataset_.lib 和对象
   D:\dev\mexopencv\opencv_contrib\+cv\private\Dataset_.exp
Dataset_.obj : error LNK2019: 无法解析的外部符号 "public: static struct cv::Ptr<class cv::datasets::TRACK_vot> __cdecl
cv::datasets::TRACK_vot::create(void)"
(?create@TRACK_vot@datasets@cv@@SA?AU?$Ptr@VTRACK_vot@datasets@cv@@@3@XZ)，该符号在函数 "struct cv::Ptr<class
cv::datasets::Dataset> __cdecl `anonymous namespace'::create_Dataset(class std::basic_string<char,struct
std::char_traits<char>,class std::allocator<char> > const &)"
(?create_Dataset@?A0x7ae8552b@@YA?AU?$Ptr@VDataset@datasets@cv@@@cv@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
中被引用
出错 mexopencv.make (line 139)
            if ~opts.dryrun, eval(cmd); end
”
I download from "https://github.com/opencv/opencv_contrib/releases/tag/3.1.0",and the mexopencv is the master.So the version should be right.

**Comment by amroamroamro** [comment]
Options can be combined, so add the "Verbose" option to the existing ones. In this case the call should have been:
``` matlab
mexopencv.make('opencv_path','D:\dev\build\install', 'opencv_contrib',true, 'verbose',2)
```

Now note that if you're switching between 'opencv_contrib' being `true` and `false`, you must cleanup the previously compiled files first:

```
mexopencv.make('clean',true, 'opencv_contrib',true);
mexopencv.make('opencv_path','D:\dev\build\install', 'opencv_contrib',true);
```

Otherwise you'll get linking errors...

**Comment by nutsqiang** [comment]
hello,it's me again,I download the program form https://github.com/postmandev/shortest_driving_path/tree/master/matlab.
I build it using matlab ,but it can't succeed,my computer is win7 32bit.So I come here ask the master's help.Could you help me turn the cc to mexw32? If you haven't enough time, you can only help me the dijkstra_matix.cc,dijkstra_graph.cc and dijkstra_nonholonomic16.cc.Thank you very mach!

**Comment by amroamroamro** [comment]
@nutsqiang Please keep it related to mexopencv issues only.
