### ISSUE TITLE
Locking mex-files

### ISSUE THREAD

**Issue by amroamroamro** [kyamagu/mexopencv#299]
I came across the bug previously reported in #70:

``` matlab
vid = cv.VideoCapture('file.mp4');
clear mex
clear vid
```

This is a worst case example as it hangs/crashes MATLAB (VideoCapture depends on an external FFmpeg library which should not be unloaded if a video file is still opened).

Other classes suffer from this as well (say `obj = cv.SVM(); clear mex, clear obj`), but the problem goes unnoticed (the last `clear obj` will in fact reload the mex-file in memory and call 'delete' with an id no longer valid).

---

I looked into this again, and I think the proposed solution of locking the MEX-files works nicely.

**Here is the code I played around with: [gist](https://gist.github.com/amroamroamro/5841304ff008049820153f63ea479a11).**

The minimum fix is that each time a new object is created and stored in the `std::map` we would call [`mexLock`](https://www.mathworks.com/help/matlab/apiref/mexlock.html). Equally every time an object is removed from the map and destroyed, we call a matching [`mexUnlock`](https://www.mathworks.com/help/matlab/apiref/mexunlock.html).
This conforms with what the doc page says:
> `mexLock` increments a lock count. If you call `mexLock` n times, call `mexUnlock` n times to unlock your MEX file.

As a result `clear mex` wont unload the MEX-file from memory as long as there are existing C++ objects (if it did we end up with inconsistent MATLAB objects with invalid "id"). Of course we are still able to unload mex-files by first clearing variables, or even by calling `clear all`.

The good news is that now when calling `clear all` MATLAB will destroy stuff in the correct order, first MATLAB variables/objects and then unloads the mex-files.  I'm not sure when the behavior changed, but previous versions did this incorrectly! (first unload mex-files then deletes variables).

So we'll be covered in both `clear mex` and `clear all` cases, with everything being destroyed/unloaded in the correct order.

---

To summarize, here are the changes I propose making to every C++ file that wraps a class (ones inside `private` folders):

``` diff
 // Constructor is called. Create a new object from argument
 if (method == "new") {
     obj_[++last_id] = XXX::create();
     plhs[0] = MxArray(last_id);
+    mexLock();
     return;
 }
```

``` diff
 // Big operation switch
 if (method == "delete") {
     obj_.erase(id);
+    mexUnlock();
 }
```

I would also add the following check for extra security
(note that the retrieved object gets default-constructed by `map::operator[]` if it didn't exist):

``` diff
 Ptr<XXX> obj = obj_[id];
+if (obj.empty())
+    mexErrMsgIdAndTxt("mexopencv:error", "Object not found id=%d", id);
```

Registering a callback with [`mexAtExit`](https://www.mathworks.com/help/matlab/apiref/mexatexit.html) is not needed, lock/unlock is sufficient.

@kyamagu Could you review this before I commit any changes?
Probably would be good to try it on other platforms/versions. The gist code above can be used for quick testing.

**Comment by kyamagu** [comment]
@amroamroamro Right, `mexLock()` and `mexUnlock()` is the solution to this issue. We don't need to use `mexAtExit()` at all. I have had this mechanism in the spin-off project ([mexplus](https://github.com/kyamagu/mexplus)), but not implemented in mexopencv. Every `new` and `delete` method should have locking.

It would be a lot of updates, though. We might be able to write some helper utility to reduce the amount of edits (e.g., macro for error checking).

**Comment by amroamroamro** [comment]
I see, `mexLock`/`mexUnlock` is already used in mexplus: https://github.com/kyamagu/mexplus/blob/master/include/mexplus/dispatch.h#L204

Since I've already made the changes locally (it wasn't that bad using a quick search/replace 😄),
I'll go ahead and push them like that for now, but we can certainly refactor it later using macros to reduce code duplication..

Thanks Kota.

**Comment by kyamagu** [comment]
@amroamroamro Alright, you can go ahead if search/replace works :)
