### ISSUE TITLE
The path for the MALTABDIR is not always /usr/bin

### ISSUE THREAD

**Issue by tatsambon** [kyamagu/mexopencv#302]
When compiling mexopencv for octave on an Ubuntu 14.04 virtual machine
I ran into the issue where the path the MATLABDIR is not /usr/bin

In terminal, Running the command
locate mkoctfile

allowed me to figure out that the path is /usr/local/bin

May be the result of evaluation of the command 
which mkoctfile
or 
which `mkoctfile`

could be parse and used to automatically set the path of the command mkoctfile

**Comment by tatsambon** [comment]
Let us discuss the best solution for that and I can make the fix

**Comment by amroamroamro** [comment]
You can override the default value directly in the call:

    make MATLABDIR=/usr/local WITH_OCTAVE=true ...

**Comment by tatsambon** [comment]
Problem solved!
