### ISSUE TITLE
Undef reference to mxArray:toString()

### ISSUE THREAD

**Issue by jdeeee** [kyamagu/mexopencv#303]
Hi!

I am trying to build mexopencv. For this, I have downloaded OpenCV 3.1.0 from opencv.org and followed http://docs.opencv.org/2.4/doc/tutorials/introduction/linux_install/linux_install.html#linux-installation to build it. It looked to be successful:

``` sh
$ pkg-config --cflags --libs opencv
-I/usr/local/include/opencv
-I/usr/local/include
-L/usr/local/lib
-lopencv_cudabgsegm
-lopencv_cudaobjdetect
-lopencv_cudastereo
-lopencv_shape
-lopencv_stitching
-lopencv_cudafeatures2d
-lopencv_superres
-lopencv_cudacodec
-lopencv_videostab
-lopencv_cudaoptflow
-lopencv_cudalegacy
-lopencv_calib3d
-lopencv_features2d
-lopencv_objdetect
-lopencv_highgui
-lopencv_videoio
-lopencv_photo
-lopencv_imgcodecs
-lopencv_cudawarping
-lopencv_cudaimgproc
-lopencv_cudafilters
-lopencv_video
-lopencv_ml
-lopencv_imgproc
-lopencv_flann
-lopencv_cudaarithm
-lopencv_viz
-lopencv_core
-lopencv_cudev
```

I then tried to build mexopencv with 

``` sh
$ make MATLABDIR=/usr/local/MATLAB/R2016b/
```

which consistently tells me that my gcc version is 5.4.0 which is not supported. I therefore installed gcc and gpp 4.9 and tried

``` sh
$ make MATLABDIR=/usr/local/MATLAB/R2016b/ MEX="/usr/local/MATLAB/R2016b/bin/mex -v GCC=/usr/bin/gcc-4.9"
```

This produces the following:

``` sh
$ make MATLABDIR=/usr/local/MATLAB/R2016b/ MEX="/usr/local/MATLAB/R2016b/bin/mex -v GCC=/usr/bin/gcc-4.9"
/usr/local/MATLAB/R2016b/bin/mex -v GCC=/usr/bin/gcc-4.9 -largeArrayDims -cxx -Iinclude -I/usr/local/include/opencv -I/usr/local/include  -output +cv/initCameraMatrix2D src/+cv/initCameraMatrix2D.cpp -Llib -lMxArray -L/usr/local/lib -lopencv_cudabgsegm -lopencv_cudaobjdetect -lopencv_cudastereo -lopencv_shape -lopencv_stitching -lopencv_cudafeatures2d -lopencv_superres -lopencv_cudacodec -lopencv_videostab -lopencv_cudaoptflow -lopencv_cudalegacy -lopencv_calib3d -lopencv_features2d -lopencv_objdetect -lopencv_highgui -lopencv_videoio -lopencv_photo -lopencv_imgcodecs -lopencv_cudawarping -lopencv_cudaimgproc -lopencv_cudafilters -lopencv_video -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_cudaarithm -lopencv_viz -lopencv_core -lopencv_cudev   
Verbose mode is on.
... Looking for compiler 'g++' ...
... Executing command 'which g++' ...Yes ('/usr/bin/g++').
... Executing command 'g++ -print-file-name=libstdc++.so' ...Yes ('/usr/lib/gcc/x86_64-linux-gnu/5/libstdc++.so').
Found installed compiler 'g++'.
Options file details
-------------------------------------------------------------------
	Compiler location: /usr/bin/gcc-4.9
	Options file: /home/meee/.matlab/R2016b/mex_C++_glnxa64.xml
	CMDLINE2 : /usr/bin/gcc-4.9 -pthread -Wl,--no-undefined  -shared -O -Wl,--version-script,"/usr/local/MATLAB/R2016b/extern/lib/glnxa64/c_exportsmexfileversion.map" /tmp/mex_389786248278256_15940/initCameraMatrix2D.o /tmp/mex_389786248278256_15940/cpp_mexapi_version.o   -lMxArray  -lopencv_cudabgsegm  -lopencv_cudaobjdetect  -lopencv_cudastereo  -lopencv_shape  -lopencv_stitching  -lopencv_cudafeatures2d  -lopencv_superres  -lopencv_cudacodec  -lopencv_videostab  -lopencv_cudaoptflow  -lopencv_cudalegacy  -lopencv_calib3d  -lopencv_features2d  -lopencv_objdetect  -lopencv_highgui  -lopencv_videoio  -lopencv_photo  -lopencv_imgcodecs  -lopencv_cudawarping  -lopencv_cudaimgproc  -lopencv_cudafilters  -lopencv_video  -lopencv_ml  -lopencv_imgproc  -lopencv_flann  -lopencv_cudaarithm  -lopencv_viz  -lopencv_core  -lopencv_cudev   -Llib  -L/usr/local/lib   -Wl,-rpath-link,/usr/local/MATLAB/R2016b/bin/glnxa64 -L"/usr/local/MATLAB/R2016b/bin/glnxa64" -lmx -lmex -lmat -lm -lstdc++ -o /home/meee/Desktop/mexopencv/mexopencv/+cv/initCameraMatrix2D.mexa64
	CXX : /usr/bin/gcc-4.9
	DEFINES : -D_GNU_SOURCE -DMATLAB_MEX_FILE 
	MATLABMEX : -DMATLAB_MEX_FILE 
	CXXFLAGS : -ansi -fexceptions -fPIC -fno-omit-frame-pointer -pthread -std=c++11
	INCLUDE : -Iinclude -I/usr/local/include/opencv -I/usr/local/include  -I"/usr/local/MATLAB/R2016b/extern/include" -I"/usr/local/MATLAB/R2016b/simulink/include"
	CXXOPTIMFLAGS : -O -DNDEBUG
	CXXDEBUGFLAGS : -g
	LDXX : /usr/bin/gcc-4.9
	LDFLAGS : -pthread -Wl,--no-undefined 
	LDTYPE : -shared
	LINKEXPORT : -Wl,--version-script,"/usr/local/MATLAB/R2016b/extern/lib/glnxa64/mexFunction.map"
	LINKEXPORTVER : -Wl,--version-script,"/usr/local/MATLAB/R2016b/extern/lib/glnxa64/c_exportsmexfileversion.map"
	LINKLIBS : -lMxArray  -lopencv_cudabgsegm  -lopencv_cudaobjdetect  -lopencv_cudastereo  -lopencv_shape  -lopencv_stitching  -lopencv_cudafeatures2d  -lopencv_superres  -lopencv_cudacodec  -lopencv_videostab  -lopencv_cudaoptflow  -lopencv_cudalegacy  -lopencv_calib3d  -lopencv_features2d  -lopencv_objdetect  -lopencv_highgui  -lopencv_videoio  -lopencv_photo  -lopencv_imgcodecs  -lopencv_cudawarping  -lopencv_cudaimgproc  -lopencv_cudafilters  -lopencv_video  -lopencv_ml  -lopencv_imgproc  -lopencv_flann  -lopencv_cudaarithm  -lopencv_viz  -lopencv_core  -lopencv_cudev   -Llib  -L/usr/local/lib   -Wl,-rpath-link,/usr/local/MATLAB/R2016b/bin/glnxa64 -L"/usr/local/MATLAB/R2016b/bin/glnxa64" -lmx -lmex -lmat -lm -lstdc++
	LDOPTIMFLAGS : -O
	LDDEBUGFLAGS : -g
	MWCPPLIB : "/usr/local/MATLAB/R2016b/sys/os/glnxa64/libstdc++.so.6"
	OBJEXT : .o
	LDEXT : .mexa64
	SETENV : CXX="/usr/bin/gcc-4.9"
CXXFLAGS="-ansi -fexceptions -fPIC -fno-omit-frame-pointer -pthread -std=c++11 -D_GNU_SOURCE -DMATLAB_MEX_FILE "
CXXOPTIMFLAGS="-O -DNDEBUG"
CXXDEBUGFLAGS="-g"
LDXX="/usr/bin/gcc-4.9"
LDFLAGS="-pthread -Wl,--no-undefined  -shared -lMxArray  -lopencv_cudabgsegm  -lopencv_cudaobjdetect  -lopencv_cudastereo  -lopencv_shape  -lopencv_stitching  -lopencv_cudafeatures2d  -lopencv_superres  -lopencv_cudacodec  -lopencv_videostab  -lopencv_cudaoptflow  -lopencv_cudalegacy  -lopencv_calib3d  -lopencv_features2d  -lopencv_objdetect  -lopencv_highgui  -lopencv_videoio  -lopencv_photo  -lopencv_imgcodecs  -lopencv_cudawarping  -lopencv_cudaimgproc  -lopencv_cudafilters  -lopencv_video  -lopencv_ml  -lopencv_imgproc  -lopencv_flann  -lopencv_cudaarithm  -lopencv_viz  -lopencv_core  -lopencv_cudev   -Llib  -L/usr/local/lib   -Wl,-rpath-link,/usr/local/MATLAB/R2016b/bin/glnxa64 -L"/usr/local/MATLAB/R2016b/bin/glnxa64" -lmx -lmex -lmat -lm -lstdc++ -Wl,--version-script,"/usr/local/MATLAB/R2016b/extern/lib/glnxa64/mexFunction.map""
LDDEBUGFLAGS="-g"
	GCC : /usr/bin/gcc-4.9
	CPPLIB_DIR : /usr/lib/gcc/x86_64-linux-gnu/5/libstdc++.so
	MATLABROOT : /usr/local/MATLAB/R2016b
	ARCH : glnxa64
	SRC : /home/meee/Desktop/mexopencv/mexopencv/src/+cv/initCameraMatrix2D.cpp;/usr/local/MATLAB/R2016b/extern/version/cpp_mexapi_version.cpp
	OBJ : /tmp/mex_389786248278256_15940/initCameraMatrix2D.o;/tmp/mex_389786248278256_15940/cpp_mexapi_version.o
	OBJS : /tmp/mex_389786248278256_15940/initCameraMatrix2D.o /tmp/mex_389786248278256_15940/cpp_mexapi_version.o 
	SRCROOT : /home/meee/Desktop/mexopencv/mexopencv/src/+cv/initCameraMatrix2D
	DEF : /tmp/mex_389786248278256_15940/initCameraMatrix2D.def
	EXP : /home/meee/Desktop/mexopencv/mexopencv/+cv/initCameraMatrix2D.exp
	LIB : /home/meee/Desktop/mexopencv/mexopencv/+cv/initCameraMatrix2D.lib
	EXE : /home/meee/Desktop/mexopencv/mexopencv/+cv/initCameraMatrix2D.mexa64
	ILK : /home/meee/Desktop/mexopencv/mexopencv/+cv/initCameraMatrix2D.ilk
	MANIFEST : /home/meee/Desktop/mexopencv/mexopencv/+cv/initCameraMatrix2D.mexa64.manifest
	TEMPNAME : /home/meee/Desktop/mexopencv/mexopencv/+cv/initCameraMatrix2D
	EXEDIR : /home/meee/Desktop/mexopencv/mexopencv/+cv/
	EXENAME : initCameraMatrix2D
	OPTIM : -O -DNDEBUG
	LINKOPTIM : -O
	CMDLINE1_0 : /usr/bin/gcc-4.9 -c -D_GNU_SOURCE -DMATLAB_MEX_FILE  -Iinclude -I/usr/local/include/opencv -I/usr/local/include  -I"/usr/local/MATLAB/R2016b/extern/include" -I"/usr/local/MATLAB/R2016b/simulink/include" -ansi -fexceptions -fPIC -fno-omit-frame-pointer -pthread -std=c++11 -O -DNDEBUG /home/meee/Desktop/mexopencv/mexopencv/src/+cv/initCameraMatrix2D.cpp -o /tmp/mex_389786248278256_15940/initCameraMatrix2D.o
	CMDLINE1_1 : /usr/bin/gcc-4.9 -c -D_GNU_SOURCE -DMATLAB_MEX_FILE  -Iinclude -I/usr/local/include/opencv -I/usr/local/include  -I"/usr/local/MATLAB/R2016b/extern/include" -I"/usr/local/MATLAB/R2016b/simulink/include" -ansi -fexceptions -fPIC -fno-omit-frame-pointer -pthread -std=c++11 -O -DNDEBUG /usr/local/MATLAB/R2016b/extern/version/cpp_mexapi_version.cpp -o /tmp/mex_389786248278256_15940/cpp_mexapi_version.o
-------------------------------------------------------------------
Building with 'g++'.
/usr/bin/gcc-4.9 -c -D_GNU_SOURCE -DMATLAB_MEX_FILE  -Iinclude -I/usr/local/include/opencv -I/usr/local/include  -I"/usr/local/MATLAB/R2016b/extern/include" -I"/usr/local/MATLAB/R2016b/simulink/include" -ansi -fexceptions -fPIC -fno-omit-frame-pointer -pthread -std=c++11 -O -DNDEBUG /home/meee/Desktop/mexopencv/mexopencv/src/+cv/initCameraMatrix2D.cpp -o /tmp/mex_389786248278256_15940/initCameraMatrix2D.o
/usr/bin/gcc-4.9 -c -D_GNU_SOURCE -DMATLAB_MEX_FILE  -Iinclude -I/usr/local/include/opencv -I/usr/local/include  -I"/usr/local/MATLAB/R2016b/extern/include" -I"/usr/local/MATLAB/R2016b/simulink/include" -ansi -fexceptions -fPIC -fno-omit-frame-pointer -pthread -std=c++11 -O -DNDEBUG /usr/local/MATLAB/R2016b/extern/version/cpp_mexapi_version.cpp -o /tmp/mex_389786248278256_15940/cpp_mexapi_version.o
/usr/bin/gcc-4.9 -pthread -Wl,--no-undefined  -shared -O -Wl,--version-script,"/usr/local/MATLAB/R2016b/extern/lib/glnxa64/c_exportsmexfileversion.map" /tmp/mex_389786248278256_15940/initCameraMatrix2D.o /tmp/mex_389786248278256_15940/cpp_mexapi_version.o   -lMxArray  -lopencv_cudabgsegm  -lopencv_cudaobjdetect  -lopencv_cudastereo  -lopencv_shape  -lopencv_stitching  -lopencv_cudafeatures2d  -lopencv_superres  -lopencv_cudacodec  -lopencv_videostab  -lopencv_cudaoptflow  -lopencv_cudalegacy  -lopencv_calib3d  -lopencv_features2d  -lopencv_objdetect  -lopencv_highgui  -lopencv_videoio  -lopencv_photo  -lopencv_imgcodecs  -lopencv_cudawarping  -lopencv_cudaimgproc  -lopencv_cudafilters  -lopencv_video  -lopencv_ml  -lopencv_imgproc  -lopencv_flann  -lopencv_cudaarithm  -lopencv_viz  -lopencv_core  -lopencv_cudev   -Llib  -L/usr/local/lib   -Wl,-rpath-link,/usr/local/MATLAB/R2016b/bin/glnxa64 -L"/usr/local/MATLAB/R2016b/bin/glnxa64" -lmx -lmex -lmat -lm -lstdc++ -o /home/meee/Desktop/mexopencv/mexopencv/+cv/initCameraMatrix2D.mexa64
/tmp/mex_389786248278256_15940/initCameraMatrix2D.o: In function 'mexFunction':
initCameraMatrix2D.cpp:(.text+0x2bf4): undefined reference to 'MxArray::toString() const'
collect2: error: ld returned 1 exit status

Makefile:171: recipe for target '+cv/initCameraMatrix2D.mexa64' failed
make: *** [+cv/initCameraMatrix2D.mexa64] Error 255
```

What could be the cause of this?

**Comment by kyamagu** [comment]
@jdeeee You should use the same compiler you used to build OpenCV. Sometimes the compiler message in Matlab is only a warning and can be ignored. Other than that, don't forget to clean old artifacts before build (`make clean`).

**Comment by jdeeee** [comment]
I just ran "make clean MATLABDIR=/usr/local/MATLAB/R2016b/" and "make MATLABDIR=/usr/local/MATLAB/R2016b/" and it completes successfully, while always showing the compiler warning however. I then ran "make test MATLABDIR=/usr/local/MATLAB/R2016b/" and it seems to fail pretty hard. Here is a snippet of the output:

> -- test_3 --
Error using cv.warpPerspective
Invalid MEX-file '/home/accm/Desktop/mexopencv/mexopencv/+cv/warpPerspective.mexa64': libopencv_imgproc.so.3.1: cannot open shared object file: No such file or directory.

Error in TestWarpPerspective.test_3 (line 32)
            dst = cv.warpPerspective(im, H, 'Dst',im, 'BorderType','Transparent');

Error in UnitTest.all (line 207)
                        feval(fname);

Error in UnitTest (line 124)
                numtests = UnitTest.all(klass);
FAIL
-- test_error_argnum --
Error using TestWarpPerspective.test_error_argnum (line 41)
Assertion failed.

Error in UnitTest.all (line 207)
                        feval(fname);

Error in UnitTest (line 124)
                numtests = UnitTest.all(klass);
FAIL
== TestWatershed ==
-- test_1 --
Error using cv.watershed
Invalid MEX-file '/home/accm/Desktop/mexopencv/mexopencv/+cv/watershed.mexa64': libopencv_imgproc.so.3.1: cannot open shared object file: No such file or directory.

Error in TestWatershed.test_1 (line 13)
            markers = cv.watershed(img, markers);

Error in UnitTest.all (line 207)
                        feval(fname);

Error in UnitTest (line 124)
                numtests = UnitTest.all(klass);
FAIL
-- test_error_argnum --
Error using TestWatershed.test_error_argnum (line 22)
Assertion failed.

Error in UnitTest.all (line 207)
                        feval(fname);

Error in UnitTest (line 124)
                numtests = UnitTest.all(klass);
FAIL

Totals:
  29 Passed, 1049 Failed
  Elapsed time is 33.046282 seconds.

What is the most likely way to success now? ;)

**Comment by amroamroamro** [comment]
@jdeeee 
I think you are using the wrong version.. You say you built OpenCV 3.1.0, but the libs listed in the output of `pkg-config` are those of OpenCV 2.x not 3.x! Also make sure you are on the right branch of mexopencv as well..

I suggest you start again and use our guide to build opencv/opencv_contrib and mexopencv:
https://github.com/kyamagu/mexopencv/wiki/Installation-%28Linux%2C-MATLAB%2C-OpenCV-3%29

To avoid any confusion, I would also remove any previous installations of opencv you had (either manually built or installed with `apt-get`).

Finally I suggest you use `update-alternatives` if you are switching between multiple versions of gcc/g++. As kyamagu mentioned, check that you are using the same compiler for building both (opencv and mexopencv).

If you later get problems with conflicting libraries at runtime, refer to https://github.com/kyamagu/mexopencv/wiki/Troubleshooting-%28UNIX%29 for possible solutions using preloading.

**Comment by jdeeee** [comment]
Hi @amroamroamro:
Thanks for your help! Actually right now I ended up to refer to the last link you provided also for "make test" and made it pass about 80% of the test by preloading /`usr/lib/x86_64-linux-gnu/libstdc++.so.6` I did as suggested in https://github.com/kyamagu/mexopencv/wiki/Troubleshooting-%28UNIX%29#macos to identify more conflicting libraries and finally tried to run

> LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6 /lib/x86_64-linux-gnu/libgcc_s.so.1 /lib/x86_64-linux-gnu/libpng12.so.0 /usr/lib/x86_64-linux-gnu/libtiff.so.5 make test MATLABDIR=/usr/local/MATLAB/R2016b/
> bash: /lib/x86_64-linux-gnu/libgcc_s.so.1: Permission denied

As you see, I get a permission denied error. Is it the most suitable way here to use chmod 777? 

Thanks a lot!

**Comment by kyamagu** [comment]
@jdeeee You have to use `:` to concatenate objects:

    LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6:/lib/x86_64-linux-gnu/libgcc_s.so.1:/lib/x86_64-linux-gnu/libpng12.so.0:/usr/lib/x86_64-linux-gnu/libtiff.so.5 make test MATLABDIR=/usr/local/MATLAB/R2016b/

**Comment by jdeeee** [comment]
Thanks @kyamagu ! It passes 854 tests now and fails 224. All failures I have seen so far are of the sort `Undefined variable "cv" or class "cv.VideoCapture".` Does that clearly hint to any mistake I make?

**Comment by amroamroamro** [comment]
@jdeeee 
Can you check if the MEX-files inside the `private/` folder are actually built.
Run the following in MATLAB and post the output here:

``` matlab
>> what('/path/to/mexopencv/+cv/private')
```

**Comment by jdeeee** [comment]
This is the requested output :)

> what('/home/meee/Desktop/mexopencv/mexopencv/+cv/private/')
> 
> MEX-files in folder /home/meee/Desktop/mexopencv/mexopencv/+cv/private
> 
> AKAZE_                          DownhillSolver_                 LineSegmentDetector_            StereoBM_                       
> ANN_MLP_                        DualTVL1OpticalFlow_            LogisticRegression_             StereoSGBM_                     
> AgastFeatureDetector_           EM_                             MSER_                           Stitcher_                       
> AlignMTB_                       ExposureCompensator_            MergeDebevec_                   Subdiv2D_                       
> BOWImgDescriptorExtractor_      FastFeatureDetector_            MergeMertens_                   SuperResolution_                
> BOWKMeansTrainer_               FeatureDetector_                MergeRobertson_                 Timelapser_                     
> BRISK_                          FeaturesFinder_                 NormalBayesClassifier_          TonemapDrago_                   
> BackgroundSubtractorKNN_        FeaturesMatcher_                ORB_                            TonemapDurand_                  
> BackgroundSubtractorMOG2_       GFTTDetector_                   OnePassStabilizer_              TonemapMantiuk_                 
> Blender_                        GeneralizedHoughBallard_        PCA_                            TonemapReinhard_                
> Boost_                          GeneralizedHoughGuil_           RTrees_                         Tonemap_                        
> BundleAdjuster_                 HOGDescriptor_                  Rect_                           TwoPassStabilizer_              
> CalibrateDebevec_               HausdorffDistanceExtractor_     RotatedRect_                    Utils_                          
> CalibrateRobertson_             HomographyBasedEstimator_       RotationWarper_                 VideoCapture_                   
> CascadeClassifier_              KAZE_                           SVD_                            VideoWriter_                    
> ConjGradSolver_                 KNearest_                       SVM_                            
> DTrees_                         KalmanFilter_                   SeamFinder_                     
> DescriptorExtractor_            KeyPointsFilter_                ShapeContextDistanceExtractor_  
> DescriptorMatcher_              LDA_                            SimpleBlobDetector_

**Comment by amroamroamro** [comment]
@jdeeee 
That looks ok.
Did you set up the MATLAB path correctly (i.e `addpath`)?

Try the following in MATLAB to run the tests:

``` matlab
>> addpath('/path/to/mexopencv')
>> addpath('/path/to/mexopencv/test')
>> cv.getBuildInformation()
>> UnitTest
```

I'm assuming that you started MATLAB with the required `LD_LIBRARY_PATH` and `LD_PRELOAD` in the call.

If it's still failing, please indicate which test is failing exactly, along with the error message.
State the call you used to invoke MATLAB. If is a library-loading error, also include the output of running `ldd` on that MEX-file both inside MATLAB and on the shell.
