### ISSUE TITLE
No added"BUILD"group(displayed in red)

### ISSUE THREAD

**Issue by ffoooooooo** [kyamagu/mexopencv#304]
I follow the steps in Installation(Windows,Matlab,Opencv3)with opencv downloaded  directly from GitHub,VS2013 and CMake (no matter which version),when I configure OpenCV,the 9th step I can not find,and I don't why.If I skip this ,I will get the error"can not find ....lib" in the step build the solution in VS.Do you know WHY and how to solve this problem?

**Comment by amroamroamro** [comment]
Can you elaborate a bit more, and post the actual output/error messages.

Perhaps you didn't configure opencv_contrib path correctly (`OPENCV_EXTRA_MODULES_PATH`)? Also please confirm that you are indeed using v3.1.0 of opencv/opencv_contrib (this exact version).

**Comment by ffoooooooo** [comment]
Yes,you are right.I didn't configure OPENCV_EXTRA_MODULES_PATH (instead of this,I reset OPENCV_CONFIG_FILE_INCLUDE_DIR,I am so careless).Thank you very much ,I try it again now.

**Comment by amroamroamro** [comment]
I'm closing this as solved.
