### ISSUE TITLE
Error when compiling in matlab

### ISSUE THREAD

**Issue by SamRosenthal** [kyamagu/mexopencv#308]
Hello,

I have Matlab 2016a.  I followed the OpenCV installation instructions in the wiki exactly as far as I know.  Yet, when I ran: `mexopencv.make('opencv_path','C:\dev\build\install', 'opencv_contrib',true)`, I got the following error tree:

```
Error using strcmp
Not enough input arguments.

Error in mexopencv.make>compiler_str (line 363)
        if strcmp(cc.Manufacturer, 'Microsoft')

Error in mexopencv.make>pkg_config (line 314)
    L_path = fullfile(opts.opencv_path, arch_str(), compiler_str(), 'lib');

Error in mexopencv.make>mex_options (line 256)
    [cv_cflags, cv_libs] = pkg_config(opts);

Error in mexopencv.make (line 81)
    mex_flags = mex_options(opts);
```

I've tried to debug this and it looks like the `cc` object - generated by calling `mex.getCompilerConfigurations('C++','Selected')` doesn't set `cc.Manufacturer` to return a string for `strcmp` to act on.  But I don't know if this is the true problem or how to fix things if it is. 

Any help would be appreciated

**Comment by amroamroamro** [comment]
What do you get when you run `mex -setup` and `mex -setup C++`? You need to configure a supported compiler.

Also please include the output of running
``` matlab
cc = mex.getCompilerConfigurations('C++','Selected')
```

**Comment by amroamroamro** [comment]
just to be on the safe side, make sure you don't have a custom `strcmp` function that shadows the native one.. Check by running `which strcmp`, it should say "built-in".

**Comment by SamRosenthal** [comment]
How Amro,

Thank you very much for the help!  The weirdest thing happened.  My computer went through an update and all of a sudden the make code worked fine.  I have no idea why.  I reset everything after the initial install.  Anyway, all is well without any extra input from me, but I do really appreciate the time you took to answer.
