### ISSUE TITLE
SolvePnPRansac works in 2.4.11 but not in 3.1.0

### ISSUE THREAD

**Issue by rasmusramsboel** [kyamagu/mexopencv#309]
I have some code, where a camera pose is estimated using `SolvePnPRansac` based on 2d-3d correspondence. I back-project a point-cloud into my image so visual confirmation is easy.

I know the data is noisy but in 2.4.11, I can set the number of iterations high and the number of inliers high and get fairly consistent results. Even using the standard settings the results are ok.

Using the exact same data but 3.1.0, I cannot produce a single result, which is right regardless of settings.

Has something fundamentally changed, which means the algorithm can no longer handle noisy data?

I made the switch in order to use other functions not available in 2.4.x.

**Comment by kyamagu** [comment]
@rasmusramsboel I believe this is not the issue of `mexopencv` but the core OpenCV. Ask a question at [OpenCV issue tracker](https://github.com/opencv/opencv/issues) or [StackOverflow](http://stackoverflow.com/) with more details on your data.

**Comment by amroamroamro** [comment]
@rasmusramsboel 
From a quick look at `git log` on our side, I can tell you that between 2.4 and 3.1 versions, the `MinInliersCount` option was replaced with `Confidence` (ad09510f), also `Flags` was renamed `Method` (3fe7543e).
So the question is did you update your calls to the `cv.solvePnPRansac` function accordingly?

It would help if you can provide a small reproducible example..

**Comment by rasmusramsboel** [comment]
Thanks, I did change the settings, but have not found one setting, which produces the right results for any frame in the video stream. The standard settings with no options set works in 2.4 in a lot of frames, while 3.1 does not produce any correct poses neither with standard settings or any other.

I know, I probably have lot of noise, but the fact that I do not get any good results with 3.1 puzzles me.

**Comment by amroamroamro** [comment]
@rasmusramsboel 
Tracing opencv git logs (which is a bit of a mess!), I think [this PR](https://github.com/opencv/opencv/pull/3042) is key; among other things, it replaced RANSAC with a new implementation, starting at commit [6eb1426e](https://github.com/opencv/opencv/commit/6eb1426ea27210213a095741e7bdfcaf10fef560), where you can see the old implementation commented and a new one added and modified over multiple commits.

I am not familiar with the code so I can't really help, but I can tell you that [Ransac](https://en.wikipedia.org/wiki/Random_sample_consensus) methods in general have an inherent randomness (non-deterministic), so you're not guaranteed same results in multiple runs even in the same version (unless of course you somehow fix random seed and such).

Ultimately this is something to report to opencv devs, and not an issue on the mexopencv side...

**Comment by rasmusramsboel** [comment]
I know of the random character of Ransac, and that is not the problem. I have created a test script, which shows that SolvePnPRansac is consistently wrong in 3.1, while SolvePnP works.


`% to swith between versions matlab has to be restarted
addpath(genpath('C:\opencv310\mexopencv\')); % the following call needs the environment variable path to include "C:\opencv310\build\x64\vc11\bin"
% addpath(genpath('C:\opencv\mexopencv-2.4.11\')); % the following call needs the environment variable path to include "C:\opencv310\build\x64\vc11\bin"

%PnPSolve
IterationsCount=5000; %5000 seems to be enough
ReprojectionError=1; %1 seems good, 2 or 0.5 does not produce good results
MinInliersCount=200;

% camera matrix
Kc= 1.0e+03*[3.349 0.003 2.291
    0     3.346 1.723
    0      0    0.001];

% transformation
A =[ -0.7614    0.1708    0.6253    2.4441
    0.1156    0.9850   -0.1283   -0.1069
    -0.6378   -0.0254   -0.7697    0.5638
    0         0         0      1.0000];

% image coordinates
uv=[10  -10  -10   10 10  -10  -10   10 20  -20   20  -20;
    20  -20   20  -20 10  -10  -10   10 20  -20   20  -20];
uv(3,:)=1;

xyz_world_combined=[];
uv_combined=[];

for index_scale=1:3

xyz_camera=Kc\uv*index_scale;
xyz_camera(4,:)=1;

%into world coordinate system
xyz_world=A\xyz_camera;

xyz_world_combined=[xyz_world_combined xyz_world];
uv_combined=[uv_combined uv];

end

% put points in camera coordinate system
xyz_camera=A*xyz_world_combined;

%find pixel coordinates (just a test)
uv=Kc*eye(3,4)*xyz_camera;
uv=uv./uv([3 3 3],:)

disp('SolvePnP Ransac')

% opencv 2.4
%[rvec, Tpnp, inliersPnP]=cv.solvePnPRansac(xyz_world_combined(1:3,:)', uv_combined(1:2,:)',Kc,[],'IterationsCount',IterationsCount,'ReprojectionError',ReprojectionError,'MinInliersCount',MinInliersCount);

% opencv 3.1
[rvec, Tpnp, inliersPnP]=cv.solvePnPRansac(xyz_world_combined(1:3,:)', uv_combined(1:2,:)',Kc,'IterationsCount',IterationsCount,'ReprojectionError',1,'Confidence',0.99,'Method','DLS');

Rpnp=rotationVectorToMatrix(rvec)';
A_estimated = [Rpnp Tpnp; 0 0 0 1]
xyz_camera=A_estimated*xyz_world_combined;

%find estimated pixel coordinates
uv=Kc*eye(3,4)*xyz_camera;
uv=uv./uv([3 3 3],:)

disp('SolvePnP')

[rvec, Tpnp]=cv.solvePnP(xyz_world_combined(1:3,:)', uv_combined(1:2,:)',Kc);

Rpnp=rotationVectorToMatrix(rvec)';
A_estimated = [Rpnp Tpnp; 0 0 0 1]
xyz_camera=A_estimated*xyz_world_combined;

%find estimated pixel coordinates
uv=Kc*eye(3,4)*xyz_camera;
uv=uv./uv([3 3 3],:)`

[solvePnP_testscript - Copy.txt](https://github.com/kyamagu/mexopencv/files/727151/solvePnP_testscript.-.Copy.txt)

**Comment by rasmusramsboel** [comment]
Ok, so I have been trying to locate the problem but one thing I just found is the returned rvec and tvec by 3.10 SolvePnPRansac seems to be mixed up somehow. This is a result from one run:

rvec =
    0.1991
    2.4549
    2.4441
tvec =
    2.4549
    2.4441
   -0.1116

It seems unlikely that rvec and tvec have identical (not close but identical) numbers (mixed order)? This happens regardless of input.

**Comment by rasmusramsboel** [comment]
I just made a test in plain OpenCV 3.1, where I could not reproduce this error, so I guess something goes wrong in the mexopencv interface.

**Comment by amroamroamro** [comment]
@rasmusramsboel  Thanks for the MATLAB example, I will look into it.
Can you also share your C++ test case?

**Comment by rasmusramsboel** [comment]
Here you go, what is included is a set of data including: transformation, cameramatrix, 2D points (uv) and their projection into 3D (xyz_world) using the Matlab code.

The included data are hardcoded into C++ and I stopped, when I realized that the transformation was identical (within reason :-) ), which it is not using mexopencv 3.1.

Thanks for the help :-)


[SolvePnP Ransac test.zip](https://github.com/kyamagu/mexopencv/files/734755/SolvePnP.Ransac.test.zip)

**Comment by amroamroamro** [comment]
I didn't get that last part, are you saying it's NOT a problem with `SolvePnPRansac` after all?

**Comment by rasmusramsboel** [comment]
It works in the C++ code and produce an "identical" transformation, but not in mexopencv 3.1, which is way off.

**Comment by amroamroamro** [comment]
ok just checking, I'll have a look.

**Comment by amroamroamro** [comment]
@rasmusramsboel 
Ok I confirm, something is off here..
For some reason the conversion from of the output vecs from `cv::Mat` back to `mxArray` is giving wrong values!

```cpp
    plhs[0] = MxArray(rvec);
    if (nlhs>1)
        plhs[1] = MxArray(tvec);
```

I still have to investigate a bit more to figure what's actually going on here, but for now I have a quick fix for you, just replace those lines with:

```diff
-    plhs[0] = MxArray(rvec);
+    plhs[0] = MxArray(rvec.clone());
     if (nlhs>1)
-        plhs[1] = MxArray(tvec);
+        plhs[1] = MxArray(tvec.clone());
```

This seem to fix the problem.

I think something funny is going on with the `Mat` and the way the `OutputArray` is being filled by [`cv::solvePnPRansac`](https://github.com/opencv/opencv/blob/3.1.0/modules/calib3d/src/solvepnp.cpp#L211) on the OpenCV side (those `_rvec.assign` and `_tvec.assign` calls maybe)..

**Comment by amroamroamro** [comment]
For reference, here is my test code:

```matlab
%% points
% intrinsic params (camera matrix)
Kc = [4    0  500
      0    4  500
      0    0    1];

% extrinsic params (rotation + translation)
A = [ -0.7614    0.1708    0.6253    2.4441
       0.1156    0.9850   -0.1283   -0.1069
      -0.6378   -0.0254   -0.7697    0.5638
       0         0         0         1];

% image coordinates
uv = [2 4 6 8 8 8 8 8;
      8 8 8 8 2 4 6 8] * 100;
uv(3,:) = 1;  % homogeneous

% world coordinates
xyz_world_combined = [];
uv_combined = [];
for scale=1:3
    % pinhole camera model: s * [UV;1] = Kc * A * [XYZ;1]
    xyz_camera = Kc \ (uv * scale);
    xyz_camera(4,:) = 1;
    xyz_world = A \ xyz_camera;

    xyz_world_combined = [xyz_world_combined xyz_world];
    uv_combined = [uv_combined uv];
end

% points in camera coordinate system
xyz_camera = A * xyz_world_combined;
% pixel coordinates
uv = Kc * xyz_camera(1:3,:);
uv = bsxfun(@rdivide, uv, uv(3,:));
display(A)
display(uv_combined)
display(uv)

% Nx3 and Nx2
opoints = single(xyz_world_combined(1:3,:)');
ipoints = single(uv_combined(1:2,:)');
if false
    % 1xNx3 and 1xNx2
    opoints = permute(opoints, [3 1 2])
    ipoints = permute(ipoints, [3 1 2])
elseif false
    % cell array of 1x3 and 1x2
    opoints = num2cell(opoints, 2);
    ipoints = num2cell(ipoints, 2);
end

%% solvePnP
[rvec, tvec, success] = cv.solvePnP(opoints, ipoints, Kc)

%uv = cv.projectPoints(opoints, rvec, tvec, Kc);
%-{
A_estimated = [cv.Rodrigues(rvec) tvec ; 0 0 0 1];
xyz_camera = A_estimated * xyz_world_combined;
uv = Kc * xyz_camera(1:3,:);
uv = bsxfun(@rdivide, uv, uv(3,:));
display(A_estimated)
%}
display(uv)

%% solvePnPRansac
[rvec, tvec, success, inliers] = cv.solvePnPRansac(opoints, ipoints, Kc)
%    'Confidence',0.99, ...
%    'IterationsCount',100, ...
%    'ReprojectionError',8.0, ...
%    'Method','Iterative', ...

%uv = cv.projectPoints(opoints, rvec, tvec, Kc);
%-{
A_estimated = [cv.Rodrigues(rvec) tvec ; 0 0 0 1];
xyz_camera = A_estimated * xyz_world_combined;
uv = Kc * xyz_camera(1:3,:);
uv = bsxfun(@rdivide, uv, uv(3,:));
display(A_estimated)
%}
display(uv)
```

**Comment by amroamroamro** [comment]
I'll push the above workaround. Thanks for the bug report and the followup :)

**Comment by rasmusramsboel** [comment]
Very cool, does this mean that you have included the fix, and I can just use an updated version of med opencv? 

Thanks again for your work it makes my life a lot easier.

**Comment by amroamroamro** [comment]
Before I push, can you confirm it fixes the problem on your side? The changes are easy to do yourself, just add the `.clone()` calls as shown above and compile.

If you can also test against your actual code with the noisy data (not the minimal example you posted)..

**Comment by rasmusramsboel** [comment]
I will get back then, right now I'm on a beach in Kenya 😊

**Comment by amroamroamro** [comment]
I'm closing as solved, you can reopen if you find otherwise.

**Comment by rasmusramsboel** [comment]
Great job locating the error, it works as it should.

Thank you so much :-)
