### ISSUE TITLE
Error setting up mexopencv

### ISSUE THREAD

**Issue by surendra1234sharma** [kyamagu/mexopencv#310]
I'm using Windows 7 (64bit) with Matlab R2015a and I'm trying to use OpenCV 3.2.0 functions in Matlab.

I first added `C:\opencv\build` to the Path in environment variables, restarted the system and did `mex -setup`, then I chose the compiler 'Microsoft Windows SDK 7.1 (C++)' (detected by Matlab after patching it), added mexopencv folder and subfolders to path and finally run `mexopencv.make`.

the following error appears:
```
Error using mexopencv.make>pkg_config (line 316)
OpenCV library path not found: C:\opencv\build\x64\vc10\lib
Error in mexopencv.make>mex_options (line 256)
[cv_cflags, cv_libs] = pkg_config(opts);
Error in mexopencv.make (line 81)
mex_flags = mex_options(opts);
```
I also tried with OpenCV 3.1.0 but the error remains same

My OpenCV folder contain following folders in the `C:\opencv\build\x64`
- vc12
- vc14

Please help me
thanks

**Comment by amroamroamro** [comment]
Two things to note:
- we haven't yet tested against 3.2.0, so please stick with 3.1.0 for the moment.
- the opencv installer doesn't contain precompiled binaries for your compiler version (WinSDK 7.1 is equivalent to VS2010), this means you either have to compile OpenCV yourself using the compiler you have, or upgrade to VS2013/VS2015 (you can download the [community edition](https://www.visualstudio.com/vs/community/) for free).

You can find an [installation guide](https://github.com/kyamagu/mexopencv/wiki/Installation-%28Windows%2C-MATLAB%2C-OpenCV-3%29) in the wiki. It shows how to compile opencv+opencv_contrib and mexopencv all from source.

**Comment by surendra1234sharma** [comment]
Thanks a lot, It worked
