### ISSUE TITLE
Question#2 about BOWImgDescriptorExtractor

### ISSUE THREAD

**Issue by ODabrowski** [kyamagu/mexopencv#312]
Hi.

I had a look to the tests for the BOWImgDescriptorExtractor class.
If I understand correctly, with the following code:
```

extractor = cv.BOWImgDescriptorExtractor('SIFT','BruteForce');
extractor.Vocabulary=dictionary;
histo1 = extractor.compute(im1, k1);
```

when I do "extractor.compute" it computes again sift descriptors&keypoints then maps them to codewords of the dictionnary. 
However, I have pre-computed sift descriptors & keypoints for my images and fed them to the 
`dictionary = trainer.cluster(descriptors)`

to create the dictionnary. I would like to avoid recomputing them again.
Is there a way to feed to the BOWImgDescriptorExtractor the **pre-computed descriptors** ?
(or is there something I misunderstood?)

thanks in advance for any explanation.

**Comment by ODabrowski** [comment]
More precisely I think that I could say, that I would like that instead of step 1) I would supply the pre-computed descriptor myself to save time:

 BOWImgDescriptorExtractor  Class to compute an image descriptor using the bag of visual words
 
  Such a computation consists of the following steps:
 
  1. Compute descriptors for a given image and its keypoints set.
  2. Find the nearest visual words from the vocabulary for each keypoint
     descriptor.
  3. Compute the bag-of-words image descriptor as is a normalized
     histogram of vocabulary words encountered in the image. The i-th bin
     of the histogram is a frequency of i-th word of the vocabulary in
     the given image.

**Comment by amroamroamro** [comment]
Yes you can. `BOWImgDescriptorExtractor` has a few overloads of the `compute` method (I believe this was [requested](http://code.opencv.org/issues/3005) at some point):

> http://docs.opencv.org/3.1.0/d2/d6b/classcv_1_1BOWImgDescriptorExtractor.html

One version of the `compute` methods takes a precomputed descriptors matrix. In mexopencv it is called `compute1`.

> https://kyamagu.github.io/mexopencv/matlab/BOWImgDescriptorExtractor.compute1.html
