### ISSUE TITLE
issue with cv.BOWKmeansTrainer

### ISSUE THREAD

**Issue by ODabrowski** [kyamagu/mexopencv#314]
Hello, 

I m having a problem with the k-means algorithm.
I recieve this error message:

```
Unexpected Standard exception from MEX file.
What() is:C:\dev\opencv\modules\core\src\kmeans.cpp:231: error: (-215) N >= K in function cv::kmeans

..

Error in cv.BOWKMeansTrainer/cluster (line 149)
                centers = BOWKMeansTrainer_(this.id, 'cluster', descs);

Error in BoW_training (line 36)
dictionary = trainer.cluster(rawDescriptors);%apply KMeans algorithm part 2

```

I have computed SIFT descriptors with `sift1=cv.SIFT('ConstrastThreshold',0.1,'NFeatures',250);` for around 500 photos.

I think I have an idea but i'm not sure... 
-the number of clusters should be smaller than the nb of descriptors (otherwise 1 cluster=1 descriptor => brute force matching?)

THe error message seems to mean that i am given too much clusters for the number of descriptors that i have ? 

Please can you confirm if my intuition is correct.

**Comment by ODabrowski** [comment]
(updated)

**Comment by amroamroamro** [comment]
Yes your intuition is right, you cannot cluster N instances into K clusters, where you have more clusters/groups than instances (K>N)..

In other words if you have this code:

``` matlab
trainer = cv.BOWKMeansTrainer(K);
dictionary = trainer.cluster(descs);
```

The following condition must be true: `K < size(descs,1)` (in fact much smaller).
The error means two things, you either don't have enough training images, and/or that keypoint detection in those images is failing or not returning enough keypoints.. Remeber that descs is usually the concatenation of multiple descriptor matrices from all training images.

**Comment by ODabrowski** [comment]
haha thanks for you answer and the link to this funny 'pigeonhole principle'.
