### ISSUE TITLE
mexopencv.make not compiling

### ISSUE THREAD

**Issue by AkuPutri** [kyamagu/mexopencv#315]
The following error comes when I run the `make` command. I have MATLAB 2014a, Opencv 3.0, Visual Studio12 and mexopencv-3.0.0 and Windows 7 32 bit

```
Error using mex
calibrateCamera.cpp
D:\Kuliah\Semester8\dev\mexopencv-master\src\+cv\calibrateCamera.cpp(64) : error C2039: 'CALIB_TILTED_MODEL' : is not a member of 'cv'
D:\Kuliah\Semester8\dev\mexopencv-master\src\+cv\calibrateCamera.cpp(64) : error C2065: 'CALIB_TILTED_MODEL' : undeclared identifier
D:\Kuliah\Semester8\dev\mexopencv-master\src\+cv\calibrateCamera.cpp(66) : error C2039: 'CALIB_FIX_TAUX_TAUY' : is not a member of 'cv'
D:\Kuliah\Semester8\dev\mexopencv-master\src\+cv\calibrateCamera.cpp(66) : error C2065: 'CALIB_FIX_TAUX_TAUY' : undeclared identifier
D:\Kuliah\Semester8\dev\mexopencv-master\src\+cv\calibrateCamera.cpp(68) : error C2039: 'CALIB_USE_LU' : is not a member of 'cv'
D:\Kuliah\Semester8\dev\mexopencv-master\src\+cv\calibrateCamera.cpp(68) : error C2065: 'CALIB_USE_LU' : undeclared identifier

Error in mexopencv.make (line 139)
            if ~opts.dryrun, eval(cmd); end
```

**Comment by AkuPutri** [comment]
if I use OpenCV 3.1.0

Error using mexopencv.make>pkg_config (line 316)
OpenCV library path not found: C:\opencv3.1.0\opencv\build\x86\vc11\lib

Error in mexopencv.make>mex_options (line 256)
    [cv_cflags, cv_libs] = pkg_config(opts);

Error in mexopencv.make (line 81)
    mex_flags = mex_options(opts);

**Comment by amroamroamro** [comment]
1. If you're working against OpenCV 3.0, you must checkout the corresponding branch of mexopencv: [v3.0](https://github.com/kyamagu/mexopencv/tree/v3.0)

2. The installer `opencv-3.1.0.exe` doesn't include 32-bit precompiled binaries anymore, you have to compile it yourself. In fact it only includes 64-bit binaries for recent VS editions (VS 2013 and VS 2015 only).

**Comment by AkuPutri** [comment]
set the source folder as C:/dev/opencv
set the destination folder as: C:/dev/build
![capture0](https://cloud.githubusercontent.com/assets/25500642/22576412/d20baf3a-e9ed-11e6-8db2-7a92dcab3767.PNG)

![capture](https://cloud.githubusercontent.com/assets/25500642/22576362/965730ea-e9ed-11e6-9b6f-21e19b8b0c89.PNG)

set the source folder as C:/dev/opencv/source
set the destination folder as: C:/dev/build
![capture2](https://cloud.githubusercontent.com/assets/25500642/22576457/1707a2e2-e9ee-11e6-882a-2fe470533d09.PNG)

Do I have to replace windows 7 32 bit to 64 bit ??

I am not very familiar with the English language.
So I do not understand the tutorial, can you make a step steps using an image or screenshot ?? please

**Comment by amroamroamro** [comment]
@AkuPutri 
According to the [error](https://cloud.githubusercontent.com/assets/25500642/22576457/1707a2e2-e9ee-11e6-882a-2fe470533d09.PNG), your compiler failed for some reason. Perhaps make sure the output directory exists first `c:\dev\build`?

As for the tutorial, just have it translated to your language: https://translate.google.com/
The guide is fairly detailed as is, including step by step instructions...

**Comment by AkuPutri** [comment]
In the tutorial "Installation (Windows, MATLAB, OpenCV 3)" it is said that

Note: You might get an error when building OpenCV using recent versions of CMake (3.5 or 3.6). In that case you should downgrade to CMake 3.4.

I have been looking for CMake 3.4 but there is only CMake 3.6.3 and CMake 3.7.2
CMake which version should I use ??
Do you have CMake 3.4 ??

**Comment by AkuPutri** [comment]
I now use

OS Windows 7 x64 bit
OpenCV 3.1
mexOpenCV 3.1
CMake 3.7.2
Matlab x64 bit
VS x86 bit

![capture](https://cloud.githubusercontent.com/assets/25500642/22618103/48e2a3c4-eb07-11e6-8109-0ff8c7fb4ca3.PNG)

What should I do??

**Comment by amroamroamro** [comment]
you say you have VS 2012, but the image shows that you selected the "Visual Studio 12 **2013** Win64" generator in CMake. That explains why no compiler could be found...

By the way, you can find all versions of cmake here: https://cmake.org/files/

**Comment by AkuPutri** [comment]
![capture1](https://cloud.githubusercontent.com/assets/25500642/22622524/177bbfb0-eb6f-11e6-979a-fcb02874fadb.PNG)

Still the same, still can not.
May I ask your line id ?? or other social media

**Comment by AkuPutri** [comment]
![untitled](https://cloud.githubusercontent.com/assets/25500642/22622942/7e3b767a-eb7c-11e6-9f4a-cc8e1c505c12.png)


Thank you very much @amroamroamro 

I am trying here to install the usual way is to use the command

mex -Setup c ++
mexopencv.make

and successfully :) 👍 

with the configuration

- OpenCV-3.0.0
- MexOpenCV-3.0
- Matlab R2014a
- Visual Studio 2012

**Comment by amroamroamro** [comment]
You're confusing the "version number" of [Visual Studio](https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#History) with the "year" part in the name:

| Product name | Version number |
| --- | --- |
| Visual Studio 2015 | 14 |
| Visual Studio 2013 | 12 |
| Visual Studio 2012 | 11 |
| Visual Studio 2010 | 10 |

So in CMake you had to select **"Visual Studio 11 2012 Win64"** as generator...

---

Setting the PATH environment variable is shown in the wiki:

![path](https://cloud.githubusercontent.com/assets/83908/22628095/99be7276-ebd6-11e6-906b-38a4363a7b6d.png)

Setting MATLAB path is shown in the instructions as well:
``` matlab
>> addpath('C:\path\to\mexopencv')
```
Read the docs: https://www.mathworks.com/help/matlab/matlab_env/add-remove-or-reorder-folders-on-the-search-path.html
