### ISSUE TITLE
mexopencv.make not compiling 

### ISSUE THREAD

**Issue by AkuPutri** [kyamagu/mexopencv#316]
Windows 7 32 bit
Matlab 2014a + Visual Studio 2012
maxopencv 3.1.0
opencv 3.2.0 + input x86

```
Error using mex
   Creating library D:\Kuliah\Semester8\dev\mexopencv-master\+cv\drawMarker.lib and object
   D:\Kuliah\Semester8\dev\mexopencv-master\+cv\drawMarker.exp
drawMarker.obj : error LNK2019: unresolved external symbol "void __cdecl cv::drawMarker(class cv::Mat &,class cv::Point_<int>,class
cv::Scalar_<double> const &,int,int,int,int)" (?drawMarker@cv@@YAXAAVMat@1@V?$Point_@H@1@ABV?$Scalar_@N@1@HHHH@Z) referenced in function
_mexFunction
D:\Kuliah\Semester8\dev\mexopencv-master\+cv\drawMarker.mexw32 : fatal error LNK1120: 1 unresolved externals

Error in mexopencv.make (line 139)
            if ~opts.dryrun, eval(cmd); end
 ```

**Comment by amroamroamro** [comment]
Not enough info to troubleshoot, please describe your configuration:

- Windows version, 32 or 64 bit?
- MATLAB version
- C++ compiler
- mexopencv version (which branch or tag)
- OpenCV version
- is opencv_contrib used?
- how was opencv built?
- where is opencv installed?
- the call you used for `mexopencv.make`
- is this a clean build, or did you previously run `mexopencv.make` with different configs?
- etc.

PS: Check the wiki for installation guides: https://github.com/kyamagu/mexopencv/wiki

**Comment by amroamroamro** [comment]
@AkuPutri 

> Windows 7 32 bit
> Matlab 2014a + Visual Studio 2012
> maxopencv 3.1.0
> opencv 3.2.0 + input x86

As indicated in the README file, mexopencv targets OpenCV 3.1.0. We still haven't updated to 3.2.0.
