### ISSUE TITLE
DoG (theoretical question)

### ISSUE THREAD

**Issue by ODabrowski** [kyamagu/mexopencv#317]
Hi,
I would have a theoretical question. I realize that it might not be the correct forum to post this question. So I apologize for this. However, as I know you are experts in this domain, perhaps you can very easily answer my question, which is the following:

Problem formulation:
Let x be my original image, and let y be a 2*scaled version of x. 

in the SIFT algorithm:
I don't understand how the SIFT detector can detect a same given keypoint from image x in image y.
I don't understand how the 'scale space' DoG pyramid is used exacley to achieve this 'scale invariance'.

Please note that I have watched quite a few videos , e.g. https://www.youtube.com/watch?v=U0wqePj4Mx0&t=1s
and read a few tutorials about it. E.g. http://docs.opencv.org/trunk/da/df5/tutorial_py_sift_intro.html
and a few others....
I understand how the DoG pyramid is constructed, by successive blurring of the image. I also understand that keypoints are the maxima or minima from comparing to adjacent images in the DoG pyramid. (I understand that the difference of 2 blurred image with different sigmas gives an edge-like image)

However, for me, in every tutorial, they sort of 'skip' the fundamental part that would clearly explain why it makes it **scale invariant** ....

best regards,
OD

**Comment by amroamroamro** [comment]
I'm afraid this is not the place to ask general questions, you should try [OpenCV Q&A](http://answers.opencv.org/) or [DSP.SE](https://dsp.stackexchange.com/questions/tagged/image-processing).
