### ISSUE TITLE
The mexopencv doesn't include cv.imshow()? is it true?

### ISSUE THREAD

**Issue by Sundrops** [kyamagu/mexopencv#319]
The function of imshow in matlab runs very slowly. And I can't find the function of cv.imshow in the mexopencv. Why not implement  this function? Can you give me some advice about replacing the imshow in matlab?

**Comment by amroamroamro** [comment]
That's right, none of the [HighGUI module](http://docs.opencv.org/3.1.0/d7/dfc/group__highgui.html) functions is exposed.

**Comment by amroamroamro** [comment]
You say `imshow` runs very slow, are you calling it inside a loop?
If so the better way would be to call it once outside the loop saving the graphic handle returned, then update its `CData` inside the loop.

**Comment by Sundrops** [comment]
Oh, Thanks a lot! I'll have a try.
