### ISSUE TITLE
osX Sierra and mexopencv with contrib: is it possible?

### ISSUE THREAD

**Issue by lasuomela** [kyamagu/mexopencv#320]
I'm running Sierra 10.12.2 . Is there any way to use opencv in matlab, with the functions in the contributions part?

Because of the issues with QTKit, Opencv3.1 cannot be installed on Sierra. This is fixed in 3.2, so that's what i have to use. Current mexopencv seems to work fine for the core (main package) functions of opencv, but if i try to run mexopencv for installation --with-contrib, it results in errors of the following type:
           no viable conversion from 'cv::aruco::Dictionary' to 'const Ptr<cv::aruco::Dictionary>'

The only module from contrib I actually would need is the xfeatures2d, is there any way to get it to work?

**Comment by amroamroamro** [comment]
I don't follow macOS updates, does this mean OpenCV 3.1.0 cannot be built anymore in the latest macOS?

The current version of mexopencv targets 3.1.0. An update for 3.2.0 is in the works and should be coming soon..

**Comment by lasuomela** [comment]
Yes, see https://github.com/Homebrew/homebrew-science/issues/4303

Basically, QTkit has been replaced with AVfoundation (which opencv 3.1.0 doesn't support) on 10.12 and there seems to be no real workaround.

**Comment by amroamroamro** [comment]
I see.

Until the 3.2.0 update is ready, try to build opencv 3.1.0 from source and disable all video I/O backends except FFmpeg (disable QTkit, AVfoundation, QuickTime, etc..). I remember that you can select which backends to compile in the cmake options.

If that doesn't work, perhaps you can build opencv 3.1.0 without the "videoio" module altogether (`cmake -DBUILD_opencv_videoio=OFF ...`). As far as I know, the capture API is the problematic part here, so you could disable it for now as workaround..
Of course you'll have to disable the corresponding parts in mexopencv, i.e. rename the files `src/+cv/private/VideoCapture_.cpp` and `src/+cv/private/VideoWriter_.cpp` (e.g. add `*.cpp.disabled` extension).

**Comment by lasuomela** [comment]
Ok, will try. Thanks for the tip!

**Comment by amroamroamro** [comment]
@lasuomela we updated to OpenCV 3.2.0 (PR #329).
I'll close as fixed, let us know if you still encounter any problems.
