### ISSUE TITLE
make: /usr/local/matlab/bin/mexext: Command not found

### ISSUE THREAD

**Issue by sarmadm** [kyamagu/mexopencv#323]
Hi

I'm using opencv 3.1.0 on ubuntu and matlab R2016b ,

when I try to make this error is showing , what should I do ?
```
tofi@tofi:~/mexopencv$ make

make: /usr/local/matlab/bin/mexext: Command not found
Makefile:67: *** "MEX extension not set". Stop.
```

**Comment by amroamroamro** [comment]
As mention in the [README file](https://github.com/kyamagu/mexopencv/blob/master/README.markdown#linux), you can specify the location where MATLAB is installed as:

    $ make MATLABDIR=/opt/local/MATLAB/R2016b

It should yield `$MATLABDIR/bin/matlab` and `$MATLABDIR/bin/mex`. The default value is `/usr/local/matlab`.

**Comment by sarmadm** [comment]
I switched to windows 10 . I'm using visual studio 2015 , opencv 3.1

I just downloaded opencv3.1 without configuring it for use with vs2015.

When I run this command in matlab (R2016b) 

>> mexopencv.make('opencv_path','C:\opencv3.1\opencv\build')

mex -O -largeArrayDims   -I'C:\Users\sarmad\Documents\MATLAB\mexopencv-master\include' -I'C:\opencv3.1\opencv\build\include' -L'C:\opencv3.1\opencv\build\x64\vc14\lib'  -lopencv_world310  -c 'C:\Users\sarmad\Documents\MATLAB\mexopencv-master\src\MxArray.cpp' -outdir 'C:\Users\sarmad\Documents\MATLAB\mexopencv-master\lib'
Building with 'Microsoft Visual C++ 2015 Professional'.
Error using mex
MxArray.cpp
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\crtdefs.h(10): fatal error C1083: Cannot open include file:
'corecrt.h': No such file or directory

Error in mexopencv.make (line 96)
            if ~opts.dryrun, eval(cmd); end
