### ISSUE TITLE
OpencCV 3.2

### ISSUE THREAD

**Issue by AvinoamK** [kyamagu/mexopencv#325]
Does mexopencv supports OpenCV 3.2?

**Comment by amroamroamro** [comment]
Not yet. I've been working on an update for 3.2.0.
I am mostly finished with the main opencv modules, but I'm still working on the opencv_contrib modules...

**Comment by AvinoamK** [comment]
I have checked 3.2.0 update with Octave 4.2.1 32-bit:

Totals:
  1170 Passed, 0 Failed
  Elapsed time is 162.087010 seconds.

**Comment by AvinoamK** [comment]
Checked on Win-7

**Comment by amroamroamro** [comment]
yep thanks, it checks out on AppVeyor CI with the same setup
(OpenCV 3.2.0 with Octave 4.2.1 x32, running on Windows Server 2012):

> https://ci.appveyor.com/project/kyamagu/mexopencv/build/3.2.0.61

```
Totals:
  1170 Passed, 0 Failed
  Elapsed time is 156.232476 seconds.
```

**Comment by amroamroamro** [comment]
Done, PR #329 merged.
