### ISSUE TITLE
Error setting up mexopencv with MinGW64

### ISSUE THREAD

**Issue by Sidhyansh** [kyamagu/mexopencv#327]
Using:
- matlab R2015b on a 64 bit, windows 10
- MinGW64 Compiler (C++)
- Open CV 3.10 . (C:\opencv). I have build it using visual studios

I am a begginer. So I don't have much understanding. Followed your instructions till now

```
>> mexopencv.make
Skipped "C:\opencv\mexopencv-master\src\MxArray.cpp"
Skipped "C:\opencv\mexopencv-master\src\mexopencv_features2d.cpp"
Skipped "C:\opencv\mexopencv-master\src\mexopencv_ml.cpp"
Skipped "C:\opencv\mexopencv-master\src\mexopencv_shape.cpp"
Skipped "C:\opencv\mexopencv-master\src\mexopencv_stitching.cpp"
Skipped "C:\opencv\mexopencv-master\src\mexopencv_videostab.cpp"
mex -O -largeArrayDims   -I'C:\opencv\mexopencv-master\include' -I'C:\opencv\build\include' -L'C:\opencv\build\x64\mingw\lib'  -lopencv_world310  'C:\opencv\mexopencv-master\src\+cv\AGAST.cpp' 'C:\opencv\mexopencv-master\lib\MxArray.obj' 'C:\opencv\mexopencv-master\lib\mexopencv_features2d.obj' 'C:\opencv\mexopencv-master\lib\mexopencv_ml.obj' 'C:\opencv\mexopencv-master\lib\mexopencv_shape.obj' 'C:\opencv\mexopencv-master\lib\mexopencv_stitching.obj' 'C:\opencv\mexopencv-master\lib\mexopencv_videostab.obj' -output 'C:\opencv\mexopencv-master\+cv\AGAST'
Building with 'MinGW64 Compiler (C++)'.
Error using mex
C:\Users\sidhy\AppData\Local\Temp\mex_1990418729150934_10888\AGAST.obj:AGAST.cpp:(.text+0x505):
undefined reference to `cv::AGAST(cv::_InputArray const&, std::vector<cv::KeyPoint,
std::allocator<cv::KeyPoint> >&, int, bool, int)'
C:\Users\sidhy\AppData\Local\Temp\mex_1990418729150934_10888\AGAST.obj:AGAST.cpp:(.text+0x554):
undefined reference to `cv::Mat::deallocate()'
C:\Users\sidhy\AppData\Local\Temp\mex_1990418729150934_10888\AGAST.obj:AGAST.cpp:(.text+0x5af):
undefined reference to `cv::fastFree(void*)'

Error in mexopencv.make (line 139)
            if ~opts.dryrun, eval(cmd); end
 ```

**Comment by amroamroamro** [comment]
You're mixing compilers, if you built OpenCV using Visual Studio, you should compile mexopencv using VS as well.

**Comment by hyeraaira** [comment]
Hello, can anyone help me. I'm really noob in this. i'm using matlab r2016a, opencv 2.4.10
>> mexopencv.make
Skipped "C:\mexopencv-master\mexopencv-master\src\MxArray.cpp"
mex -O -largeArrayDims COMPFLAGS="$COMPFLAGS \Zc:wchar_t-"  -I'C:\mexopencv-master\mexopencv-master\include' -I'C:\opencv\build\include' -L'C:\opencv\build\x64\vc11\lib'  -lopencv_calib3d2410 -lopencv_contrib2410 -lopencv_core2410 -lopencv_features2d2410 -lopencv_flann2410 -lopencv_gpu2410 -lopencv_highgui2410 -lopencv_imgproc2410 -lopencv_legacy2410 -lopencv_ml2410 -lopencv_nonfree2410 -lopencv_objdetect2410 -lopencv_ocl2410 -lopencv_photo2410 -lopencv_stitching2410 -lopencv_superres2410 -lopencv_ts2410 -lopencv_video2410 -lopencv_videostab2410  -c 'C:\mexopencv-master\mexopencv-master\src\mexopencv_features2d.cpp' -outdir 'C:\mexopencv-master\mexopencv-master\lib'
Building with 'Microsoft Visual C++ 2012'.
.
.
.

c:\mexopencv-master\mexopencv-master\include\mexopencv.hpp(130) : error C2039: 'FILLED' : is not a member of 'cv'
c:\mexopencv-master\mexopencv-master\include\mexopencv.hpp(130) : error C2065: 'FILLED' : undeclared identifier
c:\mexopencv-master\mexopencv-master\include\mexopencv.hpp(130) : error C2512: 'ConstMap<T,U>' : no appropriate default
constructor available
        with
        [
            T=std::string,
            U=int
        ]
C:\mexopencv-master\mexopencv-master\include\mexopencv_features2d.hpp(18) : fatal error C1083: Cannot open include file:
'opencv2/features2d.hpp': No such file or directory

cl : Command line warning D9024 : unrecognized source file type '\Zc:wchar_t-', object file assumed
cl : Command line warning D9027 : source file '\Zc:wchar_t-' ignored


Error in mexopencv.make (line 96)
            if ~opts.dryrun, eval(cmd); end

thanks in advance.

**Comment by amroamroamro** [comment]
@hyeraaira 
please don't post to unrelated issues, instead create a [new issue](https://github.com/kyamagu/mexopencv/issues/new).

**Comment by hyeraaira** [comment]
@amroamroamro 
sorry. i'm still new to this.
