### ISSUE TITLE
Unrecognized or unsupported array type in function cvGetMat

### ISSUE THREAD

**Issue by sarmadm** [kyamagu/mexopencv#328]
When I try to open video file I get this errors 

```
Unexpected Standard exception from MEX file.

What() is:C:\dev_opencv\opencv\modules\core\src\array.cpp:2494: error: (-206) Unrecognized or unsupported array type in function
cvGetMat

..

Error in cv.CascadeClassifier/detect (line 292)
            [boxes, varargout{1:nargout-1}] = CascadeClassifier_(this.id, ...
```

**Comment by amroamroamro** [comment]
Can you share your code that's causing the error ([MWE](https://en.wikipedia.org/wiki/Minimal_Working_Example))? According to the above, it's coming from `cv.CascadeClassifier/detect` method, not opening a video file..

**Comment by sarmadm** [comment]
Hi , This is the code i'm using . it is for a library called zface. 

that library source contains  "mexopencv" wrapper that has been compiled with the 64
bit OpenCV 2.4.11 for 64bit Windows and has dll files for \opencv_2.4.11_x64_vc11_dlls\. 

If you need to test it I can provide you the link to download it


`
clear all;

addpath('C:\Users\sarmad\Documents\MATLAB\ZFace_v1.1_ocv2.4.11_x64_vc11\ZFace_src');
addpath(genpath('C:\Users\sarmad\Documents\MATLAB\ZFace_v1.1_ocv2.4.11_x64_vc11\3rd_party\'));
zf = CZFace('C:\Users\sarmad\Documents\MATLAB\ZFace_v1.1_ocv2.4.11_x64_vc11\ZFace_models\zf_ctrl49_mesh512.dat','C:\Users\sarmad\Documents\MATLAB\ZFace_v1.1_ocv2.4.11_x64_vc11\haarcascade_frontalface_alt2.xml');

cap = cv.VideoCapture('1.avi');
I = cap.read;
h = InitDisplay( zf, I );
ctrl2D = [];

global KEY_IS_PRESSED
KEY_IS_PRESSED = 0;
set(gcf, 'KeyPressFcn', @myKeyPressFcn)

isRunning = true;
while isRunning
    I = cap.read;
    
	[ ctrl2D, mesh2D, mesh3D, pars ] = zf.Fit( I, ctrl2D );        
    UpdateDisplay( h, zf, I, ctrl2D, mesh2D, pars );

    if strcmp(KEY_IS_PRESSED,'escape')
        isRunning = false;
    end

    if strcmp(KEY_IS_PRESSED,'space')
        ctrl2D = [];
        KEY_IS_PRESSED = '';
    end
end

cap.delete;
clear cap;
clear zf;
close(h.fig);`

**Comment by amroamroamro** [comment]
Yes, please provide a link for ZFace library. I can't tell what the problem is without knowing how `CascadeClassifier` is being called.. For starters, after this line `I = cap.read;` you should check that the frame returned is not empty.

**Comment by amroamroamro** [comment]
Better yet, first run `dbstop if error` in MATLAB, then run your example. It will stop in debugger mode when an error is thrown, that way you can inspect the variables in current scope looking for any problems. You can traverse the call stack until you reach the offending code. See docs for help: https://www.mathworks.com/help/matlab/matlab_prog/examine-values.html

**Comment by sarmadm** [comment]
here is the link for the library : [https://drive.google.com/file/d/0B03WnxRSaChVSGFkZjkwVmh4NG8/view?usp=sharing ](url)

**Comment by sarmadm** [comment]
HI.

Thanks very much for your help.

Could you please let me know how you installed it ? which opencv version and mexopencv ? and how is the procedure

**Comment by amroamroamro** [comment]
@sarmadm 
I just download the 7z file you provided the other day. It includes a precompiled versions of opencv and mexopencv (v2.4.11). You just need to adjust the paths as I showed. So just run the code I posted above, and adjust the top variable `ZFACE_ROOT` to point to the full path where zface was extracted.

**Comment by sarmadm** [comment]
Thanks , for demo_camera.m . I changed it like this 

`clear all;

ZFACE_ROOT = 'C:\Users\sarmad\Documents\MATLAB\ZFace_v1.1_ocv2.4.11_x64_vc11';
setenv('PATH', [fullfile(ZFACE_ROOT,'opencv_2.4.11_x64_vc11_dlls') ';' getenv('PATH')])
addpath(fullfile(ZFACE_ROOT,'3rd_party','arrow3D_pub'));
addpath(fullfile(ZFACE_ROOT,'3rd_party','mexopencv_2.4.11'));
addpath(fullfile(ZFACE_ROOT,'ZFace_src'));

modelFile = fullfile(ZFACE_ROOT,'ZFace_models','zf_ctrl49_mesh512.dat');
cascadeFile = fullfile(ZFACE_ROOT,'haarcascade_frontalface_alt2.xml');
zf = CZFace(modelFile, cascadeFile);
cap = cv.VideoCapture(0);

I = cap.read;
h = InitDisplay( zf, I );
ctrl2D = [];

global KEY_IS_PRESSED
KEY_IS_PRESSED = 0;
set(gcf, 'KeyPressFcn', @myKeyPressFcn)

isRunning = true;
while isRunning
    I = cap.read;
    
	[ ctrl2D, mesh2D, mesh3D, pars ] = zf.Fit( I, ctrl2D );        
    UpdateDisplay( h, zf, I, ctrl2D, mesh2D, pars );

    if strcmp(KEY_IS_PRESSED,'escape')
        isRunning = false;
    end

    if strcmp(KEY_IS_PRESSED,'space')
        ctrl2D = [];
        KEY_IS_PRESSED = '';
    end
end

cap.delete;
clear cap;
clear zf;
close(h.fig);`

**Comment by amroamroamro** [comment]
@sarmadm same problem, you must specify the full path to the video file, otherwise VideoCapture can't find it and simply returns empty arrays when you try to read frames...

You would have caught this if you added a bit more validations like:

```matlab
cap = cv.VideoCapture('1.avi');
assert(cap.isOpened(), 'Failed to open video capture');

I = cap.read();
assert(~isempty(I), 'no frames');
```

To fix it, specify the full location of video file:

```matlab
cap = cv.VideoCapture('C:\path\to\1.avi');
```

**Comment by franciscotovarmit** [comment]
I can get the video from my webcam  using openCV without any issue, therefore Im assuming open cv was installed correctly.

However I cannot get any single image loaded.

Im getting this error:

opencv-4.5.3/modules/core/src/array.cpp:2494: error: (-206:Bad flag (parameter or structure field)) Unrecognized or unsupported array type in function 'cvGetMat'

**Comment by Himanshunitrr** [comment]
I am getting the same error
```terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.5-dev) /opt/opencv/modules/core/src/array.cpp:2494: error: (-206:Bad flag (parameter or structure field)) Unrecognized or unsupported array type in function 'cvGetMat'

Aborted (core dumped)```
