### ISSUE TITLE
Ubuntu 16.04 'cannot open shared object file'

### ISSUE THREAD

**Issue by LordAddy** [kyamagu/mexopencv#334]
Hello,

I am using: 
Ubuntu 16.04.2 64bit
Matlab R2016b

and I just ran the make command for building the mex files. I am trying out simple demo to test if it works and I am getting following error, even though the make went through without a single problem.

````
addpath('/home/adam/programming/matlablib/mexopencv');

im = imread('data/face.jpg');
gr = cv.cvtColor(im, 'RGB2GRAY');
imshow(gr);
````

````
Error using cv.cvtColor
Invalid MEX-file '/home/adam/programming/matlablib/mexopencv/+cv/cvtColor.mexa64':
libopencv_imgproc.so.3.2: cannot open shared object file: No such file or directory.

Error in cvtest (line 4)
````

Please could you give me advice on how to setup OpenCV properly so that the mex files find the libs?

I've tried already appending the path '/path/to/opencv/build/lib' to LD_LIBRARY_PATH variable and also adding the path to /etc/ld.so.conf.d and then calling ldconfig but with no effects. It seems to me like it didn't get linked properly during the mex build. All ideas appreciated!

**Comment by kyamagu** [comment]
@LordAddy Just to confirm, are you literally appending `/path/to/opencv/build/lib` to `LD_LIBRARY_PATH` or your own path where you installed OpenCV 3.2 (e.g., `/usr/local/lib`)?

**Comment by LordAddy** [comment]
I was appending my own path but to the build folder, not the `/usr/local/lib`, that seemed to work, thanks! Then I got a different error:

```
Error using cv.cvtColor
Invalid MEX-file '/home/adam/programming/matlablib/mexopencv/+cv/cvtColor.mexa64':
/usr/local/MATLAB/R2016b/bin/glnxa64/../../sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found
(required by /home/adam/programming/matlablib/mexopencv/+cv/cvtColor.mexa64).

Error in cvtest (line 4)
```

Which is apparently caused by MATLAB expecting different version of gcc than is installed, so I have removed the file `/usr/local/MATLAB/R2014a/sys/os/glnxa64/libstdc++.so.6` and created symlink `ln -s /usr/lib/x86_64-linux-gnu/libstdc++.so.6  /usr/local/MATLAB/R2014a/sys/os/glnxa64/libstdc++.so.6`. I'm leaving it here just in case someone has the same problem. Thanks again!

**Comment by amroamroamro** [comment]
also FYI: https://github.com/kyamagu/mexopencv/wiki/Troubleshooting-%28UNIX%29
