### ISSUE TITLE
mexopencv.make file with opencv_contrib

### ISSUE THREAD

**Issue by adityaksai** [kyamagu/mexopencv#336]
while running mexopencv.make file with contrib I got this error

```
Error using mex
Creating library
 C:\opencv3.1\mexopencv-3.1.0.\opencv_contrib+cv\private\BriefDescriptorExtractor_.lib
and object
 C:\opencv3.1\mexopencv-3.1.0.1\opencv_contrib+cv\private\BriefDescriptorExtractor_.exp

BriefDescriptorExtractor_.obj : error LNK2019:
unresolved external symbol "struct cv::Ptr __cdecl createBriefDescriptorExtractor(class std::_Vector_const_iterator<class std::_Vector_val<struct std::_Simple_types > >,class std::_Vector_const_iterator<class std::_Vector_val<struct std::_Simple_types > >)"
(?createBriefDescriptorExtractor@@YA?AU?$Ptr@VBriefDescriptorExtractor@xfeatures2d@cv@@@cv@@V?$_Vector_const_iterator@V?$_Vector_val@U?$Simple_types@VMxArray@@@std@@@std@@@std@@0@Z)
referenced in function mexFunction
C:\opencv3.1\mexopencv-3.1.0.1\opencv_contrib+cv\private\BriefDescriptorExtractor.mexw64 :
fatal error LNK1120: 1 unresolved externals

Error in mexopencv.make (line 139)
if ~opts.dryrun, eval(cmd); end
```

**Comment by amroamroamro** [comment]
https://github.com/kyamagu/mexopencv/wiki/_Footer/_compare/59bb9a2%5E...59bb9a2, uh what?

**Comment by amroamroamro** [comment]
mexopencv is developed against specific OpenCV releases, therefore you must be using the correct  opencv  &  opencv_contrib  versions.

The current version of mexopencv (master branch) is compatible with OpenCV 3.2.0.
For older OpenCV versions, please checkout the corresponding branches, [v3.1](https://github.com/kyamagu/mexopencv/tree/v3.1) in your case.

**Comment by adityaksai** [comment]
yes I am using mexopencv 3.1 and it is working fine. I want to update it to 3.1.0.1.I am getting the above mentioned error.  I am unable to include the header files while using mexopencv object detection . cpp.  It is showing header objdetect. h not found.  I have followed the instructions as per your installation process to install opencv. 

Thanks in advance. Sorry for the inconvenience

**Comment by amroamroamro** [comment]
If you are updating an existing mexopencv installation, you should clean the previous build.
Make sure to run `mexopencv.make('clean',true)` first.

**Comment by adityaksai** [comment]
Thank you so much. I have updated to opencv3.2. but the problem is while checking objectdetector,cpp  I am getting this error

Building with 'Microsoft Visual C++ 2015 Professional'.
Error using mexOpenCV (line 122)
objectDetection.cpp
C:\opencv320\objectDetection.cpp(1): fatal error C1083: Cannot open include file: 'opencv2/objdetect.hpp': No such file or directory

**Comment by amroamroamro** [comment]
Like I've said [before][0], you seem to be confusing [mexopencv][1] with the [CVST opencv interface provided by MathWorks][2] (the fact the MathWorks used `mexOpencv.m` as file name adds to the confusion).
Once again **these are completely different things!**

Using this project, you don't have to write code in C++, you can directly use OpenCV functions/classes as MATLAB ones. mexopencv provides wrappers for hundreds of APIs from opencv and opencv_contrib, you just call them in MATLAB as `cv.func` where `func` is whatever OpenCV function you want (last time I checked we had more than 400 OpenCV functions/classes exposed).

Perhaps you should start by having a look at the existing samples and demos we have:
- https://github.com/kyamagu/mexopencv/tree/master/opencv_contrib/samples
- https://github.com/kyamagu/mexopencv/tree/master/samples


[0]: https://github.com/kyamagu/mexopencv/issues/230#issuecomment-292243241
[1]: https://github.com/kyamagu/mexopencv
[2]: https://www.mathworks.com/help/vision/ug/opencv-interface.html

**Comment by amroamroamro** [comment]
Of course for advanced uses, you can write MEX-files yourself in C++. We provide a helper class `MxArray` that makes it easy to convert between datatypes used in OpenCV and MATLAB.
*This only needed for cases were you need to do something on the C++ side not exposed by mexopencv.*

**Comment by adityaksai** [comment]
while running grabcut demo I am getting this error

Undefined variable "mexopencv" or class "mexopencv.root".

Error in grabcut_demo_gui (line 13)
        src = imread(fullfile(mexopencv.root(),'test','cat.jpg'));

**Comment by adityaksai** [comment]
I am running the samples and working fine.
Thank you so much.
