### ISSUE TITLE
Mex functions never return

### ISSUE THREAD

**Issue by kazimpal87** [kyamagu/mexopencv#337]
I'm using MacOS 10.11, Matlab R2017a, OpenCV 3.2. 

I can't make any mex file using mexopenv return any value. For example, I've successfully compiled the `absdiff` example into a mex file and then invoke it in matlab using:

```matlab
foo = absdiff(1,4);
disp(foo);
```

when the execution reaches the `absdiff` function, it just hangs and never returns. I have also tried writing my own mex file which just returns a 1x1 matrix containing a zero and that hangs too. Mex files which don't use mexopencv seem to return fine.

**Comment by amroamroamro** [comment]
Are you sure you're calling functions correctly?
Normally that would be `cv.absdiff(1,4)`, unless you did `import cv` which I don't recommend..

**Comment by kazimpal87** [comment]
i'm just trying to successfully invoke a mex file. Theres a mex file called absdiff and i'm just trying to call it from within matlab. i have a more complex one based on http://docs.opencv.org/trunk/d2/d59/tutorial_ximgproc_training.html which also doesn't work, so i want to start by getting anything to return.

**Comment by amroamroamro** [comment]
Just to be clear, are you using mexopencv functions, or are you compiling your own MEX-files and using the MxArray class?

**Comment by kazimpal87** [comment]
The absdiff MEX-file I'm referring to is provided by the library (located at /+cv/absdiff.mexmaci64).
The other more complex one is my own compiled MEX-file using the MxArray class.
Neither return.

**Comment by amroamroamro** [comment]
a few things to check:

- how did you install/build opencv?
- how did you compile mexopencv? did you use the provided `Makefile`?
- did you setup the matlab path correctly? i.e `addpath` and `path`
- can matlab locate the opencv libs at runtime? i.e  `DYLD_LIBRARY_PATH`
- if possible, can you run `cv.getBuildInformation` in matlab and post the results
