### ISSUE TITLE
mexopencv.make compilation VS2017

### ISSUE THREAD

**Issue by raphael54** [kyamagu/mexopencv#338]
Hello

I'm using : 
Windows 10 Professional x64
Matlab R2015a 64 bits
Visual Studio Community 15 2017 Win64
OpenCV 3.2.0 and openCV_contrib 3.2.0

and I follow this tutorial : https://github.com/kyamagu/mexopencv/wiki/Installation-%28Windows%2C-MATLAB%2C-OpenCV-3%29

Everythings work well until the mexopencv step, where I have to run Matlab : 

![image](https://cloud.githubusercontent.com/assets/27283685/24908611/e67e5474-1ec0-11e7-8141-0f7a840f408d.png)

Moreover, "mex -setup" give this : 

![image](https://cloud.githubusercontent.com/assets/27283685/24908651/115be508-1ec1-11e7-9686-3bf3cd7c64f3.png)

Is it an issue about the compiler, or maybe a wrong path ?

Can you help me ?

Thank you very much.

**Comment by amroamroamro** [comment]
Two things:
- neither VS2017 nor VS2015 are on the list of supported compilers for your MATLAB R2015a (see [here](https://www.mathworks.com/support/sysreq/previous_releases.html)). In fact, according to [this](https://www.mathworks.com/support/compilers.html), VS2017 is not even recognized by the latest version R2017a.
- unfortunately MATLAB might not automatically detect the *Community Edition* of Visual Studio when you run `mex -setup`, it only recognizes the *Professional* edition, even though the two are pretty much equivalent in functionality!

It means you have to use a one of the supported compilers listed for your version.

**Comment by amroamroamro** [comment]
Now that doesn't mean you can't make it work, it's just not officially supported by MathWorks.
Basically you have to manually edit XML configuration files for MEX:
1. first grab a copy of the template config file matching your VS version. They are stored in `matlabroot()\bin\win64\mexopts`. Grab either `msvcpp2013.xml` or `msvcpp2015.xml` for C++ compilers, same for C compilers in `msvc201?.xml`.
2. copy the files to `prefdir()` as `mex_C++_win64.xml` and `mex_C_win64.xml`.
3. edit the files and adjust paths accordingly.

In the last step, you'll need to use correct version numbers (VS2013 is 12.0, VS2015 is 14.0, VS2017 is 15.0).
The way the script works is that it looks in the Windows registry to find the location where Visual Studio is installed (see `<locationFinder>..</locationFinder>`). It searches specific keys (both HKLM and HKCU) in order specified, according to set rules (either `<and>` or `<or>`). It populates environment variables based on those results (VCROOT, SDKROOT, etc..). I don't have Community Edition installed, so I don't know if the installer creates the same keys in the registry, you'll have to test it yourself... Once those env vars are found, the script populates the following variables (PATH, INCLUDE, LIB, and LIBPATH). You might need to fix some paths here as well based on which WinSDK is installed along with Visual Studio. When trying to debug this, you can run compile a dummy mex-file with the flag `mex -v ..`, MATLAB should print verbose messages showing where it's looking in the registry.

If that sounds too complicated (it kinda is), you should complain to MathWorks and have them include proper support for the community editions ;)

**Comment by raphael54** [comment]
Thanks a lot for your quick and precise answer, I'm going to see it clolsely ! 

Hope it's gonna be well.

**Comment by amroamroamro** [comment]
Looked into VS2017, it seems that it changed things a bit with respect to the directories layout... https://developercommunity.visualstudio.com/content/problem/2813/cant-find-registry-entries-for-visual-studio-2017.html

It might be easier to just drop `<locationFinder>` and instead use absolute paths in the `<env>` section (PATH, INCLUDE, LIB, and LIBPATH). Not portable, but should get the job done :)

**Comment by raphael54** [comment]
Thank you very much for your help, I try it today :)

**Comment by raphael54** [comment]
I've just tried to use the gist you created but unfortunately, it still doesn't work. Do I have to change something in the xml file or is it supposed to work like this ? Like
Name="Microsoft Visual C++ 2017 Professional (C)" into 
Name="Microsoft Visual C++ 2017 " ? for the community edition?

Thanks

**Comment by amroamroamro** [comment]
@raphael54 
Sorry for the late reply.

The name is not important, it's a description and you can set it to anything really..

Now please be more specific, did you follow the steps to copy the files in the correct location?

I updated the XML files in the gist. Download it again, and this time run setup in verbose mode and post the output here:

    >> mex -setup -v
    >> mex -setup -v C++
