### ISSUE TITLE
mex error in win10

### ISSUE THREAD

**Issue by wmbean** [kyamagu/mexopencv#341]
Really sorry to trouble you. But I have googled a lot and can't find the answer of my problem. 

My trouble is similar with #338 .
I have succeeded in installing opencv 3.2.0 with the WIKI guidance. ( Windows 7 pro+Matlab 2017a+VS2017RC)
However, when I do the same process in a PC with Windows 10 home operating system ( same Matlab and VS ) , the error comes out.

```
Error using mex
MxArray.cpp
D:\....\crtdefs.h(10): fatal error C1083: 
Cannot open include file: "corecrt.h": No such file or directory.
```

The difference of two PCs is the Windows 10 SDK's location: same drive with VS in Windows7, different dirve with VS in win10. ( VS and MATLAB are installed in the same drive.)
Anyway, the SDK path has been added in msvc2017.xml. ( I have searched in the regedit to confirm that KITSROOT path is OK. )
I also test your solution of #338 ( https://gist.github.com/amroamroamro/ea4541d5621f3d62e67029e393e523a0 ) and get the same error:

```
Error using mex
test.cpp
D:\....\matrix.h(10): fatal error C1083: 
Cannot open include file: "stdlib.h": No such file or directory.
```

So I wonder is there something wrong with the path recognition? And how to make it include the correct SDK's path?
I am new at programming, and hope you can understand my words.
Best wishes!

**Comment by amroamroamro** [comment]
Can you use the files from the [gist](https://gist.github.com/amroamroamro/ea4541d5621f3d62e67029e393e523a0), run the following and post the verbose output here:
```
>> mex -setup -v
>> mex -setup -v C++
```

PS: you mentioned using VS2017RC, you should install the final RTM version instead of the beta

**Comment by amroamroamro** [comment]
It would also help if you dump a few VS registry keys to make it easier for me to debug. Open a command prompt and run the following (do this from both Win7 and Win10 installations):
```
set > set.log
REG EXPORT "HKLM\SOFTWARE\Microsoft\VisualStudio\SxS" hklm_vs.reg
REG EXPORT "HKLM\SOFTWARE\Microsoft\Microsoft SDKs" hklm_sdk.reg
REG EXPORT "HKLM\SOFTWARE\Microsoft\Windows Kits" hklm_kits.reg
REG EXPORT "HKLM\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\SxS" hklm_vs_wow.reg
REG EXPORT "HKLM\SOFTWARE\Wow6432Node\Microsoft\Microsoft SDKs" hklm_sdk_wow.reg
REG EXPORT "HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows Kits" hklm_kits_wow.reg
```
Then zip all .reg and .log files and upload the results here.

**Comment by wmbean** [comment]
Thanks so much for your response.
And sorry that I made a mistake, I am using VS2017 community instead of release candidate. I apologize for the misleading information.
So far I am using the support codes provided by [Mathworks](https://www.mathworks.com/matlabcentral/answers/335092-can-i-use-microsoft-visual-studio-2017-with-matlab) , and they generated similar .xml files as you provided in the [gist](https://gist.github.com/amroamroamro/ea4541d5621f3d62e67029e393e523a0). When I test the solution before I replace them with yours and got the same error mentioned at first. Now I replace them again and zip verbose output with VS registry keys in Annex.
[files.zip](https://github.com/kyamagu/mexopencv/files/966568/files.zip)

**Comment by amroamroamro** [comment]
@wmbean 
Thanks for the link, I didn't know MathWorks provided a solution for this.

However I think you got things mixed up... The `win10+matlab+mex.txt` log shows that you're not using the config files I created, instead the MathWorks solution is configured (VS2015 seems to be modified as well?). I suggest you start again by reseting all changes you've made, and only use my VS2017 files from the gist. Then run `mex -v setup` etc. and post the output again.

---

By the way I noticed you have multiple opencv installations in the %PATH% environment variables.
```
I:\opencv\bulid\install\x64\vc15\bin
D:\Program Files\opencv\build\x64\vc14\bin
```
You should only have one exposed in the path to avoid any confusion.

Also If I got this correct, you seem to have VisualStudio/WindSDK split across several drives (`C:\`, `D:\`, and `F:\`). Were they installed like that or are you mounting drives from a different computer?

**Comment by wmbean** [comment]
Oh thank you so much!
The multiple opencv installations are in win7 PC that dose not matter. The mexopencv works fine there. I do that because the build files are too big and I don't know which can be deleted. So I keep the official compiled code for VS usage. :P It's a mess, as you can see, and I will try to find a way for simplification.
And yes you got the point! The sdkpath and sdkversion are wrong that make MATLAB include wrong filepath. I have correct the registry path but here comes another problem.
The windows10 SDK seems have different bin path from the previous. In SDK 7.1 or 8.1 the bin path or the "windowssdk executablepath " is the subfolder of $KitsRoot, such as:
`C:\Program Files (x86)\Windows Kits\8.1\bin\`
However, in Win10 the correct path seems to be the sub-subfolder of  $KitsRoot, such as:
`C:\Program Files (x86)\Windows Kits\10\bin\10.0.15063.0\`
There is no mt.exe and other necessary operable program in the path:
`C:\Program Files (x86)\Windows Kits\10\bin\x64\`
So the Matlab occurs error
`Error using mex 'mt' is not recognized as an internal or external command, operable program or batch file.`
Then I try to replace the path in .xml file 
`$SDKROOT\Bin\x64;$SDKROOT\Bin\x86;`
with
`$SDKROOT\Bin\$SDKVERSION\x64;$SDKROOT\Bin\$SDKVERSION\x86;`
but it doesn't work. And adding those to environment path doesn't work either. I guess that I didn't got the error in WIN7 because the SDK 7.1 had included the necessary program that can be used during compiling. But it can't explain why add the win10 sdk path can't work at all.
Thanks so much for your time again.

**Comment by amroamroamro** [comment]
@wmbean 
> Probably I haven't made it clear that there were two computers. One is running Windows 7 the other is Windows 10

I got that, it's just kinda messy even on your Win10 machine by itself with multiple WinSDK and VS installations across different drives, with what it seems broken registry entries..

You see VS/WinSDK are usually self-contained and they can coexist just fine with older versions (I myself have VS2010, VS2015, VS2017 and their corresponding WinSDKs all installed on the same `C:\` drive, with no problems).

> Windows 10 SDK seems to have different bin path from the previous [SDK 7.1 or 8.1]

Yes I am aware. There are multiple versions of WinSDK10, each targetting a specific build of Win10 (RTM, November Update, Anniversary Update, Creators Update, etc.).

https://en.wikipedia.org/wiki/Microsoft_Windows_SDK
https://en.wikipedia.org/wiki/Windows_10_version_history

Under `PROGFILES86\Windows Kits\10` they are installed as sub-directories when necessary (Include and Lib) but can also have shared directories (Bin).

Normally you don't have to worry about this, just let the VS installer pick the necessary packages. For the purpose of building MATLAB MEX-files, any SDK version will do really.

> I have corrected the registry path

Good. Ultimately I would consider running the VS2017 installer again, it should repair any other irregularities.

> There is no `mt.exe` and other necessary operable programs in the path

You are still mixing MEX config files...
Again please check you are indeed using my config files (and not the MathWorks ones you mentioned)!

It should be straightforward really; just undo any changes you made in `MATLABROOT\bin\win64\mexopts`, then copy only my `msvc2017.xml` and `msvcpp2017.xml` files as-is. Just to be safe, also delete `mex_C_win64.xml` and `mex_C++_win64.xml` inside your `prefidr()` directory.

Next restart MATLAB, run `mex -v -setup C++` and select VS2017, and compile a test MEX-file `mex -v -largeArrayDims test.cpp`. Don't forget to post the full outputs here (of both steps).

They should work without making any changes.
(You **don't** need to add anything from WinSDK 7 or 8, the WinSDK 10 installed with VS2017 is sufficient).

Just to be clear, I am only talking about my solution ([gist](https://gist.github.com/amroamroamro/ea4541d5621f3d62e67029e393e523a0)). DO NOT mix it with the one provided by [MathWorks support](https://www.mathworks.com/matlabcentral/answers/335092-can-i-use-microsoft-visual-studio-2017-with-matlab). I can't help with that, and any issues with those should be reported to them.

**Comment by wmbean** [comment]
@amroamroamro
I am a idiot! Sorry that I misunderstood what you said "mixed up" before. I simply deleted the Matwork's .xml files at that time and didn't realize the wrong setup. I didn't backup folders either so I reinstall matlab. Sorry for the late reply.
Now everything works fine! The installation has succeed. I still attach the mex output though I think it  may be unnecessary?
Thank you for all your assistance! It's really hard to express my gratitude.
[mex output.txt](https://github.com/kyamagu/mexopencv/files/973468/mex.output.txt)

**Comment by amroamroamro** [comment]
Glad it's working :)

**Comment by Dhafer-ML** [comment]
i have problem in connected matlab with openccv
i have matlab 2013a and opencv the last version and now download visual studio 2017 
can now connected ? and what i need from the package of visual studio because the size it more 36GB

**Comment by Dhafer-ML** [comment]
@amroamroamro  please see my problem above

**Comment by amroamroamro** [comment]
@daferkiny 
VS2017 is not officially supported in R2013a.
It was released in 2013, four years before VS2017 was made ;)

See here for the list of supported compilers for your MATLAB release:
https://www.mathworks.com/support/sysreq/previous_releases.html

As for Visual Studio installation, you really only need the Visual C++ components for compiling MEX-files.

Once you setup the required build tools, you can find instructions in the wiki:
https://github.com/kyamagu/mexopencv/wiki/Installation-%28Windows%2C-MATLAB%2C-OpenCV-3%29

**Comment by daferkiny** [comment]
@amroamroamro 
when i make mexopencv.make this error occurred
![capture](https://user-images.githubusercontent.com/11949136/51623970-f467e000-1f4a-11e9-8048-0d5cb323bfd6.PNG)
