### ISSUE TITLE
compile error at FastHoughTransform.cpp

### ISSUE THREAD

**Issue by RGring** [kyamagu/mexopencv#342]
Hello,
I am trying to build the aruco_module of openCV for matlab using mexopencv.make. I used the Version 3.1.0 in opencv and mexopencv, 64 bit, Visual Studio 2010.
I get the following error:

```
Error using mex
FastHoughTransform.cpp
c:\program files (x86)\microsoft visual studio 10.0\vc\include\codeanalysis\sourceannotations.h(27) :
error C2144: syntax error : 'unsigned __int64' should be preceded by ';'
c:\program files (x86)\microsoft visual studio 10.0\vc\include\codeanalysis\sourceannotations.h(27) :
error C4430: missing type specifier - int assumed. Note: C++ does not support default-int

Error in mexopencv.make (line 139)
            if ~opts.dryrun, eval(cmd); end
```

Actually I don't Need FastHoughTransform. Can I skip it somehow. I just need the functions of the aruco-lib.

Thanks already!
RGring

**Comment by amroamroamro** [comment]
Did you follow the installation guide?
https://github.com/kyamagu/mexopencv/wiki/Installation-%28Windows%2C-MATLAB%2C-OpenCV-3%29
