### ISSUE TITLE
Unexpected Standard exception from MEX file. What() is:vector<T> too long

### ISSUE THREAD

**Issue by SCUT2014** [kyamagu/mexopencv#344]
```
Error using cv.CalculateErr
Unexpected Standard exception from MEX file.
What() is:vector<T> too long
```

How to remove this issue ? thank you very much.

Our platform is Matlab2012a + vs2010 Compiler + Win 7 32bit system

**Comment by amroamroamro** [comment]
Describe your config:
- which OpenCV version, is opencv_contrib used?
- how was opencv built? where is it installed?
- which mexopencv version (branch or tag)
- the call you used for `mexopencv.make`

Note that we have a [detailed guide in the wiki][1] covering latest opencv/opencv_contrib 3.2.0

Now the error you mentioned originates from `cv.CalculateErr`, is this a custom MEX-file? Consider posting the source code if so...

[1]: https://github.com/kyamagu/mexopencv/wiki/Installation-%28Windows%2C-MATLAB%2C-OpenCV-3%29
