### ISSUE TITLE
bad result on stitching_detailed_demo.m

### ISSUE THREAD

**Issue by lizzzcai** [kyamagu/mexopencv#347]
![mexopencv_stitching_detail](https://user-images.githubusercontent.com/22748546/26914240-c3b0e5be-4c52-11e7-9e81-2633d4cc9d85.jpg)

Dear all, I try the stitching_detailed_demo.m in the mexopencv3.2 with Matlab 2016b. However, the result looks like this, is this any error on my result, I think it should be better. Many thanks.

**Comment by amroamroamro** [comment]
I can't reproduce outcome on my end. I just tested the example, and I get correct results (using: opencv/opencv_contrib 3.2.0, MATLAB R2017a, VS2015, Win10):

![stitching_result](https://user-images.githubusercontent.com/83908/26918680-aee9250e-4c3b-11e7-8c73-a385cc98a2d8.jpg)

Did you build mexopencv with opencv_contrib enabled? The example uses SURF features by default, which would require `xfeatures2d` contrib module to be compiled.. You might get slightly different results when using another feature finder (ORB or AKAZE, both from `features2d` part of main opencv).

Just in case, post the output of `cv.getBuildInformation()`

Also are you using the default parameters in the script? did you change any of the options, there are lots of params exposed.. Try reverting the original file if that's the case.

You see this example is meant to illustrate the low-level stitching API, which allows to customize any part of the stitching pipeline. There's also the high-level API, which is a lot easier to use:

``` matlab
imgs = {..}; % cell array of images
obj = cv.Stitcher();
out = obj.stitch(imgs);
imshow(out)
```

Using the building images from before, I get a similar result either way.

**Comment by lizzzcai** [comment]
I used the default parameters of the stitching_detailed_demo.m but get the bad results. My system is opencv3.2, Matlab2016b, win7, VS 2013.  

The output of cv.getBuildInformation() is shown below.

>> cv.getBuildInformation()

General configuration for OpenCV 3.2.0 =====================================
  Version control:               unknown

  Extra modules:
    Location (extra):            H:/OpenCV/opencv320/opencv_contrib-3.2.0/modules
    Version control (extra):     unknown

  Platform:
    Timestamp:                   2017-06-07T15:52:25Z
    Host:                        Windows 6.1.7601 AMD64
    CMake:                       3.4.3
    CMake generator:             Visual Studio 12 2013 Win64
    CMake build tool:            C:/Program Files (x86)/MSBuild/12.0/bin/MSBuild.exe
    MSVC:                        1800

  C/C++:
    Built as dynamic libs?:      YES
    C++ Compiler:                C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/x86_amd64/cl.exe  (ver 18.0.40629.0)
    C++ flags (Release):         /DWIN32 /D_WINDOWS /W4 /GR /EHa  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /wd4127 /wd4251 /wd4324 /wd4275 /wd4589 /MP4  /MD /O2 /Ob2 /D NDEBUG  /Zi
    C++ flags (Debug):           /DWIN32 /D_WINDOWS /W4 /GR /EHa  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /wd4127 /wd4251 /wd4324 /wd4275 /wd4589 /MP4  /D_DEBUG /MDd /Zi /Ob0 /Od /RTC1 
    C Compiler:                  C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/x86_amd64/cl.exe
    C flags (Release):           /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi    /MP4  /MD /O2 /Ob2 /D NDEBUG  /Zi
    C flags (Debug):             /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi    /MP4  /D_DEBUG /MDd /Zi /Ob0 /Od /RTC1 
    Linker flags (Release):      /machine:x64  /INCREMENTAL:NO  /debug
    Linker flags (Debug):        /machine:x64  /debug /INCREMENTAL 
    ccache:                      NO
    Precompiled headers:         YES
    Extra dependencies:          comctl32 gdi32 ole32 setupapi ws2_32 vfw32 C:/Anaconda3/Library/lib/hdf5.lib
    3rdparty dependencies:       zlib libjpeg libwebp libpng libtiff libjasper IlmImf libprotobuf

  OpenCV modules:
    To be built:                 core flann hdf imgproc ml photo reg surface_matching video dnn fuzzy imgcodecs shape videoio highgui objdetect plot superres xobjdetect xphoto bgsegm bioinspired dpm face features2d line_descriptor saliency text calib3d ccalib datasets rgbd stereo tracking videostab xfeatures2d ximgproc aruco optflow phase_unwrapping stitching structured_light
    Disabled:                    python3 world contrib_world
    Disabled by dependency:      -
    Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev java python2 ts viz cnn_3dobj cvv freetype matlab sfm

  Non-free algorithms are enabled

  Windows RT support:            NO

  GUI: 
    QT:                          NO
    Win32 UI:                    YES
    OpenGL support:              NO
    VTK support:                 NO

  Media I/O: 
    ZLib:                        build (ver 1.2.8)
    JPEG:                        build (ver 90)
    WEBP:                        build (ver 0.3.1)
    PNG:                         build (ver 1.6.24)
    TIFF:                        build (ver 42 - 4.0.2)
    JPEG 2000:                   build (ver 1.900.1)
    OpenEXR:                     build (ver 1.7.1)
    GDAL:                        NO
    GDCM:                        NO

  Video I/O:
    Video for Windows:           YES
    DC1394 1.x:                  NO
    DC1394 2.x:                  NO
    FFMPEG:                      YES (prebuilt binaries)
      avcodec:                   YES (ver 57.64.101)
      avformat:                  YES (ver 57.56.100)
      avutil:                    YES (ver 55.34.100)
      swscale:                   YES (ver 4.2.100)
      avresample:                YES (ver 3.1.0)
    GStreamer:                   NO
    OpenNI:                      NO
    OpenNI PrimeSensor Modules:  NO
    OpenNI2:                     NO
    PvAPI:                       NO
    GigEVisionSDK:               NO
    DirectShow:                  YES
    Media Foundation:            NO
    XIMEA:                       NO
    Intel PerC:                  NO

  Parallel framework:            Concurrency

  Other third-party libraries:
    Use IPP:                     9.0.1 [9.0.1]
         at:                     H:/OpenCV/opencv320/opencv_mat/3rdparty/ippicv/ippicv_win
    Use IPP Async:               NO
    Use Lapack:                  NO
    Use Eigen:                   NO
    Use Cuda:                    NO
    Use OpenCL:                  YES
    Use OpenVX:                  NO
    Use custom HAL:              NO

  OpenCL:                        <Dynamic loading of OpenCL library>
    Include path:                H:/OpenCV/opencv320/opencv/sources/3rdparty/include/opencl/1.2
    Use AMDFFT:                  NO
    Use AMDBLAS:                 NO

  Python 2:
    Interpreter:                 NO

  Python 3:
    Interpreter:                 C:/Anaconda3/python.exe (ver 3.6)

  Python (for build):            C:/Anaconda3/python.exe

  Java:
    ant:                         NO
    JNI:                         C:/Program Files/Java/jdk1.7.0_80/include C:/Program Files/Java/jdk1.7.0_80/include/win32 C:/Program Files/Java/jdk1.7.0_80/include
    Java wrappers:               NO
    Java tests:                  NO

  Matlab:                        NO

  Tests and samples:
    Tests:                       NO
    Performance tests:           NO
    C/C++ Examples:              NO

  Install path:                  H:/OpenCV/opencv320/opencv_mat/install

  cvconfig.h is in:              H:/OpenCV/opencv320/opencv_mat
-----------------------------------------------------------------

**Comment by amroamroamro** [comment]
Configs look fine to me. I don't know why you're getting distorted results...

Try running with a different set of images. The example lists alternatives images to try (a1,a2,a3 as well as b1,b2, all included in the test folder).

**Comment by lizzzcai** [comment]
The results of a and b are also bed... I attached them below. 
![results of test_a](https://user-images.githubusercontent.com/22748546/26919858-aa4e3d4e-4c69-11e7-8d1a-d506424137cd.jpg)
![results of test b](https://user-images.githubusercontent.com/22748546/26919862-abb1ee6a-4c69-11e7-80c0-2a1ebeb3b18e.jpg)

**Comment by amroamroamro** [comment]
huh, that is weird!

One more question, can you run `stitching_demo.m` (not `stitching_detailed_demo.m`), and see if you also get bad results??

Could this be some graphics bug related to MATLAB? Can you inspect some other image, just display it with imshow. Try restarting MATLAB just in case...

**Comment by lizzzcai** [comment]
![results of stitching demo](https://user-images.githubusercontent.com/22748546/26920360-6449c42e-4c6b-11e7-841e-7210edb71011.jpg)
The result is also like this.... I have no idea right now. I try to reintall the mexopencv and see what happen,.

**Comment by amroamroamro** [comment]
I have no idea either.

At this point, I would suggest running the original OpenCV C++ sample (which the MATLAB example is based on), and see if you also get these distorted images:

https://github.com/opencv/opencv/blob/3.2.0/samples/cpp/stitching_detailed.cpp

**Comment by lizzzcai** [comment]
Actually I have the same problem in the opencv c++ in VS2013, I notice it is a problem when I saw the result from other.

**Comment by amroamroamro** [comment]
In that case, the problem is not on the mexopencv side.
You should [report it to opencv](https://github.com/opencv/opencv/issues/new) instead.
