### ISSUE TITLE
Issue when compiling mexopencv

### ISSUE THREAD

**Issue by JuanVidal** [kyamagu/mexopencv#358]
I've been following [this guide](https://github.com/kyamagu/mexopencv/wiki/Installation-%28Windows%2C-MATLAB%2C-OpenCV-3%29) for installing mexopencv on my MatlabR2015a and was going soft and nicely... until at the very end of the process this error arose:

```
mex -O -largeArrayDims   -I'D:\mexopencv-master\include' -I'D:\mexopencv-master\opencv_contrib\include' -I'D:\opencv\opencv-build\install\include' -L'D:\opencv\opencv-build\install\x64\vc14\lib'  -lopencv_aruco330 -lopencv_bgsegm330 -lopencv_bioinspired330 -lopencv_calib3d330 -lopencv_ccalib330 -lopencv_core330 -lopencv_datasets330 -lopencv_dnn330 -lopencv_dpm330 -lopencv_face330 -lopencv_features2d330 -lopencv_flann330 -lopencv_fuzzy330 -lopencv_highgui330 -lopencv_img_hash330 -lopencv_imgcodecs330 -lopencv_imgproc330 -lopencv_line_descriptor330 -lopencv_ml330 -lopencv_objdetect330 -lopencv_optflow330 -lopencv_phase_unwrapping330 -lopencv_photo330 -lopencv_plot330 -lopencv_reg330 -lopencv_rgbd330 -lopencv_saliency330 -lopencv_shape330 -lopencv_stereo330 -lopencv_stitching330 -lopencv_structured_light330 -lopencv_superres330 -lopencv_surface_matching330 -lopencv_text330 -lopencv_tracking330 -lopencv_video330 -lopencv_videoio330 -lopencv_videostab330 -lopencv_xfeatures2d330 -lopencv_ximgproc330 -lopencv_xobjdetect330 -lopencv_xphoto330  'D:\mexopencv-master\opencv_contrib\src\+cv\private\Plot2d_.cpp' 'D:\mexopencv-master\lib\MxArray.obj' 'D:\mexopencv-master\lib\mexopencv_features2d.obj' 'D:\mexopencv-master\lib\mexopencv_ml.obj' 'D:\mexopencv-master\lib\mexopencv_shape.obj' 'D:\mexopencv-master\lib\mexopencv_stitching.obj' 'D:\mexopencv-master\lib\mexopencv_videostab.obj' 'D:\mexopencv-master\opencv_contrib\lib\mexopencv_aruco.obj' -output 'D:\mexopencv-master\opencv_contrib\+cv\private\Plot2d_'
Building with 'Microsoft Visual C++ 2015'.
Error using mex
Plot2d_.cpp
D:\mexopencv-master\opencv_contrib\src\+cv\private\Plot2d_.cpp(45): error C3861: 'createPlot2d': identifier not found
D:\mexopencv-master\opencv_contrib\src\+cv\private\Plot2d_.cpp(50): error C3861: 'createPlot2d': identifier not found
```

Any idea on how to get around this?

PD: I used to work with Visual 2012 compiled files, but Matlab was continuously crashing when trying the first tutorial of mexopencv (exactly, when evaluating cv.CascadeClassifier.detect).

**Comment by wajahat57** [comment]
Hi
I want to report another error. 
It appears that aruco is not in OpenCV 3.3.0 world version. Therefore, I encountered an error: aruco.hpp no such file or directoy. To resolve this, I had to delete arco from include and src folders in opencv_contrib.3.3.0.

**Comment by amroamroamro** [comment]
@wajahat57 that sounds like a different issue, please create a separate report.

**Comment by amroamroamro** [comment]
@JuanVidal could it be that VS2012 is not resolving namespaces correctly here. Try this patch:

``` diff
diff --git a/opencv_contrib/src/+cv/private/Plot2d_.cpp b/opencv_contrib/src/+cv/private/Plot2d_.cpp
index c3666a85..3876342d 100644
--- a/opencv_contrib/src/+cv/private/Plot2d_.cpp
+++ b/opencv_contrib/src/+cv/private/Plot2d_.cpp
@@ -9,7 +9,7 @@
 #include "opencv2/plot.hpp"
 using namespace std;
 using namespace cv;
-using namespace plot;
+using namespace cv::plot;
 
 // Persistent objects
 namespace {
```

**Comment by JuanVidal** [comment]
@amroamroamro thank you for your answer.

I've checked I've got the latest version of mexopencv.

I wasn't able to apply the patch directly because I haven't cloned the repo but downloaded the zip (I'm new to GIT BTW).

So I've manually changed line "-using namespace plot;" but to no avail.

Regards.

**Comment by amroamroamro** [comment]
Oh now I see the problem, you're probably using the dev-version of opencv_contrib, not the expected version 3.3.0

As mentioned at the top of [the installation guide](https://github.com/kyamagu/mexopencv/wiki/Installation-%28Windows%2C-MATLAB%2C-OpenCV-3%29), you MUST build the correct version of BOTH opencv and opencv_contrib, v3.3.0 being the last stable version. dev-versions are not supported here.

I could tell that by looking at the history of the "plot" header file:
https://github.com/opencv/opencv_contrib/commits/master/modules/plot/include/opencv2/plot.hpp
which made some breaking change very recently (after 3.3.0 was released), where `createPlot2d` was replaced with `Plot::create`.

**Comment by JuanVidal** [comment]
Thank you very much @amroamroamro for your kind and quick help. I'm sorry I haven't dropped an answer before but my lab's PC was broken out and had to fix that small issue before fixing this other issue.

I had to redo the entire process, cloned all repositories involved and recompile everything, and after this it I was able to finally run your examples, albeit the second one with some minor errors, which were due to (I hope) not having cleaned before reinstalling and not using Visual C++ as the Matlab compiler, but SDK.

I'm re-recompiling and I hope this time those errors are gone.

Thanks again for your assistance.

**Comment by amroamroamro** [comment]
Glad I could help.

Out of curiosity, what failing example are you talking about?
By my count, we have a little over 180 demos in mexopencv, :

* https://github.com/kyamagu/mexopencv/tree/master/samples
* https://github.com/kyamagu/mexopencv/tree/master/opencv_contrib/samples

I should also mention that I am testing using the latest MATLAB R2017a, so some examples might need to be modified to work on older versions *(this only applies to samples, mexopencv itself should work on any version)*.

**Comment by JuanVidal** [comment]
Sorry, I was refering to examples posted in another repository. Specifically [this](https://github.com/psurya1994/mexopencv-tutorial/tree/master/Tutorial%203%20-%20Camera%20Input), in which, when closing the camera window, some errors appear because Matlab couldn't properly close the handle. The examples you've provided are running very nicely. My thesis project is up and running :)
