### ISSUE TITLE
Error using grabCut: Unrecognized option MaxIter

### ISSUE THREAD

**Issue by KASANA-KKING** [kyamagu/mexopencv#362]
Sir,
I am using the latest version of **mexpoencv** and try to run a code that is designed on an older version. It's working fine on older one but showing error on latest one. It is showing this:

```
Error using grabCut
Unrecognized option MaxIter

Error in demo_edited (line 154)
trimap= cv.grabCut( im_, trimap,'MaxIter',3 );
```

![capture2](https://user-images.githubusercontent.com/26364680/30522992-871872fe-9bf6-11e7-909c-3741987de804.PNG)

**Comment by amroamroamro** [comment]
You should check the [function](https://github.com/kyamagu/mexopencv/blob/master/%2Bcv/grabCut.m) documentation:
http://kyamagu.github.io/mexopencv/matlab/grabCut.html

The option `MaxIter` was renamed `IterCount` some time ago.
Also note that you now set the `Mode` option ("initialize" in first call, then "eval" in subsequent calls).

See [`TestGrabCut.m`](https://github.com/kyamagu/mexopencv/blob/master/test/unit_tests/TestGrabCut.m) for usage examples, and [`grabcut_demo_gui.m`](https://github.com/kyamagu/mexopencv/blob/master/samples/grabcut_demo_gui.m) for a full demo.

**Comment by KASANA-KKING** [comment]
Sir, it will be very helpful if you can tell me, what should be the replacement for above line of code. Because **trimap= cv.grabCut( im_, trimap,'IterCount',3 );** , is giving me error .

And **trimap= cv.grabCut( im_, trimap,'Mode', 'Eval/InitRect','IterCount',3 );** is not giving me result as older version.

**Comment by amroamroamro** [comment]
The replacement call would be:

```matlab
trimap = cv.grabCut(im_, trimap, 'Mode','InitWithMask', 'IterCount',3);
```
