### ISSUE TITLE
OpenCV 3 package was not found in pkg-config search path

### ISSUE THREAD

**Issue by CesMak** [kyamagu/mexopencv#363]
Hey there,
just followed the installation for ubuntu 16.04:

```
sudo apt-get install libopencv-dev

cd ~/Desktop

git clone https://github.com/kyamagu/mexopencv.git

cd mexopencv

export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig

make WITH_OCTAVE=true
```

Getting this error:

> Makefile:78: *** "OpenCV 3 package was not found in pkg-config search path".  Stop.

My outputs are as follows:

> pkg-config --cflags --libs opencv

> -I/usr/include/opencv /usr/lib/x86_64-linux-gnu/libopencv_calib3d.so -lopencv_calib3d /usr/lib/x86_64-linux-gnu/libopencv_contrib.so -lopencv_contrib /usr/lib/x86_64-linux-gnu/libopencv_core.so -lopencv_core /usr/lib/x86_64-linux-gnu/libopencv_features2d.so -lopencv_features2d /usr/lib/x86_64-linux-gnu/libopencv_flann.so -lopencv_flann /usr/lib/x86_64-linux-gnu/libopencv_gpu.so -lopencv_gpu /usr/lib/x86_64-linux-gnu/libopencv_highgui.so -lopencv_highgui /usr/lib/x86_64-linux-gnu/libopencv_imgproc.so -lopencv_imgproc /usr/lib/x86_64-linux-gnu/libopencv_legacy.so -lopencv_legacy /usr/lib/x86_64-linux-gnu/libopencv_ml.so -lopencv_ml /usr/lib/x86_64-linux-gnu/libopencv_objdetect.so -lopencv_objdetect /usr/lib/x86_64-linux-gnu/libopencv_ocl.so -lopencv_ocl /usr/lib/x86_64-linux-gnu/libopencv_photo.so -lopencv_photo /usr/lib/x86_64-linux-gnu/libopencv_stitching.so -lopencv_stitching /usr/lib/x86_64-linux-gnu/libopencv_superres.so -lopencv_superres /usr/lib/x86_64-linux-gnu/libopencv_ts.so -lopencv_ts /usr/lib/x86_64-linux-gnu/libopencv_video.so -lopencv_video /usr/lib/x86_64-linux-gnu/libopencv_videostab.so -lopencv_videostab

> pkg-config --variable pc_path pkg-config

> /usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig

Any ideas?

**Comment by amroamroamro** [comment]
That's because you apt-get installed opencv 2.4.9 (https://packages.ubuntu.com/xenial/libopencv-dev)

    pkg-config --modversion opencv

This is only compatible with the old [v2.4 branch](https://github.com/kyamagu/mexopencv/tree/v2.4) of mexopencv.

---

The current version targets opencv 3.3.0. You'll have to build opencv from source if you want to work with the latest mexopencv. You can find instructions in the wiki:
https://github.com/kyamagu/mexopencv/wiki/Installation-(Linux,-Octave,-OpenCV-3)

**Comment by CesMak** [comment]
Thanks I just followed your more detailed instruction on your wiki page and got it installed correctly.
Thanks :)

**Comment by babahooja** [comment]
I have the same issue, when I run `mexopencv.make` in MATLAB, I get:

```
make MATLABDIR="/Applications/MATLAB_R2016a.app" MEXEXT=mexmaci64 all
/bin/sh: pkg-config: command not found
Makefile:77: *** "OpenCV 3 package was not found in pkg-config search path".  Stop.
```
Running `pkg-config --modversion opencv`, gives the output `3.4.0`
Running `pkg-config --cflags --libs opencv`, gives the output:

```
-I/usr/local/include/opencv -I/usr/local/include -L/usr/local/lib -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_dpm -lopencv_face -lopencv_photo -lopencv_fuzzy -lopencv_hdf -lopencv_img_hash -lopencv_line_descriptor -lopencv_optflow -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_surface_matching -lopencv_tracking -lopencv_datasets -lopencv_text -lopencv_dnn -lopencv_plot -lopencv_xfeatures2d -lopencv_shape -lopencv_video -lopencv_ml -lopencv_ximgproc -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_flann -lopencv_xobjdetect -lopencv_imgcodecs -lopencv_objdetect -lopencv_xphoto -lopencv_imgproc -lopencv_core
```
I am running MacOSX 10.13 High Sierra. Please help.

**Comment by amroamroamro** [comment]
@babahooja please create a separate issue.

Anyway notice this error above:

    /bin/sh: pkg-config: command not found

It seems `pkg-config` was not found. I'm guessing it has to do with interactive shells and your `.bashrc` config file setting up things like `PATH` and `PKG_CONFIG_PATH`. If you wanna check, you can compare by running this in a terminal and inside MATLAB:

    # in a terminal
    $ which pkg-config

    % in MATLAB
    >> system('which pkg-config')

So instead just run `make` directly from a terminal. The `mexopencv.make` in MATLAB was really meant for Windows users (where `make` is not usually available unlike Linux/Mac).

Also it seems you have built opencv + open_contrib, so be sure to run this:

    $ make all contrib

**Comment by ghost** [comment]
> I have the same issue, when I run `mexopencv.make` in MATLAB, I get:
> 
> ```
> make MATLABDIR="/Applications/MATLAB_R2016a.app" MEXEXT=mexmaci64 all
> /bin/sh: pkg-config: command not found
> Makefile:77: *** "OpenCV 3 package was not found in pkg-config search path".  Stop.
> ```
> 
> Running `pkg-config --modversion opencv`, gives the output `3.4.0`
> Running `pkg-config --cflags --libs opencv`, gives the output:
> 
> ```
> -I/usr/local/include/opencv -I/usr/local/include -L/usr/local/lib -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_dpm -lopencv_face -lopencv_photo -lopencv_fuzzy -lopencv_hdf -lopencv_img_hash -lopencv_line_descriptor -lopencv_optflow -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_surface_matching -lopencv_tracking -lopencv_datasets -lopencv_text -lopencv_dnn -lopencv_plot -lopencv_xfeatures2d -lopencv_shape -lopencv_video -lopencv_ml -lopencv_ximgproc -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_flann -lopencv_xobjdetect -lopencv_imgcodecs -lopencv_objdetect -lopencv_xphoto -lopencv_imgproc -lopencv_core
> ```
> 
> It seems mexopencv can't find the location where I installed the build for openCV. I am running MacOSX 10.13 High Sierra. Please help.

hi I have the same problem with you and how u deal with it ? thanks!!
