### ISSUE TITLE
Trying to train HOG classifier with MexOpenCV

### ISSUE THREAD

**Issue by JuanVidal** [kyamagu/mexopencv#366]
Hi.

I've gotten an issue when trying to do what the title suggests. It may be possible that I'm not having adequately configuring this for MexOpenCV, because I'm able to run this on Matlab.

This is what I'm trying for E being a 1024x1280 uint8 image.

```
opts = {'WinSize', [1024 1280], 'BlockSize', [400 400], 'BlockStride', [16 16], 'CellSize', [400 400], 'NBins', 9, 'SignedGradient', true};  % Options for HOG feature
hog = cv.HOGDescriptor(opts{:});
nfeats = hog.compute(E);
```

This has been raising errors like this one (others have appear when modyfing the parameters):

> Unexpected Standard exception from MEX file.
> What() is:C:\dev\opencv\modules\objdetect\src\hog.cpp:90: error: (-215) blockSize.width % cellSize.width == 0
> && blockSize.height % cellSize.height == 0 in function cv::HOGDescriptor::getDescriptorSize
> 
> ..
> 
> Error in cv.HOGDescriptor/compute (line 332)
>             descs = HOGDescriptor_(this.id, 'compute', im, varargin{:});
> 
> Error in Code_HOG_Eye (line 20)
> nfeats = numel(hog.compute(E));

Any help would be appreciated.

Best regards.

**Comment by amroamroamro** [comment]
**This is really an opencv usage question, [OpenCV Q&A][3] is a better place to ask.**

So it looks like you have a non-working combination of HOGDescriptor options. The sizes and strides must satisfy certain conditions; If I'm not mistaken, WinSize must align with both BlockSize & BlockStride, which are in turn multiples of CellSize.

See the docs of [`help cv.HOGDescriptor.getDescriptorSize`][1] method for an intuition about cells/blocks/windows:

> https://github.com/kyamagu/mexopencv/blob/master/%2Bcv/HOGDescriptor.m#L231-L249

For the sliding windows, see the docs of [`help cv.HOGDescriptor.compute`][2] method:

> https://github.com/kyamagu/mexopencv/blob/master/%2Bcv/HOGDescriptor.m#L307-L319

You seem to be using one big window to cover the whole image, so WinStride won't matter here. But You might need to resize/pad your image if its size is not compatible with window/block/cell sizes.

For example:

``` matlab
>> img = randi(256, [1024 1024], 'uint8');
>> hog = cv.HOGDescriptor('WinSize',[1024 1024], 'BlockSize',[256 256], 'BlockStride',[128 128], 'CellSize',[128 128]);
>> hog.getDescriptorSize()
ans =
        1764
>> size(hog.compute(img))
ans =
           1        1764
```

[1]: https://kyamagu.github.io/mexopencv/matlab/HOGDescriptor.getDescriptorSize.html
[2]: https://kyamagu.github.io/mexopencv/matlab/HOGDescriptor.compute.html
[3]: http://answers.opencv.org/questions/

**Comment by amroamroamro** [comment]
The implementation of HoG is a bit tricky, but here is my understanding of the idea..

Basically you have a detection window (WinSize) that is sliding over the image (WinStride). The window is divided into cells (CellSize) where histograms of gradient directions (NBins) are computed in each cell. Histograms are grouped into blocks of cells (BlockSize), and normalized over overlapping blocks (BlockStride). The descriptors are flattened to form a feature vector, then the combined vectors from all sliding window are returned as the final result.

Hence CellSize somewhat controls the resolution of details HOG captures, while BlockSize controls the normalization of cell histograms for invariant against local change in illumination. The BlockStride produces overlapping blocks with more info, but increases the feature vector size. WinSize is determined by the object detection task at hand and dataset. WinStride along with Scale affect the accuracy and speed of the detector when running at multiple scales (image pyramid).

I found this nice visualization of HOG:

![hog](https://user-images.githubusercontent.com/83908/31983204-fadf47ae-b964-11e7-8fc4-3977b368d4b1.jpg)

Ultimately you should refer to the reference paper for full details:
> https://hal.inria.fr/inria-00548512

**Comment by JuanVidal** [comment]
Thank you very much. It really helped me a lot.

After having some clarification on the meaning of each parametric option, I was able to make it work using MexOpenCV.

Kudos.
