### ISSUE TITLE
Error LNK2019: unresolved external symbol

### ISSUE THREAD

**Issue by ale152** [kyamagu/mexopencv#370]
Hello!

I'm trying to compile mexopencv on windows.
I followed the instructions on the wiki, downloaded opencv, compiled and ran mexopencv.make.

After compiling most of the files, matlab stops here:

```
Error using mex
Creating library
   *******\matlab_opencv\mexopencv-master\opencv_contrib\+cv\private\BoostDesc_.lib
and object
   *******\matlab_opencv\mexopencv-master\opencv_contrib\+cv\private\BoostDesc_.exp
BoostDesc_.obj : error LNK2019: unresolved external symbol
"struct cv::Ptr<class cv::xfeatures2d::BoostDesc> __cdecl createBoostDesc(class std::_Vector_const_iterator<class std::_Vector_val<struct std::_Simple_types<class MxArray> > >,class std::_Vector_const_iterator<class std::_Vector_val<struct std::_Simple_types<class MxArray> > >)"
(?createBoostDesc@@YA?AU?$Ptr@VBoostDesc@xfeatures2d@cv@@@cv@@V?$_Vector_const_iterator@V?$_Vector_val@U?$_Simple_types@VMxArray@@@std@@@std@@@std@@0@Z)
referenced in function mexFunction
*******\matlab_opencv\mexopencv-master\opencv_contrib\+cv\private\BoostDesc_.mexw64 : fatal error
LNK1120: 1 unresolved externals
```

I'm using Windows 7, MATLAB Version: 9.2.0.538062 (R2017a), Opencv 3.3.0 and Visual Studio 2013.

**Comment by amroamroamro** [comment]
A list of things to check:

- make sure you checked out version 3.3.0 of opencv **AND** opencv_contrib (the same version of both repos)
- make sure you are building opencv+opencv_contrib and mexopencv all using the same compiler (VS2013 in your case)
- make sure that you enabled contributed modules in the make call:

      >> mexopencv.make('opencv_path','...', 'opencv_contrib',true)

  *(Note: if you had previously started running `mexopencv.make` without that last option specified, it might not get picked properly in later runs, you must start over by first doing: `mexopencv.make('clean',true)`)*
