### ISSUE TITLE
mexopencv.make doesnt work

### ISSUE THREAD

**Issue by junsubae** [kyamagu/mexopencv#371]
Hi. I am not good at this thing  and I couldnt figure what is wrong

I followed this video.

https://www.youtube.com/watch?v=X3yi9vyY-WI

I am using visual studio 2017 community and MATLAB R2017b

And I got that message

```
다음 사용 중 오류가 발생함: mexopencv.make>pkg_config (line 324)
OpenCV library path not found: C:\opencv\build\x64\vc15\lib

오류 발생: mexopencv.make>mex_options (line 264)
    [cv_cflags, cv_libs] = pkg_config(opts);

오류 발생: mexopencv.make (line 81)
    mex_flags = mex_options(opts);
```

plz help me... I hav to use this...

and sorry that my English is so bad

**Comment by amroamroamro** [comment]
Follow the instructions in the wiki:

> https://github.com/kyamagu/mexopencv/wiki/Installation-(Windows,-MATLAB,-OpenCV-3)

The official opencv installer doesn't includes binaries for VS2017, you'll have to compile opencv from source as shown. Make sure to use the correct opencv version as explained.
