### ISSUE TITLE
Unable to find correct path

### ISSUE THREAD

**Issue by snphnolt** [kyamagu/mexopencv#372]
Hi,
I followed the instructions, but when I tried to initiate mexopencv.make MATLAB gave me this exception:
OpenCV library path not found:
C:\dev\build\install\x64\vc12\lib

Which is strange since I build OpenCV using VS 2015 and OpenCV 3.3.0. When I checked the the folders th e path C:\dev\build\install\x64\vc14 exists.

Any Idea why the path is wrong ?

Thank you in advance.

**Comment by amroamroamro** [comment]
Check which compiler is configured in MATLAB:

    >> mex -setup C++

make sure you select the same compiler used for building opencv (VS2015 in your case).

**Comment by snphnolt** [comment]
Thank you very much that seemed to be working.
