### ISSUE TITLE
Error using mex function

### ISSUE THREAD

**Issue by tehreem1** [kyamagu/mexopencv#373]
I am using MATLAB (2015a) on Windows 10 (64 bit) system with visual studio 2012 and mexopencv 3.0. When I use function 

`M = cv.estimateRigidTransform(cell1, cell2);`

it shows following error:

Error using estimateRigidTransform, MxArray is not a cv::Point

what is its reason and solution?

**Comment by amroamroamro** [comment]
The [function](http://kyamagu.github.io/mexopencv/matlab/estimateRigidTransform.html) expects two point sets, both expressed as cell-arrays of 2D points, i.e `{[x1 y1], [x2 y2], ..}`.

Check that your cells are indeed all cell-arrays of 2-element vectors. In other words the following must be true:

```matlab
assert(iscell(pts1));
for i=1:numel(pts1)
    p = pts1{i};
    assert(isnumeric(p) && numel(p)==2);
end
```

same thing for `pts2`, given `M = cv.estimateRigidTransform(pts1, pts2);`

**Comment by tehreem1** [comment]
yes I figured it out, it worked
thanks
