### ISSUE TITLE
Ransac with findHomography function

### ISSUE THREAD

**Issue by surendra1234sharma** [kyamagu/mexopencv#379]
How to use Ransac and other options (mentioned here http://kyamagu.github.io/mexopencv/matlab/findHomography.html) in findHomography function

I am using [H,mask] = cv.findHomography(vp1,vp2,'Method',Ransac); and getting error
Undefined function or variable 'Ransac'

**Comment by amroamroamro** [comment]
You should pass a string, i.e:

    [H, mask] = cv.findHomography(p1, p2, 'Method','Ransac');

**Comment by surendra1234sharma** [comment]
Thanks a lot...
