### ISSUE TITLE
How can I cite your work?

### ISSUE THREAD

**Issue by snphnolt** [kyamagu/mexopencv#380]
Hi, 

I used your orb-function for my research. How can I give you credit in my thesis?

**Comment by kyamagu** [comment]
@snphnolt you can cite [github URL](https://github.com/kyamagu/mexopencv), thanks

**Comment by amroamroamro** [comment]
@snphnolt 
PS if you also want to cite OpenCV:
http://answers.opencv.org/question/32411/opencv-bibtex-citation/
