### ISSUE TITLE
Weird results when using cv.calcOpticalFlowFarneback

### ISSUE THREAD

**Issue by ChongYunPeng** [kyamagu/mexopencv#382]
I was comparing the results of `calcOpticalFlowFarneback` implemented using Matlab and C++ and found that the values generated were very different. I was wondering if I had made a mistake somewhere.

`prev` and `next` are from the same images for both cases.

**Matlab**
```matlab
flow = cv.calcOpticalFlowFarneback(prev, next, 'PyrScale', 0.5, 'Levels', 3, 'WinSize', 15,'Iterations', 3, 'PolyN', 5, 'PolySigma', 1.2);
disp(flow(1,1,1))
```

**C++** 
```cpp
cv::calcOpticalFlowFarneback(prev, next, flow, 0.5, 3, 15, 3, 5, 1.2, 0);
cout << flow.at<float>(0,0,0) << endl;
```

My Python implementation gives the same results as the C++ one.

**Comment by amroamroamro** [comment]
You are not passing the same options:

- In MATLAB: `..., 'Iterations', 5, 'PolyN', 3, ...`
- In C++: `..., /*iterations*/ 3, /*polyN/* 5, ...`

See the function signature:
https://docs.opencv.org/3.4.0/dc/d6b/group__video__track.html#ga5d10ebbd59fe09c5f650289ec0ece5af

**Comment by amroamroamro** [comment]
Here's a full example that compares C++, Python, and MATLAB:

## C++
```cpp
#include "opencv2/opencv.hpp"
#include <iostream>
using namespace std;
using namespace cv;

int main()
{
  Mat prev = imread("RubberWhale1.png", IMREAD_GRAYSCALE);
  Mat next = imread("RubberWhale2.png", IMREAD_GRAYSCALE);

  double pyrScale = 0.5;
  int levels = 3;
  int winsize = 15;
  int iterations = 3;
  int polyN = 5;
  double polySigma = 1.2;
  int flags = 0;
  Mat flow;
  calcOpticalFlowFarneback(prev, next, flow,
    pyrScale, levels, winsize, iterations, polyN, polySigma, flags);

  cout << "size = " << flow.size() << ", cn = " << flow.channels() << endl;
  cout << "flow(0,0,:) = " << flow.at<Vec2f>(0,0) << endl;

  return 0;
}
```

### Output
```
size = [584 x 388], cn = 2
flow(0,0,:) = [0.461871, 0.435717]
```

---

## Python
```python
import cv2 as cv

prev = cv.imread("RubberWhale1.png", cv.IMREAD_GRAYSCALE);
next = cv.imread("RubberWhale2.png", cv.IMREAD_GRAYSCALE);

flow = cv.calcOpticalFlowFarneback(prev, next, None,
  pyr_scale=0.5, levels=3, winsize=15, iterations=3,
  poly_n=5, poly_sigma=1.2, flags=0)

print flow.shape
print flow[0,0,:]
```

### Output
```
(388, 584, 2)
[ 0.4618707   0.43571693]
```

---

## MATLAB
```matlab
prev = cv.imread(which('RubberWhale1.png'), 'Grayscale',true);
next = cv.imread(which('RubberWhale2.png'), 'Grayscale',true);

opts = {
    'PyrScale',0.5, ...
    'Levels',3, ...
    'WinSize',15, ...
    'Iterations',3, ...
    'PolyN',5, ...
    'PolySigma',1.2
};
flow = cv.calcOpticalFlowFarneback(prev, next, opts{:});

size(flow)
flow(1,1,:)
```

### Output
```
>> whos flow
  Name        Size                 Bytes  Class     Attributes
  flow      388x584x2            1812736  single              

>> flow(1,1,:)
  1×1×2 single array
ans(:,:,1) =
    0.4619
ans(:,:,2) =
    0.4357
```

---

I tested the above in v3.4.0 (a work-in-progress mexopencv version I'm going to release soon), but the same should hold in v3.3.1

**Comment by ChongYunPeng** [comment]
Thanks for putting in the sample code as well.

I figured out the mistake. Apparently these two lines of code are not the same thing:

`next = rgb2gray(imread('RubberWhale2.png'));`
`next = cv.imread('RubberWhale2.png', 'Grayscale',true);`

**Comment by amroamroamro** [comment]
yep, rgb2gray might not give bit-exact same results as opencv conversion (due to rounding error an other implementation differences), but I don't think the difference would be big enough to be significant...

Also if the image is in a lossy format like JPEG, then it is not guaranteed to be decoded bit-exactly the same by matlab's `imread` and opencv's `cv.imread`. PNG images shouldn't have that problem.

Your **real mistake** however was passing 3 and 5 in one code, while 5 and 3 in another (see my first comment).

**Comment by ChongYunPeng** [comment]
Oh that mistake was just a typo here. I didn't have the same mistake in my code.

Chaning from imread to cv.imread solved the problem though.

**Comment by ChongYunPeng** [comment]
Maybe you could try running the following:
```matlab
prev = rgb2gray(imread('RubberWhale1.png'));
next = rgb2gray(imread('RubberWhale2.png'));

% prev = cv.imread('RubberWhale1.png', 'Grayscale',true);
% next = cv.imread('RubberWhale2.png', 'Grayscale',true);

flow = cv.calcOpticalFlowFarneback(prev, next, ...
    'PyrScale', 0.5, 'Levels', 3, 'WinSize', 15,...
    'Iterations', 3, 'PolyN', 5, 'PolySigma', 1.2);

flow(1,1,1)
```

I got different results depending on which imread i used, which I thought was really weird.

**Comment by amroamroamro** [comment]
As I already stated, the color-to-grayscale conversion produces slightly different results between matlab and opencv:

- [rgb2gray](https://www.mathworks.com/help/matlab/ref/rgb2gray.html#buiz8mj-9)
- [cvtColor](https://docs.opencv.org/master/de/d25/imgproc_color_conversions.html)

This is attributed to differences in implementation and floating-point rounding errors.
(e.g opencv working in CV_32F precision, while MATLAB working in double-precision).

So when you call `calcOpticalFlowFarneback`, you can't expect getting exactly the same output given different inputs!

That said, the differences should be negligible. If you visualize the optical flow, you should see a similar thing in the big picture. We have several samples that demonstrate optical flow visualization:

- samples/opt_flow_demo.m
- samples/tvl1_optical_flow_demo.m
- samples/fback_demo.m
- opencv_contrib/samples/optical_flow_evaluation_demo.m

**Comment by ChongYunPeng** [comment]
Got it! Thanks for your help.
