### ISSUE TITLE
permission problem when using mexopencv.make

### ISSUE THREAD

**Issue by LiangJiong** [kyamagu/mexopencv#384]
Hi, Ｉhave downloaded opencv3.3.1 and mexopencv-master and put then at some folder. And I began to use `mexopencv.make` command. but some problem was told:

```
>> mex -O -largeArrayDims   -I'C:\Program Files\MATLAB\Lib\mexopencv-master\include' -I'C:\Program Files\MATLAB\Lib\opencv\build\include' -L'C:\Program Files\MATLAB\Lib\opencv\build\x64\vc12\lib'  -lopencv_world331  -c 'C:\Program Files\MATLAB\Lib\mexopencv-master\src\MxArray.cpp' -outdir 'C:\Program Files\MATLAB\Lib\mexopencv-master\lib'
please determine that you have the right to visit 'C:\Program Files\MATLAB\Lib\mexopencv-master\lib'
```

the folder exists and with `.gitkeep` only 0 bytes. 

Can you tell me how to solve the problem . Waiting.... Thanks.

**Comment by amroamroamro** [comment]
It is advised against installing mexopencv inside `C:\Program Files`. This is a protected folder, and you will be denied write-access unless you run MATLAB itself as admin or turn off Windows UAC, but neither of these things is the right thing to do...

Just use another folder with normal user permissions, for example something under `C:\Users\<username>`.

**Comment by LiangJiong** [comment]
Thanks, amroamroamro . I have resolved these problem by what you said. I appreciate you for that.

**Comment by LiangJiong** [comment]
When I try to load the command cv.imread('a1.jpg') in the folder of ' \mexopencv-master' , Some problem happens, just like the following:

MEX-file 'C:\DV\mexopencv-master\+cv\imread.mexw64'  invade: can't find the opencv_world331.dll
'C:\DV\mexopencv-master\+cv\imread.mexw64' needs 'opencv_world331.dll'. 
'C:\Program Files\MATLAB\R2017b/bin/win64\VCRUNTIME140.dll->C:\Program Files\MATLAB\R2017b/bin/win64\MSVCP140.dll->C:\Program
Files\MATLAB\R2017b/bin/win64\libmwresource_core.dll->C:\Program Files\MATLAB\R2017b/bin/win64\libmwi18n.dll->C:\Program
Files\MATLAB\R2017b/bin/win64\libmx.dll->C:\DV\mexopencv-master\+cv\imread.mexw64' needs 'KERNEL32.dll'. 

What does make the problem ? How to resolve it?
Thanks.

**Comment by amroamroamro** [comment]
did you add the OpenCV binaries folder to the PATH environment variable?

    C:\path\to\opencv\build\x64\vc14\bin

replace with the correct path and the VS compiler version you're using..

---

PS: we have detailed build instructions in the wiki
https://github.com/kyamagu/mexopencv/wiki/Installation-(Windows,-MATLAB,-OpenCV-3)

**Comment by LiangJiong** [comment]
Hi, Amro. If I would like to change the compiler from C++ 2013 to C++2015. How can I do? I have installed the visual studio 2015 in my computer. But the mex -setup shows still C++2013.

**Comment by LiangJiong** [comment]
Hi, Amro.　I checked the PATH environment variable, and truely the OpenCV binary  folder have been set up ,just like "C:\MATLABPlugIns\opencv\build\x64\vc12\bin". But still the same problem appears when I tried to run cv.imread('a1.jpg') under the 'mexopencv' folder. If I have to do some other setting for the opencv binary folder? Thanks.

**Comment by LiangJiong** [comment]
I know how to change the compiler for c++. Thanks.

**Comment by amroamroamro** [comment]
I need you to be more specific and provide more info:

- what versions are you using? Windows, Visual Studio, MATLAB, OpenCV
- which opencv are you using? did you download the installer of prebuilt binaries? or did you build it from source?
- where is opencv installed?
- are you using opencv_contrib as well? if so which version?
- how did you compile mexopencv? what is the exact call you used for `mexopencv.make`?
- what compiler is configured in matlab? i.e `mex -setup` and `mex -setup C++`

Run the following commands in MATLAB and post the output:

```matlab
>> regexp(getenv('PATH'), pathsep(), 'split')'
>> path

% replace this with the correct location to opencv
>> !tree /F "C:\path\to\opencv\build\x64"
```

If possible, can you also run `cv.getBuildInformation` in matlab and post the results

**Comment by LiangJiong** [comment]
Hi, Amro. Thanks for your answer. I am  trying to do as the installation said step by step. I set the folder " C:/MATLABPlugIns" to let all the downloaded files in it. But when I run  Cmake to cofigure , a problem I can't bypass, just like:


"
Could NOT find Pylint (missing: PYLINT_EXECUTABLE) 
CMake Error at cmake/OpenCVModule.cmake:270 (foreach):
  Syntax error in cmake code at

    C:/MATLABPlugIns/opencv/cmake/OpenCVModule.cmake:270

  when parsing string

    C:/MATLABPlugIns/opencv/modules;EXTRA;C:\MATLABPlugIns\opencv_contrib\modules

  Invalid escape sequence \M
Call Stack (most recent call first):
  modules/CMakeLists.txt:7 (ocv_glob_modules) "

**Comment by LiangJiong** [comment]
Also, In this step:
"under "BUILD" group, deselect the following:
BUILD_DOCS, BUILD_EXAMPLES, BUILD_PACKAGE, BUILD_PERF_TESTS, BUILD_TESTS
BUILD_opencv_apps, BUILD_opencv_cuda*, BUILD_opencv_cudev, BUILD_opencv_java, BUILD_opencv_python*, BUILD_opencv_ts, BUILD_opencv_viz, BUILD_opencv_world"

I can't find  "BUILD_opencv_cuda*, BUILD_opencv_cudev, BUILD_opencv_java, BUILD_opencv_python*,BUILD_opencv_viz"

**Comment by LiangJiong** [comment]
I choose the compiler is C++2013

**Comment by LiangJiong** [comment]
Also Could NOT find LAPACK. What is LAPACK. If can I deselect it？

**Comment by LiangJiong** [comment]
it seems that I can't use the opencv_contrib

**Comment by LiangJiong** [comment]
Fine， Amro. I have completed the installation for the opencv. It's OK. But only opencv_contrib，I dare not to try its installation. Some problem in it ? Thanks for your advice again.

**Comment by amroamroamro** [comment]
> Could NOT find LAPACK

OpenCV has many optional dependencies, so it's normal if it prints that something was not found. That's an informational message, not an error.

> I can't find "BUILD_...."

if something is not listed, ignore it. It probably means you don't have it anyway (like CUDA, Java, Python, etc.)

> Invalid escape sequence \M

This error is probably caused by the path you specified in `OPENCV_EXTRA_MODULES_PATH`, you have to use forward slashes in the path, i.e: `C:/MATLABPlugIns/opencv_contrib/modules`.

**Comment by LiangJiong** [comment]
OK， Thanks, Amro. I will try it again just like what you said.
