### ISSUE TITLE
error: OpenCV library path not found

### ISSUE THREAD

**Issue by NIDHIPANDA** [kyamagu/mexopencv#385]
Hello I am using Matlab 2015a ,visual stdio 2015 , openCV and openCV contribution 3.3.1

In the final step while running 
`mexopencv.make('opencv_path','C:\opencv\build\install', 'opencv_contrib',true)`
I am getting this error.

```
Error using mexopencv.make>pkg_config (line 325)
OpenCV library path not found: C:\opencv\build\install\x64\vc10\lib

Error in mexopencv.make>mex_options (line 265)
    [cv_cflags, cv_libs] = pkg_config(opts);

Error in mexopencv.make (line 82)
    mex_flags = mex_options(opts);
```

My `C:\opencv\build\install` folder includes `\x86\vc14` not the `\x64\vc10`.  I really appreciate if somebody helps me.  Thank you

**Comment by amroamroamro** [comment]
two things:

- make sure you first run `mex -setup` in MATLAB, and select the same compiler you used to build opencv. I assume you have multiple versions of Visual Studio installed, maybe VS2010 and VS2015?

- you must have built the 32-bit version of opencv instead of the 64-bit version.
So in this image from the [wiki][1], notice it says "**x64** Release mode" at the top.
Obviously you can't use 32-bit binaries in 64-bit matlab.
![][2]

[1]: https://github.com/kyamagu/mexopencv/wiki/Installation-%28Windows%2C-MATLAB%2C-OpenCV-3%29#compile-opencv
[2]: https://camo.githubusercontent.com/7c12921145d29160678456c373b9e8f5af8ab982/687474703a2f2f692e696d6775722e636f6d2f3251766d504e502e706e67

**Comment by NIDHIPANDA** [comment]
Thank you for your response.
I tried mex -setup in MATLAB it is showing " MEX configured to use 'Microsoft Visual C++ 2015 (C)' for C language compilation." Also on following your second suggestion "When you run CMake, make sure to select the right generator, i.e "Visual Studio 14 2015 Win64""  I was able to successfully build in Visual studio. But the error is now also same i.e.  

Error using mexopencv.make>pkg_config (line 325)
OpenCV library path not found: C:\opencv\build\install\x64\vc10\lib

Error in mexopencv.make>mex_options (line 265)
    [cv_cflags, cv_libs] = pkg_config(opts);

Error in mexopencv.make (line 82)
    mex_flags = mex_options(opts);
 
I have already uninstalled the visual stdio 10.

**Comment by amroamroamro** [comment]
You should do both `mex -setup` and `mex -setup C++` for C and C++ compilers respectively.

**Comment by NIDHIPANDA** [comment]
I tried both in both of the command it is detection VS15 only.
![capture_1](https://user-images.githubusercontent.com/23721905/35745573-f304dca2-0800-11e8-80b8-92f146e21f6e.JPG)

**Comment by amroamroamro** [comment]
That's weird, if VS2015 is configured as compiler, how come it still picks `vc10`?

Can you run this in MATLAB and post the output:
```matlab
>> cc = mex.getCompilerConfigurations('C++', 'Selected');
>> disp(cc)
```

**Comment by NIDHIPANDA** [comment]
Sorry for my late reply. I tried your suggested command. The output is 
![test](https://user-images.githubusercontent.com/23721905/35851207-84d27ffa-0ae4-11e8-8ac2-33275b405358.JPG)
Now it is not take visual stdio 10 but now the error is 
![test2](https://user-images.githubusercontent.com/23721905/35851624-cde93606-0ae5-11e8-8dac-00c0bf39747d.JPG)
One more thing I noticed that in my build-install  folder  there is no bin folder created. 
![test3](https://user-images.githubusercontent.com/23721905/35851837-72a42eb2-0ae6-11e8-99f0-2dd75d053f16.JPG).

**Comment by amroamroamro** [comment]
Seeing the above images, you passed the wrong path, it should be:

```matlab
>> mexopencv.make('opencv_path','C:\opencv\build\install', 'opencv_contrib',true)
```

Please follow the installation instructions more carefully:
https://github.com/kyamagu/mexopencv/wiki/Installation-(Windows,-MATLAB,-OpenCV-3)

---

Now just to be clear, you must build opencv and mexopencv all using the same compiler with the same architecture, this means compiling both as x64 in VS2015.

Seeing your previous comments, you once had VS2010 vs VS2015, you were also mixing 32-bit and 64-bit binaries... So first thing is make sure you're using the correct configuration. Run this in MATLAB and post the output here:

```matlab
>> !tree /F "C:\opencv\build\install\x64"
```
