### ISSUE TITLE
Problem with "make" in Matlab

### ISSUE THREAD

**Issue by marcomessina25** [kyamagu/mexopencv#386]
Hello,
I followed step by step the procedure for installing mexopencv. Everything went just fine with CMake and Visual Studio 2015. 
But the following error occurred with the `make` command in MATLAB:

```
mexopencv.make('opencv_path','C:\opencv331\build\install\','opencv_contrib',true)

Error using mex
   Creating library
   C:\opencv331\mexopencv-master\opencv_contrib\+cv\private\BoostDesc_.lib
   and object
   C:\opencv331\mexopencv-master\opencv_contrib\+cv\private\BoostDesc_.exp
   BoostDesc_.obj : error LNK2019: unresolved external symbol "struct
   cv::Ptr<class cv::xfeatures2d::BoostDesc> __cdecl
   createBoostDesc(class std::_Vector_const_iterator<class
   std::_Vector_val<struct std::_Simple_types<class MxArray> > >,class
   std::_Vector_const_iterator<class std::_Vector_val<struct
   std::_Simple_types<class MxArray> > >)"
   (?createBoostDesc@@YA?AU?$Ptr@VBoostDesc@xfeatures2d@cv@@@cv@@V?$_Vector_const_iterator@V?$_Vector_val@U?$_Simple_types@VMxArray@@@std@@@std@@@std@@0@Z)
   referenced in function mexFunction
C:\opencv331\mexopencv-master\opencv_contrib\+cv\private\BoostDesc_.mexw64
: fatal error LNK1120: 1 unresolved externals
```

The error did not occur immediately, it occurred after a while. 
It generated a lot of mex64 files, but it did not finish the process.

Could you please help me figuring out what went wrong?
Thank you all a lot 

Note: I am using Visual Studio 2015, MATLAB 2017a with the Visual Studio 2015 selected as default compiler, Windows 7.

**Comment by amroamroamro** [comment]
Did you previously run the command `mexopencv.make()` without specifying `'opencv_contrib',true` in the options?

I suspect you have stale .obj files, compiled without contrib support...

To quote the README file:

> If you have previously compiled mexopencv with a different configuration,
> don't forget to clean old artifacts before building:
>
>     >> mexopencv.make('clean',true, 'opencv_contrib',true)

**Comment by marcomessina25** [comment]
That helped, thank you.
I did not run the command mexopencv.make() without options, but I have had a first run of Cmake without specifying the opencv_contrib/modules 
To fix that I cleaned up the whole directory and I repeated the "download/cmake/visual studio compile/mexopencv.make" procedure.
Thank you again

**Comment by amroamroamro** [comment]
right, if you want to use the contrib modules in mexopencv,
you must build both opencv + opencv_contrib.
