### ISSUE TITLE
Error: use of undeclared identifier 'EMDL1'

### ISSUE THREAD

**Issue by hoonkai** [kyamagu/mexopencv#387]
I'm trying to compile `mexopencv` (3.3.1) on OS X. I've already compiled `opencv` (3.4.0) and that went flawlessly. However, after I run `make`, I get the following:

```
Building with 'LLVM Clang++ OpenMP'.
/Volumes/Data/Projects/mexopencv/src/+cv/EMDL1.cpp:30:15: error: use of undeclared identifier 'EMDL1'
    float d = EMDL1(signature1, signature2);
              ^
1 error generated.

make: *** [+cv/EMDL1.mexmaci64] Error 255
```

Isn't `EMDL1` in the `opencv_shape` module? Here's my `pkg-config` output:

```
$ pkg-config --cflags --libs opencv
-I/usr/local/include/opencv -I/usr/local/include -L/usr/local/lib -lopencv_dnn -lopencv_ml -lopencv_objdetect -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_video -lopencv_photo -lopencv_img_hash -lopencv_line_descriptor -lopencv_stereo -lopencv_ximgproc -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_imgproc -lopencv_flann -lopencv_core
```

The default `Libs` doesn't include `opencv_shape` though. Should it be explicitly included? I've tried adding `-lopencv_shape`, but I still get the same error.

**Comment by amroamroamro** [comment]
> trying to compile mexopencv (3.3.1) on OS X [...] already compiled opencv (3.4.0) [..]

mexopencv releases are targeted at the corresponding opencv release.
Therefore you must build mexopencv 3.3.1 against opencv 3.3.1
(PS: we are in the process of updating mexopencv to 3.4.0, we're just running a bit behind)

> Isn't `EMDL1` in the opencv_shape module?

Yes it is. Did you disable the "shape" module when building opencv?

    -lopencv_calib3d
    -lopencv_core
    -lopencv_dnn
    -lopencv_features2d
    -lopencv_flann
    -lopencv_highgui
    -lopencv_img_hash  <--
    -lopencv_imgcodecs
    -lopencv_imgproc
    -lopencv_line_descriptor  <--
    -lopencv_ml
    -lopencv_objdetect
    -lopencv_photo
    -lopencv_stereo  <--
    -lopencv_stitching
    -lopencv_superres
    -lopencv_video
    -lopencv_videoio
    -lopencv_videostab
    -lopencv_ximgproc  <--

Looking at the modules list, you seem to have built opencv + some parts of opencv_contrib but not others.
Our build scripts (Makefile and make.m) do not support selectively picking modules, it's all-in or nothing (i.e you either enable all of opencv_contrib or none of it):

```sh
# with opencv_contrib
$ make all contrib

# without opencv_contrib
$ make all
```

Similarly when it comes to the main modules, you gotta have all of them enabled, which is the default anyway (note that optional ones like cuda, ts, and viz are disabled by default and not used in mexopencv).

So the question now is **how did you build opencv (and opencv_contrib)?**
You should share the output of CMake during configuration.

**Comment by amroamroamro** [comment]
We haven't written instructions in the wiki explicitly for OSX (help is welcome), but it should be similar to the [Linux case](https://github.com/kyamagu/mexopencv/wiki/Installation-%28Linux%2C-Octave%2C-OpenCV-3%29#2-opencv) when manually building from source:

```sh
$ cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DOPENCV_ENABLE_NONFREE=ON -DOPENCV_EXTRA_MODULES_PATH=~/cv/opencv_contrib-3.3.1/modules ~/cv/opencv-3.3.1
```

Otherwise the recommend way is using Homebrew to build/install [opencv](https://github.com/Homebrew/homebrew-core/blob/master/Formula/opencv.rb). I don't use a mac, but I imagine it's something like:

    $ brew install opencv3 --with-contrib

Of course for the time being, you'll have to install the expected version 3.3.1 instead of the latest 3.4.0
Here's a blog post explaining how you can do that: http://zoltanaltfatter.com/2017/09/07/Install-a-specific-version-of-formula-with-homebrew/

**Comment by hoonkai** [comment]
@amroamroamro I have now rebuilt using 3.3.1 with all modules:

```
--   OpenCV modules:
--     To be built:                 core flann imgproc ml objdetect phase_unwrapping photo plot reg surface_matching video xphoto bgsegm dnn face fuzzy img_hash imgcodecs shape videoio xobjdetect highgui superres bioinspired dpm features2d line_descriptor saliency text calib3d ccalib datasets rgbd stereo structured_light tracking videostab xfeatures2d ximgproc aruco java optflow stitching python2
--     Disabled:                    js world contrib_world
--     Disabled by dependency:      -
--     Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev python3 ts viz cnn_3dobj cvv dnn_modern freetype hdf matlab sfm
--
```

I can build `mexopencv` successfully:

```
$ls lib
MxArray.o              mexopencv_features2d.o mexopencv_shape.o      mexopencv_videostab.o
libMxArray.a           mexopencv_ml.o         mexopencv_stitching.o
```

However, I now keep getting this error in Matlab:

```
>> mex private/getFeatures.cpp -outdir private '-DUSEOMP' CXXFLAGS="\$CXXFLAGS -fopenmp" LDFLAGS="\$LDFLAGS -fopenmp -L/usr/local/lib" -I/usr/local/include/opencv -I/usr/local/include -I/Volumes/Data/Projects/mexopencv/include -lopencv_ximgproc -lopencv_core -lMxArray -L/Volumes/Data/Projects/mexopencv/lib

Building with 'LLVM Clang++ OpenMP'.
Error using mex
Undefined symbols for architecture x86_64:
  "cv::Moments::Moments(double, double, double, double, double, double, double, double, double,
  double)", referenced from:
      MxArray::toMoments(unsigned long) const in libMxArray.a(MxArray.o)
ld: symbol(s) not found for architecture x86_64
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
```
Any idea why this is the case?
