### ISSUE TITLE
Corrupt string printed

### ISSUE THREAD

**Issue by munum** [kyamagu/mexopencv#389]
Hi

I'm following [this tutorial](https://docs.opencv.org/master/d2/d59/tutorial_ximgproc_training.html#gsc.tab=0) and working with `RFFeatureGetter`.  When I run the following mex function, a corrupt string is printed and then Matlab (2017b) crashes:

```
#include <cv.h>
#include <highgui.h>
#include <mat.h>
#include <mex.h>
#include "MxArray.hpp"

MEXFUNCTION_LINKAGE void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    if (nlhs != 1) mexErrMsgTxt("nlhs != 1");
    if (nrhs != 1) mexErrMsgTxt("nrhs != 1");
    cv::Mat src = MxArray(prhs[0]).toMat();
    src.convertTo(src, cv::DataType<float>::type);
    std::string modelFile = MxArray(prhs[1]).toString();
    NewRFFeatureGetter *pDollar = RFFeatureGetter();
    cv::String n = pDollar->name;
    mexPrintf("String output: %s\n", n.c_str());
    cv::Mat edges;
    pDollar->getFeatures(src, edges, 4, 0, 2, 13, 4);
    // you can use other numbers here
    edges.convertTo(edges, cv::DataType<double>::type);
    plhs[0] = MxArray(edges);
}
```
(`RFFeatureGetter.name` is set to public here)

I'd expect the output to be `RFFeatureGetter`, but I get `­¾¡S8ÝºÀ:Ga` instead. I'm running opencv 3.3.0 and mexopencv 3.3.0.

Similarly, if I run another function:

```
MEXFUNCTION_LINKAGE void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    if (nlhs != 1) mexErrMsgTxt("nlhs != 1");
    if (nrhs != 1) mexErrMsgTxt("nrhs != 1");
    cv::Mat src = MxArray(prhs[0]).toMat();
    cv::ximgproc::SuperpixelSLIC *test = cv::ximgproc::createSuperpixelSLIC(src);
}
```
I get the following error:

```
Unexpected Standard exception from MEX file.
What() is:/Volumes/Documents/openCV/modules/imgproc/src/filter.cpp:3741: error: (-213)
Unsupported combination of buffer format (=6), and destination format (=5) in function
getLinearColumnFilter
```

The line that's causing the error is `cv::ximgproc::SuperpixelSLIC *test = cv::ximgproc::createSuperpixelSLIC(src);` so I wonder if `src` is created/converted properly.

**Comment by amroamroamro** [comment]
### re: RFFeatureGetter

Ignoring the errors there in your c++ code,
I'm confused, what are you trying to do here?

Do you want to use the `StructuredEdgeDetection` class in MATLAB?
If so, it's already exposed in mexopencv and you can use it directly.
There's a pretrained model provided by opencv `model.yml.gz` you can load. See this demo:

- [structured_edge_detection_demo.m][1] ([published][2])

Or are you trying to train your own model?

If that's the case, I gotta say the tutorial is *misleading* in the sense that opencv doesn't even implement the training part, and you must do so in MATLAB using the "Structured Edge Detection Toolbox" by *Piotr Dollar*.
In doing so, you don't need either opencv or mexopencv; You just need a feature extraction function, either the existing one in the toolbox `edgesChns` or creating your own (i.e `getFeatures`), whether it's written in pure MATLAB or in C++ as a MEX-function.
I guess mexopencv was used there only for its `MxArray` being a helper class, not for its role as an opencv wrapper for MATLAB...

### re: SuperpixelSLIC

Same thing, you don't have to write MEX-files yourself, we already expose superpixel classes in mexopencv. See this demo for an example:

- [superpixels_demo.m][3] ([published][4])


[1]: https://github.com/kyamagu/mexopencv/blob/master/opencv_contrib/samples/structured_edge_detection_demo.m
[2]: http://amroamroamro.github.io/mexopencv/opencv_contrib/structured_edge_detection_demo.html
[3]: https://github.com/kyamagu/mexopencv/blob/master/opencv_contrib/samples/superpixels_demo.m
[4]: http://amroamroamro.github.io/mexopencv/opencv_contrib/superpixels_demo.html

**Comment by munum** [comment]
@amroamroamro Indeed, I'm trying to train my own model. re SuperpixelSLIC, if `createSuperpixelSLIC()` is used in a MEX-function, isn't the way I did it correct? Since the argument is already a `Mat`, it shouldn't be giving an error - right?

**Comment by amroamroamro** [comment]
> Indeed, I'm trying to train my own model.

ok. did you implemented your own feature detector function?
or are you going to use opencv's implementation?
namely this: https://github.com/opencv/opencv_contrib/blob/master/modules/ximgproc/src/structured_edge_detection.cpp#L348-L394

Here's how you can use opencv's implementation:

### getFeatures.cpp
```cpp
#include "mexopencv.hpp"
#include "opencv2/ximgproc.hpp"
using namespace std;
using namespace cv;
using namespace cv::ximgproc;

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    // check the number of arguments
    nargchk(nrhs == 2 && nlhs <= 1);

    // arguments vector
    vector<MxArray> rhs(prhs, prhs + nrhs);

    // inputs (image and options structure)
    Mat src(rhs[0].toMat(CV_32F)),
        features;
    int gnrmRad  = rhs[1].at("normRad").toInt();   // 4
    int gsmthRad = rhs[1].at("grdSmooth").toInt(); // 0
    int shrink   = rhs[1].at("shrink").toInt();    // 2
    int outNum   = rhs[1].at("nChns").toInt();     // 13
    int gradNum  = rhs[1].at("nOrients").toInt();  // 4

    // extracts feature
    Ptr<RFFeatureGetter> obj = createRFFeatureGetter();
    obj->getFeatures(src, features, gnrmRad, gsmthRad, shrink, outNum, gradNum);

    // output
    plhs[0] = MxArray(features);
}
```

and here's the modified `edgesChns` function:

### edgesChns.m

```matlab
function [chnsReg, chnsSim] = edgesChns(I, opts)
    %EDGESCHNS  Compute features for structured edge detection.

    % call our MEX-function
    chns = getFeatures(im2single(I), opts);

    chnSm = opts.chnSmooth/opts.shrink;
    if (chnSm>1), chnSm = round(chnSm); end
    simSm = opts.simSmooth/opts.shrink;
    if (simSm>1), simSm = round(simSm); end

    chnsReg = convTri(chns, chnSm);
    chnsSim = convTri(chns, simSm);
end
```

**Comment by amroamroamro** [comment]
### re: SuperpixelSLIC

You're using the API incorrectly, `createSuperpixelSLIC` returns a smart pointer, not a raw one!
See the docs:
https://docs.opencv.org/3.3.1/df/d6c/group__ximgproc__superpixel.html#gacf29df20eaca242645a8d3a2d88e6c06

```cpp
Ptr<SuperpixelSLIC> cv::ximgproc::createSuperpixelSLIC (InputArray image, int algorithm=SLICO, int region_size=10, float ruler=10.0f)
```

Also did you read the note there about the expected input...

> For enhanced results it is recommended for color images to preprocess image with little Gaussian blur using a small 3 x 3 kernel and additional conversion into CIELAB color space

The error means you're passing an image with the wrong type..

**Comment by mun3** [comment]
I had to install Matlab and it's fixed now. Thanks.

**Comment by munum** [comment]
I had to reinstall Matlab and it's fixed now. I also had to rebuild opencv for some reason.

**Comment by amroamroamro** [comment]
PS: I added `RFFeatureGetter::getFeatures` in latest mexopencv (#390), exposed as a static function. So now in `edgesChns.m`, you can just write the following without creating your own mex-file:

```matlab
function [chnsReg, chnsSim] = edgesChns(I, opts)
    chns = cv.StructuredEdgeDetection.getFeatures(im2single(I), opts);
    % ... the rest
end
```
