### ISSUE TITLE
Undefined function or variable 'ORB_'.

### ISSUE THREAD

**Issue by AboLregal** [kyamagu/mexopencv#391]
Hello
I have MatLab R2017b
after downloading all files , I tried to try ORBdemo.m

it gives me this message

![image](https://user-images.githubusercontent.com/36906638/36766507-e936af3c-1c3e-11e8-828d-a54694accad5.png)

please help me

**Comment by amroamroamro** [comment]
You have to compile the MEX-files first...
Don't forget to `addpath` as well.

Did you follow the steps in the README file?
https://github.com/kyamagu/mexopencv/blob/master/README.markdown#windows

Also be sure to checkout the wiki:
https://github.com/kyamagu/mexopencv/wiki
