### ISSUE TITLE
BundleAdjuster issue

### ISSUE THREAD

**Issue by franex** [kyamagu/mexopencv#394]
I'm trying to refine with Bundle Adjuster the position of a simple stereopair but Matlab returns me this error:

command:
```
Bundle = cv.BundleAdjuster('BundleAdjusterReproj');%,'ConfThresh',1, 'RefinementMask',refine);
Bundle.refine(features,matched,cameras);

```
Error:
Unexpected Standard exception from MEX file.
What() is:C:\dev\opencv_2\modules\stitching\src\motion_estimators.cpp:347: error: (-215) rvec.type() == 5 in function
cv::detail::BundleAdjusterReproj::setUpInitialCameraParams

I have generated:
- features using cv.FeatureMatcher and pairwise option
- matched using cv.FeatureMatcher
- cameras using cv.Estimator

It seems that the format of the file cameras is not correct...
Any idea?

**Comment by amroamroamro** [comment]
You can refer to the sample `stitching_detailed_demo.m` for reference usage.

I vaguely remember that the stitching API was inconsistent in some places in that the `R` matrices were sometimes of CV_64F type, and of CV_32F type in other places. Here it had a hard assert on the type being CV_32F (the constant 5):

> https://github.com/opencv/opencv/blob/3.4.0/modules/stitching/src/motion_estimators.cpp#L347

The solution is to manaully cast them from double to single, which explains this snippet in the above demo :

```matlab
for i=1:numel(cameras)
    % some subsequent functions require CV_32F matrices
    cameras(i).R = single(cameras(i).R);
    cameras(i).K = single(cameras(i).K);
end
```

**Comment by franex** [comment]
Thanks it works now!
Is there a way to estimate the F or the E matrices using cv.FeatureMatcher?
At the moment it estimates an H matrix but this is not what I want...
Thanks in advance

**Comment by amroamroamro** [comment]
Don't you need camera calibration for that?

You should ask over at [OpenCV Q&A](http://answers.opencv.org/questions/)..
