### ISSUE TITLE
Pose Estimation MATLAB vs. MEXOPENCV - Why Contradicting Results?

### ISSUE THREAD

**Issue by alina33** [kyamagu/mexopencv#403]
I was testing mexopencv functions for estimating pose for an image pair from MATLAB's Visual Odometry Example. However, the result of relative location computed by mexopencv functions is different (negative sign of 3rd element of the Location Vector) from the ground-truth.
Moreover, the results computed from MATLAB's Functions are matching with the ground-truth.

I has been observed that this discrepancy is generated when there is a forward movement in the camera (for viewId = 15), however results are good for other images (viewId = 2,3,4 etc.).

Why is it so? Both results are provided below.
### Results:

```
groundTruth_Loc = -2.191584000000000  -0.018982000000000  26.857834000000000

relativeLoc_normalized = -0.065220918814029  -0.049103970994921  26.946984672662680 % MATLAB's Result

relativeLoc_normalized = 2.487593988338816  3.514638449996284  -26.600861652057898 % MEXOPENCV's Result
```

**Comment by sakts** [comment]
No one will help here

**Comment by sakts** [comment]
@amroamroamro please explain

**Comment by alina33** [comment]
Could anyone help ???????????????

**Comment by alina33** [comment]
@amroamroamro why are u not helping me with this issue? But u are helping others
