### ISSUE TITLE
Problem building Facemark

### ISSUE THREAD

**Issue by KenMele** [kyamagu/mexopencv#404]
Hi,
I am having a problem building Facemark.  When I try to compile, it throws errors in the mexfunction. In particular, it says that the member functions starting with addTrainingSample() line 432, are not in the class Facemark.  They are in FaceRecognizer, but has something changed?

**Comment by amroamroamro** [comment]
I'm quoting the readme file:

> The current version of mexopencv is compatible with OpenCV 3.4.0.

> DO NOT use the "master" branch of opencv and opencv_contrib! Only the 3.4.0 release is supported by mexopencv.

Make sure you are compiling against the expected version.

**Comment by KenMele** [comment]
Thanks that worked. It build like a champ!.
