### ISSUE TITLE
Visual odometry

### ISSUE THREAD

**Issue by alina33** [kyamagu/mexopencv#410]
How can monocular visual odometry be implemented on mexopencv ?
Plz add sample code of mono-visual odometry in this repository

**Comment by tobycollins** [comment]
This is not appropriate. You cannot expect someone to do your work for you.

**Comment by amroamroamro** [comment]
#398, #399, #400, #401, #403, #406, #407, and this.

First @sakts asks questions which I tried to answer. But [my](https://github.com/kyamagu/mexopencv/issues/400#issuecomment-378911016) [respones](https://github.com/kyamagu/mexopencv/issues/400#issuecomment-379219548) get ignored for some reason... Then his posts are edited omitting the code, and @alina33 asks the same thing again, verbatim! And then later, code is removed once again and the whole thing repeats...

I've already pointed out that there are better places for opencv usage questions, [provided](https://github.com/kyamagu/mexopencv/issues/400#issuecomment-379219154) one asks focused questions not just dumping snippets of borrowed code expecting others to do their work for them. Response is I'm not being positive or wanting to help... *sigh*

**Comment by alina33** [comment]
what i have noticed on many posts here, the real reason is that amro has a rude attitude and lacks guts of helping others. keep sighing.
some one else will surely help me. _bye_

**Comment by princessina** [comment]
We both are lab members and both are working on same project. Disappointed over @amroamroamro's response. He got so personal. Anyways, never-mind.

**Comment by amroamroamro** [comment]
I'm not being rude or trying to offend anyone. I'm just explaining, as I have said many times in previous posts now, that https://github.com/kyamagu/mexopencv/issues/ is intended for reporting mexopencv issues and bugs. It is not the right place for asking for opencv or matlab usage help.

And yet, looking at your previous three issues (which I have left open), you've posted duplicate questions plus an empty one..
