### ISSUE TITLE
Error in any "cv." examples,  The specified module could not be found

### ISSUE THREAD

**Issue by alexander946** [kyamagu/mexopencv#413]
Hello, I want to use mexopencv on my Matlab R2017a (64 bits). I followed  the introductions: I download and install and extract in:

- opencv 3.4.2:  `C:\opencv`
- mexopencv-master:  `C:\mexopencv-master`

After that, I add `mexopencv-master` to MATLAB by right click the folder. Then, I used `mex -setup` and selected *Microsoft Visual C++ 2015* . After I have put opencv into system variable path:

    PATH=   C:\opencv\build\x64\vc14\bin

 I run `mexopencv.make('opencv_path', 'C:\opencv\build')` and it worked. 

The problem occurs when i try to run any example code which use `cv.` (Example:` VideoCapture.m` from `C:\mexopencv-master\mexopencv-master`), I always get the same results:

    Invalid MEX-file 'C:\mexopencv-master\mexopencv-master\+cv\private\VideoCapture_.mexw64':
    No se puede encontrar el módulo especificado.
    .
    Error in cv.VideoCapture (line 182)
         this.id = VideoCapture_(0, 'new');

(translation: The specified module could not be found)

Can someone help me, I am new in this and try all i found.

**Comment by amroamroamro** [comment]
The error message `The specified module could not be found` means that MATLAB is unable to find OpenCV DLLs required by mexopencv MEX-files.

I think you've modified the `PATH` system environment variable after you had opened MATLAB. You see changes to environment variables are not picked up by processes that are already running, so try to restart MATLAB after changing PATH. You could also dynamically change it inside MATLAB by calling:

```matlab
>> setenv('PATH', ['C:\opencv\build\x64\vc14\bin;', getenv('PATH')])
```

Also FYI, the latest mexopencv was tested against OpenCV 3.4.0, so you might get some compile errors if you use the newer 3.4.2 (we will be updating mexopencv soon to the latest version).
