### ISSUE TITLE
cv.estimatePoseSingleMarkers from ArUco module

### ISSUE THREAD

**Issue by changh95** [kyamagu/mexopencv#414]
Hi all,

I have been using the aruco module for pose estimation + tracking purpose.
I realised most of the OpenCV tutorials and the official documents of aruco has the cv.estimatePoseSingleMarkers function to return the rotation/translation vectors for camera pose estimation (i.e. from the marker coordinate to the camera coordinate), but the mexopencv returns marker pose estimation(i.e. from the camera coordinate to the marker coordinate).

Can anyone check on this, and perhaps we can consider to change the function to camera pose estimation, just as the original opencv functions?

Thanks.

**Comment by amroamroamro** [comment]
Just to clear up, mexopencv is a wrapper for OpenCV, we do not implement the estimation ourselves, we simply expose the OpenCV C++ functions to MATLAB, with additional glue code for things like conversion between `cv::Mat` and `mxArray` and such.

You can see the source code for this function:
> https://github.com/kyamagu/mexopencv/blob/master/opencv_contrib/src/+cv/estimatePoseSingleMarkers.cpp

So whatever result you're getting, it is what OpenCV algorithms implement...

---

Note that we have a few demos included in mexopencv showing the usage of Aruco functions:

> http://amroamroamro.github.io/mexopencv/opencv_contrib.html#aruco

For example, see this one:
https://github.com/kyamagu/mexopencv/blob/master/opencv_contrib/samples/aruco_detect_markers_demo.m
