### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by MOONBEAR0703** [kyamagu/mexopencv#415]
[Usage](https://github.com/kyamagu/mexopencv/tree/v3.2.0#usage)

I typed `result = cv.filter2D(img,kern);`, but matlab said there is no definition of "img"

**Comment by amroamroamro** [comment]
`img` is the input image, `kern` is the convolution kernel you want to apply. Obviously you must supply both. Be sure to refer to [function documentation](http://amroamroamro.github.io/mexopencv/matlab/cv.filter2D.html).

Quick example:

```matlab
img = im2single(imread('coins.png'));
kern = [1 1 1; 1 -8 1; 1 1 1];
res = cv.filter2D(img, kern);
imshow(res,[])
```
