### ISSUE TITLE
cv.projectPoints: Wrong number of arguments

### ISSUE THREAD

**Issue by X1l10on88** [kyamagu/mexopencv#430]
MATLAB 2015a
GCC 4.7
mexopencv: current branch
OpenCV 3.4.1

Error:

imagePoints = cv.projectPoints(src2, rvec, tvec, K, distCoeffs)
Error using projectPoints
Wrong number of arguments

opencvmex compiled without warnings or errors and others cv. functions works properly.

**Comment by amroamroamro** [comment]
Distortion coefficients param is an option, not required input (defaults to zero ceoffs).

> http://amroamroamro.github.io/mexopencv/matlab/cv.projectPoints.html

So the call should be:

    imagePoints = cv.projectPoints(src2, rvec, tvec, K, 'DistCoeffs',distCoeffs);

**Comment by X1l10on88** [comment]
Solved, thanks!
