### ISSUE TITLE
Latency in Mexopencv codes

### ISSUE THREAD

**Issue by youthiya** [kyamagu/mexopencv#440]
Hi, I have an important question whose answer is difficult to find.

Does MEXOPENCV's benchmark functions like cv.SIFT, cv.SURF, cv.descriptorMatcher etc. have same computation cost as the original OPENCV C++ Library codes cv.SIFT, cv.SURF, cv.descriptorMatcher etc.?

Or is some latency (delay) present in MEXOPENCV functions as compared to genuine OPENCV Library functions?

**Comment by amroamroamro** [comment]
mexopencv is a wrapper library, meaning we directly call OpenCV C++ functions.

The only overhead (small) is that of calling MEX-functions from MATLAB code, and converting between MATLAB and OpenCV data types (think from/to `mxArray` and `cv::Mat`)

**Comment by youthiya** [comment]
Thank you for answering.
