### ISSUE TITLE
`GLIBCXX_3.4.15' not found

### ISSUE THREAD

**Issue by peugas** [kyamagu/mexopencv#45]
I'm having this error while using cv.findChessboardCorners:
```
   Error using cv.findChessboardCorners
   Invalid MEX-file '/home/tiago/Documents/MATLAB/mexopencv/+cv/findChessboardCorners.mexa64': /usr/local/MATLAB/R2012b/bin/glnxa64/../../sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by usr/local/lib/libopencv_calib3d.so.2.4)
```

I've tried to run matlab as:

    LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/libstdc++.so.6 matlab

but I got the same result...

I'm able to use some other mexopencv functions but not this one.
I'm on Ubuntu 12.04 LTS and running MATLAB r2012b

**Comment by aleksandaratanasov** [comment]
https://fantasticzr.wordpress.com/2013/05/29/matlab-error-libstdc-so-version-glibcxx_3-4-15-not-found/

You can also link to the correct libstdc++ library and replace the one in Matlab's installation directory.

**Comment by zhengchuansh** [comment]
and I also has use: sudo ln -sf /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19   /usr/local/MATLAB/R2011a/bin/glnxa64/libstdc++.so.6
than solve the problem, but unfortunately, when I  running  run_cifar10, it running to：
 Preparing /examples/cvprw15-cifar10/dataset/test/4590.jpg
Warning: Problems with file 
> In prepare_batch>(parfor body) at 39
  In parallel_function at 472
  In prepare_batch at 21
  In matcaffe_batch_feat at 55
  In run_cifar10 at 41 
Elapsed time is 0.196153 seconds.
an  unexpectation error happened: Matlab has encountered an internal problem and need to close
This error was detected while a MEX-file was running. If the MEX-file
is not an official MathWorks function, please examine its source code
for errors. Please consult the External Interfaces Guide for information
on debugging MEX-files.
