### ISSUE TITLE
libharfbuzz.so.0: undefined symbol: FT_Get_Advance

### ISSUE THREAD

**Issue by pinchal** [kyamagu/mexopencv#74]
Hi!

I am using mexopencv for a few months, everything was ok until a recent update -from ubuntu or opencv, I don't know-. There's no issue during build, but when I try to use the object 'CascadeClassifier', I get this 'Invalid MEX-file' error:

```
Invalid MEX-file '/home/stephane/dev/matlab/common/+cv/private/CascadeClassifier_.mexa64':
/usr/lib/x86_64-linux-gnu/libharfbuzz.so.0: undefined symbol: FT_Get_Advance
```

A quick (and dirty) way to get round this problem is to launch matlab with "LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libfreetype.so", but it doesn't fix the main problem.

**Comment by cruz** [comment]
Thanks a lot. I'm calling a python script from MATLAB R2011a, Ubuntu 14.04. My python script calls "import cv", but it kept throwing: 

    ImportError: /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0: undefined symbol: FT_Face_GetCharVarientIndex

I used ```LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libfreetype.so.6```, and it worked :)

**Comment by aleksandaratanasov** [comment]
You can also use symbolic linking to use the library that is installed along with your Linux distro and not the one that is shipped with Matlab. I had the same issue along with `libstdc++.so.6` and I solved it by simply doing the following:

    sudo ln -sf /usr/lib/i386-linux-gnu/libfreetype.so.6 /opt/MATLAB/R2012a/bin/glnx86/libfreetype.so.6

Note that I have a 32bit system and that is why I use the library in `i386-linux-gnu`. Also my Matlab installation is in `/opt` and again I go for the 32bit folder there.

**Comment by shikha4444** [comment]
Thank you @aleksandaratanasov

**Comment by tesla500** [comment]
Works perfectly for Ubuntu 18.10  too, thank you @aleksandaratanasov.

**Comment by amroamroamro** [comment]
https://github.com/kyamagu/mexopencv/wiki/Troubleshooting-%28UNIX%29
