### ISSUE TITLE
Matlab and opencv

### ISSUE THREAD

**Issue by Ragheedok** [kyamagu/mexopencv#75]
I want to know how to link and configure opencv2.4 or 2.3 with MatlabR2013a on windows vista 32-bit?
Thanks

**Comment by sumeetssaurav** [comment]
Hello Kyamagu,
I have interfaced mexopencv with Matlab 2015a on windows8. It got interfaced properly, but when i tried to run the facedetect sample code, i am not getting any detection on the Live Camera stream. I can see only the camera stream without any detection. Please help me to solve the issue.

Thanking You,
Sumeet Saurav
