### ISSUE TITLE
Compiles fine, but can't find OpenCV at run time. MATLAB 2011b, Linux, OpenCV 2.4.5

### ISSUE THREAD

**Issue by fagg** [kyamagu/mexopencv#77]
Running on Linux with MATLAB 2011b. mexopencv freshly cloned from github this morning. I have a custom installation of OpenCV 2.4.5 (custom meaning I compiled it myself, but the settings are default). The compilation works fine with no errors, but when I add the install directory to my path, it complains it can't find OpenCV libraries.

For example:
![image](https://f.cloud.github.com/assets/1742468/802493/3b893294-edca-11e2-81fc-ce7606f34f98.png)

If I examine the mex file from the previous example, it cannot find OpenCV at all (this is a portion of the output from ldd):

![image](https://f.cloud.github.com/assets/1742468/802496/89744b1a-edca-11e2-8cbc-e12ffd10db64.png)

But curiously, even using LD_PRELOAD doesn't work as I get this error (pkg-config is definitely pointing at my OpenCV install):

![image](https://f.cloud.github.com/assets/1742468/802499/eae2ffcc-edca-11e2-92c2-1ddf6d0e1855.png)

Any help greatly appreciated, however please bear in mind that I do not have permission to modify anything outside of my home directory.

**Comment by 13293824182** [comment]
你好  ，我和您的问题差不多。小白，看您的总结还是不明白，希望您给点指导。
![image](https://user-images.githubusercontent.com/34392695/35571327-beca8fa4-060c-11e8-9670-a07a9004f1de.png)
![image](https://user-images.githubusercontent.com/34392695/35571337-c5f76fcc-060c-11e8-9559-44c58d54edce.png)。

**Comment by amroamroamro** [comment]
@13293824182

> https://github.com/kyamagu/mexopencv/issues/352#issuecomment-361616388

ditto. please don't multi-post.
