### ISSUE TITLE
CascadeClassifier_ Invalid path or file specified

### ISSUE THREAD

**Issue by adtadhikari** [kyamagu/mexopencv#81]
I used the face detection in the samples of mexopencv. I added the path of mexopencv in matlab and ran the program which calls the mex for Cascade Classifier.The program runs with no error in matlab.

When I use the deploytool to produce c++ shared library and compile it to an exe and run it i get the error `CascadeClassifier_ Invalid path or file specified`. I read that this is because the xml file is not found but I have added the xml file while generating the c++ shared library.

I am using linux. should I add any new path in the system or Matlab? The xml file is called as

```
xml_file=fullfile( mexopencv.root(),'test','haarcascade_frontalface_alt2.xml'); 
```

Will the exe know what the `mexopencv.root()` is. Should I change the path? I tried with: 

```
xml_file=fullfile('haarcascade_frontalface_alt2.xml'); 
```

this too but the error was the same `Invalid path or file specified`. How can I solve this problem?? Please give the solution for linux.

**Comment by amroamroamro** [comment]
For anyone stumbling here, this should be of help:

- [Path Management in Deployed Applications](https://blogs.mathworks.com/loren/2008/08/11/path-management-in-deployed-applications/)
