### ISSUE TITLE
"What() is:vector<T> too long", persistent error when trying to run template for developing my own mex-file

### ISSUE THREAD

**Issue by bengtsst** [kyamagu/mexopencv#83]
EDIT: all of a sudden this worked, I have no idea if I changed anything, that is pretty frustrating in itself.. :)

---

Because I had troubles using an openCV class that I wanted (StereoSGBM, whereas StereoBM worked without any errors), I decided to make my own mex interface instead to see if that would work, and I am now interested to sort that out. Code is attached at the bottom of the message.

I am using MATLAB R2012b with Windows SDK 7.1 compiler, latest opencv 2.4.6. I have setup opencv in c:\opencv, mexopencv in c:\mexopencv and they both work somewhat fine by themselves. 

I am trying to run the template for "Developing a new mex function" given at https://github.com/kyamagu/mexopencv. Using the same mex command as mexopencv.make uses (i.e. making sure library directories and include directories are there):
```
mex -largeArrayDims   -I'c:\mexopencv\mexopencv-master\include' -I'C:\opencv\build\include' -L'C:\opencv\build\x64\vc10\lib'  -lopencv_calib3d246 -lopencv_contrib246 -lopencv_core246 -lopencv_features2d246 -lopencv_flann246 -lopencv_gpu246 -lopencv_haartraining_engine -lopencv_highgui246 -lopencv_imgproc246 -lopencv_legacy246 -lopencv_ml246 -lopencv_nonfree246 -lopencv_objdetect246 -lopencv_ocl246 -lopencv_photo246 -lopencv_stitching246 -lopencv_superres246 -lopencv_ts246 -lopencv_video246 -lopencv_videostab246 'c:\mexopencv\mextest.cpp' 'c:\mexopencv\mexopencv-master\lib\MxArray.obj'
```

(Side comment: I've also tried changing the `D_SECURE_SCL` flag (although I don't know really what it does) by changing its value by `COMPFLAGS="$COMPFLAGS /D_SECURE_SCL=1"`, just gives another error instead, no help)

The template code (pasted into `mextest.cpp` in the mexopencv directory) then compiles but when i run it in MATLAB, e.g. using `>> a = mextest(1)` MATLAB crashes. If the only alteration to the template is to comment out the row `cv::Mat mat = MxArray(prhs[0]).toMat();`, the program both compiles and runs in MATLAB. Then I add new rows of code one by one.

Adding `MxArray test = MxArray(prhs[0]);` and `cv::Mat mat;` causes no problem (see under "//Do whatever you want" in the code below). When I add `mat = test.toMat();`, the program still compiles and MATLAB does not crash when I run it. The addition of the row `plhs[0] = MxArray(mat);` however gives the error in the title, "Unexpected Standard exception from MEX file. What() is:vector<T> is too long".

What is very curious is that if I run the exact same thing on another computer with MATLAB R2011a, the template program works immediately, i.e., `>> a = mextest(1)` runs and sets the variable a to 1 in MATLAB as it should.
``` cpp
# include "mexopencv.hpp"

void mexFunction(int nlhs, mxArray *plhs[],
                 int nrhs, const mxArray *prhs[])
{
    // Check arguments
    if (nlhs!=1 || nrhs!=1)
        mexErrMsgIdAndTxt("myfunc:invalidArgs", "Wrong number of arguments");

// Convert MxArray to cv::Mat
//cv::Mat mat = MxArray(prhs[0]).toMat();

// Do whatever you want
MxArray test = MxArray(prhs[0]);
cv::Mat mat;
mat = test.toMat(); 
cv::Mat mat2;

// Convert cv::Mat back to mxArray*
plhs[0] = MxArray(mat); //causes "...What() is:vector<T> is too long" error

}
```

**Comment by SCUT2014** [comment]
I met the same issue with you, could you tell me how to resolve it? Thank you very much.
