### ISSUE TITLE
cap.read() returns empty 0*0 uint

### ISSUE THREAD

**Issue by godprince** [kyamagu/mexopencv#84]
There occurs a problem when I used you code in Linux (Matlab 2013b, Opencv2.4.6).
The problem is `cap.read()` returns an empty empty `0 * 0 uint8` image.
But cap's id is non-zero. `cap.isOpened()` returns zero.

**Comment by ErCmos** [comment]
Hi all,
I have the same problem reading a file, but cap.isOpen() returns 1 and cap.isvalid() returns that the file is valid. I'm running Matlab_R2014b and opencv 2.4.10 on ubuntu 14.04.02. If I try mexopencv with jpg files works perfect, Any Idea?.
P.D. I install Gstreamer 0.10 pluggings (good, bad and ugly) and codecs with sudo apt-get install ubuntu-restricted-extras. The video file is played without problem in VLC.

Thanks in advance

**Comment by amroamroamro** [comment]
@ErCmos 
I just tried the following example and it worked fine (tested using the prebuilt OpenCV 2.4.9 on Windows):

``` matlab
% open video file
vid = cv.VideoCapture(which('xylophone.mp4'));
pause(1)
if ~vid.isOpened(), error('failed to open video file'); end

% read and display all 141 frames in this video
numFrames = vid.get('FrameCount');
for i=1:numFrames
	% read next frame
	frame = vid.read();
	%if isempty(frame), break; end
	
	% display it
	imshow(frame)
	drawnow
end

% close video file
clear vid
```

The file `xylophone.mp4` is a video sample that ships with MATLAB (encoded in [H.264](https://en.wikipedia.org/wiki/H.264/MPEG-4_AVC)).

If I'm not mistaken, OpenCV relies on the FFmpeg library to handle video IO (Gstreamer or VLC are not involved). So if you are building from sources, you need to make sure to have the required dev-package installed and enabled during building (follow the instructions in this [Linux guide](http://docs.opencv.org/doc/tutorials/introduction/linux_install/linux_install.html)).

**Comment by ErCmos** [comment]
Hi @amroamroamro 
First at all thanks for your answer. I think that all dev- packages are installed (I reinstalled opencv using the linux guide). GStreamer is used for standard Matlab to load video and I installed VLC to see if all the codecs were installed properly. I think that opencv is properly installed (all works with .jpg files), but I don't know why vid.read() is always returning an empty frame.
Thanks for all your help, I'll keep working on it.

**Comment by amroamroamro** [comment]
@ErCmos 
There are two ways to get OpenCV in Ubuntu:
- one option is to build OpenCV from sources. First you'll need to install the required dev-packages, configure and generate the Makefiles using CMake, then compile the sources and install the built libraries.
 This is all explained in [the documentation](http://docs.opencv.org/doc/tutorials/introduction/linux_install/linux_install.html).

- the other way is to just install the [prebuilt packages](http://packages.ubuntu.com/trusty/libopencv-dev) using your system's package manager:

        $ sudo apt-get install libopencv-dev

 This will take care of any dependencies as well. You don't have to do anything special.

---

Now I don't have MATLAB installed on Linux to test this myself, instead I tried the following equivalent C++ code:

### testvid.cpp
``` cpp
#include <iostream>
#include "opencv2/highgui/highgui.hpp"

int main()
{
    // open video file
    cv::VideoCapture vid("./xylophone.mp4");
    if (!vid.isOpened()) {
        std::cerr << "Failed to open video file." << std::endl;
        return EXIT_FAILURE;
    }

    // create a window
    std::string window_name = "video";
    cv::namedWindow(window_name, CV_WINDOW_KEEPRATIO);

    // get number of frames
    int num_frames = static_cast<int>(vid.get(CV_CAP_PROP_FRAME_COUNT));
    std::cout << num_frames << " frames." << std::endl;

    // read and display all frames
    cv::Mat frame;
    for (int i=0; i<num_frames; i++) {
        // read next frame
        vid >> frame;
        if (frame.empty())
            break;

        // display it
        cv::imshow(window_name, frame);
        if (cv::waitKey(30) >= 0)
            break;
    }

    return EXIT_SUCCESS;
}
```

You can compile and run it using:
``` sh
$ g++ -o testvid testvid.cpp `pkg-config --cflags --libs opencv`
$ ./testvid
```

I tested the above in a virtual machine running Ubuntu 14.04 with OpenCV installed using `apt-get` as explained before (this is mostly a vanilla install, I didn't mess much with codecs or video players).

If that works (which it did for me), then it's safe to assume mexopencv would work as well with MATLAB.

If you're experiencing problems, then I suspect your video file is either corrupted or is encoded with something that OpenCV does not support...

**Comment by ErCmos** [comment]
Sorry for the late answer @amroamroamro,
At the end I was able to fix the problem, but I forgot to answer you, sorry. The problem was a compiled library in a wrong version.

Thanks for all your help and sorry for my mistake.

Best regards
