### ISSUE TITLE
Error building mexopencv.make

### ISSUE THREAD

**Issue by nekojan** [kyamagu/mexopencv#90]
Hello. I have some problem, could you please help me with this?
I'm using Mac OS X 10.9 with Matlab 2013a
I installed OpenCV using homebrew, and checked `pkg-config` command.

```
$ pkg-config --cflags opencv
-I/usr/local/Cellar/opencv/2.4.6.1/include/opencv -I/usr/local/Cellar/opencv/2.4.6.1/include 
```

But I get the following error when I try `mexopencv.make` on Matlab:

```
>> mexopencv.make('opencv_path','/usr/local/Cellar/opencv/2.4.6.1')
make MATLABDIR="/Applications/MATLAB_R2013a.app" MEXEXT=mexmaci64  
make: pkg-config: Command not found
make: pkg-config: Command not found
/Applications/MATLAB_R2013a.app/bin/mex -c -cxx -largeArrayDims -Iinclude  src/MxArray.cpp -outdir lib
In file included from src/MxArray.cpp:6:
include/MxArray.hpp:14:10: fatal error: 'opencv2/opencv.hpp' file not found
#include "opencv2/opencv.hpp"
         ^
1 error generated.
    mex: compile of ' "src/MxArray.cpp"' failed.
make: *** [lib/libMxArray.a] Error 1
```

**Comment by rafacallejas** [comment]
Hello. I´m trying to install mexopencv in OSX 10.9.5 and Matlab2013a, and i have the same problem that previous issues, but the error keep appearing after using mexopencv.make or mexopencv.make('extra', ...).

The message is:

>> mexopencv.make
make MATLABDIR="/Applications/MATLAB_R2013a.app" MEXEXT=mexmaci64  
make: pkg-config: Command not found
make: pkg-config: Command not found
/Applications/MATLAB_R2013a.app/bin/mex -c -cxx -largeArrayDims -Iinclude  src/MxArray.cpp -outdir lib
clang: warning: no such sysroot directory: '-mmacosx-version-min=10.9'
In file included from src/MxArray.cpp:6:
In file included from include/MxArray.hpp:9:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/functional:477:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:600:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iterator:332:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iosfwd:90:10: fatal error: 
      'wchar.h' file not found
#include <wchar.h>  // for mbstate_t
         ^
1 error generated.

    mex: compile of ' "src/MxArray.cpp"' failed.

make: *** [lib/libMxArray.a] Error 1

Thanks for help!

**Comment by kyamagu** [comment]
@rafacallejas mexopencv in UNIX environment requires `pkg-config` tool properly set up (See README). For OS X, I recommend installing a package manager like [Homebrew](http://brew.sh) or [MacPorts](https://www.macports.org) first, and install `opencv` using that; i.e., `brew install opencv` or `port install opencv`. Otherwise, manually install `pkg-config` and set up the path to OpenCV.

**Comment by rafacallejas** [comment]
Sorry for being so awkward, i think i've follow your instructions and now, whe i´m trying to compile mexopencv in my console i get:

MacBook-Pro-de-Rafael:kyamagu-mexopencv-24b0b0c callejas$ make MATLABDIR=/Applications/MATLAB_R2013a.app
/Applications/MATLAB_R2013a.app/bin/mex -c -cxx -largeArrayDims -Iinclude -I/usr/local/include/opencv -I/usr/local/include  src/MxArray.cpp -outdir lib
In file included from src/MxArray.cpp:6:
In file included from include/MxArray.hpp:13:
In file included from /Applications/MATLAB_R2013a.app/extern/include/mex.h:58:
In file included from /Applications/MATLAB_R2013a.app/extern/include/matrix.h:294:
/Applications/MATLAB_R2013a.app/extern/include/tmwtypes.h:819:18: error: expected unqualified-id
typedef char16_t CHAR16_T;
                 ^
<command line>:2:18: note: expanded from here
#define CHAR16_T 1
                 ^
In file included from src/MxArray.cpp:6:
In file included from include/MxArray.hpp:13:
In file included from /Applications/MATLAB_R2013a.app/extern/include/mex.h:58:
/Applications/MATLAB_R2013a.app/extern/include/matrix.h:319:9: error: expected unqualified-id
typedef CHAR16_T mxChar;
        ^
<command line>:2:18: note: expanded from here
#define CHAR16_T 1
                 ^
In file included from src/MxArray.cpp:6:
In file included from include/MxArray.hpp:13:
In file included from /Applications/MATLAB_R2013a.app/extern/include/mex.h:58:
/Applications/MATLAB_R2013a.app/extern/include/matrix.h:632:10: error: unknown type name 'mxChar'
EXTERN_C mxChar *mxGetChars(
         ^
In file included from src/MxArray.cpp:6:
include/MxArray.hpp:923:51: error: unknown type name 'mxChar'
            *(mxGetChars(p_)+index) = static_cast<mxChar>(value); break;
                                                  ^
4 errors generated.

    mex: compile of ' "src/MxArray.cpp"' failed.

It seem's that something is wrong with my MxArray.ccp but i don't know what to do...

Thank you so much for your help.

**Comment by kyamagu** [comment]
The error is probably due to Apple's old `g++` compiler. Using `mex` with C++ in OS X is always a headache...

Anyway, set up `mex` to use `clang++` and `libc++` instead. Open `~/.matlab/R2013a/mexopts.sh` and edit the maci64 section to include something like the following.

    CC='clang'
    CXX='clang++'
    SDKROOT='/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/'
    MACOSX_DEPLOYMENT_TARGET='10.9'
    CFLAGS="$CFLAGS -Dchar16_t=uint16_t"
    CXXFLAGS="$CXXFLAGS -std=c++11 -stdlib=libc++ -DCHAR16_T"
    CXXLIBS="$MLIBS -lc++"
